/-
**Well-positioned families: Lemma 8.1, Propositions 8.2 and 8.4, Lemma 8.3** (Bergman §8), for a
family of `R_μ`-modules `N' μ` embedded in `Std` by `R_μ`-linear maps `φ μ` with well-positioned
images.

* `Idx`: the index set of Bergman's family `t_n ⋯ t_1 q` of Lemma 8.1: `q` runs over a basis of
  `e_j N'_μ` with distinct greatest terms for the order `gord (side t_1)` (`eb`).
* `Idx.linearIndependent_V`: **Lemma 8.1**: these products have distinct leading terms
  (`Idx.K_injective`), hence are linearly independent.
* `exists_liftΦ`: **Proposition 8.2**: the lift `Std(N') → Std` of the `φ μ` is injective, with
  image the `C`-submodule generated by the images.
* `mem_range_of_mem_span`: **Lemma 8.3** (in the form used): an element of that submodule all of
  whose terms are base elements of `N_{μ₁}` lies in the image of `φ μ₁`.
* `range_eq_incl`: **Proposition 8.4**: if the images generate `Std`, they are the components.
-/
import KappaMonoid.Bergman.Core.Lemma81

universe u

set_option linter.unusedSectionVars false

namespace Bergman.Core

open Module

variable {k : Type u} [Field k] {ι : Type} [Fintype ι] [DecidableEq ι]
  {Λ : Type} [Fintype Λ] [DecidableEq Λ]
  {R : Λ → Type u} [∀ l, Ring (R l)] [∀ l, Algebra k (R l)]
  {σ : ∀ l, (ι → k) →ₐ[k] R l} [Fact (∀ l, Function.Injective (σ l))]
  {C : Type u} [Ring C] [Algebra k C] {σC : (ι → k) →ₐ[k] C} {inc : ∀ l, R l →ₐ[k] C}
  [Fact (IsCoprod k σ C σC inc)]
  {N : Option Λ → Type u} [∀ μ, AddCommGroup (N μ)] [∀ μ, Module (Rμ k ι R μ) (N μ)]
  [∀ μ, Module k (N μ)] [∀ μ, IsScalarTower k (Rμ k ι R μ) (N μ)] {B : HomBases σ N}

/-! ## Consequences of well-positionedness -/

theorem Std.ne_zero_of_mem_supp {y : Std σC inc B} {w : Mono σ B.S} (hw : w ∈ y.supp) : y ≠ 0 := by
  rintro rfl; rw [Std.supp_eq_empty.2 rfl] at hw; exact absurd hw (by simp)

theorem Std.deg_eq_zero {y : Std σC inc B} (h : ∀ w ∈ y.supp, w.deg = 0) : y.deg = 0 :=
  le_antisymm (Finset.sup_le fun w hw => (h w hw).le) (Nat.zero_le _)

/-- An element of `L μ` is not `l`-pure for `some l ≠ μ`. -/
theorem WP.not_pureS {L : Option Λ → Set (Std σC inc B)} (hW : WP L) {μ : Option Λ}
    {y : Std σC inc B} (hy : y ∈ L μ) (hy0 : y ≠ 0) {l : Λ} (hne : some l ≠ μ) :
    ¬ IsPureS l y := by
  cases μ with
  | none => exact (show ∀ l, ¬ IsPureS l y from hW.pure_none y hy) l
  | some l' =>
    intro hp
    have hp' := hW.pure_some l' y hy hy0
    obtain ⟨w, hw, hwd⟩ := Std.exists_mem_supp hy0
    exact hne ((hp.2 w hw hwd).symm.trans (hp'.2 w hw hwd))

/-- **Lemma 8.3, the combinatorial part**: a sum of elements `xs μ ∈ L μ` of degree `0` whose terms
are all on side `μ₁` lies in `L μ₁`. -/
theorem WP.mem_of_sum {L : Option Λ → Submodule k (Std σC inc B)}
    (hWP : WP fun μ => (L μ : Set (Std σC inc B))) (xs : Option Λ → Std σC inc B)
    (hxs : ∀ μ, xs μ ∈ L μ) (hdeg : ∀ μ, ∀ w ∈ (xs μ).supp, w.deg = 0) {μ₁ : Option Λ}
    (hsupp : ∀ w ∈ (∑ μ, xs μ).supp, w.side = μ₁) : ∑ μ, xs μ ∈ L μ₁ := by
  classical
  set x := ∑ μ, xs μ with hxdef
  have hside : ∀ l, ∀ w ∈ (xs (some l)).supp, w.side = some l := fun l w hw =>
    (hWP.pure_some l _ (hxs _) (Std.ne_zero_of_mem_supp hw)).2 w hw
      (by rw [hdeg _ w hw, Std.deg_eq_zero (hdeg _)])
  have hzero : ∀ l, some l ≠ μ₁ → xs (some l) = 0 := by
    intro l hl
    by_contra hne
    have hne' : (xs (some l)).supp.Nonempty :=
      Finset.nonempty_iff_ne_empty.2 (mt Std.supp_eq_empty.1 hne)
    set W := (xs (some l)).supp.max' hne'
    have hW' : W ∈ (xs (some l)).supp := Finset.max'_mem _ _
    have hmax : ∀ w ∈ (xs (some l)).supp, w ≤ W := fun w hw => Finset.le_max' _ w hw
    have hcx : Std.coeff σC inc B x W = 0 := by
      by_contra h
      exact hl ((hside l W hW').symm.trans (hsupp W (Std.mem_supp.2 h)))
    have hsum : Std.coeff σC inc B x W =
        Std.coeff σC inc B (xs none) W + Std.coeff σC inc B (xs (some l)) W := by
      rw [hxdef, map_sum, Finsupp.finsetSum_apply, Fintype.sum_option, Finset.sum_eq_single l]
      · intro l' _ hl'
        by_contra h
        exact hl' (Option.some.inj ((hside l' W (Std.mem_supp.2 h)).symm.trans
          (hside l W hW')))
      · simp
    have hnone : W ∈ (xs none).supp := by
      rw [Std.mem_supp]; intro h
      rw [hsum, h, zero_add] at hcx
      exact Std.mem_supp.1 hW' hcx
    have := hWP.nolead none (some l) (xs none) (hxs none) (xs (some l)) (hxs _) 1 W
      (by rw [msupp_none]; exact hnone)
      (by rw [one_smul]; exact isLead_none_of_max (hWP.pure_some l _ (hxs _) hne) hW' hmax)
    exact absurd this.1 (by simp)
  cases μ₁ with
  | none =>
    have : x = xs none := by
      rw [hxdef, Fintype.sum_option, Finset.sum_eq_zero (fun l _ => hzero l (by simp)), add_zero]
    rw [this]; exact hxs none
  | some l₁ =>
    have hx : x = xs none + xs (some l₁) := by
      rw [hxdef, Fintype.sum_option,
        Finset.sum_eq_single l₁ (fun l _ hl => hzero l (by simpa using hl)) (by simp)]
    have hn : xs none = 0 := by
      by_contra hne
      apply (show ∀ l, ¬ IsPureS l (xs none) from hWP.pure_none _ (hxs none)) l₁
      refine ⟨hne, fun w hw _ => ?_⟩
      have : xs none = x + -(xs (some l₁)) := by rw [hx]; abel
      rw [this] at hw
      rcases Finset.mem_union.1 (Std.supp_add _ _ hw) with h | h
      · exact hsupp w h
      · rw [Std.supp_neg] at h; exact hside l₁ w h
    rw [hx, hn, zero_add]; exact hxs _

/-! ## The family of Lemma 8.1 -/

variable {N' : Option Λ → Type u} [∀ μ, AddCommGroup (N' μ)] [∀ μ, Module (Rμ k ι R μ) (N' μ)]
  [∀ μ, Module k (N' μ)] [∀ μ, IsScalarTower k (Rμ k ι R μ) (N' μ)]
  (φ : ∀ μ, N' μ →ₗ[k] Std σC inc B) (hφ : ∀ μ, Function.Injective (φ μ))

/-- `e_j N'_μ`, embedded in the coefficient space of `Std`. -/
noncomputable def φe (μ : Option Λ) (j : ι) : eSub σ N' μ j →ₗ[k] Mono σ B.S →₀ k :=
  (Std.coeff σC inc B).toLinearMap ∘ₗ φ μ ∘ₗ (eSub σ N' μ j).subtype

include hφ in
theorem φe_injective (μ : Option Λ) (j : ι) : Function.Injective (φe φ μ j) :=
  fun a b h => Subtype.ext (hφ μ ((Std.coeff σC inc B).injective h))

/-- The chosen bases: a basis of `e_j N'_μ` with distinct greatest terms for `gord o`. -/
noncomputable def eb (μ : Option Λ) (j : ι) (o : Option Λ) : EchBasis (gord o) (φe φ μ j) :=
  (nonempty_echBasis (gord o) (gord_injective o) (φe φ μ j) (φe_injective φ hφ μ j)).some

/-- The index set of Bergman's family `t_n ⋯ t_1 q`. -/
structure Idx where
  /-- The component of `q`. -/
  μ : Option Λ
  /-- The idempotent `e_j` with `e_j q = q`. -/
  j : ι
  /-- The letters `[t_n, …, t_1]`. -/
  ts : List (Letter σ)
  chain : ChainAt j μ ts
  /-- The basis element `q`, indexed by its greatest term. -/
  q : (eb φ hφ μ j (firstSide ts)).s

namespace Idx

variable {φ hφ}

/-- The basis element `q ∈ N'_μ`. -/
noncomputable def elt (i : Idx φ hφ) : N' i.μ := ((eb φ hφ i.μ i.j (firstSide i.ts)).b i.q : N' i.μ)

/-- The basis element `q`, in `Std`. -/
noncomputable def qv (i : Idx φ hφ) : Std σC inc B := φ i.μ i.elt

/-- The greatest term of `q` for `gord (side t_1)`. -/
def kap (i : Idx φ hφ) : Mono σ B.S := i.q.1

/-- The member `t_n ⋯ t_1 q` of the family. -/
noncomputable def V (i : Idx φ hφ) : Std σC inc B := wordAct inc i.ts • i.qv

theorem top (i : Idx φ hφ) : IsTopF (gord (firstSide i.ts)) (Std.coeff σC inc B i.qv) i.kap :=
  (eb φ hφ i.μ i.j (firstSide i.ts)).top i.q

theorem qv_ne_zero (i : Idx φ hφ) : i.qv ≠ 0 := fun h =>
  (eb φ hφ i.μ i.j (firstSide i.ts)).b.ne_zero i.q
    (Subtype.ext (hφ i.μ (h.trans (map_zero (φ i.μ)).symm)))

theorem qv_mem (i : Idx φ hφ) {μ : Option Λ} (h : i.μ = μ) : i.qv ∈ Set.range (φ μ) := by
  subst h; exact ⟨_, rfl⟩

theorem le_kap_nil (i : Idx φ hφ) (h : i.ts = []) : ∀ w ∈ i.qv.supp, w ≤ i.kap := by
  have ht := i.top
  rw [h] at ht
  exact ht.le_none

end Idx

section WP

variable (hφs : ∀ μ (r : Rμ k ι R μ) a, φ μ (r • a) = incμ σC inc μ r • φ μ a)
  (hW : WP fun μ => Set.range (φ μ))

namespace Idx

variable {φ hφ}

include hφs in
theorem kap_left (i : Idx φ hφ) : i.kap.left = i.j := by
  have he : eμ σ i.μ i.j • i.elt = i.elt := ((eb φ hφ i.μ i.j (firstSide i.ts)).b i.q).2
  have hy : σC (ee i.j) • i.qv = i.qv := by
    rw [← incμ_eμ (σ := σ) σC inc i.μ i.j]
    show incμ σC inc i.μ (eμ σ i.μ i.j) • φ i.μ i.elt = φ i.μ i.elt
    rw [← hφs, he]
  exact left_of_mem_supp_homog hy i.top.1

include hW in
theorem lead (i : Idx φ hφ) {l : Λ} (hl : firstSide i.ts = some l) :
    IsLead (some l) i.qv i.kap := by
  have h := i.top
  rw [hl] at h
  obtain ⟨t, ht, rfl⟩ := exists_of_firstSide hl
  exact h.isLead (hW.not_pureS (i.qv_mem rfl) i.qv_ne_zero (i.chain.last_ne t ht))

include hW in
theorem side_kap_some (i : Idx φ hφ) {l : Λ} (h : i.μ = some l) : i.kap.side = some l :=
  (hW.pure_some l _ (i.qv_mem h) i.qv_ne_zero).2 _ i.top.1 i.top.deg_eq

include hW in
theorem le_kap_some (i : Idx φ hφ) {l : Λ} (h : i.μ = some l) :
    ∀ w ∈ i.qv.supp, w ≤ i.kap := by
  apply i.top.le_of_bit
  intro w hw hwd
  have hs : w.side = some l := (hW.pure_some l _ (i.qv_mem h) i.qv_ne_zero).2 w hw hwd
  cases ho : firstSide i.ts with
  | none => rfl
  | some l' =>
    obtain ⟨t, ht, rfl⟩ := exists_of_firstSide ho
    have := i.chain.last_ne t ht
    rw [h] at this
    simp only [sideBit, hs, ne_eq, decide_eq_true_eq]
    exact fun e => this e.symm

include hφs hW in
theorem chainK (i : Idx φ hφ) : ChainAt i.kap.left i.kap.side i.ts := by
  rw [i.kap_left hφs]
  refine i.chain.mono_side fun t ht e => ?_
  have hl : firstSide i.ts = some t.side := by
    rw [firstSide, Option.mem_def.1 ht]; rfl
  exact (i.lead hW hl).side_ne e.symm

/-- The leading term `t_n ⋯ t_1 κ(q)` of `t_n ⋯ t_1 q`. -/
def K (i : Idx φ hφ) : Mono σ B.S := Mono.pre i.ts i.kap (i.chainK hφs hW)

end Idx


theorem top_wordAct {y : Std σC inc B} {v : Mono σ B.S}
    (ts : List (Letter σ)) (h : ChainAt v.left v.side ts) (hv : v ∈ y.supp)
    (hnil : ts = [] → ∀ w ∈ y.supp, w ≤ v)
    (hcons : ∀ l, firstSide ts = some l → IsLead (some l) y v) :
    IsTopF id (Std.coeff σC inc B (wordAct inc ts • y)) (Mono.pre ts v h) := by
  cases ts with
  | nil =>
    rw [wordAct_nil, one_smul, Mono.pre_nil]
    exact ⟨hv, hnil rfl⟩
  | cons t ts =>
    obtain ⟨l, hl⟩ : ∃ l, firstSide (t :: ts) = some l :=
      Option.ne_none_iff_exists'.1 (by simp [firstSide])
    obtain ⟨-, h2, h3, -⟩ := lead_word (inc := inc) t ts h hl (hcons l hl)
    refine ⟨?_, h2⟩
    rw [Finsupp.mem_support_iff]
    change Std.coeff σC inc B _ _ ≠ 0
    rw [h3]; exact Std.mem_supp.1 hv

namespace Idx

variable {φ hφ}

theorem top_V (i : Idx φ hφ) : IsTopF id (Std.coeff σC inc B i.V) (i.K hφs hW) :=
  top_wordAct i.ts _ i.top.1 (fun h => i.le_kap_nil h) (fun _ hl => i.lead hW hl)

include hφs hW in
theorem eq_of (i i' : Idx φ hφ) (hts : i.ts = i'.ts) (hk : i.kap = i'.kap) : i = i' := by
  have hj : i.j = i'.j := by rw [← i.kap_left hφs, ← i'.kap_left hφs, hk]
  have hμ : i.μ = i'.μ := by
    by_contra hne
    have hsome : ∀ (a b : Idx φ hφ) (l : Λ), a.kap = b.kap → a.μ = none → b.μ = some l →
        False := by
      intro a b l hab ha hb
      have := hW.nolead none (some l) a.qv (a.qv_mem ha) b.qv (b.qv_mem hb) 1 a.kap
        (by rw [msupp_none]; exact a.top.1)
        (by
          rw [one_smul, hab]
          exact isLead_none_of_max (hW.pure_some l _ (b.qv_mem hb) b.qv_ne_zero) b.top.1
            (b.le_kap_some hW hb))
      exact absurd this.1 (by simp)
    rcases hi : i.μ with _ | l <;> rcases hi' : i'.μ with _ | l'
    · exact hne (hi.trans hi'.symm)
    · exact hsome i i' l' hk hi hi'
    · exact hsome i' i l hk.symm hi' hi
    · have e1 := i.side_kap_some hW hi
      have e2 := i'.side_kap_some hW hi'
      rw [hk] at e1
      exact hne ((hi.trans (e1.symm.trans e2)).trans hi'.symm)
  obtain ⟨μ, j, ts, ch, q⟩ := i
  obtain ⟨μ', j', ts', ch', q'⟩ := i'
  obtain rfl : μ = μ' := hμ
  obtain rfl : j = j' := hj
  obtain rfl : ts = ts' := hts
  obtain rfl : q = q' := Subtype.ext hk
  rfl

include hφs hW in
theorem no_proper (i i' : Idx φ hφ) (m : List (Letter σ)) (hm : m ≠ [])
    (hts : i.ts = i'.ts ++ m) (hw : i'.kap.word = m ++ i.kap.word)
    (hb : i'.kap.base = i.kap.base) : False := by
  set v := i.kap with hvdef
  have hch : ChainAt v.left v.side m := by
    have := i'.kap.chain
    rw [hw, hb, chain_iff, chainAt_append, ← wordLeft_eq, ← wordSide_eq] at this
    exact this.1
  have hv' : i'.kap = Mono.pre m v hch := Mono.ext hb hw
  have hv'supp : i'.kap ∈ i'.qv.supp := i'.top.1
  obtain ⟨t, m₀, rfl⟩ := List.exists_cons_of_ne_nil hm
  have hfs : firstSide i.ts = firstSide (t :: m₀) := by rw [hts, firstSide_append _ _ hm]
  obtain ⟨l, hl⟩ : ∃ l, firstSide (t :: m₀) = some l :=
    Option.ne_none_iff_exists'.1 (by simp [firstSide])
  have hlead : IsLead (some l) i.qv v := i.lead hW (hfs.trans hl)
  obtain ⟨p1, p2, p3, p4⟩ := lead_word (inc := inc) t m₀ hch hl hlead
  rcases hμ' : i'.μ with _ | l'
  · have := hW.nolead none i.μ i'.qv (i'.qv_mem hμ') i.qv (i.qv_mem rfl)
      (wordAct inc (t :: m₀)) i'.kap (by rw [msupp_none]; exact hv'supp) (by
        rw [hv']
        refine isLead_none_of_max p1 ?_ p2
        rw [Std.mem_supp, p3]; exact Std.mem_supp.1 hlead.mem_supp)
    have h2 := this.2
    rw [p4] at h2; omega
  · have hside : i'.kap.side = some l' := i'.side_kap_some hW hμ'
    rw [hv', Mono.side_pre] at hside
    have hl' : t.side = l' := Option.some.inj hside
    subst hl'
    have hmem : Mono.pre m₀ v hch.1 ∈ msupp σC inc B (some t.side) i'.qv := by
      rw [mem_msupp_some]
      refine ⟨?_, i'.kap, hv'supp, ?_⟩
      · rw [Mono.side_pre]; exact fun e => hch.2.2 e.symm
      · rw [hv', Mono.pre_cons, strip_cons]
    cases m₀ with
    | nil =>
      rw [Mono.pre_nil] at hmem
      rw [firstSide_singleton, Option.some.injEq] at hl
      subst hl
      have := hW.nolead (some t.side) i.μ i'.qv (i'.qv_mem hμ') i.qv (i.qv_mem rfl) 1 v hmem
        (by rw [one_smul]; exact hlead)
      obtain ⟨t', ht', htt⟩ := exists_of_firstSide (hfs.trans (firstSide_singleton t))
      exact i.chain.last_ne t' ht' (by rw [htt]; exact this.1)
    | cons t₂ m₁ =>
      have hl2 : firstSide (t₂ :: m₁) = some l := by rw [← firstSide_cons_cons t]; exact hl
      obtain ⟨r1, r2, r3, r4⟩ := lead_word (inc := inc) t₂ m₁ hch.1 hl2 hlead
      have hmem' : Mono.pre (t₂ :: m₁) v hch.1 ∈ (wordAct inc (t₂ :: m₁) • i.qv).supp := by
        rw [Std.mem_supp, r3]; exact Std.mem_supp.1 hlead.mem_supp
      have hs2 : (Mono.pre (t₂ :: m₁) v hch.1).side ≠ some t.side := by
        rw [Mono.side_pre]; exact fun e => hch.2.2 e.symm
      have := hW.nolead (some t.side) i.μ i'.qv (i'.qv_mem hμ') i.qv (i.qv_mem rfl)
        (wordAct inc (t₂ :: m₁)) _ hmem (isLead_of_max hmem' r2 hs2)
      have h2 := this.2
      rw [r4] at h2; omega

/-- **Lemma 8.1**: the leading terms are pairwise distinct. -/
theorem K_injective : Function.Injective (Idx.K (φ := φ) (hφ := hφ) hφs hW) := by
  intro i i' h
  have hb : i.kap.base = i'.kap.base := by
    have := congrArg Mono.base h; exact this
  have hw : i.ts ++ i.kap.word = i'.ts ++ i'.kap.word := by
    have := congrArg Mono.word h; exact this
  rcases List.append_eq_append_iff.1 hw with ⟨a', h1, h2⟩ | ⟨c', h1, h2⟩
  · by_cases ha : a' = []
    · subst ha
      rw [List.append_nil] at h1
      exact eq_of hφs hW i i' h1.symm (Mono.ext hb h2)
    · exact (no_proper hφs hW i' i a' ha h1 h2 hb).elim
  · by_cases hc : c' = []
    · subst hc
      rw [List.append_nil] at h1
      exact eq_of hφs hW i i' h1 (Mono.ext hb h2.symm)
    · exact (no_proper hφs hW i i' c' hc h1 h2 hb.symm).elim

include hφs hW in
/-- **Lemma 8.1**: the family `t_n ⋯ t_1 q` is linearly independent. -/
theorem linearIndependent_V : LinearIndependent k (Idx.V (φ := φ) (hφ := hφ) (inc := inc)) :=
  LinearIndependent.of_comp (Std.coeff σC inc B).toLinearMap
    (linearIndependent_of_top id Function.injective_id _ (Idx.K hφs hW) (K_injective hφs hW)
      (top_V hφs hW))

end Idx

/-! ## Proposition 8.2 -/

variable (B' : HomBases σ N')

/-- The lift `Std(N') → Std` of the `φ μ`. -/
noncomputable def liftΦ : Std σC inc B' →ₗ[C] Std σC inc B :=
  (Std.exists_unique_lift σC inc B' (Std σC inc B) φ hφs).exists.choose

theorem liftΦ_incl (μ : Option Λ) (a : N' μ) :
    liftΦ φ hφs B' (Std.incl σC inc B' μ a) = φ μ a :=
  (Std.exists_unique_lift σC inc B' (Std σC inc B) φ hφs).exists.choose_spec μ a

variable {φ hφ} in
/-- The family `t_n ⋯ t_1 q`, in `Std(N')`. -/
noncomputable def Idx.V' (i : Idx φ hφ) : Std σC inc B' :=
  wordAct inc i.ts • Std.incl σC inc B' i.μ i.elt

variable {hφ} in
theorem Idx.liftΦ_V' (i : Idx φ hφ) : liftΦ φ hφs B' (i.V' B') = i.V := by
  rw [Idx.V', map_smul, liftΦ_incl]; rfl

/-- The family `t_n ⋯ t_1 q` spans `Std(N')`. -/
theorem Idx.span_V' : Submodule.span k (Set.range (Idx.V' (φ := φ) (hφ := hφ) (inc := inc) B')) = ⊤ := by
  rw [eq_top_iff, ← (Std.monoBasis σC inc B').span_eq, Submodule.span_le]
  rintro _ ⟨w, rfl⟩
  rw [Std.monoBasis_apply]
  obtain ⟨⟨μ, j, s⟩, ts, ch⟩ := w
  have h' : ChainAt j μ ts := (chain_iff _ _).1 ch
  have e := Std.mono_pre (σC := σC) (inc := inc) (B := B') ts (Mono.ofBase ⟨μ, j, s⟩) h'
  rw [← Std.incl_basis, B'.basis_apply] at e
  rw [show (⟨⟨μ, j, s⟩, ts, ch⟩ : Mono σ B'.S) = Mono.pre ts (Mono.ofBase ⟨μ, j, s⟩) h' from
    Mono.ext rfl (List.append_nil ts).symm, e]
  let ψ : eSub σ N' μ j →ₗ[k] Std σC inc B' :=
    smulLin (k := k) (wordAct inc ts) ∘ₗ Std.incl σC inc B' μ ∘ₗ (eSub σ N' μ j).subtype
  have hmem := Submodule.apply_mem_span_image_of_mem_span ψ
    ((eb φ hφ μ j (firstSide ts)).b.mem_span (B'.b μ j s))
  refine Submodule.span_mono ?_ hmem
  rintro _ ⟨_, ⟨q, rfl⟩, rfl⟩
  exact ⟨⟨μ, j, ts, h', q⟩, rfl⟩

include hφ hW in
theorem liftΦ_injective : Function.Injective (liftΦ φ hφs B') := by
  rw [injective_iff_map_eq_zero]
  intro z hz
  have hz' : z ∈ LinearMap.range (Finsupp.linearCombination k
      (Idx.V' (φ := φ) (hφ := hφ) (inc := inc) B')) := by
    rw [Finsupp.range_linearCombination, Idx.span_V']; trivial
  obtain ⟨c, rfl⟩ := hz'
  have h1 : (liftΦ φ hφs B').restrictScalars k (Finsupp.linearCombination k (Idx.V' B') c) =
      Finsupp.linearCombination k (Idx.V (φ := φ) (hφ := hφ) (inc := inc)) c := by
    rw [Finsupp.apply_linearCombination]
    have hc : ⇑((liftΦ φ hφs B').restrictScalars k) ∘ Idx.V' B' =
        Idx.V (φ := φ) (hφ := hφ) (inc := inc) := funext fun i => Idx.liftΦ_V' φ hφs B' i
    rw [hc]
  have h2 : Finsupp.linearCombination k (Idx.V (φ := φ) (hφ := hφ) (inc := inc)) c = 0 := by
    rw [← h1]; exact hz
  have hc : c = 0 := linearIndependent_iff.1 (Idx.linearIndependent_V (hφ := hφ) hφs hW) c h2
  rw [hc, map_zero]

theorem range_liftΦ :
    LinearMap.range (liftΦ φ hφs B') = Submodule.span C (⋃ μ, Set.range (φ μ)) := by
  rw [LinearMap.range_eq_map, ← Std.span_incl σC inc B', Submodule.map_span, Set.image_iUnion]
  congr 1
  refine Set.iUnion_congr fun μ => ?_
  rw [← Set.range_comp]
  congr 1
  funext a
  exact liftΦ_incl φ hφs B' μ a

include hφ hφs hW in
/-- **Proposition 8.2**: the lift of the `φ μ` is injective, with image the submodule they
generate. -/
theorem exists_liftΦ : ∃ Φ : Std σC inc B' →ₗ[C] Std σC inc B, Function.Injective Φ ∧
    LinearMap.range Φ = Submodule.span C (⋃ μ, Set.range (φ μ)) ∧
    ∀ μ a, Φ (Std.incl σC inc B' μ a) = φ μ a :=
  ⟨liftΦ φ hφs B', liftΦ_injective φ hφ hφs hW B', range_liftΦ φ hφs B', liftΦ_incl φ hφs B'⟩

include hφs in
/-- The submodule generated is spanned over `k` by the family `t_n ⋯ t_1 q`. -/
theorem exists_linearCombination {x : Std σC inc B}
    (hx : x ∈ Submodule.span C (⋃ μ, Set.range (φ μ))) :
    ∃ c : Idx φ hφ →₀ k, Finsupp.linearCombination k (Idx.V (inc := inc)) c = x := by
  let B' : HomBases σ N' := (nonempty_homBases σ N').some
  rw [← range_liftΦ φ hφs B'] at hx
  obtain ⟨z, rfl⟩ := hx
  have hz : z ∈ LinearMap.range (Finsupp.linearCombination k
      (Idx.V' (φ := φ) (hφ := hφ) (inc := inc) B')) := by
    rw [Finsupp.range_linearCombination, Idx.span_V']; trivial
  obtain ⟨c, rfl⟩ := hz
  refine ⟨c, ?_⟩
  have h1 : (liftΦ φ hφs B').restrictScalars k (Finsupp.linearCombination k (Idx.V' B') c) =
      Finsupp.linearCombination k (Idx.V (φ := φ) (hφ := hφ) (inc := inc)) c := by
    rw [Finsupp.apply_linearCombination]
    have hc : ⇑((liftΦ φ hφs B').restrictScalars k) ∘ Idx.V' B' =
        Idx.V (φ := φ) (hφ := hφ) (inc := inc) := funext fun i => Idx.liftΦ_V' φ hφs B' i
    rw [hc]
  exact h1.symm

/-! ## Lemma 8.3 and Proposition 8.4 -/

include hφ hφs hW in
/-- **Lemma 8.3**: an element of the submodule generated by the family, all of whose terms are
base elements of `N_{μ₁}`, lies in the image of `φ μ₁`. -/
theorem mem_range_of_mem_span {μ₁ : Option Λ} {x : Std σC inc B}
    (hx : x ∈ Submodule.span C (⋃ μ, Set.range (φ μ)))
    (hsupp : ∀ w ∈ x.supp, w.deg = 0 ∧ w.side = μ₁) : x ∈ Set.range (φ μ₁) := by
  classical
  obtain ⟨c, rfl⟩ := exists_linearCombination φ hφ hφs hx
  have hcoeff : Std.coeff σC inc B (Finsupp.linearCombination k (Idx.V (inc := inc)) c) =
      Finsupp.linearCombination k (fun i : Idx φ hφ => Std.coeff σC inc B i.V) c := by
    rw [Finsupp.linearCombination_apply, Finsupp.linearCombination_apply, map_finsuppSum]
    simp [map_smul]
  have hdeg : ∀ i ∈ c.support, i.ts = [] ∧ ∀ w ∈ i.qv.supp, w.deg = 0 := by
    by_cases hc : c = 0
    · simp [hc]
    obtain ⟨i₀, -, htop, hle⟩ := top_of_linearCombination id Function.injective_id
      (fun i : Idx φ hφ => Std.coeff σC inc B i.V) (Idx.K hφs hW) (Idx.K_injective hφs hW)
      (Idx.top_V hφs hW) hc
    have h0 : (i₀.K hφs hW).deg = 0 := by
      refine (hsupp _ ?_).1
      change _ ∈ (Std.coeff σC inc B _).support
      rw [hcoeff]; exact htop.1
    intro i hi
    have hKi : (i.K hφs hW).deg = 0 := by
      have := Mono.deg_le_of_le (w := i.K hφs hW) (w' := i₀.K hφs hW) (hle i hi); omega
    rw [Idx.K, Mono.deg_pre] at hKi
    have hts : i.ts = [] := List.eq_nil_of_length_eq_zero (by omega)
    refine ⟨hts, fun w hw => ?_⟩
    have := Mono.deg_le_of_le (i.le_kap_nil hts w hw)
    omega
  -- the components
  let xs : Option Λ → Std σC inc B := fun μ =>
    ∑ i ∈ c.support.filter (fun i => i.μ = μ), c i • i.qv
  have hsum : Finsupp.linearCombination k (Idx.V (inc := inc)) c = ∑ μ, xs μ := by
    rw [Finsupp.linearCombination_apply, Finsupp.sum,
      Finset.sum_congr rfl fun i hi => (show c i • i.V = c i • i.qv by
        rw [Idx.V, (hdeg i hi).1, wordAct_nil, one_smul])]
    exact (Finset.sum_fiberwise c.support (fun i => i.μ) _).symm
  have hL : WP fun μ => ((LinearMap.range (φ μ) : Submodule k (Std σC inc B)) :
      Set (Std σC inc B)) := by
    simpa only [LinearMap.coe_range] using hW
  have hmem := WP.mem_of_sum hL xs (fun μ => Submodule.sum_mem _ fun i hi =>
      Submodule.smul_mem _ _ (LinearMap.mem_range.2 (i.qv_mem (Finset.mem_filter.1 hi).2)))
    (fun μ w hw => by
      obtain ⟨i, hi, hw⟩ := Finset.mem_biUnion.1 (Std.supp_sum _ _ hw)
      exact (hdeg i (Finset.mem_filter.1 hi).1).2 w (Std.supp_smul _ _ hw))
    (μ₁ := μ₁) (fun w hw => (hsupp w (by rw [hsum]; exact hw)).2)
  rw [hsum]
  exact LinearMap.mem_range.1 hmem

theorem eq_ofBase_of_strip {μ : Option Λ} {w : Mono σ B.S} (h : strip B μ w = none) :
    ∃ j s, w = Mono.ofBase ⟨μ, j, s⟩ := by
  obtain ⟨x, rfl⟩ := monoJoin_surjective B μ w
  rcases x with ⟨j, s⟩ | ⟨u, o⟩
  · exact ⟨j, s, rfl⟩
  · rw [strip_join_inr] at h; exact absurd h (by simp)

variable (htop : Submodule.span C (⋃ μ, Set.range (φ μ)) = ⊤)

include hφ hφs hW htop in
/-- `N_μ ⊆ L_μ` (Lemma 8.3). -/
theorem incl_mem_range (μ₁ : Option Λ) (n : N μ₁) :
    Std.incl σC inc B μ₁ n ∈ Set.range (φ μ₁) :=
  mem_range_of_mem_span φ hφ hφs hW (by rw [htop]; trivial) fun w hw => by
    obtain ⟨j, s, rfl⟩ := eq_ofBase_of_strip (strip_of_mem_supp_incl hw)
    exact ⟨rfl, rfl⟩

include hφ hφs hW htop in
/-- `L_μ ⊆ N_μ`: a monomial of `y ∈ L_μ` that is not a base element of `N_μ` would give a
`μ`-leading term `u = t_n ⋯ t_1 s` in the `μ`-support of `y`, with `s ∈ N_ν ⊆ L_ν`. -/
theorem mem_range_incl (μ : Option Λ) (a : N' μ) :
    φ μ a ∈ Set.range (Std.incl σC inc B μ) := by
  by_contra hne
  obtain ⟨w, hw, hs⟩ : ∃ w ∈ (φ μ a).supp, strip B μ w ≠ none := by
    by_contra hc
    push_neg at hc
    apply hne
    rw [← LinearMap.coe_range, SetLike.mem_coe, Std.eq_sum_mono (φ μ a)]
    refine Submodule.sum_mem _ fun w hw => Submodule.smul_mem _ _ ?_
    obtain ⟨j, s, rfl⟩ := eq_ofBase_of_strip (hc w hw)
    exact ⟨_, Std.incl_basis σC inc B μ j s⟩
  obtain ⟨u, hu⟩ := Option.ne_none_iff_exists'.1 hs
  have hmem : u.1 ∈ msupp σC inc B μ (φ μ a) :=
    (mem_msupp_iff_coord u).2 (coord_ne_zero_iff.2 ⟨w, hw, hu⟩)
  obtain ⟨⟨⟨ν, j, s⟩, ts, ch⟩, hus⟩ := u
  have hx := incl_mem_range φ hφ hφs hW htop ν (B.basis ν ⟨j, s⟩)
  have hmono : Std.mono σC inc B ⟨⟨ν, j, s⟩, ts, ch⟩ =
      wordAct inc ts • Std.incl σC inc B ν (B.basis ν ⟨j, s⟩) := by
    rw [Std.incl_basis]
    have h := Std.mono_pre (σC := σC) (inc := inc) ts (Mono.ofBase ⟨ν, j, s⟩) ((chain_iff _ _).1 ch)
    rwa [← Mono.eq_pre_ofBase ⟨⟨ν, j, s⟩, ts, ch⟩] at h
  obtain ⟨hμν, hdeg⟩ := hW.nolead μ ν (φ μ a) ⟨a, rfl⟩ _ hx (wordAct inc ts) _ hmem
    (by rw [← hmono]; exact isLead_mono hus)
  rw [← hmono, Std.deg_mono, Std.incl_basis, Std.deg_mono] at hdeg
  have hts : ts = [] := List.eq_nil_of_length_eq_zero (by change ts.length ≤ 0 at hdeg; omega)
  subst hts
  exact hus hμν.symm

include hφ hφs hW htop in
/-- **Proposition 8.4**: a well-positioned family generating `Std` is the family of components. -/
theorem range_eq_incl (μ : Option Λ) :
    Set.range (φ μ) = Set.range (Std.incl σC inc B μ) :=
  Set.Subset.antisymm (by rintro _ ⟨a, rfl⟩; exact mem_range_incl φ hφ hφs hW htop μ a)
    (by rintro _ ⟨n, rfl⟩; exact incl_mem_range φ hφ hφs hW htop μ n)

end WP

end Bergman.Core
