/-
**The submodule generated by a well-positioned family** (Bergman §8).

A `SubFam` is a family of `k`-subspaces `L μ ⊆ Std` closed under `R_μ` (so each `L μ` is an
`R_μ`-module).

* `SubFam.lift_of_wp` — **Proposition 8.2**: if `(L μ)` is well-positioned, the `C`-submodule it
  generates is standard with components `L μ` (the natural map `⊕ C ⊗ L μ → ∑ C L μ` is an
  isomorphism), i.e. it has the universal property.  Bergman's proof: choose bases `Q_μ` of `L μ`
  with distinct leading terms (and bases `Q_{0,λ}` of `L none` with distinct `λ`-leading terms);
  the products `t_n ⋯ t_1 q` have distinct leading terms (Lemma 8.1), hence are linearly
  independent, and they span.
* `SubFam.eq_incl_of_wp` — **Proposition 8.4**: if moreover it generates all of `Std`, then
  `L μ = N_μ` for all `μ`.
-/
import KappaMonoid.Bergman.Core.Pure
import KappaMonoid.Bergman.Core.Pres

universe u

set_option linter.unusedSectionVars false

namespace Bergman.Core

open Module

variable {k : Type u} [Field k] {ι : Type} [Fintype ι] [DecidableEq ι]
  {Λ : Type} [Fintype Λ] [DecidableEq Λ]
  {R : Λ → Type u} [∀ l, Ring (R l)] [∀ l, Algebra k (R l)]
  {σ : ∀ l, (ι → k) →ₐ[k] R l} [Fact (∀ l, Function.Injective (σ l))]
  {C : Type u} [Ring C] [Algebra k C] (σC : (ι → k) →ₐ[k] C) (inc : ∀ l, R l →ₐ[k] C)
  [Fact (IsCoprod k σ C σC inc)]
  {N : Option Λ → Type u} [∀ μ, AddCommGroup (N μ)] [∀ μ, Module (Rμ k ι R μ) (N μ)]
  [∀ μ, Module k (N μ)] [∀ μ, IsScalarTower k (Rμ k ι R μ) (N μ)] (B : HomBases σ N)

/-- A family of `k`-subspaces of `Std`, each closed under `R_μ`. -/
structure SubFam where
  /-- The subspaces. -/
  L : Option Λ → Submodule k (Std σC inc B)
  smul_mem : ∀ μ (r : Rμ k ι R μ) y, y ∈ L μ → incμ σC inc μ r • y ∈ L μ

variable {σC inc B}

noncomputable instance SubFam.instModule (F : SubFam σC inc B) (μ : Option Λ) :
    Module (Rμ k ι R μ) (F.L μ) where
  smul r y := ⟨incμ σC inc μ r • (y : Std σC inc B), F.smul_mem μ r y y.2⟩
  one_smul y := Subtype.ext (show incμ σC inc μ 1 • (y : Std σC inc B) = y by
    rw [map_one, one_smul])
  mul_smul r s y := Subtype.ext (show incμ σC inc μ (r * s) • (y : Std σC inc B) =
    incμ σC inc μ r • incμ σC inc μ s • (y : Std σC inc B) by rw [map_mul, mul_smul])
  smul_zero r := Subtype.ext (show incμ σC inc μ r • (0 : Std σC inc B) = 0 from smul_zero _)
  smul_add r y z := Subtype.ext (show incμ σC inc μ r • ((y : Std σC inc B) + z) =
    incμ σC inc μ r • (y : Std σC inc B) + incμ σC inc μ r • (z : Std σC inc B) from smul_add _ _ _)
  add_smul r s y := Subtype.ext (show incμ σC inc μ (r + s) • (y : Std σC inc B) =
    incμ σC inc μ r • (y : Std σC inc B) + incμ σC inc μ s • (y : Std σC inc B) by
    rw [map_add, add_smul])
  zero_smul y := Subtype.ext (show incμ σC inc μ 0 • (y : Std σC inc B) = 0 by
    rw [map_zero, zero_smul])

theorem SubFam.coe_smul (F : SubFam σC inc B) (μ : Option Λ) (r : Rμ k ι R μ) (y : F.L μ) :
    ((r • y : F.L μ) : Std σC inc B) = incμ σC inc μ r • (y : Std σC inc B) := rfl

instance SubFam.instTower (F : SubFam σC inc B) (μ : Option Λ) :
    IsScalarTower k (Rμ k ι R μ) (F.L μ) :=
  ⟨fun c r y => Subtype.ext (show incμ σC inc μ (c • r) • (y : Std σC inc B) =
    c • incμ σC inc μ r • (y : Std σC inc B) by rw [map_smul, smul_assoc])⟩

/-- The `C`-submodule generated by the family. -/
noncomputable abbrev SubFam.span (F : SubFam σC inc B) : Submodule C (Std σC inc B) :=
  Submodule.span C (⋃ μ, (F.L μ : Set (Std σC inc B)))

/-- The inclusion of a member of the family into the submodule it generates. -/
noncomputable def SubFam.incl (F : SubFam σC inc B) (μ : Option Λ) : F.L μ →ₗ[k] F.span where
  toFun y := ⟨y, Submodule.subset_span (Set.mem_iUnion.2 ⟨μ, y.2⟩)⟩
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- **Proposition 8.2**: a well-positioned family is a standard presentation of the submodule it
generates. -/
theorem SubFam.lift_of_wp (F : SubFam σC inc B) (hF : WP fun μ => (F.L μ : Set (Std σC inc B)))
    (P : Type u) [AddCommGroup P] [Module C P] [Module k P] [IsScalarTower k C P]
    (g : ∀ μ, F.L μ →ₗ[k] P)
    (hg : ∀ μ (r : Rμ k ι R μ) a, g μ (r • a) = incμ σC inc μ r • g μ a) :
    ∃! f : F.span →ₗ[C] P, ∀ μ a, f (F.incl μ a) = g μ a := sorry

/-- The standard presentation of the submodule generated by a well-positioned family. -/
noncomputable def SubFam.pres (F : SubFam σC inc B)
    (hF : WP fun μ => (F.L μ : Set (Std σC inc B))) : StdPres σ σC inc F.span where
  coprod := Fact.out
  A μ := F.L μ
  j := F.incl
  j_smul μ r a := rfl
  lift P _ _ _ _ g hg := F.lift_of_wp hF P g hg

/-- **Proposition 8.4**: a well-positioned family generating `Std` is the family of components. -/
theorem SubFam.eq_incl_of_wp (F : SubFam σC inc B)
    (hF : WP fun μ => (F.L μ : Set (Std σC inc B))) (htop : F.span = ⊤) (μ : Option Λ) :
    F.L μ = LinearMap.range (Std.incl σC inc B μ) := sorry

end Bergman.Core
