/-
**Section 5, unnumbered claims — the monoid theory.**

Two things §5 says in passing and does not prove, both pure monoid theory:

* **The counterexample `ℕ₀² ∪ {∞}` of Corollary 5.5(2), (3) satisfies the standing hypotheses of
  the section** (`kappa_monoids.tex:1995`): it is generated by `x₁ = (1,0)` and `x₂ = (0,1)`
  (`cex_kGenerates`) and it is not cyclic (`cex_not_cyclic`).  Without this the counterexample
  would not refute a statement made *under* those hypotheses.

* **Cyclic `ℵ₀`-monoids** (`kappa_monoids.tex:1989–1992`).  For `H = ⟨x⟩` the condition
  `ℵ₀x ≠ nx` for all `n ∈ ℕ₀` is equivalent to `x` being a faithful order-unit
  (`isFaithful_iff_of_kGenerates`), makes `H` braided over `add x` (`isBraidedOver_addOf_of_ne`),
  and is equivalent to `H ≅ C ∪ {∞}` for a nonzero reduced cyclic monoid `C`
  (`ne_nsmul_iff_exists_withTop`).  The module-theoretic half of the claim — realisation as
  `V^{ℵ₀}(R)` of a nonzero hereditary ring — is in `TwoGen/ExtraRealization.lean`.
-/
import KappaMonoid.TwoGen.Counterexample
import KappaMonoid.TwoGen.Lemma52
import KappaMonoid.Examples.NatBraiding
import KappaMonoid.Core.Cyclic
import KappaMonoid.Core.OrderUnitTransfer
import KappaMonoid.Braiding.Prop310

universe u v w

open Cardinal Function Set

namespace KappaMonoid

namespace TwoGen

open KMonoid LMonoid

/-! ## Cyclic `κ`-monoids: every element is a finite multiple or `ℵ₀ x` -/

section CyclicBasic

variable {H : Type v} [KMonoid (ℵ₀ : Cardinal.{u}) H]

/-- In an `ℵ₀`-monoid generated by `x`, every element is `ℵ₀ x` or a finite multiple `k x`.

This is `exists_cmul_of_kGenerates` (every element is `α x` with `α ≤ ℵ₀`) with the two cases
`α < ℵ₀` and `α = ℵ₀` separated. -/
theorem eq_cmul_top_or_nsmul {x : H} (hgen : KGenerates (ℵ₀ : Cardinal.{u}) ({x} : Set H))
    (y : H) : y = ℵ₀∙x ∨ ∃ k : ℕ, y = k • x := by
  obtain ⟨α, hα, rfl⟩ := exists_cmul_of_kGenerates hgen y
  rcases lt_or_ge α ℵ₀ with hfin | hinf
  · obtain ⟨k, rfl⟩ := Cardinal.lt_aleph0.mp hfin
    exact Or.inr ⟨k, (cmul_congr rfl _ _ x).trans (cmul_natCast x k)⟩
  · exact Or.inl (cmul_congr (le_antisymm hα hinf) _ _ x)

/-- In an `ℵ₀`-monoid generated by `x`, the element `ℵ₀ x` absorbs everything: `ℵ₀ x + t = ℵ₀ x`.
Every `t` is `α x` with `α ≤ ℵ₀`, and `ℵ₀ + α = ℵ₀`. -/
theorem cmul_top_add_of_kGenerates {x : H} (hgen : KGenerates (ℵ₀ : Cardinal.{u}) ({x} : Set H))
    (t : H) : ℵ₀∙x + t = ℵ₀∙x := by
  obtain ⟨α, hα, rfl⟩ := exists_cmul_of_kGenerates hgen t
  have hsum : (ℵ₀ : Cardinal.{u}) + α = ℵ₀ := Cardinal.add_eq_left le_rfl hα
  rw [← cmul_add le_rfl hα hsum.le]
  exact cmul_congr hsum _ _ x

/-- **A faithful order-unit forbids `ℵ₀ x = n x`** in an `ℵ₀`-monoid generated by `x`.

Paper proof (unwritten; the forward half of "easily seen", `kappa_monoids.tex:1989`): if
`ℵ₀ x = n x`, every element — in particular `u` — is a finite multiple `k x`, and then
`ℵ₀ u ≼ n u`: for `k = 0` because `ℵ₀ u = 0`, for `k ≥ 1` because `ℵ₀ u = ℵ₀ x = n x ≼ n u`.
With `n < ℵ₀` that contradicts faithfulness of `u`. -/
theorem ne_nsmul_of_isFaithful {x : H} (hgen : KGenerates (ℵ₀ : Cardinal.{u}) ({x} : Set H))
    {u : H} (hu : IsFaithful (κ := (ℵ₀ : Cardinal.{u})) u) (n : ℕ) : ℵ₀∙x ≠ n • x := by
  intro h
  have hnκ : ((n : ℕ) : Cardinal.{u}) ≤ ℵ₀ := le_of_lt Cardinal.natCast_lt_aleph0
  obtain ⟨k, rfl⟩ : ∃ k : ℕ, u = k • x := by
    rcases eq_cmul_top_or_nsmul hgen u with rfl | hk
    · exact ⟨n, h⟩
    · exact hk
  -- `ℵ₀ u ≼ n u`, contradicting faithfulness
  have hle : ℵ₀∙(k • x) ≼ n • (k • x) := by
    rcases Nat.eq_zero_or_pos k with rfl | hk
    · rw [zero_nsmul, cmul_zero]
      exact AddLe.zero_le _
    · have hmul : (ℵ₀ : Cardinal.{u}) * (k : Cardinal.{u}) = ℵ₀ :=
        Cardinal.mul_eq_left le_rfl (le_of_lt Cardinal.natCast_lt_aleph0)
          (Nat.cast_ne_zero.mpr (by omega))
      have hkκ : ((k : ℕ) : Cardinal.{u}) ≤ ℵ₀ := le_of_lt Cardinal.natCast_lt_aleph0
      have htop : ℵ₀∙(k • x) = ℵ₀∙x := by
        rw [← cmul_natCast x k, cmul_cmul le_rfl hkκ hmul.le]
        exact cmul_congr hmul _ _ x
      have hxk : x ≼ k • x := ⟨(k - 1) • x, by
        rw [← succ_nsmul', Nat.sub_add_cancel hk]⟩
      rw [htop, h]
      exact nsmul_le_nsmul_right hxk n
  refine hu.2 (n : Cardinal.{u}) ℵ₀ hnκ le_rfl Cardinal.natCast_lt_aleph0 le_rfl ?_
  rw [cmul_natCast]
  exact hle

/-- **For a cyclic `ℵ₀`-monoid `⟨x⟩`, `x` is a faithful order-unit iff `ℵ₀ x ≠ n x` for every
`n ∈ ℕ₀`.**  This is the link between the §5 preamble (`kappa_monoids.tex:1989`) and Lemma 2.15,
which describes the cyclic monoids generated by a faithful order-unit. -/
theorem isFaithful_iff_of_kGenerates {x : H}
    (hgen : KGenerates (ℵ₀ : Cardinal.{u}) ({x} : Set H)) :
    IsFaithful (κ := (ℵ₀ : Cardinal.{u})) x ↔ ∀ n : ℕ, ℵ₀∙x ≠ n • x := by
  refine ⟨fun hu n => ne_nsmul_of_isFaithful hgen hu n, fun hx => ⟨fun y => ?_, ?_⟩⟩
  · obtain ⟨α, hα, rfl⟩ := exists_cmul_of_kGenerates hgen y
    exact cmul_le_cmul hα le_rfl hα x
  · rintro α β hα hβ hαβ hβ0 ⟨c, hc⟩
    obtain ⟨k, rfl⟩ := Cardinal.lt_aleph0.mp (lt_of_lt_of_le hαβ hβ)
    rw [cmul_congr (le_antisymm hβ hβ0) hβ le_rfl x, cmul_top_add_of_kGenerates hgen c] at hc
    exact hx k (hc.trans (cmul_natCast x k))

end CyclicBasic

/-- **Faithfulness is invariant under isomorphism**: a bijective `κ`-homomorphism carries a
faithful order-unit to a faithful order-unit. -/
theorem isFaithful_map_of_bijective {κ : Cardinal.{u}} {H : Type v} {K : Type w} [KMonoid κ H]
    [KMonoid κ K] {e : H → K} (he : IsKHom κ e) (hbij : Function.Bijective e) {u : H}
    (hu : IsFaithful (κ := κ) u) : IsFaithful (κ := κ) (e u) := by
  refine ⟨fun y => ?_, fun α β hα hβ hαβ hβ0 hle => ?_⟩
  · obtain ⟨y', rfl⟩ := hbij.2 y
    obtain ⟨c, hc⟩ := hu.1 y'
    exact ⟨e c, by rw [← he.map_add, hc, he.map_cmul]⟩
  · obtain ⟨c, hc⟩ := hle
    obtain ⟨c', rfl⟩ := hbij.2 c
    refine hu.2 α β hα hβ hαβ hβ0 ⟨c', hbij.1 ?_⟩
    rw [he.map_add, he.map_cmul, he.map_cmul]
    exact hc

/-! ## Braiding over a cyclic base -/

/-- **Braiding over a cyclic `ℵ₀⁻`-monoid.**  Let `X` be an `ℵ₀⁻`-monoid whose every element is a
multiple `n c` of one element `c`, embedded in an `ℵ₀`-monoid `K` by an injective
`ℵ₀⁻`-homomorphism `f` whose image generates `K`.  If a family in `X` with infinite support never
sums to an element of `f(X)`, then `K` is `ℵ₀⁻`-braided over `X`.

Two families with equal sum are both finitely or both infinitely supported, by the last
hypothesis.  In the first case they have equal finite sums in `X` (injectivity of `f`) and are
braided by Lemma 3.4(1).  In the second, write each entry as `m_i c` with `m_i = 0` exactly when
the entry is `0`: the two families of multiplicities in `ℕ₀` have infinite support, so are braided
by Examples 3.3(1), and `n ↦ n c` carries that braiding to `X`.  The case `X = ℕ₀` is
`isBraidedOver_withTop_nat`. -/
theorem isBraidedOver_of_cyclic_base {X : Type v} [LMonoid (ℵ₀ : Cardinal.{u}) X] {K : Type w}
    [KMonoid (ℵ₀ : Cardinal.{u}) K] (c : X) (hc : ∀ y : X, ∃ n : ℕ, y = n • c) {f : X → K}
    (hf : IsLHom (Order.le_succ (ℵ₀ : Cardinal.{u})) f) (hinj : Function.Injective f)
    (hgen : ∀ h : K, ∃ a : Idx (ℵ₀ : Cardinal.{u}) → X,
      h = KMonoid.ksum (κ := ℵ₀) fun i => f (a i))
    (hinf : ∀ a : Idx (ℵ₀ : Cardinal.{u}) → X, (Function.support a).Infinite →
      (KMonoid.ksum (κ := ℵ₀) fun i => f (a i)) ∉ Set.range f) :
    IsBraidedOver ℵ₀ ℵ₀ X K (Order.le_succ ℵ₀) f := by
  classical
  -- a finitely supported family sums to the image of its finite sum
  have hfin : ∀ (a : Idx (ℵ₀ : Cardinal.{u}) → X) (hs : #(Function.support a) < ℵ₀),
      (KMonoid.ksum (κ := ℵ₀) fun i => f (a i))
        = f (LMonoid.lsumOf (lam := ℵ₀) hs fun i : Function.support a => a i) := by
    intro a hs
    rw [hf.2 hs]
    refine KMonoid.sumOf_eq_sumOf_subset (hι := CardLE.mk' (le_of_eq (mk_Idx _))) _ fun i hi => ?_
    show f (a i) = 0
    rw [Function.notMem_support.mp hi]
    exact hf.1
  refine ⟨hf, hinj, hgen, fun a b hab => ?_⟩
  by_cases ha : (Function.support a).Finite <;> by_cases hb : (Function.support b).Finite
  · have ha' := Cardinal.lt_aleph0_iff_set_finite.mpr ha
    have hb' := Cardinal.lt_aleph0_iff_set_finite.mpr hb
    refine isBraided_of_small_support a b ha' hb' (hinj ?_)
    rw [← hfin a ha', ← hfin b hb']
    exact hab
  · exact absurd ⟨_, ((hfin a (Cardinal.lt_aleph0_iff_set_finite.mpr ha)).symm.trans hab)⟩
      (hinf b hb)
  · exact absurd ⟨_, ((hfin b (Cardinal.lt_aleph0_iff_set_finite.mpr hb)).symm.trans hab.symm)⟩
      (hinf a ha)
  · -- lift both families to `ℕ₀` along `n ↦ n c`, keeping the supports
    choose m hm using hc
    let m' : X → ℕ := fun y => if y = 0 then 0 else m y
    have hm' : ∀ y, y = m' y • c := by
      intro y
      by_cases hy : y = 0
      · simp only [m', if_pos hy, zero_nsmul]
        exact hy
      · simp only [m', if_neg hy]
        exact hm y
    have hsupp : ∀ z : Idx (ℵ₀ : Cardinal.{u}) → X,
        Function.support (fun i => m' (z i)) = Function.support z := by
      intro z
      ext i
      simp only [Function.mem_support, ne_eq]
      constructor
      · intro h hz
        exact h (by simp only [m', if_pos hz])
      · intro hz h
        exact hz ((hm' (z i)).trans (by rw [h, zero_nsmul]))
    let : LMonoid (ℵ₀ : Cardinal.{u}) ℕ := LMonoid.ofAddCommMonoid ℕ
    have hnat : IsBraided (ℵ₀ : Cardinal.{u}) (fun i => m' (a i)) (fun i => m' (b i)) :=
      isBraided_nat_of_infinite_support (le_of_eq (mk_Idx _)) _ _
        (by rw [hsupp]; exact ha) (by rw [hsupp]; exact hb)
    have hg : IsLMonoidHom (ℵ₀ : Cardinal.{u}) (fun n : ℕ => n • c) :=
      isLMonoidHom_aleph0_of_add (g := fun n : ℕ => n • c) (zero_nsmul c)
        (fun p q => add_nsmul c p q)
    have hbr := IsBraided.map_lmonoidHom (g := fun n : ℕ => n • c) hg hnat
    have ea : (fun i => m' (a i) • c) = a := funext fun i => (hm' (a i)).symm
    have eb : (fun i => m' (b i) • c) = b := funext fun i => (hm' (b i)).symm
    rw [ea, eb] at hbr
    exact hbr

/-! ## Cyclic `ℵ₀`-monoids with `ℵ₀ x ≠ n x` -/

section CyclicNe

variable {H : Type u} [KMonoid (ℵ₀ : Cardinal.{u}) H]

/-- If `ℵ₀ x ≠ n x` for all `n`, then `add x` is exactly the set of finite multiples of `x`. -/
theorem mem_addOf_iff_of_ne {x : H} (hgen : KGenerates (ℵ₀ : Cardinal.{u}) ({x} : Set H))
    (hx : ∀ n : ℕ, ℵ₀∙x ≠ n • x) (y : H) : y ∈ add(x) ↔ ∃ m : ℕ, y = m • x := by
  refine ⟨fun ⟨z, n, hzn⟩ => ?_, fun ⟨m, hm⟩ => ⟨0, m, by rw [add_zero, cmul_natCast, hm]⟩⟩
  rcases eq_cmul_top_or_nsmul hgen y with rfl | hk
  · rw [cmul_top_add_of_kGenerates hgen z, cmul_natCast] at hzn
    exact absurd hzn (hx n)
  · exact hk

/-- Finite multiples in `add x` are computed in `H`. -/
theorem coe_nsmul_addOf_self (x : H) (m : ℕ) (a : ↥(add(x))) :
    ((m • a : ↥(add(x))) : H) = m • (a : H) := by
  induction m with
  | zero => rw [zero_nsmul, zero_nsmul]; rfl
  | succ p hp => rw [succ_nsmul, succ_nsmul, ← hp]; rfl

/-- If `ℵ₀ x ≠ n x` for all `n`, the `ℵ₀⁻`-monoid `add x` is cyclic, generated by `x`. -/
theorem exists_nsmul_eq_of_ne {x : H} (hgen : KGenerates (ℵ₀ : Cardinal.{u}) ({x} : Set H))
    (hx : ∀ n : ℕ, ℵ₀∙x ≠ n • x) (y : ↥(add(x))) :
    ∃ m : ℕ, y = m • (⟨x, self_mem_addOf x⟩ : ↥(add(x))) := by
  obtain ⟨m, hm⟩ := (mem_addOf_iff_of_ne hgen hx y).mp y.2
  exact ⟨m, Subtype.ext (by rw [coe_nsmul_addOf_self]; exact hm)⟩

/-- If `ℵ₀ x ≠ n x` for all `n`, no element of `add x` lies above `ℵ₀ x`. -/
theorem not_cmul_top_le_of_mem_addOf {x : H}
    (hgen : KGenerates (ℵ₀ : Cardinal.{u}) ({x} : Set H)) (hx : ∀ n : ℕ, ℵ₀∙x ≠ n • x)
    {y : H} (hy : y ∈ add(x)) : ¬ (ℵ₀∙x ≼ y) := by
  rintro ⟨w, rfl⟩
  obtain ⟨z, n, hzn⟩ := hy
  rw [add_assoc, cmul_top_add_of_kGenerates hgen, cmul_natCast] at hzn
  exact hx n hzn

/-- **A cyclic `ℵ₀`-monoid `⟨x⟩` with `ℵ₀ x ≠ n x` for all `n` is `ℵ₀⁻`-braided over `add x`**,
the cyclic submonoid `{n x : n ∈ ℕ₀}`.  This is the monoid-theoretic content of the backward half
of the §5 preamble (`kappa_monoids.tex:1989`), which the paper calls easily seen.

An infinitely supported family in `add x` sums to something above `ℵ₀ x` — each nonzero entry is
`m x` with `m ≥ 1`, so lies above `x` — and nothing in `add x` lies above `ℵ₀ x`; so
`isBraidedOver_of_cyclic_base` applies. -/
theorem isBraidedOver_addOf_of_ne {x : H} (hgen : KGenerates (ℵ₀ : Cardinal.{u}) ({x} : Set H))
    (hx : ∀ n : ℕ, ℵ₀∙x ≠ n • x) :
    IsBraidedOver ℵ₀ ℵ₀ ↥(add(x)) H (Order.le_succ ℵ₀) (fun y => (y : H)) := by
  classical
  have hx0 : (0 : H) ∈ add(x) := (addOf_isLSubset (κ := (ℵ₀ : Cardinal.{u})) le_rfl x).zero_mem
  refine isBraidedOver_of_cyclic_base ⟨x, self_mem_addOf x⟩ (exists_nsmul_eq_of_ne hgen hx)
    ⟨rfl, fun _ _ => rfl⟩ Subtype.val_injective (fun h => ?_) (fun a ha => ?_)
  · -- `add x` generates `H`, since `x` does
    have hmem : h ∈ kclosure (ℵ₀ : Cardinal.{u}) (add(x)) :=
      kclosure_mono (fun _ hy => (Set.mem_singleton_iff.mp hy) ▸ self_mem_addOf x)
        (kGenerates_iff.mp hgen h)
    obtain ⟨y, hy, rfl⟩ := (mem_kclosure_iff hx0 h).mp hmem
    exact ⟨fun i => ⟨y i, hy i⟩, rfl⟩
  · -- an infinitely supported family sums to something above `ℵ₀ x`
    rintro ⟨w, hw⟩
    refine not_cmul_top_le_of_mem_addOf hgen hx w.2 ?_
    rw [show ((w : ↥(add(x))) : H) = _ from hw]
    set S := Function.support a with hSdef
    have hSle : #S ≤ ℵ₀ := (Cardinal.mk_set_le S).trans (le_of_eq (mk_Idx _))
    have : Infinite S := ha.to_subtype
    have hSeq : #S = ℵ₀ := le_antisymm hSle (Cardinal.aleph0_le_mk S)
    have hsum : (KMonoid.ksum (κ := ℵ₀) fun i => ((a i : ↥(add(x))) : H))
        = ∑[≤ ℵ₀] i : S, ((a i : ↥(add(x))) : H) :=
      sumOf_eq_sumOf_subset (hι := CardLE.mk' (le_of_eq (mk_Idx _))) (hS := CardLE.mk' hSle) _ fun i hi => by
        rw [Function.notMem_support.mp hi]; rfl
    have hge : ∀ i : S, x ≼ ((a i : ↥(add(x))) : H) := by
      rintro ⟨i, hi⟩
      obtain ⟨m, hm⟩ := (mem_addOf_iff_of_ne hgen hx _).mp (a i).2
      have hm0 : m ≠ 0 := by
        rintro rfl
        exact hi (Subtype.ext (hm.trans (zero_nsmul x)))
      exact ⟨(m - 1) • x, by rw [hm, ← succ_nsmul', Nat.sub_add_cancel (Nat.pos_of_ne_zero hm0)]⟩
    refine AddLe.trans (AddLe.of_eq ?_)
      (AddLe.trans (sumOf_le_sumOf (h := CardLE.mk' hSle) hge) (AddLe.of_eq hsum.symm))
    rw [← cmul_eq_sumOf hSle x]
    exact cmul_congr hSeq.symm _ _ x

/-- **The §5 preamble, second sentence** (`kappa_monoids.tex:1992`): a cyclic `ℵ₀`-monoid
`⟨x⟩` has `ℵ₀ x ≠ n x` for all `n ∈ ℕ₀` if and only if it is `C ∪ {∞}` for a nonzero cyclic
monoid `C`.

`C ∪ {∞}` is read as the trivial `ℵ₀`-extension of Examples 2.3(1), `TrivExt.instKMonoid`, which
is how the paper's §2.2 (Lemma 2.15) describes these monoids: finite multiples of the generator
together with one infinite element.  **Not in the paper**: `C` is required to be *reduced*
(`IsConical`).  The trivial extension is only defined for reduced `C`, and nothing is lost —
every `κ`-monoid is reduced (Lemma 2.8(1)), and so is every submonoid of one; among the nonzero
cyclic monoids this excludes only the groups `C_{0,n}`, `n ≥ 2`, which the paper's `C ∪ {∞}`
cannot mean.

Paper proof (unwritten): forward, `C = add x = {n x}` and both `H` and `C ∪ {∞}` are
`ℵ₀⁻`-braided over `C`, hence are the universal `ℵ₀`-extension of `C` (Theorem 3.12(2)) and so
isomorphic.  Backward, the generator `c` of `C` is a faithful order-unit of `C ∪ {∞}`, so its
image in `H` is one, and `ne_nsmul_of_isFaithful` applies. -/
theorem ne_nsmul_iff_exists_withTop {x : H}
    (hgen : KGenerates (ℵ₀ : Cardinal.{u}) ({x} : Set H)) :
    (∀ n : ℕ, ℵ₀∙x ≠ n • x) ↔
      ∃ (C : Type u) (_ : AddCommMonoid C) (hC : IsConical C) (c : C), c ≠ 0 ∧
        (∀ y : C, ∃ n : ℕ, y = n • c) ∧
        letI := TrivExt.instKMonoid hC (le_refl (ℵ₀ : Cardinal.{u}))
        ∃ e : WithTop C → H, IsKHom ℵ₀ e ∧ Function.Bijective e := by
  classical
  constructor
  · intro hx
    -- `C := add x`, which is reduced and cyclic
    have hcoe : ∀ a b : ↥(add(x)), ((a + b : ↥(add(x))) : H) = (a : H) + (b : H) :=
      fun _ _ => rfl
    have hC : IsConical ↥(add(x)) :=
      LMonoid.isConical_of_injective (lam := ℵ₀) (κ := ℵ₀) (fun y : ↥(add(x)) => (y : H))
        Subtype.val_injective rfl hcoe
    have hxmem := self_mem_addOf (κ := (ℵ₀ : Cardinal.{u})) x
    have hx0 : x ≠ 0 := by
      rintro rfl
      exact hx 0 (by rw [cmul_zero, zero_nsmul])
    refine ⟨↥(add(x)), inferInstance, hC, ⟨x, hxmem⟩, fun h => hx0 (congrArg Subtype.val h),
      exists_nsmul_eq_of_ne hgen hx, ?_⟩
    let : KMonoid (ℵ₀ : Cardinal.{u}) (WithTop ↥(add(x))) := TrivExt.instKMonoid hC le_rfl
    have hsupp : ∀ a : Idx (ℵ₀ : Cardinal.{u}) → ↥(add(x)),
        Function.support (fun i => ((a i : ↥(add(x))) : WithTop ↥(add(x))))
          = Function.support a := by
      intro a
      ext i
      simp [Function.mem_support]
    -- `C ∪ {∞}` is braided over `C`
    have hbrW : IsBraidedOver ℵ₀ ℵ₀ ↥(add(x)) (WithTop ↥(add(x))) (Order.le_succ ℵ₀)
        (fun y => (y : WithTop ↥(add(x)))) := by
      refine isBraidedOver_of_cyclic_base ⟨x, hxmem⟩ (exists_nsmul_eq_of_ne hgen hx)
        ⟨rfl, fun {ι} h a => ?_⟩ WithTop.coe_injective (fun h => ?_) (fun a ha => ?_)
      · have : Finite ι := Cardinal.lt_aleph0_iff_finite.mp h
        have : Fintype ι := Fintype.ofFinite ι
        rw [LMonoid.lsumOf_aleph0_eq_finsum h a, KMonoid.sumOf_eq_sum (h := CardLE.mk' h.le)]
        simp
      · induction h using WithTop.recTopCoe with
        | top =>
            refine ⟨fun _ => ⟨x, hxmem⟩, ?_⟩
            have : Infinite (Idx (ℵ₀ : Cardinal.{u})) := infinite_Idx le_rfl
            rw [TrivExt.instKMonoid_ksum]
            refine (TrivExt.sigma_eq_top_of_infinite ?_).symm
            rw [show (Function.support fun _ : Idx (ℵ₀ : Cardinal.{u}) =>
                (((⟨x, hxmem⟩ : ↥(add(x))) : ↥(add(x))) : WithTop ↥(add(x)))) = Set.univ from
              Set.eq_univ_of_forall fun _ => fun h =>
                hx0 (congrArg Subtype.val (WithTop.coe_eq_zero.mp h))]
            exact Set.infinite_univ
        | coe y =>
            obtain ⟨i₀⟩ := nonempty_Idx (le_refl (ℵ₀ : Cardinal.{u}))
            refine ⟨fun i => if i = i₀ then y else 0, ?_⟩
            rw [KMonoid.ksum_single i₀ _ fun i hi => by simp [hi]]
            simp
      · rw [TrivExt.instKMonoid_ksum, TrivExt.sigma_eq_top_of_infinite (by rw [hsupp]; exact ha)]
        rintro ⟨w, hw⟩
        exact WithTop.coe_ne_top hw
    -- both are the universal `ℵ₀`-extension of `C`, hence isomorphic
    have h₁ : IsUniversalKExtension.{u, u, u, u} ℵ₀ ℵ₀ ↥(add(x)) (WithTop ↥(add(x)))
        (Order.le_succ ℵ₀) (fun y => (y : WithTop ↥(add(x)))) :=
      hbrW.isUniversalKExtension (Order.le_succ ℵ₀)
    have h₂ : IsUniversalKExtension.{u, u, u, u} ℵ₀ ℵ₀ ↥(add(x)) H (Order.le_succ ℵ₀)
        (fun y => (y : H)) :=
      (isBraidedOver_addOf_of_ne hgen hx).isUniversalKExtension (Order.le_succ ℵ₀)
    obtain ⟨e, ⟨he, -, hbij⟩, -⟩ := isUniversalKExtension_unique (Order.le_succ ℵ₀) h₁ h₂
    exact ⟨e, he, hbij⟩
  · rintro ⟨C, _, hC, c, hc0, -, hiso⟩
    let : KMonoid (ℵ₀ : Cardinal.{u}) (WithTop C) := TrivExt.instKMonoid hC le_rfl
    obtain ⟨e, he, hbij⟩ := hiso
    have hcW : ((c : C) : WithTop C) ≠ 0 := fun h => hc0 (WithTop.coe_eq_zero.mp h)
    have htop : ℵ₀∙((c : C) : WithTop C) = ⊤ := TrivExt.cmul_top_eq_top hC le_rfl hcW
    -- the generator `c` is a faithful order-unit of `C ∪ {∞}`
    have hfaith : IsFaithful (κ := (ℵ₀ : Cardinal.{u})) ((c : C) : WithTop C) := by
      refine ⟨fun y => ⟨⊤, ?_⟩, fun α β hα hβ hαβ hβ0 ⟨z, hz⟩ => ?_⟩
      · rw [htop, WithTop.add_top]
      · obtain ⟨k, rfl⟩ := Cardinal.lt_aleph0.mp (lt_of_lt_of_le hαβ hβ)
        rw [cmul_congr (le_antisymm hβ hβ0) hβ le_rfl, htop, WithTop.top_add, cmul_natCast,
          ← TrivExt.coe_nsmul] at hz
        exact WithTop.top_ne_coe hz
    exact fun n => ne_nsmul_of_isFaithful hgen (isFaithful_map_of_bijective he hbij hfaith) n

end CyclicNe

/-! ## The counterexample `ℕ₀² ∪ {∞}` satisfies the standing hypotheses of §5 -/

section Counterexample

/-- **The counterexample of Corollary 5.5(2), (3) is two-generated**: `ℕ₀² ∪ {∞}` is generated as
an `ℵ₀`-monoid by `x₁ = (1,0)` and `x₂ = (0,1)`.  `(a, b) = a x₁ + b x₂` and `∞ = ℵ₀ x₁`. -/
theorem cex_kGenerates :
    KGenerates (ℵ₀ : Cardinal.{u}) ({cex₁.{u}, cex₂.{u}} : Set (WithTop NatSq.{u})) := by
  have hT := isKSubmonoid_kclosure (ℵ₀ : Cardinal.{u})
    ({cex₁.{u}, cex₂.{u}} : Set (WithTop NatSq.{u}))
  have h1 : cex₁.{u} ∈ kclosure (ℵ₀ : Cardinal.{u})
      ({cex₁.{u}, cex₂.{u}} : Set (WithTop NatSq.{u})) :=
    subset_kclosure (Set.mem_insert _ _)
  have h2 : cex₂.{u} ∈ kclosure (ℵ₀ : Cardinal.{u})
      ({cex₁.{u}, cex₂.{u}} : Set (WithTop NatSq.{u})) :=
    subset_kclosure (Set.mem_insert_of_mem _ rfl)
  refine kGenerates_iff.mpr fun y => ?_
  induction y using WithTop.recTopCoe with
  | top =>
      -- `∞ = ℵ₀ x₁`
      have h := TwoGen.IsKSubmonoid.ecmul_mem hT h1 ⊤
      rwa [ecmul_top, cmul_top_cex₁] at h
  | coe p =>
      -- `(a, b) = a x₁ + b x₂`
      obtain ⟨⟨a, b⟩⟩ := p
      have h := hT.add_mem (TwoGen.IsKSubmonoid.ecmul_mem hT h1 (a : ℕ∞))
        (TwoGen.IsKSubmonoid.ecmul_mem hT h2 (b : ℕ∞))
      have heq : ((⟨(a, b)⟩ : NatSq.{u}) : WithTop NatSq.{u})
          = ecmul (a : ℕ∞) cex₁.{u} + ecmul (b : ℕ∞) cex₂.{u} := by
        rw [ecmul_natCast, ecmul_natCast, cex₁, cex₂, ← TrivExt.coe_nsmul, ← TrivExt.coe_nsmul,
          nsmul_natSq, nsmul_natSq, ← WithTop.coe_add]
        congr 1
        show (⟨(a, b)⟩ : NatSq.{u}) = ⟨(a * 1 + b * 0, a * 0 + b * 1)⟩
        simp
      rw [heq]
      exact h

/-- **The counterexample of Corollary 5.5(2), (3) is not cyclic.**  A generator `y` would make
`x₁ = k y` and `x₂ = l y` finite multiples (`ℵ₀ y` is `0` or `∞`), and then `y` would be a common
divisor of `(1,0)` and `(0,1)` in `ℕ₀²`. -/
theorem cex_not_cyclic (y : WithTop NatSq.{u}) :
    ¬ KGenerates (ℵ₀ : Cardinal.{u}) ({y} : Set (WithTop NatSq.{u})) := by
  intro hy
  -- `ℵ₀ y` is `0` or `∞`, so the two generators are finite multiples of `y`
  have htop : ℵ₀∙y = 0 ∨ ℵ₀∙y = ⊤ := by
    by_cases h0 : y = 0
    · left
      rw [h0, cmul_zero]
    · exact Or.inr (TrivExt.cmul_top_eq_top isConical_natSq le_rfl h0)
  have hfin : ∀ z : WithTop NatSq.{u}, z ≠ 0 → z ≠ ⊤ → ∃ k : ℕ, z = k • y := by
    intro z hz0 hztop
    rcases eq_cmul_top_or_nsmul hy z with rfl | hk
    · rcases htop with h | h
      · exact absurd h hz0
      · exact absurd h hztop
    · exact hk
  obtain ⟨k, hk⟩ := hfin cex₁ cex₁_ne_zero WithTop.coe_ne_top
  obtain ⟨l, hl⟩ := hfin cex₂ cex₂_ne_zero WithTop.coe_ne_top
  unfold cex₁ at hk
  unfold cex₂ at hl
  induction y using WithTop.recTopCoe with
  | top =>
      have hj : ∀ j : ℕ, j • (⊤ : WithTop NatSq.{u}) = 0 ∨ j • (⊤ : WithTop NatSq.{u}) = ⊤ := by
        intro j
        cases j with
        | zero => exact Or.inl (zero_nsmul _)
        | succ j => exact Or.inr (by rw [succ_nsmul, WithTop.add_top])
      rcases hj k with h | h
      · exact cex₁_ne_zero (hk.trans h)
      · exact WithTop.coe_ne_top (hk.trans h)
  | coe p =>
      -- `y = (a, b)` would divide both `(1, 0)` and `(0, 1)`
      obtain ⟨⟨a, b⟩⟩ := p
      rw [← TrivExt.coe_nsmul, nsmul_natSq] at hk hl
      have hk' := WithTop.coe_injective hk
      have hl' := WithTop.coe_injective hl
      have e1 : 1 = k * a := congrArg (fun z : NatSq.{u} => z.down.1) hk'
      have e2 : 0 = l * a := congrArg (fun z : NatSq.{u} => z.down.1) hl'
      have e3 : 1 = l * b := congrArg (fun z : NatSq.{u} => z.down.2) hl'
      rcases Nat.mul_eq_zero.mp e2.symm with h | h
      · rw [h, zero_mul] at e3
        exact absurd e3 one_ne_zero
      · rw [h, mul_zero] at e1
        exact absurd e1 one_ne_zero

end Counterexample

end TwoGen

end KappaMonoid
