/-
**Lemma 5.1**: if `H ≅ V^{ℵ₀}(R)` for a ring whose projectives are direct sums of finitely
generated modules, then `H` is braided over `add (x₁ + x₂)`.  The one module-theoretic file of
§5's braiding material.
-/
import KappaMonoid.TwoGen.Prelim
import KappaMonoid.Modules.Corollary47

universe u v

open Cardinal Function Set

namespace KappaMonoid

namespace TwoGen

variable {H : Type u} [KMonoid (ℵ₀ : Cardinal.{u}) H]

section Lemma51

variable (R : Type u) [Ring R]

/-- **Lemma 5.1**: two generators of `V^{ℵ₀}(R)` force braidedness over `add (x₁ + x₂)`.

Follows from `corollary_4_5_three` and `corollary_4_7_one_backward`.  The step needing care is
that *both* `x₁` and `x₂` must arise from finitely generated modules: otherwise `V(R)` would be
cyclic, hence so would `V^{ℵ₀}(R)`, contradicting non-cyclicity.  That is where the non-cyclicity
hypothesis first bites. -/
theorem lemma_5_1 (hfg : EveryProjectiveIsSumOfFG R) (x₁ x₂ : H)
    (hgen : KMonoid.KGenerates ℵ₀ ({x₁, x₂} : Set H))
    (hnoncyclic : ∀ x : H, ¬ KMonoid.KGenerates ℵ₀ ({x} : Set H))
    (e : H → (projClass R ℵ₀ le_rfl).carrier)
    (hhom : letI := (projClass R ℵ₀ le_rfl).instKMonoid le_rfl; KMonoid.IsKHom ℵ₀ e)
    (hbij : Function.Bijective e) :

    IsBraidedOver ℵ₀ ℵ₀ ↥(KMonoid.addOf (κ := ℵ₀) (x₁ + x₂)) H le_rfl (fun y => (y : H)) := by
  classical
  letI := (projClass R ℵ₀ le_rfl).instKMonoid le_rfl
  letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
    ((projClass R ℵ₀ le_rfl).lambdaSmallPart_isLSubset le_rfl ℵ₀ Cardinal.isRegular_aleph0 le_rfl)

  -- Corollary 4.5(3): `V^{ℵ₀}(R)` is braided over `V(R)`, the `ℵ₀⁻`-small classes
  have hbrV := (corollary_4_5_three.{u, u} R ℵ₀ le_rfl hfg).1
  -- `S = e⁻¹(V(R))` is the set of elements of `H` corresponding to finitely generated modules
  set S : Set H := e ⁻¹' ((projClass R ℵ₀ le_rfl).lambdaSmallPart ℵ₀) with hSdef
  have hWsub := (projClass R ℵ₀ le_rfl).lambdaSmallPart_isLSubset le_rfl ℵ₀
    Cardinal.isRegular_aleph0 le_rfl
  have h0S : (0 : H) ∈ S := by
    show e 0 ∈ (projClass R ℵ₀ le_rfl).lambdaSmallPart ℵ₀
    rw [hhom.1]
    exact hWsub.zero_mem
  -- `V(R)` is closed under binary sums: `+` is a two-element `ℵ₀⁻`-sum
  have haddS : ∀ a ∈ S, ∀ b ∈ S, a + b ∈ S := by
    intro a ha b hb
    show e (a + b) ∈ (projClass R ℵ₀ le_rfl).lambdaSmallPart ℵ₀
    rw [KMonoid.IsKHom.map_add hhom]
    exact hWsub.add_mem le_rfl ha hb
  -- `S` is divisor-closed, because `V(R)` is (a summand of a f.g. module is f.g.)
  have hSsat : ∀ a ∈ S, ∀ b c : H, a = b + c → b ∈ S := by
    intro a ha b c habc
    exact (projClass R ℵ₀ le_rfl).lambdaSmallPart_summand le_rfl ℵ₀ (e a) ha (e b)
      ⟨e c, by rw [← KMonoid.IsKHom.map_add hhom, ← habc]⟩
  -- and `S` generates `H`, because `V(R)` generates `V^{ℵ₀}(R)`
  have hSgen : KMonoid.KGenerates (ℵ₀ : Cardinal.{u}) S := by
    refine KMonoid.kGenerates_iff.mpr fun h => ?_
    obtain ⟨z, hz⟩ := hbrV.generates (e h)
    choose w hw using fun i => hbij.2 ((z i : (projClass R ℵ₀ le_rfl).carrier))
    refine (KMonoid.mem_kclosure_iff (S := S) h0S h).mpr ⟨w, fun i => ?_, hbij.1 ?_⟩
    · show e (w i) ∈ (projClass R ℵ₀ le_rfl).lambdaSmallPart ℵ₀
      rw [hw i]
      exact (z i).2
    · rw [hz, hhom.2 w]
      exact congrArg _ (funext fun i => (hw i).symm)
  -- **the paper's parenthetical**: both generators lie in `S`, else `H` would be cyclic
  obtain ⟨hx₁S, hx₂S⟩ :=
    mem_of_divisorClosed_of_generates x₁ x₂ hSsat hSgen hgen hnoncyclic
  -- hence `add (x₁ + x₂) ⊆ S`: it is generated by a divisor-closed set containing `x₁ + x₂`
  have hnsmulS : ∀ (n : ℕ) (a : H), a ∈ S → n • a ∈ S := by
    intro n a ha
    induction n with
    | zero => rwa [zero_nsmul]
    | succ p hp => rw [succ_nsmul]; exact haddS _ hp _ ha
  have hTS : ∀ a ∈ KMonoid.addOf (κ := ℵ₀) (x₁ + x₂),
      e a ∈ (projClass R ℵ₀ le_rfl).lambdaSmallPart ℵ₀ := by
    rintro a ⟨z, n, hzn⟩
    refine hSsat _ ?_ a z hzn.symm
    rw [KMonoid.cmul_natCast]
    exact hnsmulS n _ (haddS _ hx₁S _ hx₂S)
  -- `add (x₁ + x₂)` still generates `H`, since it contains both generators
  have hx₁T : x₁ ∈ KMonoid.addOf (κ := ℵ₀) (x₁ + x₂) :=
    KMonoid.addOf_isSaturated (x₁ + x₂) _ (KMonoid.self_mem_addOf _) x₁ x₂ rfl
  have hx₂T : x₂ ∈ KMonoid.addOf (κ := ℵ₀) (x₁ + x₂) :=
    KMonoid.addOf_isSaturated (x₁ + x₂) _ (KMonoid.self_mem_addOf _) x₂ x₁ (add_comm x₁ x₂)
  have hTgen : KMonoid.KGenerates (ℵ₀ : Cardinal.{u}) (KMonoid.addOf (κ := ℵ₀) (x₁ + x₂)) := by
    refine Set.eq_univ_of_univ_subset ?_
    rw [← hgen]
    refine KMonoid.kclosure_le ?_ (KMonoid.isKSubmonoid_kclosure _ _)
    rintro w (rfl | rfl)
    · exact KMonoid.subset_kclosure hx₁T
    · exact KMonoid.subset_kclosure hx₂T
  exact IsBraidedOver.of_kIso_subset Cardinal.isRegular_aleph0 hWsub
    (KMonoid.addOf_isLSubset (κ := ℵ₀) le_rfl (x₁ + x₂)) hbrV hhom hbij hTS
    (KMonoid.addOf_isSaturated (x₁ + x₂)) hTgen

end Lemma51

end TwoGen

end KappaMonoid
