/-
**Examples 4.8(3)** of

  Zahra Nazemian and Daniel Smertnig,
  *A monoid-theoretical approach to infinite direct-sum decompositions of modules*,

at the level of rings: if every projective `R`-module is a direct sum of finitely generated ones,
then `V(R)` determines `V^{ℵ₀}(R)`, and the universal `ℵ₀`-extensions computed in §3 describe it.

* `V(R) ≅ ℕ₀` gives `V^{ℵ₀}(R) ≅ ℕ₀ ∪ {∞}` (Examples 3.3(1)): `examples_4_8_3_nat`;
* `V(R) ≅ ℝ≥0` gives `V^{ℵ₀}(R) ≅ ℝ≥0 ∪ ℝ̃>0 ∪ {∞}` (Examples 3.3(2)): `examples_4_8_3_nnreal`;
* `V(R) ≅ ℚ≥0` gives `V^{ℵ₀}(R) ≅ ⟨ℚ≥0⟩_{ℵ₀} = ℚ≥0 ∪ ℝ̃>0 ∪ {∞}` (Examples 3.3(3)):
  `examples_4_8_3_rat`;
* `V(R) ≅ H ⊆ ℕ₀^n` cut out by homogeneous equations and congruences gives `V^{ℵ₀}(R) ≅ H + ℵ₀H`
  (Proposition 3.15(2)): `examples_4_8_3_diophantine`.

Each is `exists_kIso_of_fgIso_univ` — Corollary 4.5(3) plus uniqueness of universal
`κ`-extensions across universes — applied to the corresponding universal extension from
`Examples/`.  `V(R)` is `V(R).lambdaGenPart ℵ₀`, the finitely generated classes inside
`V^{ℵ₀}(R)` (the notation `V(R)` of the development denotes `V^{ℵ₀}(R)`), with its
`ℵ₀⁻`-monoid structure, whose homomorphisms are the additive maps (`isLMonoidHom_aleph0_of_add`).

**Placement.**  These combine a module-theoretic result (`Modules/`) with concrete monoids
(`Examples/`), and the layering allows only `TwoGen/` and `Paper/` to import both; they are
numbered results of the paper, so they sit here.

**The inequality case.**  The paper also allows inequalities, turned into equations by slack
variables (Example 3.17).  That reduction is an isomorphism of the base monoid, so it composes
with `examples_4_8_3_diophantine` through `example_3_17_slack_iso`; it is not restated here.
-/
import KappaMonoid.Modules.Transport
import KappaMonoid.Examples.NatBraiding
import KappaMonoid.Examples.Reals
import KappaMonoid.Examples.Diophantine

universe u

open Cardinal
open scoped NNReal

namespace KappaMonoid

/-- **Examples 4.8(3)**, first item: if every projective `R`-module is a direct sum of finitely
generated modules and `V(R) ≅ ℕ₀`, then `V^{ℵ₀}(R) ≅ ℕ₀ ∪ {∞}`, extending the given isomorphism.

`ℕ₀ ∪ {∞}` is the universal `ℵ₀`-extension of `ℕ₀` by Examples 3.3(1). -/
theorem examples_4_8_3_nat (R : Type u) [Ring R] (hfg : EveryProjectiveIsSumOfFG R)
    (φ : ↥(V(R).lambdaGenPart ℵ₀) → ℕ)
    (hφ :
      letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
        (V(R).lambdaGenPart_isLSubset le_rfl ℵ₀ Cardinal.isRegular_aleph0 (Order.le_succ ℵ₀))
      letI : LMonoid (ℵ₀ : Cardinal.{u}) ℕ := LMonoid.ofAddCommMonoid ℕ
      IsLMonoidHom ℵ₀ φ)
    (hbij : Function.Bijective φ) :
    letI := TrivExt.instKMonoid (M := ℕ) (κ := (ℵ₀ : Cardinal.{u})) (fun a b h => by omega) le_rfl
    ∃ e : V(R).carrier → WithTop ℕ, KMonoid.IsKHom ℵ₀ e ∧
      (∀ a : ↥(V(R).lambdaGenPart ℵ₀), e (a : V(R).carrier) = (φ a : WithTop ℕ)) ∧
        Function.Bijective e := by
  let := TrivExt.instKMonoid (M := ℕ) (κ := (ℵ₀ : Cardinal.{u})) (fun a b h => by omega) le_rfl
  let : LMonoid (ℵ₀ : Cardinal.{u}) ℕ := LMonoid.ofAddCommMonoid ℕ
  exact exists_kIso_of_fgIso_univ le_rfl R hfg isUniversalKExtension_withTop_nat
    isUniversalKExtension_withTop_nat φ hφ hbij

/-- **Examples 4.8(3)**, second item, for `ℝ≥0`: if every projective `R`-module is a direct sum of
finitely generated modules and `V(R) ≅ ℝ≥0`, then `V^{ℵ₀}(R) ≅ ℝ≥0 ∪ ℝ̃>0 ∪ {∞}`.

`ℝ≥0 ∪ ℝ̃>0 ∪ {∞}` is the universal `ℵ₀`-extension of `ℝ≥0` by Examples 3.3(2). -/
theorem examples_4_8_3_nnreal (R : Type u) [Ring R] (hfg : EveryProjectiveIsSumOfFG R)
    (φ : ↥(V(R).lambdaGenPart ℵ₀) → ℝ≥0)
    (hφ :
      letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
        (V(R).lambdaGenPart_isLSubset le_rfl ℵ₀ Cardinal.isRegular_aleph0 (Order.le_succ ℵ₀))
      letI : LMonoid (ℵ₀ : Cardinal.{u}) ℝ≥0 := LMonoid.ofAddCommMonoid ℝ≥0
      IsLMonoidHom ℵ₀ φ)
    (hbij : Function.Bijective φ) :
    letI : KMonoid (ℵ₀ : Cardinal.{u}) RTilde := RTilde.instKMonoid
    ∃ e : V(R).carrier → RTilde, KMonoid.IsKHom ℵ₀ e ∧
      (∀ a : ↥(V(R).lambdaGenPart ℵ₀), e (a : V(R).carrier) = RTilde.ofReal (φ a)) ∧
        Function.Bijective e := by
  let : KMonoid (ℵ₀ : Cardinal.{u}) RTilde := RTilde.instKMonoid
  let : LMonoid (ℵ₀ : Cardinal.{u}) ℝ≥0 := LMonoid.ofAddCommMonoid ℝ≥0
  exact exists_kIso_of_fgIso_univ le_rfl R hfg RTilde.isUniversalKExtension_rtilde
    RTilde.isUniversalKExtension_rtilde φ hφ hbij

/-- **Examples 4.8(3)**, second item, for `ℚ≥0`: if every projective `R`-module is a direct sum of
finitely generated modules and `V(R) ≅ ℚ≥0`, then `V^{ℵ₀}(R)` is isomorphic to the
`ℵ₀`-submonoid of `ℝ≥0 ∪ ℝ̃>0 ∪ {∞}` generated by `ℚ≥0`, which is `ℚ≥0 ∪ ℝ̃>0 ∪ {∞}`
(`kclosure_ofReal_ratSet`).

`ℚ≥0` is `ratSet`, the non-negative rationals inside `ℝ≥0`, as in Examples 3.3(3). -/
theorem examples_4_8_3_rat (R : Type u) [Ring R] (hfg : EveryProjectiveIsSumOfFG R)
    (φ : ↥(V(R).lambdaGenPart ℵ₀) → ↥ratSet)
    (hφ :
      letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
        (V(R).lambdaGenPart_isLSubset le_rfl ℵ₀ Cardinal.isRegular_aleph0 (Order.le_succ ℵ₀))
      letI : LMonoid (ℵ₀ : Cardinal.{u}) ℝ≥0 := LMonoid.ofAddCommMonoid ℝ≥0
      letI := (isLSubmonoid_ratSet : IsLSubmonoid (ℵ₀ : Cardinal.{u}) ratSet).lmonoid
      IsLMonoidHom ℵ₀ φ)
    (hbij : Function.Bijective φ) :
    letI : KMonoid (ℵ₀ : Cardinal.{u}) RTilde := RTilde.instKMonoid
    letI := (KMonoid.isKSubmonoid_kclosure (ℵ₀ : Cardinal.{u})
      (RTilde.ofReal '' ratSet)).kmonoid
    ∃ e : V(R).carrier → ↥(KMonoid.kclosure (ℵ₀ : Cardinal.{u}) (RTilde.ofReal '' ratSet)),
      KMonoid.IsKHom ℵ₀ e ∧
      (∀ a : ↥(V(R).lambdaGenPart ℵ₀),
        (e (a : V(R).carrier) : RTilde) = RTilde.ofReal (φ a : ℝ≥0)) ∧
        Function.Bijective e := by
  let : KMonoid (ℵ₀ : Cardinal.{u}) RTilde := RTilde.instKMonoid
  let := (KMonoid.isKSubmonoid_kclosure (ℵ₀ : Cardinal.{u}) (RTilde.ofReal '' ratSet)).kmonoid
  let : LMonoid (ℵ₀ : Cardinal.{u}) ℝ≥0 := LMonoid.ofAddCommMonoid ℝ≥0
  let := (isLSubmonoid_ratSet : IsLSubmonoid (ℵ₀ : Cardinal.{u}) ratSet).lmonoid
  obtain ⟨e, he, hcomm, hbij⟩ := exists_kIso_of_fgIso_univ le_rfl R hfg
    isUniversalKExtension_ratSet isUniversalKExtension_ratSet φ hφ hbij
  exact ⟨e, he, fun a => congrArg Subtype.val (hcomm a), hbij⟩

/-- **Examples 4.8(3)**, third item: if every projective `R`-module is a direct sum of finitely
generated modules and `V(R) ≅ H` for a submonoid `H ⊆ ℕ₀^n` defined by homogeneous linear
equations and congruences, then `V^{ℵ₀}(R) ≅ H + ℵ₀H ⊆ F_{ℵ₀}^n`, extending the given isomorphism.

`H + ℵ₀H` is the universal `ℵ₀`-extension of `H` by Proposition 3.15(2)
(`prop_3_15_two_of_ineqs_empty`).  `H` is `sys.finSolutions`, the solutions with finite
coordinates, as in Proposition 3.15(2). -/
theorem examples_4_8_3_diophantine (R : Type u) [Ring R] (hfg : EveryProjectiveIsSumOfFG R)
    {n : ℕ} (sys : LinSystem n) (hineq : sys.ineqs = ∅)
    (φ : ↥(V(R).lambdaGenPart ℵ₀) → ↥(LinSystem.finSolutions.{u} sys))
    (hφ :
      letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
        (V(R).lambdaGenPart_isLSubset le_rfl ℵ₀ Cardinal.isRegular_aleph0 (Order.le_succ ℵ₀))
      letI := Fcard.instKMonoid (le_refl (ℵ₀ : Cardinal.{u}))
      letI := KMonoid.pi ℵ₀ (fun _ : Fin n => Fcard ℵ₀) (le_refl ℵ₀)
      letI : AddCommMonoid ↥sys.finSolutions :=
        addCommMonoidOfClosed sys.addSubmonoid_finSolutions.1
          (fun a ha b hb => sys.addSubmonoid_finSolutions.2 a ha b hb)
      letI := LMonoid.ofAddCommMonoid ↥sys.finSolutions
      IsLMonoidHom ℵ₀ φ)
    (hbij : Function.Bijective φ) :
    letI := Fcard.instKMonoid (le_refl (ℵ₀ : Cardinal.{u}))
    letI := KMonoid.pi ℵ₀ (fun _ : Fin n => Fcard ℵ₀) (le_refl ℵ₀)
    letI := sys.isKSubmonoid_alephExt.kmonoid
    ∃ e : V(R).carrier → ↥sys.alephExt, KMonoid.IsKHom ℵ₀ e ∧
      (∀ a : ↥(V(R).lambdaGenPart ℵ₀),
        (e (a : V(R).carrier) : Fin n → Fcard ℵ₀) = (φ a : Fin n → Fcard ℵ₀)) ∧
        Function.Bijective e := by
  let := Fcard.instKMonoid (le_refl (ℵ₀ : Cardinal.{u}))
  let := KMonoid.pi ℵ₀ (fun _ : Fin n => Fcard ℵ₀) (le_refl ℵ₀)
  let : AddCommMonoid ↥sys.finSolutions :=
    addCommMonoidOfClosed sys.addSubmonoid_finSolutions.1
      (fun a ha b hb => sys.addSubmonoid_finSolutions.2 a ha b hb)
  let := LMonoid.ofAddCommMonoid ↥sys.finSolutions
  let := sys.isKSubmonoid_alephExt.kmonoid
  obtain ⟨e, he, hcomm, hbij⟩ := exists_kIso_of_fgIso_univ le_rfl R hfg
    (prop_3_15_two_of_ineqs_empty sys hineq) (prop_3_15_two_of_ineqs_empty sys hineq) φ hφ hbij
  exact ⟨e, he, fun a => congrArg Subtype.val (hcomm a), hbij⟩

end KappaMonoid
