/-
**Section 5 of the paper**, and nothing else: every numbered result of

  *Realization to hereditary rings for two-generated `ℵ₀`-monoids*

restated in the paper's own terms and discharged from `KappaMonoid/TwoGen/`.  Read this file
against the PDF; the library files behind it carry the proofs.

Two things this layer adds, both of which the library statements lack:

* **`Setting5` bundles the standing assumptions.**  The paper says, once, "throughout the
  section, let `H` be a non-cyclic `ℵ₀`-monoid generated by two elements `x₁` and `x₂`"
  (`kappa_monoids.tex:1995`), and then every result assumes it silently.  In the library those
  two hypotheses travel as separate arguments, and Lemma 5.2(3) and 5.2(4) genuinely need them.
  Taking them as one structure makes dropping one from an individual statement impossible.

* **`IsRealizableAsV` names the conclusion.**  "`H ≅ V^{ℵ₀}(R)` for a ring over which projective
  modules are direct sums of finitely generated ones" is a nine-line blob repeated in all three
  parts of Corollary 5.5 and in Theorem 5.3.  Named once, these read as the paper writes them.
  Theorem 5.3 as the paper states it is `theorem_5_3_realizable`, over exactly this class of
  rings; `theorem_5_3` is its closing "in fact" sentence, over a hereditary `k`-algebra.

A warning on notation: the scoped `V(R)` of the development is `projClass R ℵ₀ le_rfl`, the paper's
`V^{ℵ₀}(R)` of countably generated projectives.  The paper's `V(R)` (finitely generated ones) is
`lambdaGenPart ℵ₀` inside it.

What the statements owe to the current version of the paper is in the docstrings, and in
`README.md` under "Differences from the paper".  The unnumbered claims of §5 are in
`Paper/Section5Extra.lean`; see the foot of this file.
-/
import KappaMonoid.TwoGen

universe u

open Cardinal Function Set

namespace KappaMonoid

namespace Paper

open TwoGen KMonoid

variable {H : Type u} [KMonoid (ℵ₀ : Cardinal.{u}) H]

/-! ## The setting of §5 -/

/-- **The standing assumptions of §5** (`kappa_monoids.tex:1995`): *"Throughout the section, let
`H` be a non-cyclic `ℵ₀`-monoid generated by two elements `x₁` and `x₂`."*

Every result of the section is stated below against this structure, so that no part of the
standing hypothesis can be dropped from an individual statement. -/
structure Setting5 (H : Type u) [KMonoid (ℵ₀ : Cardinal.{u}) H] where
  /-- The first generator. -/
  x₁ : H
  /-- The second generator. -/
  x₂ : H
  /-- `H` is generated, as an `ℵ₀`-monoid, by `x₁` and `x₂`. -/
  gen : KGenerates ℵ₀ ({x₁, x₂} : Set H)
  /-- `H` is not cyclic. -/
  noncyclic : ∀ x : H, ¬ KGenerates ℵ₀ ({x} : Set H)

/-- **Exchanging the two generators.**  The paper's §5 statements are quantified over `1 ≤ i ≠ j ≤ 2`;
the library fixes `i = 1`, `j = 2`, and the case `i = 2`, `j = 1` is the same statement applied to
this swapped setting.  Nothing is lost, because the standing hypothesis is symmetric in the two
generators. -/
def Setting5.swap {H : Type u} [KMonoid (ℵ₀ : Cardinal.{u}) H] (S : Setting5 H) : Setting5 H where
  x₁ := S.x₂
  x₂ := S.x₁
  gen := by rw [Set.pair_comm]; exact S.gen
  noncyclic := S.noncyclic

@[simp] theorem Setting5.swap_x₁ {H : Type u} [KMonoid (ℵ₀ : Cardinal.{u}) H] (S : Setting5 H) :
    S.swap.x₁ = S.x₂ := rfl

@[simp] theorem Setting5.swap_x₂ {H : Type u} [KMonoid (ℵ₀ : Cardinal.{u}) H] (S : Setting5 H) :
    S.swap.x₂ = S.x₁ := rfl

/-- **Realizability**, the conclusion of Theorem 5.3 and of all three parts of Corollary 5.5:
`H` is isomorphic, as an `ℵ₀`-monoid, to `V^{ℵ₀}(R)` for a ring `R` over which every projective
module is a direct sum of finitely generated ones.

This is the paper's condition verbatim in Theorem 5.3 and in Corollary 5.5(1) and (3), which read
"for a ring whose projective modules are direct sums of finitely generated modules".  Corollary
5.5(2) does not use it: its clause names only the freeness of the countably (non finitely)
generated projectives, and that already implies the condition (`everyProjectiveIsSumOfFG_of_free`).
Hereditariness implies it too, by Albrecht's theorem (`ForMathlib/Albrecht.lean`), which is how the
closing sentence of Theorem 5.3 — a hereditary ring — feeds these corollaries. -/
abbrev IsRealizableAsV (H : Type u) [KMonoid (ℵ₀ : Cardinal.{u}) H] : Prop :=
  TwoGen.IsRealizableAsV H

/-- The `ℵ₀⁻`-monoid structure on `add (x₁ + x₂)`, which the braiding statements of §5 live
over. -/
abbrev addBase (S : Setting5 H) : Set H := add((S.x₁ + S.x₂))

/-- The base `add (x₁ + x₂)` does not see the exchange of the two generators. -/
theorem Setting5.addBase_swap (S : Setting5 H) : addBase S.swap = addBase S := by
  show add((S.x₂ + S.x₁)) = add((S.x₁ + S.x₂))
  rw [add_comm]

/-- **The opening of §5**: every element of `H` is `αx₁ + βx₂` for some form, `0 ≤ α, β ≤ ℵ₀` —
`TwoGen.exists_form`, in `TwoGen/Forms.lean`.  Only the generation half of `Setting5` is used. -/
theorem exists_form (S : Setting5 H) (y : H) : ∃ F : Form, eval S.x₁ S.x₂ F = y :=
  TwoGen.exists_form S.x₁ S.x₂ S.gen y

/-! ## Lemma 5.1 -/


/-- **Lemma 5.1** (`l:twogen-braided`).  *Suppose `H ≅ V^{ℵ₀}(R)` for some ring `R` over which
projective modules are direct sums of finitely generated modules.  Then `x₁` and `x₂` correspond
to finitely generated modules, the `ℵ₀`-monoid `H` is braided over `add(x₁+x₂)`, and
`V(R) ≅ add(x₁+x₂) = ⟨x₁,x₂⟩`.*

All three conclusions are recorded.  `V(R)`, the monoid of finitely generated projective modules,
is `V^{ℵ₀}(R)_{ℵ₀⁻}`, and `⟨x₁, x₂⟩` is the ordinary submonoid generated by the two elements. -/
theorem lemma_5_1 (S : Setting5 H) (R : Type u) [Ring R] (hfg : EveryProjectiveIsSumOfFG R)
    (e : H → V(R).carrier)
    (hhom : letI := V(R).instKMonoid le_rfl; IsKHom ℵ₀ e)
    (hbij : Function.Bijective e) :
    letI := V(R).instKMonoid le_rfl
    letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
      (V(R).lambdaGenPart_isLSubset le_rfl ℵ₀ Cardinal.isRegular_aleph0 (Order.le_succ ℵ₀))
    (Module.Finite R (V(R).rep (e S.x₁)) ∧ Module.Finite R (V(R).rep (e S.x₂))) ∧
      IsBraidedOver ℵ₀ ℵ₀ ↥(addBase S) H (Order.le_succ ℵ₀) (fun y => (y : H)) ∧
      addBase S = (AddSubmonoid.closure ({S.x₁, S.x₂} : Set H) : Set H) ∧
      (∃ φ : ↥(addBase S) → ↥(V(R).lambdaGenPart ℵ₀),
        IsLMonoidHom ℵ₀ φ ∧ Function.Bijective φ) :=
  ⟨TwoGen.lemma_5_1_fg R hfg S.x₁ S.x₂ S.gen S.noncyclic e hhom hbij,
    TwoGen.lemma_5_1 R hfg S.x₁ S.x₂ S.gen S.noncyclic e hhom hbij,
    TwoGen.lemma_5_1_addOf_eq_closure R hfg S.x₁ S.x₂ S.gen S.noncyclic e hhom hbij,
    TwoGen.lemma_5_1_iso R hfg S.x₁ S.x₂ S.gen S.noncyclic e hhom hbij⟩

/-- **Lemma 5.1**, the braiding alone — what the rest of the section runs on. -/
theorem lemma_5_1_braided (S : Setting5 H) (R : Type u) [Ring R]
    (hfg : EveryProjectiveIsSumOfFG R)
    (e : H → V(R).carrier)
    (hhom : letI := V(R).instKMonoid le_rfl; IsKHom ℵ₀ e)
    (hbij : Function.Bijective e) :
    IsBraidedOver ℵ₀ ℵ₀ ↥(addBase S) H (Order.le_succ ℵ₀) (fun y => (y : H)) :=
  TwoGen.lemma_5_1 R hfg S.x₁ S.x₂ S.gen S.noncyclic e hhom hbij

/-! ## Lemma 5.2 -/

/-- **Lemma 5.2(1)** (`easyfactlemma1`).  An infinite form and a finite form are never braided.

The library statement additionally takes `x₁ ≠ 0` and `x₂ ≠ 0`; with `x₁ = 0` the infinite form
`(ℵ₀, 0)` *is* braided with `(0,0)`.  Here they come free from the setting, by
`ne_zero_of_not_cyclic`: a zero generator could be dropped, making `H` cyclic. -/
theorem lemma_5_2_one (S : Setting5 H) (F G : Form) (hF : F.IsInfinite) (hG : G.IsFinite)
    (hFm : ∀ n, familyOfForm S.x₁ S.x₂ F n ∈ addBase S)
    (hGm : ∀ n, familyOfForm S.x₁ S.x₂ G n ∈ addBase S) :
    ¬ BraidedForms S.x₁ S.x₂ F G hFm hGm :=
  let h := ne_zero_of_not_cyclic S.x₁ S.x₂ S.gen S.noncyclic
  TwoGen.lemma_5_2_one S.x₁ S.x₂ F G hF hG h.1 h.2 hFm hGm

/-- **Lemma 5.2(2)**.  Two finite forms with the same value are braided. -/
theorem lemma_5_2_two (S : Setting5 H) (F G : Form) (hF : F.IsFinite) (hG : G.IsFinite)
    (heq : eval S.x₁ S.x₂ F = eval S.x₁ S.x₂ G)
    (hFm : ∀ n, familyOfForm S.x₁ S.x₂ F n ∈ addBase S)
    (hGm : ∀ n, familyOfForm S.x₁ S.x₂ G n ∈ addBase S) :
    BraidedForms S.x₁ S.x₂ F G hFm hGm :=
  TwoGen.lemma_5_2_two S.x₁ S.x₂ F G hF hG heq hFm hGm

/-- **Lemma 5.2(3)**.  If `x₁ ∈ add x₂` then any two forms `α X₁ + ℵ₀ X₂` and `β X₁ + ℵ₀ X₂` are
braided.

The generation hypothesis is a standing assumption of the section, and the proof genuinely needs
it — it is where `t = m' x₁ + n' x₂` comes from.  Here it is `S.gen`. -/
theorem lemma_5_2_three (S : Setting5 H) (hmem : S.x₁ ∈ add(S.x₂))
    (hmix : NoMixedForms S.x₁ S.x₂) (α β : ℕ∞)
    (hFm : ∀ n, familyOfForm S.x₁ S.x₂ (α, ⊤) n ∈ addBase S)
    (hGm : ∀ n, familyOfForm S.x₁ S.x₂ (β, ⊤) n ∈ addBase S) :
    BraidedForms S.x₁ S.x₂ (α, ⊤) (β, ⊤) hFm hGm :=
  TwoGen.lemma_5_2_three S.x₁ S.x₂ hmem hmix S.gen α β hFm hGm

/-- **Lemma 5.2(4)**.  If `x₁ ∉ add x₂` and `m X₁ + ℵ₀ X₂` is braided with `n X₁ + ℵ₀ X₂`, then
already `m X₁ + k X₂ = n X₁ + k' X₂` for some natural numbers `k`, `k'`.

Takes the standing generation hypothesis, as `S.gen`; the proof needs it to write `v (a, K+1)` in
a form at all. -/
theorem lemma_5_2_four (S : Setting5 H) (hmem : S.x₁ ∉ add(S.x₂))
    (hmix : NoMixedForms S.x₁ S.x₂) (m n : ℕ)
    (hFm : ∀ i, familyOfForm S.x₁ S.x₂ ((m : ℕ∞), ⊤) i ∈ addBase S)
    (hGm : ∀ i, familyOfForm S.x₁ S.x₂ ((n : ℕ∞), ⊤) i ∈ addBase S)
    (hbr : BraidedForms S.x₁ S.x₂ ((m : ℕ∞), ⊤) ((n : ℕ∞), ⊤) hFm hGm) :
    ∃ k k' : ℕ, eval S.x₁ S.x₂ ((m : ℕ∞), (k : ℕ∞)) = eval S.x₁ S.x₂ ((n : ℕ∞), (k' : ℕ∞)) :=
  TwoGen.lemma_5_2_four S.x₁ S.x₂ hmem hmix S.gen m n hFm hGm hbr

/-- **Lemma 5.2(5)**.  Given the braiding of Lemma 5.1, `x₁ ∈ add x₂` iff `ℵ₀(x₁+x₂) = ℵ₀x₂`. -/
theorem lemma_5_2_five (S : Setting5 H)
    (hbr :      IsBraidedOver ℵ₀ ℵ₀ ↥(addBase S) H (Order.le_succ ℵ₀) (fun y => (y : H))) :
    S.x₁ ∈ add(S.x₂) ↔
      ℵ₀∙(S.x₁ + S.x₂) = ℵ₀∙S.x₂ :=
  TwoGen.lemma_5_2_five S.x₁ S.x₂ hbr

/-- **Lemma 5.2(5)** with the two generators exchanged — the case `i = 2`, `j = 1` of the paper's
`1 ≤ i ≠ j ≤ 2`.  It is the statement above applied to `Setting5.swap`, and every other `i ≠ j`
statement of the section is obtained the same way; `Setting5.addBase_swap` says the base is
unchanged. -/
theorem lemma_5_2_five' (S : Setting5 H)
    (hbr : IsBraidedOver ℵ₀ ℵ₀ ↥(addBase S) H (Order.le_succ ℵ₀) (fun y => (y : H))) :
    S.x₂ ∈ add(S.x₁) ↔
      ℵ₀∙(S.x₁ + S.x₂) = ℵ₀∙S.x₁ := by
  have hbr' : IsBraidedOver ℵ₀ ℵ₀ ↥(addBase S.swap) H (Order.le_succ ℵ₀) (fun y => (y : H)) :=
    IsBraidedOver.of_set_eq Cardinal.isRegular_aleph0
      (KMonoid.addOf_isLSubset (κ := (ℵ₀ : Cardinal.{u})) le_rfl (S.swap.x₁ + S.swap.x₂))
      (KMonoid.addOf_isLSubset (κ := (ℵ₀ : Cardinal.{u})) le_rfl (S.x₁ + S.x₂))
      (Setting5.addBase_swap S) hbr
  have h := lemma_5_2_five S.swap hbr'
  rw [Setting5.swap_x₁, Setting5.swap_x₂, add_comm] at h
  exact h

/-! ## Theorem 5.3 -/


/-- **Theorem 5.3** (`hereditarycasecor`), forward direction.  If `H` is realizable then the three
conditions hold, for both orderings of the generators. -/
theorem theorem_5_3_forward (S : Setting5 H) (R : Type u) [Ring R]
    (hfg : EveryProjectiveIsSumOfFG R)
    (e : V(R).carrier → H)
    (hhom : letI := V(R).instKMonoid le_rfl; IsKHom ℵ₀ e)
    (hbij : Function.Bijective e) :
    Cond1 S.x₁ S.x₂ ∧ Cond1 S.x₂ S.x₁ ∧ Cond2 S.x₁ S.x₂ ∧ Cond2 S.x₂ S.x₁ ∧
      NoMixedForms S.x₁ S.x₂ :=
  TwoGen.theorem_5_3_forward S.x₁ S.x₂ R hfg S.gen S.noncyclic e hhom hbij

/-- **Theorem 5.3**, backward direction: the conditions make `H` realizable, over a `k`-algebra
for any field `k`, and the ring produced is hereditary. -/
theorem theorem_5_3_backward (S : Setting5 H) (k : Type u) [Field k]
    (hc1 : Cond1 S.x₁ S.x₂) (hc1' : Cond1 S.x₂ S.x₁)
    (hc2 : Cond2 S.x₁ S.x₂) (hc2' : Cond2 S.x₂ S.x₁) (hmix : NoMixedForms S.x₁ S.x₂) :
    ∃ (R : Type u) (_ : Ring R) (_ : Algebra k R) (_ : IsHereditary R),
      ∃ e : V(R).carrier → H,
        IsKHom ℵ₀ e ∧ Function.Bijective e :=
  TwoGen.theorem_5_3_backward S.x₁ S.x₂ k S.gen hc1 hc1' hc2 hc2' hmix

/-- **Theorem 5.3** as the paper states it: `H ≅ V^{ℵ₀}(R)` for a ring `R` whose projective
modules are direct sums of finitely generated modules if and only if the three conditions hold. -/
theorem theorem_5_3_realizable (S : Setting5 H) :
    IsRealizableAsV H ↔
      (Cond1 S.x₁ S.x₂ ∧ Cond1 S.x₂ S.x₁ ∧ Cond2 S.x₁ S.x₂ ∧ Cond2 S.x₂ S.x₁ ∧
        NoMixedForms S.x₁ S.x₂) :=
  TwoGen.theorem_5_3_sumFG S.x₁ S.x₂ S.gen S.noncyclic

/-- **Theorem 5.3**, the paper's closing sentence: *"In fact, if `H` satisfies these conditions,
then `H ≅ V^{ℵ₀}(R)` for a hereditary ring `R`."*  Realizability over a hereditary `k`-algebra is
equivalent to the same three conditions, for any field `k`. -/
alias theorem_5_3 := TwoGen.theorem_5_3

/-! ## Proposition 5.4 -/

/-- **Proposition 5.4**.  For two generators `p₁`, `p₂` of `V^{ℵ₀}(R)` the four statements
`Tr(P₂) ≤ Tr(P₁)`, `Tr(P₁) = R`, `P₂ | P₁^{(ℵ₀)}` and `P₁^{(ℵ₀)}` free are equivalent, recorded
as three equivalences, each with `Tr(P₁) = R`.  The facts about trace ideals the paper recalls
before the proposition — `Tr(P)` is an idempotent two-sided ideal, the least with `P = P Tr(P)` —
are `traceIdeal_isTwoSided`, `traceIdeal_mul_self`, `smul_traceIdeal_eq` and
`traceIdeal_le_of_smul_eq`, in `ForMathlib/TraceIdeal.lean`.

Stated at `V^{ℵ₀}(R)` itself rather than through an isomorphism, as the paper does.  The standing
assumptions of §5 appear here as explicit hypotheses rather than as a `Setting5`, because the
`KMonoid` instance on `V^{ℵ₀}(R)` is not in scope while the binder elaborates (trap 3). -/
theorem prop_5_4 (R : Type u) [Ring R] (p₁ p₂ : V(R).carrier)
    (hgen : letI := V(R).instKMonoid le_rfl
      KGenerates ℵ₀ ({p₁, p₂} : Set V(R).carrier))
    (hnoncyclic : letI := V(R).instKMonoid le_rfl
      ∀ x : V(R).carrier,
        ¬ KGenerates ℵ₀ ({x} : Set V(R).carrier)) :
    (traceIdeal R (V(R).rep p₂) ≤ traceIdeal R (V(R).rep p₁)
        ↔ traceIdeal R (V(R).rep p₁) = ⊤) ∧
      (traceIdeal R (V(R).rep p₁) = ⊤ ↔
        ∃ (Q : Type u) (_ : AddCommGroup Q) (_ : Module R Q),
          Nonempty (DirectSum ℕ (fun _ => V(R).rep p₁) ≃ₗ[R]
            V(R).rep p₂ × Q)) ∧
      (traceIdeal R (V(R).rep p₁) = ⊤ ↔
        ∃ ι : Type u, #ι ≤ ℵ₀ ∧
          letI := V(R).instKMonoid le_rfl
          Nonempty (V(R).rep (ℵ₀∙p₁) ≃ₗ[R] DirectSum ι (fun _ => R))) :=
  ⟨(TwoGen.prop_5_4 R p₁ p₂ hgen hnoncyclic).1,
    (TwoGen.prop_5_4 R p₁ p₂ hgen hnoncyclic).2,
    TwoGen.prop_5_4_free R p₁ p₂ hgen hnoncyclic⟩

/-- **Proposition 5.4**, final sentence: for a ring whose projective modules are direct sums of
finitely generated ones, `Tr(P₁) = Tr(P₂)` exactly when every countably but not finitely
generated projective module is free. -/
alias prop_5_4_hereditary := TwoGen.prop_5_4_hereditary

/-! ## The remark before Corollary 5.5

If `H ≅ V^{ℵ₀}(R)` for a ring whose projectives are direct sums of finitely generated modules,
then `V^{ℵ₀}(R)` is braided over `add([R])` — `corollary_4_7_one_backward_braided`, in
`Modules/Corollary47.lean` — and `H ≅ V^{ℵ₀}(S)` for a hereditary `k`-algebra `S`, which is
`corollary_4_7_one_backward_iso` followed by `corollary_4_7_one_forward`.  Both hold for an arbitrary
`κ`-monoid `H`, not only a two-generated one.  The "in particular" clause, that such an `H`
satisfies (i)–(iii) of Theorem 5.3, is `theorem_5_3_forward` above. -/

/-- **The remark before Corollary 5.5** — `KappaMonoid.corollary_4_7_one_backward_braided`. -/
alias remark_before_5_5_braided := KappaMonoid.corollary_4_7_one_backward_braided

/-! ## Corollary 5.5 -/

/-- **Corollary 5.5(1)** (`hereditarycase`).  When `add x₁` and `add x₂` are incomparable, `H` is
realizable iff finite and infinite forms never share a value, and infinite forms with the same
value agree after replacing the infinite coefficient by suitable finite ones.

The condition is quantified over **both** orderings of the generators, as the paper's
`1 ≤ i ≠ j ≤ 2` requires; both instances of each clause are needed. -/
theorem corollary_5_5_one (S : Setting5 H) (h₁ : S.x₁ ∉ add(S.x₂))
    (h₂ : S.x₂ ∉ add(S.x₁)) :
    IsRealizableAsV H ↔
      ((∀ F G : Form, eval S.x₁ S.x₂ F = eval S.x₁ S.x₂ G →
          (F.1 = ⊤ ↔ G.1 = ⊤) ∧ (F.2 = ⊤ ↔ G.2 = ⊤)) ∧
        (∀ F G : Form, F.1 = ⊤ → G.1 = ⊤ → eval S.x₁ S.x₂ F = eval S.x₁ S.x₂ G →
          ∃ m₁ m₂ : ℕ, eval S.x₁ S.x₂ ((m₁ : ℕ∞), F.2) = eval S.x₁ S.x₂ ((m₂ : ℕ∞), G.2)) ∧
        (∀ F G : Form, F.2 = ⊤ → G.2 = ⊤ → eval S.x₁ S.x₂ F = eval S.x₁ S.x₂ G →
          ∃ n₁ n₂ : ℕ, eval S.x₁ S.x₂ (F.1, (n₁ : ℕ∞)) = eval S.x₁ S.x₂ (G.1, (n₂ : ℕ∞)))) :=
  TwoGen.corollary_5_5_one S.x₁ S.x₂ h₁ h₂ S.gen S.noncyclic

/-- **Corollary 5.5(2)**.  `H` is realizable over a ring all of whose countably but not finitely
generated projectives are free on a countable basis iff `add x₁ = add x₂` and `NoMixedForms x₁ x₂`
holds.  Both conditions sit inside the equivalence; neither is a hypothesis.

The freeness clause ranges over the classes of `V^{ℵ₀}(R)`, the countably generated projectives,
not over all projective modules: for those it is false — `R^{(ℵ₁)}` is a counterexample, by
invariance of infinite rank (`mk_le_of_span_eq_top`).

Unlike parts (1) and (3) this one names no condition on the decompositions of projective modules,
and needs none: the freeness clause gives `EveryProjectiveIsSumOfFG R` through Kaplansky's theorem
(`everyProjectiveIsSumOfFG_of_free`), which is what Theorem 5.3's forward direction is applied
with. -/
theorem corollary_5_5_two (S : Setting5 H) :
    (add(S.x₁) = add(S.x₂) ∧ NoMixedForms S.x₁ S.x₂) ↔
      TwoGen.IsRealizableAsVFree H :=
  TwoGen.corollary_5_5_two S.x₁ S.x₂ S.gen S.noncyclic

/-- **Corollary 5.5(2)**, first sentence: *"If `add(x₁) = add(x₂)`, then `H` has only one element
with an infinite form."* -/
theorem corollary_5_5_two_unique_infinite (S : Setting5 H) (h : add(S.x₁) = add(S.x₂)) :
    ∀ F G : Form, F.IsInfinite → G.IsInfinite →
      eval S.x₁ S.x₂ F = eval S.x₁ S.x₂ G :=
  TwoGen.unique_infinite_form_of_addOf_eq h

/-- **Corollary 5.5(2)**, second sentence: *"The converse is not true."*  In `ℕ₀² ∪ {∞}` with
`x₁ = (1,0)` and `x₂ = (0,1)` the only element with an infinite form is `∞`, yet
`add(x₁) ≠ add(x₂)`. -/
alias corollary_5_5_two_converse_false := TwoGen.cex_unique_infinite

/-- **Corollary 5.5(3)**.  When `add x₁ ⊊ add x₂`, `H` is realizable iff every form equal to
`ℵ₀X₁ + nX₂` has finite `X₂`-coefficient and agrees with it after replacing the infinite
`X₁`-coefficient by finite ones.

The paper's part (3) is a three-way equivalence; the other two clauses are
`corollary_5_5_three_nonfree` and `corollary_5_5_three_trace` below. -/
theorem corollary_5_5_three (S : Setting5 H) (h₁ : S.x₁ ∈ add(S.x₂))
    (h₂ : S.x₂ ∉ add(S.x₁)) :
    TwoGen.Relations3 S.x₁ S.x₂ ∧ NoMixedForms S.x₁ S.x₂ ↔ IsRealizableAsV H :=
  TwoGen.corollary_5_5_three S.x₁ S.x₂ h₁ h₂ S.gen S.noncyclic

/-- **Corollary 5.5(3)**, first sentence: *"If `x₁ ∈ add(x₂)`, then `ℵ₀ x₂ = ℵ₀ x₂ + β x₁` for
every cardinal `β ≤ ℵ₀`."* -/
theorem corollary_5_5_three_absorb (S : Setting5 H) (h₁ : S.x₁ ∈ add(S.x₂)) (β : ℕ∞) :
    ℵ₀∙S.x₂ + TwoGen.ecmul β S.x₁ = ℵ₀∙S.x₂ :=
  TwoGen.cmul_top_add_ecmul_of_mem_addOf h₁ β

/-- **Corollary 5.5(3)**, second sentence: *"The converse is not true."*  In `ℕ₀² ∪ {∞}` the two
generators are `add`-incomparable, yet `ℵ₀ x₂` absorbs every `β x₁`. -/
alias corollary_5_5_three_converse_false := TwoGen.cex_absorb

/-- The two generators of the counterexample `ℕ₀² ∪ {∞}` are `add`-incomparable, which is what
makes it refute both converses. -/
alias cex_incomparable := TwoGen.cex_incomparable

/-- **Corollary 5.5(3)**, second clause: the same relation condition is equivalent to
realizability by a ring which in addition carries a finitely generated projective `P` with
`P^{(ℵ₀)}` not free. -/
theorem corollary_5_5_three_nonfree (S : Setting5 H) (h₁ : S.x₁ ∈ add(S.x₂))
    (h₂ : S.x₂ ∉ add(S.x₁)) :
    TwoGen.Relations3 S.x₁ S.x₂ ∧ NoMixedForms S.x₁ S.x₂ ↔
      TwoGen.IsRealizableAsVNonfree H :=
  TwoGen.corollary_5_5_three_nonfree S.x₁ S.x₂ h₁ h₂ S.gen S.noncyclic

/-- **Corollary 5.5(3)**, third clause: equivalently, `H ≅ V^{ℵ₀}(R)` for a ring with two finitely
generated projective modules `P₁`, `P₂` generating `V^{ℵ₀}(R)` and satisfying
`Tr(P₁) ⊊ Tr(P₂)`. -/
theorem corollary_5_5_three_trace (S : Setting5 H) (h₁ : S.x₁ ∈ add(S.x₂))
    (h₂ : S.x₂ ∉ add(S.x₁)) :
    TwoGen.Relations3 S.x₁ S.x₂ ∧ NoMixedForms S.x₁ S.x₂ ↔
      TwoGen.IsRealizableAsVTracePair H :=
  TwoGen.corollary_5_5_three_trace S.x₁ S.x₂ h₁ h₂ S.gen S.noncyclic

/-! ## Further unnumbered claims

The §5 preamble's one-generator criterion (tex 1989–1991), the §5 standing hypotheses for the
counterexample `ℕ₀² ∪ {∞}`, the `i = 2, j = 1` instances of Lemma 5.2(3)(4), and the remark before
Corollary 5.5 in its general form are in `Paper/Section5Extra.lean`.  Nothing in §5 is left
unformalised. -/

end Paper

end KappaMonoid
