/-
**Section 5 of the paper, the claims `Paper/Section5.lean` leaves implicit**, restated over
`Setting5` and discharged from `TwoGen/Extra.lean` and `TwoGen/ExtraRealization.lean`:

* the counterexample `ℕ₀² ∪ {∞}` of Corollary 5.5(2), (3) as an instance of the standing
  assumptions (`cexSetting5`), so that "the converse is not true" is refuted *within* the setting
  of §5;
* the remark before Corollary 5.5 (`kappa_monoids.tex:2237–2240`);
* Lemma 5.2(3) and 5.2(4) for `i = 2`, `j = 1`, written out;
* the §5 preamble on cyclic `ℵ₀`-monoids (`kappa_monoids.tex:1989–1992`).
-/
import KappaMonoid.Paper.Section5
import KappaMonoid.TwoGen.ExtraRealization

universe u

open Cardinal Function Set

namespace KappaMonoid

namespace Paper

open TwoGen KMonoid

variable {H : Type u} [KMonoid (ℵ₀ : Cardinal.{u}) H]

/-! ## The §5 preamble: cyclic `ℵ₀`-monoids -/

/-- **The §5 preamble** (`kappa_monoids.tex:1989–1991`): a cyclic `ℵ₀`-monoid `⟨x⟩` is
`V^{ℵ₀}(R)` for a nonzero hereditary ring iff `ℵ₀x ≠ nx` for all `n ∈ ℕ₀` —
`TwoGen.cyclic_realizable_iff`.  The paper calls it easily seen and gives no proof. -/
alias preamble_cyclic_realizable := TwoGen.cyclic_realizable_iff

/-- **The §5 preamble**, second sentence (`kappa_monoids.tex:1992`): equivalently the monoid is
`C ∪ {∞}` for a nonzero cyclic monoid `C` — `TwoGen.ne_nsmul_iff_exists_withTop`.  `C` is taken
reduced, which the trivial extension `C ∪ {∞}` requires and which the paper leaves implicit. -/
alias preamble_cyclic_withTop := TwoGen.ne_nsmul_iff_exists_withTop

/-- **The §5 preamble**, both sentences together: realisable over a nonzero hereditary ring iff
`C ∪ {∞}` for a nonzero reduced cyclic monoid `C`. -/
alias preamble_cyclic_realizable_withTop := TwoGen.cyclic_realizable_iff_withTop

/-! ## The remark before Corollary 5.5 -/

/-- **The remark before Corollary 5.5** (`kappa_monoids.tex:2237–2240`): if `H ≅ V^κ(R)` for a
ring whose projective modules are direct sums of finitely generated ones, then `H ≅ V^κ(S)` for a
hereditary `k`-algebra `S`, for any field `k`.  For an arbitrary `κ`-monoid `H`; it rests on
Bergman–Dicks realisation. -/
alias remark_before_5_5 := TwoGen.remark_before_5_5

/-- **The remark before Corollary 5.5**, in the terms of §5: `IsRealizableAsV H` gives a
hereditary `k`-algebra `S` with `H ≅ V^{ℵ₀}(S)`, for every field `k`. -/
alias remark_before_5_5_realizable := TwoGen.remark_before_5_5_realizable

/-! ## Lemma 5.2(3) and 5.2(4) for `i = 2`, `j = 1` -/

/-- **Lemma 5.2(3)** with `i = 2`, `j = 1`.  If `x₂ ∈ add x₁` then any two forms
`α X₂ + ℵ₀ X₁` and `β X₂ + ℵ₀ X₁` are braided.  `lemma_5_2_three` applied to `Setting5.swap`; the
forms and families are written in the order `(x₂, x₁)`, and their base `add (x₂ + x₁)` is
`addBase S` (`Setting5.addBase_swap`).  `NoMixedForms` is symmetric (`noMixedForms_swap`). -/
theorem lemma_5_2_three' (S : Setting5 H) (hmem : S.x₂ ∈ add(S.x₁))
    (hmix : NoMixedForms S.x₁ S.x₂) (α β : ℕ∞)
    (hFm : ∀ n, familyOfForm S.x₂ S.x₁ (α, ⊤) n ∈ add((S.x₂ + S.x₁)))
    (hGm : ∀ n, familyOfForm S.x₂ S.x₁ (β, ⊤) n ∈ add((S.x₂ + S.x₁))) :
    BraidedForms S.x₂ S.x₁ (α, ⊤) (β, ⊤) hFm hGm :=
  lemma_5_2_three S.swap hmem (noMixedForms_swap S.x₁ S.x₂ hmix) α β hFm hGm

/-- **Lemma 5.2(4)** with `i = 2`, `j = 1`.  If `x₂ ∉ add x₁` and `m X₂ + ℵ₀ X₁` is braided with
`n X₂ + ℵ₀ X₁`, then already `k X₁ + m X₂ = k' X₁ + n X₂` for some natural numbers `k`, `k'`.
`lemma_5_2_four` applied to `Setting5.swap`, with the conclusion read back in the order
`(x₁, x₂)` (`eval_swap`). -/
theorem lemma_5_2_four' (S : Setting5 H) (hmem : S.x₂ ∉ add(S.x₁))
    (hmix : NoMixedForms S.x₁ S.x₂) (m n : ℕ)
    (hFm : ∀ i, familyOfForm S.x₂ S.x₁ ((m : ℕ∞), ⊤) i ∈ add((S.x₂ + S.x₁)))
    (hGm : ∀ i, familyOfForm S.x₂ S.x₁ ((n : ℕ∞), ⊤) i ∈ add((S.x₂ + S.x₁)))
    (hbr : BraidedForms S.x₂ S.x₁ ((m : ℕ∞), ⊤) ((n : ℕ∞), ⊤) hFm hGm) :
    ∃ k k' : ℕ, eval S.x₁ S.x₂ ((k : ℕ∞), (m : ℕ∞)) = eval S.x₁ S.x₂ ((k' : ℕ∞), (n : ℕ∞)) := by
  obtain ⟨k, k', h⟩ :=
    lemma_5_2_four S.swap hmem (noMixedForms_swap S.x₁ S.x₂ hmix) m n hFm hGm hbr
  exact ⟨k, k', by rw [eval_swap S.x₁ S.x₂, eval_swap S.x₁ S.x₂]; exact h⟩

/-! ## The counterexample of Corollary 5.5 satisfies the standing assumptions -/

/-- **The counterexample `ℕ₀² ∪ {∞}` of Corollary 5.5(2), (3) as an instance of `Setting5`**,
with `x₁ = (1,0)` and `x₂ = (0,1)`: it is generated by them (`TwoGen.cex_kGenerates`) and is not
cyclic (`TwoGen.cex_not_cyclic`).  The paper asserts neither; both are needed for the example to
refute statements made under the standing assumptions of §5. -/
def cexSetting5 : Setting5 (WithTop NatSq.{u}) where
  x₁ := cex₁
  x₂ := cex₂
  gen := cex_kGenerates
  noncyclic := cex_not_cyclic

/-- **Corollary 5.5(2)**, *"the converse is not true"*, within the setting of §5: there is a
non-cyclic two-generated `ℵ₀`-monoid with only one element having an infinite form, yet
`add x₁ ≠ add x₂`. -/
theorem corollary_5_5_two_converse_false_setting :
    ∃ (H : Type u) (_ : KMonoid (ℵ₀ : Cardinal.{u}) H) (S : Setting5 H),
      (∀ F G : Form, F.IsInfinite → G.IsInfinite → eval S.x₁ S.x₂ F = eval S.x₁ S.x₂ G) ∧
        add(S.x₁) ≠ add(S.x₂) :=
  ⟨WithTop NatSq.{u}, inferInstance, cexSetting5, cex_unique_infinite⟩

/-- **Corollary 5.5(3)**, *"the converse is not true"*, within the setting of §5: there is a
non-cyclic two-generated `ℵ₀`-monoid with `ℵ₀ x₂ + β x₁ = ℵ₀ x₂` for every `β ≤ ℵ₀`, yet
`x₁ ∉ add x₂`. -/
theorem corollary_5_5_three_converse_false_setting :
    ∃ (H : Type u) (_ : KMonoid (ℵ₀ : Cardinal.{u}) H) (S : Setting5 H),
      (∀ β : ℕ∞, ℵ₀∙S.x₂ + ecmul β S.x₁ = ℵ₀∙S.x₂) ∧ S.x₁ ∉ add(S.x₂) :=
  ⟨WithTop NatSq.{u}, inferInstance, cexSetting5, cex_absorb, cex_incomparable.1⟩

end Paper

end KappaMonoid
