/-
**Section 5 of the paper**, and nothing else: every numbered result of

  *Realization to hereditary rings for two-generated `ℵ₀`-monoids*

restated in the paper's own terms and discharged from `KappaMonoid/TwoGen/`.  Read this file
against the PDF; the library files behind it carry the proofs.

Two things this layer adds, both of which the library statements lack:

* **`Setting5` bundles the standing assumptions.**  The paper says, once, "throughout the
  section, let `H` be a non-cyclic `ℵ₀`-monoid generated by two elements `x₁` and `x₂`"
  (`kappa_monoids.tex:1893`), and then every result assumes it silently.  In the library those
  two hypotheses travel as separate arguments, and Lemma 5.2(3) and 5.2(4) genuinely need them.
  Taking them as one structure makes dropping one from an individual statement impossible.

* **`IsRealizableAsV` names the conclusion.**  "`H ≅ V^{ℵ₀}(R)` for a ring over which projective
  modules are direct sums of finitely generated ones" is a nine-line blob repeated in all three
  parts of Corollary 5.5.  Named once, the corollaries read as the paper writes them.  Theorem 5.3
  does *not* use it: the paper states that one for a hereditary ring, and so does this
  formalisation.

The deviations are in the docstrings, and in `README.md` under "Deviations from the paper".
-/
import KappaMonoid.TwoGen

universe u

open Cardinal Function Set

namespace KappaMonoid

namespace Paper

open TwoGen KMonoid

variable {H : Type u} [KMonoid (ℵ₀ : Cardinal.{u}) H]

/-! ## The setting of §5 -/

/-- **The standing assumptions of §5** (`kappa_monoids.tex:1893`): *"Throughout the section, let
`H` be a non-cyclic `ℵ₀`-monoid generated by two elements `x₁` and `x₂`."*

Every result of the section is stated below against this structure, so that no part of the
standing hypothesis can be dropped from an individual statement. -/
structure Setting5 (H : Type u) [KMonoid (ℵ₀ : Cardinal.{u}) H] where
  /-- The first generator. -/
  x₁ : H
  /-- The second generator. -/
  x₂ : H
  /-- `H` is generated, as an `ℵ₀`-monoid, by `x₁` and `x₂`. -/
  gen : KGenerates ℵ₀ ({x₁, x₂} : Set H)
  /-- `H` is not cyclic. -/
  noncyclic : ∀ x : H, ¬ KGenerates ℵ₀ ({x} : Set H)

/-- **Realizability**, the conclusion of Theorem 5.3 and of all three parts of Corollary 5.5:
`H` is isomorphic, as an `ℵ₀`-monoid, to `V^{ℵ₀}(R)` for a ring `R` over which every projective
module is a direct sum of finitely generated ones.

This is the paper's condition verbatim in Corollary 5.5(1) and (3), which read "for a ring whose
projective modules are direct sums of finitely generated modules".  Corollary 5.5(2) does not use
it: its clause names only the freeness of the countably (non finitely) generated projectives, and
that already implies the condition (`everyProjectiveIsSumOfFG_of_free`).  Hereditariness implies it
too, by Albrecht's theorem (`ForMathlib/Albrecht.lean`), which is how Theorem 5.3's backward
direction — stated for a hereditary ring, as in the paper — feeds these corollaries; the forward
direction is stated for this weaker condition, because 5.5(2) has nothing stronger to offer it.
See `README.md`, "The statements corrected in Section 5". -/
def IsRealizableAsV (H : Type u) [KMonoid (ℵ₀ : Cardinal.{u}) H] : Prop :=
  ∃ (R : Type u) (_ : Ring R), EveryProjectiveIsSumOfFG R ∧
    ∃ e : V(R).carrier → H,
      IsKHom ℵ₀ e ∧ Function.Bijective e

/-- The `ℵ₀⁻`-monoid structure on `add (x₁ + x₂)`, which the braiding statements of §5 live
over. -/
abbrev addBase (S : Setting5 H) : Set H := add((S.x₁ + S.x₂))

/-! ## Lemma 5.1 -/

/-- **Lemma 5.1** (`l:twogen-braided`).  *Suppose `H ≅ V^{ℵ₀}(R)` for some ring `R` over which
projective modules are direct sums of finitely generated modules.  Then `x₁` and `x₂` correspond
to finitely generated modules, the `ℵ₀`-monoid `H` is braided over `add(x₁+x₂)`, and
`V(R) ≅ add(x₁+x₂) = ⟨x₁,x₂⟩`.*

The braiding is what the rest of the section runs on, and is what is recorded here. -/
theorem lemma_5_1 (S : Setting5 H) (R : Type u) [Ring R] (hfg : EveryProjectiveIsSumOfFG R)
    (e : H → V(R).carrier)
    (hhom : letI := V(R).instKMonoid le_rfl; IsKHom ℵ₀ e)
    (hbij : Function.Bijective e) :
    IsBraidedOver ℵ₀ ℵ₀ ↥(addBase S) H le_rfl (fun y => (y : H)) :=
  TwoGen.lemma_5_1 R hfg S.x₁ S.x₂ S.gen S.noncyclic e hhom hbij

/-! ## Lemma 5.2 -/

/-- **Lemma 5.2(1)** (`easyfactlemma1`).  An infinite form and a finite form are never braided.

The library statement additionally takes `x₁ ≠ 0` and `x₂ ≠ 0`; with `x₁ = 0` the infinite form
`(ℵ₀, 0)` *is* braided with `(0,0)`.  Here they come free from the setting, by
`ne_zero_of_not_cyclic`: a zero generator could be dropped, making `H` cyclic. -/
theorem lemma_5_2_one (S : Setting5 H) (F G : Form) (hF : F.IsInfinite) (hG : G.IsFinite)
    (hFm : ∀ n, familyOfForm S.x₁ S.x₂ F n ∈ addBase S)
    (hGm : ∀ n, familyOfForm S.x₁ S.x₂ G n ∈ addBase S) :
    ¬ BraidedForms S.x₁ S.x₂ F G hFm hGm :=
  let h := ne_zero_of_not_cyclic S.x₁ S.x₂ S.gen S.noncyclic
  TwoGen.lemma_5_2_one S.x₁ S.x₂ F G hF hG h.1 h.2 hFm hGm

/-- **Lemma 5.2(2)**.  Two finite forms with the same value are braided. -/
theorem lemma_5_2_two (S : Setting5 H) (F G : Form) (hF : F.IsFinite) (hG : G.IsFinite)
    (heq : eval S.x₁ S.x₂ F = eval S.x₁ S.x₂ G)
    (hFm : ∀ n, familyOfForm S.x₁ S.x₂ F n ∈ addBase S)
    (hGm : ∀ n, familyOfForm S.x₁ S.x₂ G n ∈ addBase S) :
    BraidedForms S.x₁ S.x₂ F G hFm hGm :=
  TwoGen.lemma_5_2_two S.x₁ S.x₂ F G hF hG heq hFm hGm

/-- **Lemma 5.2(3)**.  If `x₁ ∈ add x₂` then any two forms `α X₁ + ℵ₀ X₂` and `β X₁ + ℵ₀ X₂` are
braided.

The generation hypothesis is a standing assumption of the section, and the proof genuinely needs
it — it is where `t = m' x₁ + n' x₂` comes from.  Here it is `S.gen`. -/
theorem lemma_5_2_three (S : Setting5 H) (hmem : S.x₁ ∈ add(S.x₂))
    (hmix : NoMixedForms S.x₁ S.x₂) (α β : ℕ∞)
    (hFm : ∀ n, familyOfForm S.x₁ S.x₂ (α, ⊤) n ∈ addBase S)
    (hGm : ∀ n, familyOfForm S.x₁ S.x₂ (β, ⊤) n ∈ addBase S) :
    BraidedForms S.x₁ S.x₂ (α, ⊤) (β, ⊤) hFm hGm :=
  TwoGen.lemma_5_2_three S.x₁ S.x₂ hmem hmix S.gen α β hFm hGm

/-- **Lemma 5.2(4)**.  If `x₁ ∉ add x₂` and `m X₁ + ℵ₀ X₂` is braided with `n X₁ + ℵ₀ X₂`, then
already `m X₁ + k X₂ = n X₁ + k' X₂` for some natural numbers `k`, `k'`.

Takes the standing generation hypothesis, as `S.gen`; the proof needs it to write `v (a, K+1)` in
a form at all. -/
theorem lemma_5_2_four (S : Setting5 H) (hmem : S.x₁ ∉ add(S.x₂))
    (hmix : NoMixedForms S.x₁ S.x₂) (m n : ℕ)
    (hFm : ∀ i, familyOfForm S.x₁ S.x₂ ((m : ℕ∞), ⊤) i ∈ addBase S)
    (hGm : ∀ i, familyOfForm S.x₁ S.x₂ ((n : ℕ∞), ⊤) i ∈ addBase S)
    (hbr : BraidedForms S.x₁ S.x₂ ((m : ℕ∞), ⊤) ((n : ℕ∞), ⊤) hFm hGm) :
    ∃ k k' : ℕ, eval S.x₁ S.x₂ ((m : ℕ∞), (k : ℕ∞)) = eval S.x₁ S.x₂ ((n : ℕ∞), (k' : ℕ∞)) :=
  TwoGen.lemma_5_2_four S.x₁ S.x₂ hmem hmix S.gen m n hFm hGm hbr

/-- **Lemma 5.2(5)**.  Given the braiding of Lemma 5.1, `x₁ ∈ add x₂` iff `ℵ₀(x₁+x₂) = ℵ₀x₂`. -/
theorem lemma_5_2_five (S : Setting5 H)
    (hbr :      IsBraidedOver ℵ₀ ℵ₀ ↥(addBase S) H le_rfl (fun y => (y : H))) :
    S.x₁ ∈ add(S.x₂) ↔
      ℵ₀∙(S.x₁ + S.x₂) = ℵ₀∙S.x₂ :=
  TwoGen.lemma_5_2_five S.x₁ S.x₂ hbr

/-! ## Theorem 5.3 -/

/-- **Theorem 5.3** (`hereditarycasecor`), forward direction.  If `H` is realizable then the three
conditions hold, for both orderings of the generators. -/
theorem theorem_5_3_forward (S : Setting5 H) (R : Type u) [Ring R]
    (hfg : EveryProjectiveIsSumOfFG R)
    (e : V(R).carrier → H)
    (hhom : letI := V(R).instKMonoid le_rfl; IsKHom ℵ₀ e)
    (hbij : Function.Bijective e) :
    Cond1 S.x₁ S.x₂ ∧ Cond1 S.x₂ S.x₁ ∧ Cond2 S.x₁ S.x₂ ∧ Cond2 S.x₂ S.x₁ ∧
      NoMixedForms S.x₁ S.x₂ :=
  TwoGen.theorem_5_3_forward S.x₁ S.x₂ R hfg S.gen S.noncyclic e hhom hbij

/-- **Theorem 5.3**, backward direction: the conditions make `H` realizable, over a `k`-algebra
for any field `k`, and the ring produced is hereditary. -/
theorem theorem_5_3_backward (S : Setting5 H) (k : Type u) [Field k]
    (hc1 : Cond1 S.x₁ S.x₂) (hc1' : Cond1 S.x₂ S.x₁)
    (hc2 : Cond2 S.x₁ S.x₂) (hc2' : Cond2 S.x₂ S.x₁) (hmix : NoMixedForms S.x₁ S.x₂) :
    ∃ (R : Type u) (_ : Ring R) (_ : Algebra k R) (_ : IsLeftHereditary R),
      ∃ e : V(R).carrier → H,
        IsKHom ℵ₀ e ∧ Function.Bijective e :=
  TwoGen.theorem_5_3_backward S.x₁ S.x₂ k S.gen hc1 hc1' hc2 hc2' hmix

/-- **Theorem 5.3** as a single equivalence, in the library's form: realizability over a
hereditary `k`-algebra is equivalent to the three conditions. -/
alias theorem_5_3 := TwoGen.theorem_5_3

/-! ## Proposition 5.4 -/

/-- **Proposition 5.4**.  For two generators `p₁`, `p₂` of `V^{ℵ₀}(R)`: `Tr(P₂) ≤ Tr(P₁)` iff
`Tr(P₁) = R`, and `Tr(P₁) = R` iff `P₁^{(ℵ₀)}` has `P₂` as a direct summand.

Stated at `V^{ℵ₀}(R)` itself rather than through an isomorphism, as the paper does.  The standing
assumptions of §5 appear here as explicit hypotheses rather than as a `Setting5`, because the
`KMonoid` instance on `V^{ℵ₀}(R)` is not in scope while the binder elaborates (trap 3). -/
theorem prop_5_4 (R : Type u) [Ring R] (p₁ p₂ : V(R).carrier)
    (hgen : letI := V(R).instKMonoid le_rfl
      KGenerates ℵ₀ ({p₁, p₂} : Set V(R).carrier))
    (hnoncyclic : letI := V(R).instKMonoid le_rfl
      ∀ x : V(R).carrier,
        ¬ KGenerates ℵ₀ ({x} : Set V(R).carrier)) :
    (traceIdeal R (V(R).rep p₂) ≤ traceIdeal R (V(R).rep p₁)
        ↔ traceIdeal R (V(R).rep p₁) = ⊤) ∧
      (traceIdeal R (V(R).rep p₁) = ⊤ ↔
        ∃ (Q : Type u) (_ : AddCommGroup Q) (_ : Module R Q),
          Nonempty (DirectSum ℕ (fun _ => V(R).rep p₁) ≃ₗ[R]
            V(R).rep p₂ × Q)) :=
  TwoGen.prop_5_4 R p₁ p₂ hgen hnoncyclic

/-! ## Corollary 5.5 -/

/-- **Corollary 5.5(1)** (`hereditarycase`).  When `add x₁` and `add x₂` are incomparable, `H` is
realizable iff finite and infinite forms never share a value, and infinite forms with the same
value agree after replacing the infinite coefficient by suitable finite ones.

The condition is quantified over **both** orderings of the generators, as the paper's
`1 ≤ i ≠ j ≤ 2` requires; both instances of each clause are needed. -/
theorem corollary_5_5_one (S : Setting5 H) (h₁ : S.x₁ ∉ add(S.x₂))
    (h₂ : S.x₂ ∉ add(S.x₁)) :
    IsRealizableAsV H ↔
      ((∀ F G : Form, eval S.x₁ S.x₂ F = eval S.x₁ S.x₂ G →
          (F.1 = ⊤ ↔ G.1 = ⊤) ∧ (F.2 = ⊤ ↔ G.2 = ⊤)) ∧
        (∀ F G : Form, F.1 = ⊤ → G.1 = ⊤ → eval S.x₁ S.x₂ F = eval S.x₁ S.x₂ G →
          ∃ m₁ m₂ : ℕ, eval S.x₁ S.x₂ ((m₁ : ℕ∞), F.2) = eval S.x₁ S.x₂ ((m₂ : ℕ∞), G.2)) ∧
        (∀ F G : Form, F.2 = ⊤ → G.2 = ⊤ → eval S.x₁ S.x₂ F = eval S.x₁ S.x₂ G →
          ∃ n₁ n₂ : ℕ, eval S.x₁ S.x₂ (F.1, (n₁ : ℕ∞)) = eval S.x₁ S.x₂ (G.1, (n₂ : ℕ∞)))) :=
  TwoGen.corollary_5_5_one S.x₁ S.x₂ h₁ h₂ S.gen S.noncyclic

/-- **Corollary 5.5(2)**.  When `add x₁ = add x₂`, `H` is realizable — over a ring all of whose
countably but not finitely generated projectives are free on a countable basis — iff no element
has both a mixed infinite form and another form.

The freeness clause ranges over the classes of `V^{ℵ₀}(R)`, the countably generated projectives,
not over all projective modules: for those it is false — `R^{(ℵ₁)}` is a counterexample, by
invariance of infinite rank (`mk_le_of_span_eq_top`).

Unlike parts (1) and (3) this one names no condition on the decompositions of projective modules,
and needs none: the freeness clause gives `EveryProjectiveIsSumOfFG R` through Kaplansky's theorem
(`everyProjectiveIsSumOfFG_of_free`), which is what Theorem 5.3's forward direction is applied
with. -/
theorem corollary_5_5_two (S : Setting5 H) :
    (add(S.x₁) = add(S.x₂) ∧ NoMixedForms S.x₁ S.x₂) ↔
      (∃ (R : Type u) (_ : Ring R),
        (∀ q : V(R).carrier,
            ¬ Module.Finite R (V(R).rep q) →
            ∃ ι : Type u, #ι ≤ ℵ₀ ∧
              Nonempty (V(R).rep q ≃ₗ[R] DirectSum ι (fun _ => R))) ∧
        ∃ e : V(R).carrier → H,
          IsKHom ℵ₀ e ∧ Function.Bijective e) :=
  TwoGen.corollary_5_5_two S.x₁ S.x₂ S.gen S.noncyclic

/-- **Corollary 5.5(3)**.  When `add x₁ ⊊ add x₂`, `H` is realizable iff every form equal to
`ℵ₀X₁ + nX₂` has finite `X₂`-coefficient and agrees with it after replacing the infinite
`X₁`-coefficient by finite ones.

The paper's part (3) is a three-way equivalence; the other two clauses are
`corollary_5_5_three_nonfree` and `corollary_5_5_three_trace` below. -/
theorem corollary_5_5_three (S : Setting5 H) (h₁ : S.x₁ ∈ add(S.x₂))
    (h₂ : S.x₂ ∉ add(S.x₁)) :
    (∀ (n : ℕ) (β : ℕ∞), eval S.x₁ S.x₂ (⊤, (n : ℕ∞)) = eval S.x₁ S.x₂ (⊤, β) →
        β ≠ ⊤ ∧ ∃ m m' : ℕ,
          eval S.x₁ S.x₂ ((m : ℕ∞), β) = eval S.x₁ S.x₂ ((m' : ℕ∞), (n : ℕ∞)))
      ∧ NoMixedForms S.x₁ S.x₂ ↔ IsRealizableAsV H :=
  TwoGen.corollary_5_5_three S.x₁ S.x₂ h₁ h₂ S.gen S.noncyclic

/-- **Corollary 5.5(3)**, second clause: the same relation condition is equivalent to
realizability by a ring which in addition carries a finitely generated projective `P` with
`P^{(ℵ₀)}` not free. -/
theorem corollary_5_5_three_nonfree (S : Setting5 H) (h₁ : S.x₁ ∈ add(S.x₂))
    (h₂ : S.x₂ ∉ add(S.x₁)) :
    (∀ (n : ℕ) (β : ℕ∞), eval S.x₁ S.x₂ (⊤, (n : ℕ∞)) = eval S.x₁ S.x₂ (⊤, β) →
        β ≠ ⊤ ∧ ∃ m m' : ℕ,
          eval S.x₁ S.x₂ ((m : ℕ∞), β) = eval S.x₁ S.x₂ ((m' : ℕ∞), (n : ℕ∞)))
      ∧ NoMixedForms S.x₁ S.x₂ ↔
      (∃ (R : Type u) (_ : Ring R), EveryProjectiveIsSumOfFG R ∧
        (∃ p : V(R).carrier,
            Module.Finite R (V(R).rep p) ∧
            ¬ ∃ ι : Type u, Nonempty (DirectSum ℕ (fun _ => V(R).rep p)
              ≃ₗ[R] DirectSum ι (fun _ => R))) ∧
          ∃ e : V(R).carrier → H,
            IsKHom ℵ₀ e ∧ Function.Bijective e) :=
  TwoGen.corollary_5_5_three_nonfree S.x₁ S.x₂ h₁ h₂ S.gen S.noncyclic

/-- **Corollary 5.5(3)**, third clause: equivalently, `H ≅ V^{ℵ₀}(R)` for a ring with two finitely
generated projective modules `P₁`, `P₂` generating `V^{ℵ₀}(R)` and satisfying
`Tr(P₁) ⊊ Tr(P₂)`. -/
theorem corollary_5_5_three_trace (S : Setting5 H) (h₁ : S.x₁ ∈ add(S.x₂))
    (h₂ : S.x₂ ∉ add(S.x₁)) :
    (∀ (n : ℕ) (β : ℕ∞), eval S.x₁ S.x₂ (⊤, (n : ℕ∞)) = eval S.x₁ S.x₂ (⊤, β) →
        β ≠ ⊤ ∧ ∃ m m' : ℕ,
          eval S.x₁ S.x₂ ((m : ℕ∞), β) = eval S.x₁ S.x₂ ((m' : ℕ∞), (n : ℕ∞)))
      ∧ NoMixedForms S.x₁ S.x₂ ↔
      (∃ (R : Type u) (_ : Ring R),
        ∃ p₁ p₂ : V(R).carrier,
          Module.Finite R (V(R).rep p₁) ∧
            Module.Finite R (V(R).rep p₂) ∧
            KGenerates ℵ₀ ({p₁, p₂} : Set V(R).carrier) ∧
            traceIdeal R (V(R).rep p₁)
              < traceIdeal R (V(R).rep p₂) ∧
            ∃ e : V(R).carrier → H,
              IsKHom ℵ₀ e ∧ Function.Bijective e) :=
  TwoGen.corollary_5_5_three_trace S.x₁ S.x₂ h₁ h₂ S.gen S.noncyclic

end Paper

end KappaMonoid
