/-
**Section 4 of the paper**: an index of its numbered results.

Each entry names the paper result, and the declaration that formalises it.  Unlike
`Paper/Section5.lean`, which restates §5 in the paper's own terms, this file is an index: the
`alias` checks only that the declaration exists — it copies the target's type, so it does not check
what that type is — and the docstring says which paper result it stands for.  Follow the name, or
`#check` the alias, to read the statement.

Results the development deliberately does not formalise are recorded at the foot of the file.
-/
import KappaMonoid.Modules.Corollary47
import KappaMonoid.Modules.Transport
import KappaMonoid.Paper.Examples48
import KappaMonoid.Modules.Rings.Realisation
import KappaMonoid.Modules.Rings.Semisimple
import KappaMonoid.Examples
import KappaMonoid.Core.Cyclic
import KappaMonoid.Paper.Definition21

namespace KappaMonoid

namespace Paper

/-- **Definition 4.1** — `KappaMonoid.IsLambdaSmall`, in `Modules/Small.lean`. -/
alias definition_4_1_IsLambdaSmall := KappaMonoid.IsLambdaSmall

/-- **Example 4.2(1)** — `KappaMonoid.IsLambdaSmallLe`, in `Modules/Small.lean`: the non-strict
variant of Definition 4.1. -/
alias example_4_2_1_IsLambdaSmallLe := KappaMonoid.IsLambdaSmallLe

/-- **Example 4.2(1)** — `KappaMonoid.IsLambdaSmallLe.isLambdaSmall_succ`: every `λ`-small module
is `(λ⁺)⁻`-small. -/
alias example_4_2_1_isLambdaSmall_succ := KappaMonoid.IsLambdaSmallLe.isLambdaSmall_succ

/-- **Example 4.2(1)**, the converse — `KappaMonoid.IsLambdaSmall.isLambdaSmallLe_of_succ`, in
`Modules/Transport.lean`: a `(λ⁺)⁻`-small module is `λ`-small. -/
alias example_4_2_1_isLambdaSmallLe_of_succ := KappaMonoid.IsLambdaSmall.isLambdaSmallLe_of_succ

/-- **Example 4.2(1)** — `KappaMonoid.isLambdaSmall_succ_iff`: `(λ⁺)⁻`-small iff `λ`-small. -/
alias example_4_2_1_isLambdaSmall_succ_iff := KappaMonoid.isLambdaSmall_succ_iff

/-- **Example 4.2(2)**, last sentence — `KappaMonoid.isLambdaSmall_succ_aleph0_of_countable`:
countably generated modules are `ℵ₁⁻`-small. -/
alias example_4_2_2_isLambdaSmall_succ_aleph0_of_countable :=
  KappaMonoid.isLambdaSmall_succ_aleph0_of_countable

/-- **Example 4.2(2)**, last sentence — `KappaMonoid.isLambdaSmallLe_aleph0_of_countable`:
equivalently, `ℵ₀`-small. -/
alias example_4_2_2_isLambdaSmallLe_aleph0_of_countable :=
  KappaMonoid.isLambdaSmallLe_aleph0_of_countable

/-- **Example 4.2(3)** — `KappaMonoid.IsLambdaGenerated.isLambdaSmall`: the members of `C_{λ⁻}`
are `λ⁻`-small. -/
alias example_4_2_3_isLambdaSmall := KappaMonoid.IsLambdaGenerated.isLambdaSmall

/-- **Example 4.2(3)** — `KappaMonoid.isLambdaGenerated_dsum`: `C_{λ⁻}` is closed under direct
sums over index sets of cardinality `< λ`. -/
alias example_4_2_3_dsum := KappaMonoid.isLambdaGenerated_dsum

/-- **Example 4.2(3)** — `KappaMonoid.IsLambdaGenerated.of_prod_left`: `C_{λ⁻}` is closed under
direct summands. -/
alias example_4_2_3_of_prod_left := KappaMonoid.IsLambdaGenerated.of_prod_left

/-- **Example 4.2(3)** — `KappaMonoid.IsLambdaGenerated.of_equiv`: `C_{λ⁻}` is closed under
isomorphisms. -/
alias example_4_2_3_of_equiv := KappaMonoid.IsLambdaGenerated.of_equiv

/-- **Example 4.2(3)**, for the subclass `C_{λ⁻}` of `C` — `KappaMonoid.ModuleClass.lambdaGenPart_subset_lambdaSmallPart`,
in `Modules/SmallPart.lean`: its members are `λ⁻`-small. -/
alias example_4_2_3_lambdaGenPart_subset_lambdaSmallPart :=
  KappaMonoid.ModuleClass.lambdaGenPart_subset_lambdaSmallPart

/-- **Example 4.2(3)**, for the subclass `C_{λ⁻}` of `C` — `KappaMonoid.ModuleClass.lambdaGenPart_isLSubset`:
it is closed under sums of fewer than `λ` elements, for regular `λ ≤ κ⁺`. -/
alias example_4_2_3_lambdaGenPart_isLSubset := KappaMonoid.ModuleClass.lambdaGenPart_isLSubset

/-- **Example 4.2(3)**, for the subclass `C_{λ⁻}` of `C` — `KappaMonoid.ModuleClass.lambdaGenPart_summand`:
it is closed under direct summands. -/
alias example_4_2_3_lambdaGenPart_summand := KappaMonoid.ModuleClass.lambdaGenPart_summand

/-- **Example 4.2(2)** — `KappaMonoid.isLambdaSmall_aleph0_of_fg`, in `Modules/Small.lean`. -/

alias example_4_2_2_isLambdaSmall_aleph0_of_fg := KappaMonoid.isLambdaSmall_aleph0_of_fg

/-- **Example 4.2(2)** — `KappaMonoid.isLambdaSmall_of_span`, in `Modules/Small.lean`: a module
generated by fewer than `λ` elements is `λ⁻`-small, for every infinite `λ`, regular or not. -/
alias example_4_2_2_isLambdaSmall_of_span := KappaMonoid.isLambdaSmall_of_span

/-- **Theorem 4.3**, the braiding clause (module-theoretic core) — `KappaMonoid.DoubleDecomp.isBraided`,
in `Modules/Theorem43.lean`: families with equal `κ`-sums are `λ⁻`-braided. -/
alias theorem_4_3_isBraided := KappaMonoid.DoubleDecomp.isBraided

/-- **Theorem 4.3** — `KappaMonoid.exists_braided_of_iso`, in `Modules/Theorem43.lean`. -/
alias theorem_4_3_exists_braided_of_iso := KappaMonoid.exists_braided_of_iso

/-- **Theorem 4.3** — `KappaMonoid.theorem_4_3`, in `Modules/Theorem43.lean`: `⟨V^{λ⁻}(C_{λ⁻})⟩_κ` is
`λ⁻`-braided over `V^{λ⁻}(C_{λ⁻})`. -/
alias theorem_4_3_theorem_4_3 := KappaMonoid.theorem_4_3

/-- **Theorem 4.3**, the braiding clause (module-theoretic core) — `KappaMonoid.theorem_4_3_core`,
in `Modules/Theorem43.lean`. -/
alias theorem_4_3_theorem_4_3_core := KappaMonoid.theorem_4_3_core

/-- **Theorem 4.3**, the "in particular" — `KappaMonoid.corollary_4_4`, in `Modules/Theorem43.lean`:
if `V^{λ⁻}(C_{λ⁻})` `κ`-generates `V^κ(C)`, then `V^κ(C)` is `λ⁻`-braided over it (and is its
universal `κ`-extension), for an arbitrary `λ⁻`-closed, summand-closed subset of `V^κ(C)`. -/
alias theorem_4_3_in_particular := KappaMonoid.corollary_4_4

/-- **Corollary 4.4** — `KappaMonoid.corollary_4_4`: the same general form, from which both parts of
Corollary 4.4 follow by taking `C_{λ⁻}` to be the modules generated by fewer than `λ` elements. -/
alias corollary_4_4_corollary_4_4 := KappaMonoid.corollary_4_4

/-- **Corollary 4.4(1)** — `KappaMonoid.corollary_4_4_one`, in `Modules/SmallPart.lean`. -/
alias corollary_4_4_1_corollary_4_4_one := KappaMonoid.corollary_4_4_one

/-- **Corollary 4.4(2)** — `KappaMonoid.corollary_4_4_two`, in `Modules/SmallPart.lean`. -/
alias corollary_4_4_2_corollary_4_4_two := KappaMonoid.corollary_4_4_two

/-- **Corollary 4.5(1)** — `KappaMonoid.corollary_4_5`, in `Modules/Projective.lean`. -/
alias corollary_4_5_1_corollary_4_5 := KappaMonoid.corollary_4_5

/-- **Corollary 4.5(2)** — `KappaMonoid.corollary_4_5_two`, in `Modules/Projective.lean`. -/
alias corollary_4_5_2_corollary_4_5_two := KappaMonoid.corollary_4_5_two

/-- **Corollary 4.5(3)** — `KappaMonoid.corollary_4_5_three`, in `Modules/Projective.lean`. -/
alias corollary_4_5_3_corollary_4_5_three := KappaMonoid.corollary_4_5_three

/-- **After Corollary 4.5** (tex 1743–1748): `V^{ℵ₀}(R)` determines `V^κ(R)` —
`KappaMonoid.exists_kIso_of_aleph1Iso`, in `Modules/Transport.lean`. -/
alias after_corollary_4_5_exists_kIso_of_aleph1Iso := KappaMonoid.exists_kIso_of_aleph1Iso

/-- **After Corollary 4.5**: under `EveryProjectiveIsSumOfFG`, `V(R)` determines `V^κ(R)` —
`KappaMonoid.exists_kIso_of_fgIso`. -/
alias after_corollary_4_5_exists_kIso_of_fgIso := KappaMonoid.exists_kIso_of_fgIso

/-- **Corollary 4.6(2)**, the hereditary case — `KappaMonoid.corollary_4_6_hereditary`: over a
left hereditary ring (the paper's right hereditary, for left modules) `V^κ(R)` is the universal
`κ`-extension of `V(R)`, by Albrecht's theorem and Corollary 4.5(3). -/
alias corollary_4_6_2_hereditary := KappaMonoid.corollary_4_6_hereditary

/-- **Corollary 4.7(1)** — `KappaMonoid.corollary_4_7_one`, in `Modules/Corollary47.lean`: the
three-way equivalence, stated as the two implications (i) ⇔ (ii) and (ii) ⇔ (iii). -/
alias corollary_4_7_1_corollary_4_7_one := KappaMonoid.corollary_4_7_one

/-- **Corollary 4.7(1)**, (iii) ⇒ (i) — `KappaMonoid.corollary_4_7_one_backward_iso`. -/
alias corollary_4_7_1_corollary_4_7_one_backward_iso := KappaMonoid.corollary_4_7_one_backward_iso

/-- **Corollary 4.7(1)**, (iii) ⇒ (i), generation clause only — `KappaMonoid.corollary_4_7_one_backward`,
in `Modules/Corollary47.lean`: `add([R])` `κ`-generates `V^κ(R)`.  The full implication is
`corollary_4_7_one_backward_braided` and `_iso`. -/
alias corollary_4_7_1_corollary_4_7_one_backward := KappaMonoid.corollary_4_7_one_backward

/-- **Corollary 4.7(1)** — `KappaMonoid.corollary_4_7_one_backward_braided`, in `Modules/Corollary47.lean`. -/
alias corollary_4_7_1_corollary_4_7_one_backward_braided := KappaMonoid.corollary_4_7_one_backward_braided

/-- **Corollary 4.7(1)** — `KappaMonoid.corollary_4_7_one_forward`, in `Modules/Corollary47.lean`. -/
alias corollary_4_7_1_corollary_4_7_one_forward := KappaMonoid.corollary_4_7_one_forward

/-- **Corollary 4.7(2)** — `KappaMonoid.corollary_4_7_two_iff`, in `Modules/Corollary47.lean`:
the equivalence itself, over `add_{ℵ₀}(x)` and `V^{ℵ₀}(R)`. -/
alias corollary_4_7_2_corollary_4_7_two_iff := KappaMonoid.corollary_4_7_two_iff

/-- **Corollary 4.7(2)** — `KappaMonoid.corollary_4_7_two`, in `Modules/Corollary47.lean`: the
engine, for an arbitrary `λ⁻`-monoid base braiding both `H` and `V^κ(R)`. -/
alias corollary_4_7_2_corollary_4_7_two := KappaMonoid.corollary_4_7_two

/-- **`add_{ℵ₀} [R] = V^{ℵ₀}(R)`** — `KappaMonoid.addOfCard_unitClass_eq`, the identification
behind both directions of Corollary 4.7(2). -/
alias corollary_4_7_2_addOfCard_unitClass_eq := KappaMonoid.addOfCard_unitClass_eq

/-- **Example 4.8(1)** — `KappaMonoid.krsa_ascent`, in `Modules/Corollary47.lean`: `V^κ(C)` is
`λ⁻`-braided over `F_{λ⁻}(B)`. -/
alias example_4_8_1_krsa_ascent := KappaMonoid.krsa_ascent

/-- **Example 4.8(1)** as printed — `KappaMonoid.krsa_ascent_lambdaGen`: the case where the base
is `V^{λ⁻}(C_{λ⁻})` with `C_{λ⁻}` the `<λ`-generated modules, the braiding supplied by
Corollary 4.4(2). -/
alias example_4_8_1_krsa_ascent_lambdaGen := KappaMonoid.krsa_ascent_lambdaGen

/-- **Example 4.8(1)**, the isomorphism `V^κ(C) ≅ F_κ(B)` the paper states —
`KappaMonoid.krsa_ascent_iso`, in `Modules/Corollary47.lean`.  The two sides live one universe
apart, which is why the test universe of `IsUniversalKExtension` is a parameter. -/
alias example_4_8_1_iso := KappaMonoid.krsa_ascent_iso

/-- **Example 4.8(1)**, the `B`-indexed universal property — `KappaMonoid.krsa_ascent_free`. -/
alias example_4_8_1_free := KappaMonoid.krsa_ascent_free

/-- **Examples 4.8(4)** — `KappaMonoid.Dedekind.isBraided_iff`, in `Examples/Dedekind.lean`: two
families in `D = {(n, g) ∈ ℕ₀ × G : n ≥ 1 or g = 0}` are braided iff both have finite support and
equal sums, or both have infinite support and equal rank sums. -/
alias example_4_8_4_isBraided_iff := KappaMonoid.Dedekind.isBraided_iff

/-- **Examples 4.8(4)** — `KappaMonoid.Dedekind.instKMonoid`: `E_κ = {(α, g) ∈ F_κ × G :
1 ≤ α < ℵ₀ or g = 0}` is a `κ`-monoid. -/
alias example_4_8_4_instKMonoid := KappaMonoid.Dedekind.instKMonoid

/-- **Examples 4.8(4)** — `KappaMonoid.Dedekind.isBraidedOver_dedExt`: `E_κ` is braided over `D`. -/
alias example_4_8_4_isBraidedOver := KappaMonoid.Dedekind.isBraidedOver_dedExt

/-- **Examples 4.8(3)**, `ℕ₀` — `KappaMonoid.examples_4_8_3_nat`, in `Paper/Examples48.lean`: for a ring
whose projectives are sums of finitely generated ones, `V(R) ≅ ℕ₀` gives `V^{ℵ₀}(R) ≅ ℕ₀ ∪ {∞}`. -/
alias example_4_8_3_nat := KappaMonoid.examples_4_8_3_nat

/-- **Examples 4.8(3)**, `ℝ≥0` — `KappaMonoid.examples_4_8_3_nnreal`: `V^{ℵ₀}(R) ≅ ℝ≥0 ∪ ℝ̃>0 ∪ {∞}`. -/
alias example_4_8_3_nnreal := KappaMonoid.examples_4_8_3_nnreal

/-- **Examples 4.8(3)**, `ℚ≥0` — `KappaMonoid.examples_4_8_3_rat`: `V^{ℵ₀}(R) ≅ ℚ≥0 ∪ ℝ̃>0 ∪ {∞}`. -/
alias example_4_8_3_rat := KappaMonoid.examples_4_8_3_rat

/-- **Examples 4.8(3)**, Diophantine monoids (equations and congruences) —
`KappaMonoid.examples_4_8_3_diophantine`: `V^{ℵ₀}(R) ≅ H + ℵ₀H`. -/
alias example_4_8_3_diophantine := KappaMonoid.examples_4_8_3_diophantine

/-- **Examples 4.8(4)** — `KappaMonoid.Dedekind.isUniversalKExtension_dedExt`: `D̂ = E_κ`.
Steinitz's identification `V(R) ≅ D` for a Dedekind domain, which turns this into
`V^κ(R) ≅ E_κ`, is quoted from the literature and not formalised. -/
alias example_4_8_4_isUniversalKExtension := KappaMonoid.Dedekind.isUniversalKExtension_dedExt


/-! ## Not formalised, deliberately

* **Corollary 4.6** is Corollary 4.5(3) together with six results quoted from the literature —
  weakly semihereditary (Bergman), one-sided semihereditary (Bergman), exchange (Warfield),
  semiperfect (Mueller), weakly noetherian commutative (Hinohara), Bézout with one-sided Krull
  dimension (McGovern–Puninski–Rothmaler) — none of them monoid-theoretic and none in Mathlib.
  `EveryProjectiveIsSumOfFG` is the hypothesis those six results supply, and it is what
  `corollary_4_5_three` takes.  The *hereditary* case of the second is formalised
  (`corollary_4_6_hereditary`, through Albrecht's theorem in `ForMathlib/Albrecht.lean`); the
  other cases stay quoted.
* **Examples 4.8**.  Item (1) is formalised as printed, `V^κ(C) ≅ F_κ(B)` included
  (`krsa_ascent_iso`); the general `λ⁻` form above has the paper's finite-KRSA and
  countable/Kaplansky readings as the cases `λ = ℵ₀` and `λ = ℵ₁`.  Item (2) is a question
  (Herbera–Příhoda–Wiegand, Question 1.1) restated in `κ`-monoid language, not a claim.  Item (3)
  is formalised above (`examples_4_8_3_*`), for equations and congruences in the Diophantine case;
  the inequality case goes through slack variables, as the paper says.  Item (4) is formalised on
  the monoid side (above): the braiding criterion over `D` and the universal `κ`-extension
  `D̂ = E_κ`, for every infinite `κ`; only Steinitz's theorem `V(R) ≅ D` is quoted.  Items (5)–(7)
  rest on classical descriptions of `V(R)` or `V^*(R)` quoted from the literature and not in
  Mathlib — Bass, Herbera–Příhoda, Levy–Robson; for (5) Bass's theorem gives the description
  directly, and for (6) the `κ`-monoid step is Proposition 3.15(1), with 3.15(2) recovering
  Herbera–Příhoda's description of `V^{ℵ₀}(R)`.
* **The remark after Corollary 4.7** (tex 1840) that without the sum-of-finitely-generated
  hypothesis `V(R)` does not in general determine `V^{ℵ₀}(R)` is stated in the paper without proof
  or example, and is not formalised.  See `README.md` for the itemised account. -/

end Paper

end KappaMonoid
