/-
**Definition 3.1(2)**: `IsBraidedOver`, a `λ⁻`-braided extension.
-/
import KappaMonoid.Braiding.TransUncountable

universe u v w

open Cardinal Function Set

namespace KappaMonoid

open KMonoid LMonoid


/-! ## Definition 3.1(2): `λ⁻`-braided extensions -/

/-- Definition 3.1(2): the `κ`-monoid `H` is `λ⁻`-braided over the `λ⁻`-monoid `X`,
embedded by `f`.  We ask that

* `f` is an injective `λ⁻`-homomorphism (so that `X` is a `λ⁻`-submonoid of `H`);
* `H` is generated by the image of `f` as a `κ`-monoid;
* any two `κ`-indexed families in `X` with equal `κ`-sum in `H` are `λ⁻`-braided. -/
structure IsBraidedOver (lam κ : Cardinal.{u}) (X : Type v) (H : Type w)
    [LMonoid lam X] [KMonoid κ H] (hlk : lam ≤ κ) (f : X → H) : Prop where
  isLHom : IsLHom hlk f
  injective : Function.Injective f
  generates : ∀ h : H, ∃ x : Idx κ → X, h = ksum (κ := κ) fun i => f (x i)
  braided : ∀ x y : Idx κ → X,
    (ksum (κ := κ) fun i => f (x i)) = (ksum (κ := κ) fun i => f (y i)) → IsBraided lam x y

end KappaMonoid
