/-
`V(R) = add [R]`, **Corollary 4.7** (both directions; the forward one is the only use of axiom
A5) and **Examples 4.8(1)**, the ascent of KRSA.
-/
import KappaMonoid.Modules
import KappaMonoid.Core.AddOf
import KappaMonoid.Core.Free
import KappaMonoid.Core.OrderUnit
import KappaMonoid.Modules.Rings.ProjOrderUnit
import KappaMonoid.Braiding.Saturated

universe u v t

open Cardinal Function Set DirectSum

namespace KappaMonoid

/-! ## `ℵ₀⁻`-small classes are finitely generated

The one module-theoretic input Corollary 4.7(1) needs beyond what `ModuleClass.lean` has.  Both
directions of the corollary want to move between *finitely generated* projective modules — which is
what Bergman–Dicks realises and what `EveryProjectiveIsSumOfFG` produces — and the `ℵ₀⁻`-small
classes of `V^κ(R)`, which is the base Corollary 4.5(3) braids over.  Example 4.2(2) gives one
direction (finitely generated ⟹ `ℵ₀⁻`-small); this is the converse for a class of `V^κ(R)`.

The argument: `ℵ₀⁻`-smallness applied to the inclusion of the representative into `R^{(κ)}` confines
it to finitely many coordinates, so it lies in the span `N` of the corresponding finitely many
standard generators; the projection of `R^{(κ)}` onto the representative is then already surjective
on `N`, and a quotient of a finitely generated module is finitely generated. -/

section FgSmall

variable (R : Type u) [Ring R] (κ : Cardinal.{u})

open DirectSum

/-- An element of `R^{(κ)}` whose coordinates vanish off `s` lies in the span of the standard
generators indexed by `s`. -/
theorem mem_span_freeGen_of_component_eq_zero {x : freeMod R κ} {s : Set (Idx κ)}
    (h : ∀ i ∉ s, (DirectSum.component R (Idx κ) (fun _ => R) i) x = 0) :
    x ∈ Submodule.span R (freeGen R κ '' s) := by
  classical
  rw [← DFinsupp.sum_single (f := x)]
  refine Submodule.sum_mem _ fun i hi => ?_
  have hmem : i ∈ s := by
    by_contra hns
    exact (DFinsupp.mem_support_iff.mp hi) (h i hns)
  have hsingle : (DFinsupp.single i (x i) : freeMod R κ) = (x i) • freeGen R κ i := by
    show (DirectSum.lof R (Idx κ) (fun _ => R) i) (x i) = _
    rw [freeGen, ← LinearMap.map_smul]
    simp
  rw [hsingle]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, hmem, rfl⟩)

/-- **An `ℵ₀⁻`-small summand of `R^{(κ)}` is finitely generated.** -/
theorem finite_of_isLambdaSmall_aleph0 (P : Summand R κ) (h : IsLambdaSmall R ℵ₀ ↥P.1) :
    Module.Finite R ↥P.1 := by
  classical
  -- `ℵ₀⁻`-smallness of the inclusion confines `P` to finitely many coordinates
  obtain ⟨s, hs, hzero⟩ := h (fun _ : Idx κ => R) (fun _ => inferInstance) (fun _ => inferInstance)
    P.1.subtype
  have hsfin : s.Finite := Cardinal.lt_aleph0_iff_set_finite.mp hs
  -- the span of the corresponding generators is finitely generated and contains `P`
  set N : Submodule R (freeMod R κ) := Submodule.span R (freeGen R κ '' s) with hNdef
  have hNfin : Module.Finite R ↥N := by
    rw [hNdef, show freeGen R κ '' s = ((hsfin.image (freeGen R κ)).toFinset : Set (freeMod R κ)) by
      rw [Set.Finite.coe_toFinset]]
    exact Module.Finite.span_finset R _
  have hPN : ∀ y : ↥P.1, (y : freeMod R κ) ∈ N :=
    fun y => mem_span_freeGen_of_component_eq_zero R κ fun i hi => hzero y i hi
  -- the projection of `R^{(κ)}` onto `P` is already surjective on that span
  set q : freeMod R κ →ₗ[R] ↥P.1 :=
    Submodule.projectionOnto P.1 (Summand.compl R κ P) (Summand.isCompl R κ P) with hqdef
  have hq : ∀ y : ↥P.1, q (y : freeMod R κ) = y := fun y =>
    congrFun (congrArg (fun f : ↥P.1 →ₗ[R] ↥P.1 => (f : ↥P.1 → ↥P.1))
      (Submodule.projectionOnto_comp_subtype (p := P.1) (q := Summand.compl R κ P)
        (h := Summand.isCompl R κ P))) y
  refine Module.Finite.of_surjective (q.comp N.subtype) fun y => ?_
  exact ⟨⟨(y : freeMod R κ), hPN y⟩, hq y⟩

/-- **A finitely generated projective module is a direct summand of a finitely generated free
module.**  If `M` is projective and generated by a family `g : ι → M`, then `R^{(ι)}` splits as
`M ⊕ ker π` along the surjection `π : R^{(ι)} → M` sending the `i`-th generator to `g i`.

This is the argument of `exists_summand_of_projective` with the fixed index type `Idx κ` replaced by
an arbitrary one, which is what makes a *finitely generated* free module available. -/
theorem exists_isCompl_of_projective {M : Type u} [AddCommGroup M] [Module R M]
    (hproj : Module.Projective R M) {ι : Type u} (g : ι → M)
    (hspan : Submodule.span R (Set.range g) = ⊤) :
    ∃ Y Z : Submodule R (⨁ _ : ι, R), IsCompl Y Z ∧ Nonempty (↥Y ≃ₗ[R] M) := by
  classical
  haveI := hproj
  set π : (⨁ _ : ι, R) →ₗ[R] M :=
    DirectSum.toModule R ι M (fun i => LinearMap.toSpanSingleton R M (g i)) with hπdef
  have hπgen : ∀ i, π (lof R ι (fun _ => R) i 1) = g i := by
    intro i
    rw [hπdef, DirectSum.toModule_lof (M := fun _ : ι => R) R i (1 : R)]
    show (1 : R) • g i = g i
    rw [one_smul]
  have hπsurj : Function.Surjective π := by
    rw [← LinearMap.range_eq_top, eq_top_iff, ← hspan, Submodule.span_le]
    rintro y ⟨i, rfl⟩
    exact ⟨lof R ι (fun _ => R) i 1, hπgen i⟩
  obtain ⟨σ, hσ⟩ := Module.projective_lifting_property π LinearMap.id hπsurj
  have hσπ : ∀ q, π (σ q) = q := fun q => LinearMap.congr_fun hσ q
  have hσinj : Function.Injective σ := fun q q' h => by rw [← hσπ q, ← hσπ q', h]
  refine ⟨LinearMap.range σ, LinearMap.ker π, ⟨?_, ?_⟩,
    ⟨(LinearEquiv.ofInjective σ hσinj).symm⟩⟩
  · rw [Submodule.disjoint_def]
    rintro y ⟨q, rfl⟩ hker
    have hq : q = 0 := by rw [← hσπ q]; exact hker
    rw [hq, map_zero]
  · rw [codisjoint_iff, eq_top_iff]
    intro y _
    refine Submodule.mem_sup.mpr ⟨σ (π y), ⟨π y, rfl⟩, y - σ (π y), ?_, by abel⟩
    show π (y - σ (π y)) = 0
    rw [map_sub, hσπ, sub_self]

/-- A finitely generated projective module is the representative of an `ℵ₀⁻`-small class of
`V^κ(R)`: being finitely generated it is generated by at most `κ` elements, hence a summand of
`R^{(κ)}`, and finitely generated modules are `ℵ₀⁻`-small (Example 4.2(2)). -/
theorem exists_class_of_fg_projective (hκ : ℵ₀ ≤ κ) (Q : Type u) [AddCommGroup Q] [Module R Q]
    (hproj : Module.Projective R Q) (hfin : Module.Finite R Q) :
    ∃ a : (projClass R κ hκ).carrier, a ∈ (projClass R κ hκ).lambdaSmallPart ℵ₀ ∧
      Nonempty ((projClass R κ hκ).rep a ≃ₗ[R] Q) := by
  haveI := hproj
  obtain ⟨s, hs⟩ := hfin.fg_top
  have hlt : #(↑s : Set Q) < ℵ₀ := by
    rw [Cardinal.lt_aleph0_iff_set_finite]
    exact s.finite_toSet
  obtain ⟨P, hP⟩ := exists_summand_of_projective R κ Q ↑s (hlt.le.trans hκ) hs
  -- state the isomorphism at the summand rather than at `rep ⟦P⟧`: instance search does not see
  -- through `projClass` (trap 1), so `⟦P⟧` must not appear in an index of a class
  have e : ↥((⟦P⟧ : Quotient (summandSetoid R κ)).out.1) ≃ₗ[R] Q :=
    (Quotient.mk_out (s := summandSetoid R κ) P).some.trans hP.some
  have hsmall : IsLambdaSmall R ℵ₀ ↥((⟦P⟧ : Quotient (summandSetoid R κ)).out.1) :=
    IsLambdaSmall.of_equiv (M := Q) (M' := ↥((⟦P⟧ : Quotient (summandSetoid R κ)).out.1))
      (isLambdaSmall_aleph0_of_fg R Q hfin) e.symm
  exact ⟨⟦P⟧, hsmall, ⟨e⟩⟩

end FgSmall

/-! ## `V(R) = add [R]`

The identification behind both directions of Corollary 4.7(1).  The `ℵ₀⁻`-small classes of
`V^κ(R)` are — by `finite_of_isLambdaSmall_aleph0` and Example 4.2(2) — the finitely generated
projective modules, and those are exactly the summands of the finite multiples `n·[R]` of the class
of `R`.  Neither inclusion needs a hypothesis on `R`. -/

section AddUnit

variable (R : Type u) [Ring R] (κ : Cardinal.{u}) (hκ : ℵ₀ ≤ κ)

/-- `#ι` copies of `[R]` are represented by the free module `R^{(ι)}`, for any index type of
cardinality at most `κ`: the form of `rep_cmul_unitClass` that does not go through `Idx`. -/
theorem rep_cmul_mk_unitClass {ι : Type u} (hι : #ι ≤ κ) (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    Nonempty ((projClass R κ hκ).rep
      (KMonoid.cmul (κ := κ) #ι hι (Projective.unitClass R κ hκ k)) ≃ₗ[R] ⨁ _ : ι, R) := by
  letI := (projClass R κ hκ).instKMonoid hκ
  have he : Idx (#ι) ≃ ι := (Cardinal.eq.mp (mk_Idx #ι)).some
  exact ⟨(Projective.rep_cmul_unitClass R κ hκ hι k).some.trans (DirectSum.lequivCongrLeft R he)⟩

/-- A class of `V^κ(R)` with finitely generated representative is a summand of a finite multiple of
`[R]`: a finitely generated projective module is a direct summand of some `R^n`. -/
theorem exists_add_eq_cmul_unitClass (k : Idx κ) (a : (projClass R κ hκ).carrier)
    (hfin : Module.Finite R ((projClass R κ hκ).rep a)) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ (c : (projClass R κ hκ).carrier) (n : ℕ),
      a + c = KMonoid.cmul (κ := κ) ((n : ℕ) : Cardinal.{u})
        (le_trans (le_of_lt Cardinal.natCast_lt_aleph0) hκ) (Projective.unitClass R κ hκ k) := by
  letI := (projClass R κ hκ).instKMonoid hκ
  classical
  -- a finite generating set of the representative, and the free module on it
  obtain ⟨s, hs⟩ := hfin.fg_top
  have hlt : #(↑s : Set ((projClass R κ hκ).rep a)) < ℵ₀ := by
    rw [Cardinal.lt_aleph0_iff_set_finite]
    exact s.finite_toSet
  obtain ⟨Y, Z, hYZ, hY⟩ := exists_isCompl_of_projective R (summand_projective R κ a.out)
    (fun i : (↑s : Set ((projClass R κ hκ).rep a)) => (i : (projClass R κ hκ).rep a))
    (by rw [Subtype.range_coe]; exact hs)
  -- `R^{(s)}` is `#s` copies of `[R]`, and `Z` is again a class
  have hA := rep_cmul_mk_unitClass R κ hκ (hlt.le.trans hκ) k
  obtain ⟨c, hc⟩ := (projClass R κ hκ).exists_class_of_summand _ hA.some hYZ.symm
  obtain ⟨n, hn⟩ := Cardinal.lt_aleph0.mp hlt
  refine ⟨c, n, ?_⟩
  have hsum : a + c = KMonoid.cmul (κ := κ) #(↑s : Set ((projClass R κ hκ).rep a))
      (hlt.le.trans hκ) (Projective.unitClass R κ hκ k) :=
    (projClass R κ hκ).add_eq_of_relCompl hκ hYZ.disjoint (codisjoint_iff.mp hYZ.codisjoint)
      ⟨hY.some.symm⟩ hc ⟨hA.some.trans Submodule.topEquiv.symm⟩
  rw [hsum]
  exact KMonoid.cmul_congr hn _ _ (Projective.unitClass R κ hκ k)

/-- **`V(R) = add([R])`**: the `ℵ₀⁻`-small part of `V^κ(R)` — the classes of finitely generated
projective modules — is the set of summands of the finite multiples of the class of `R`. -/
theorem addOf_unitClass_eq (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KMonoid.addOf (κ := κ) (Projective.unitClass R κ hκ k)
      = (projClass R κ hκ).lambdaSmallPart ℵ₀ := by
  letI := (projClass R κ hκ).instKMonoid hκ
  refine Set.Subset.antisymm (fun y hy => ?_) (fun y hy => ?_)
  · -- a summand of `R^n` is finitely generated, hence `ℵ₀⁻`-small
    obtain ⟨z, n, hzn⟩ := hy
    haveI : Finite (Idx ((n : ℕ) : Cardinal.{u})) := by
      rw [← Cardinal.lt_aleph0_iff_finite, mk_Idx]
      exact Cardinal.natCast_lt_aleph0
    have hiso : Nonempty (((projClass R κ hκ).rep y × (projClass R κ hκ).rep z)
        ≃ₗ[R] ⨁ _ : Idx ((n : ℕ) : Cardinal.{u}), R) :=
      ⟨((projClass R κ hκ).rep_add hκ y z).some.symm.trans
        (((projClass R κ hκ).iso_of_eq hzn).some.trans
          (Projective.rep_cmul_unitClass R κ hκ _ k).some)⟩
    haveI : Module.Finite R ((projClass R κ hκ).rep y × (projClass R κ hκ).rep z) :=
      Module.Finite.equiv hiso.some.symm
    haveI : Nonempty ((projClass R κ hκ).rep z) := ⟨0⟩
    have hfiny : Module.Finite R ((projClass R κ hκ).rep y) :=
      Module.Finite.of_surjective (LinearMap.fst R ((projClass R κ hκ).rep y)
        ((projClass R κ hκ).rep z)) Prod.fst_surjective
    -- `IsLambdaSmall` unfolds to a `∀`, so the goal has to be put in that form before `exact`
    show IsLambdaSmall R ℵ₀ ((projClass R κ hκ).rep y)
    exact isLambdaSmall_aleph0_of_fg R ((projClass R κ hκ).rep y) hfiny
  · -- an `ℵ₀⁻`-small class has a finitely generated representative, hence divides some `n·[R]`
    obtain ⟨c, n, hcn⟩ := exists_add_eq_cmul_unitClass R κ hκ k y
      (finite_of_isLambdaSmall_aleph0 R κ y.out ((projClass R κ hκ).isLambdaSmall_of_mem hy))
    exact ⟨c, n, hcn⟩

end AddUnit

/-! ## Corollary 4.6

Each of the six conditions — weakly semihereditary, one-sided semihereditary, exchange,
semiperfect, weakly noetherian commutative, Bézout with one-sided Krull dimension — implies that
every projective module is a direct sum of finitely generated modules, and the corollary then
follows from `corollary_4_5_three`, which is *proved*.

Those six implications are the quoted results (Bergman; Warfield; Mueller; Hinohara;
McGovern–Puninski–Rothmaler).  There is nothing further to formalise: Corollary 4.6 is exactly
`corollary_4_5_three` plus six citations, so the documented stub in `ModuleClass.lean` is the right
treatment and this file adds nothing for it.  `EveryProjectiveIsSumOfFG` names the hypothesis so
that the six implications can be stated if that module theory ever lands in Mathlib. -/

/-- The property quoted from the literature for each of the six classes of Corollary 4.6. -/
def EveryProjectiveIsSumOfFG (R : Type u) [Ring R] : Prop :=
  ∀ (P : Type u) (_ : AddCommGroup P) (_ : Module R P), Module.Projective R P →
    ∃ (ι : Type u) (Q : ι → Type u) (_ : ∀ i, AddCommGroup (Q i)) (_ : ∀ i, Module R (Q i)),
      (∀ i, Module.Projective R (Q i)) ∧ (∀ i, Module.Finite R (Q i)) ∧
        Nonempty (P ≃ₗ[R] ⨁ i, Q i)

/-! ## Corollary 4.7

Part (2) is provable with what is already here.  Part (1) needs the Bergman–Dicks realisation
theorem, which is axiom A5 — `bergmanDicksData` in `KappaMonoid/Axioms.lean`. -/

section Cor47

variable {κ : Cardinal.{u}}

/-- **The engine of Corollary 4.7(2)**: two `κ`-monoids braided over the same `λ⁻`-monoid are
isomorphic.  Both are universal `κ`-extensions of it (Theorem 3.11(2)), and a universal
`κ`-extension is unique up to a unique isomorphism.

This needs no external input, and it is what makes Corollary 4.7(2) reachable now. -/
theorem isKIso_of_braidedOver_same {lam : Cardinal.{u}} {S : Type u} [LMonoid lam S]
    {H₁ H₂ : Type u} [KMonoid κ H₁] [KMonoid κ H₂] (hlk : lam ≤ κ)
    {f : S → H₁} {g : S → H₂}
    (hbr₁ : IsBraidedOver lam κ S H₁ hlk f) (hbr₂ : IsBraidedOver lam κ S H₂ hlk g) :
    ∃ e : H₁ → H₂, KMonoid.IsKHom κ e ∧ (∀ s, e (f s) = g s) ∧ Function.Bijective e :=
  -- the test universe of the universal property is now a parameter, so it has to be pinned:
  -- here both extensions live in `Type u` and are compared against test objects there.
  have h₁ : IsUniversalKExtension.{u, u, u, u} lam κ S H₁ hlk f := hbr₁.isUniversalKExtension hlk
  have h₂ : IsUniversalKExtension.{u, u, u, u} lam κ S H₂ hlk g := hbr₂.isUniversalKExtension hlk
  (isUniversalKExtension_unique hlk h₁ h₂).exists

/-- **Corollary 4.7(2)**: for a ring `R` and a `κ`-monoid `H`, if `H` is `ℵ₁⁻`-braided over a
`λ⁻`-monoid `S` and `V^{ℵ₀}(R)` is too — which is Corollary 4.5(2) — then `V^κ(R) ≅ H`.

The `S` of the paper is `add_{ℵ₀} x` for a suitable `x ∈ H`; the statement is given for a general
`S` because that is what the proof uses, and `addOfCard` supplies the paper's instance. -/
theorem corollary_4_7_two {S : Type u} [LMonoid ℵ₀ S] {H : Type u} [KMonoid κ H]
    (R : Type u) [Ring R] (hκ : ℵ₀ ≤ κ) {f : S → H}
    (hbr : IsBraidedOver ℵ₀ κ S H hκ f)
    {g : S → (projClass R κ hκ).carrier}
    (hbr' : letI := (projClass R κ hκ).instKMonoid hκ
      IsBraidedOver ℵ₀ κ S (projClass R κ hκ).carrier hκ g) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ e : H → (projClass R κ hκ).carrier,
      KMonoid.IsKHom κ e ∧ (∀ s, e (f s) = g s) ∧ Function.Bijective e := by
  letI := (projClass R κ hκ).instKMonoid hκ
  exact isKIso_of_braidedOver_same hκ hbr hbr'

/-- **Corollary 4.7(1)**, (iii) ⇒ (i): if `V^κ(R) ≅ H` for a ring `R` all of whose projectives
are direct sums of finitely generated modules — in particular a hereditary ring, by Corollary 4.6
— then `V^κ(R)` is `κ`-generated by `add [R]`, since `V(R) = add [R]`. -/
theorem corollary_4_7_one_backward (R : Type u) [Ring R] (hκ : ℵ₀ ≤ κ)
    (hfg : EveryProjectiveIsSumOfFG R) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ x : (projClass R κ hκ).carrier,
      KMonoid.KGenerates κ (KMonoid.addOf (κ := κ) x) := by
  letI := (projClass R κ hκ).instKMonoid hκ
  letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
    ((projClass R κ hκ).lambdaSmallPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 hκ)
  obtain ⟨k⟩ := nonempty_Idx hκ
  refine ⟨Projective.unitClass R κ hκ k, ?_⟩
  rw [addOf_unitClass_eq R κ hκ k]
  exact (corollary_4_5_three.{u, u} R κ hκ hfg).1.kGenerates_coe

/-- **Corollary 4.7(1)**, (iii) ⇒ (i) in the form the paper states it: `V^κ(R)` is `ℵ₀⁻`-braided
over `add [R]`.  This is Corollary 4.5(3) — which braids `V^κ(R)` over `V(R)` — moved along the
identification `V(R) = add [R]` of `addOf_unitClass_eq`.

It is this form, rather than the generation statement above, that feeds
`corollary_4_7_one_forward`, so that the two together are the equivalence (i) ⇔ (ii) of the
corollary. -/
theorem corollary_4_7_one_backward_braided (R : Type u) [Ring R] (hκ : ℵ₀ ≤ κ)
    (hfg : EveryProjectiveIsSumOfFG R) (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
      (KMonoid.addOf_isLSubset hκ (Projective.unitClass R κ hκ k))
    IsBraidedOver ℵ₀ κ ↥(KMonoid.addOf (κ := κ) (Projective.unitClass R κ hκ k))
      (projClass R κ hκ).carrier hκ (fun y => (y : (projClass R κ hκ).carrier)) := by
  letI := (projClass R κ hκ).instKMonoid hκ
  exact IsBraidedOver.of_set_eq Cardinal.isRegular_aleph0
    (KMonoid.addOf_isLSubset hκ (Projective.unitClass R κ hκ k))
    ((projClass R κ hκ).lambdaSmallPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 hκ)
    (addOf_unitClass_eq R κ hκ k) (corollary_4_5_three.{u, u} R κ hκ hfg).1

/-- **The isomorphism `M ≅ V(R)` packaged by `BergmanDicksData`.**  The four conditions
`iso_zero`, `iso_add`, `inj`, `surj` say that `a ↦ [P a]` is a monoid isomorphism from `M` onto the
finitely generated projective modules; here it is read as an isomorphism of `ℵ₀⁻`-monoids from `M`
onto the `ℵ₀⁻`-small part of `V^κ(bd.R)`, which is the base Corollary 4.5(3) braids over.

Only `isLMonoidHom_aleph0_of_add` is needed for the multiplicativity: for `λ = ℵ₀` a homomorphism of
`λ⁻`-monoids is just an additive map.  Surjectivity is where `finite_of_isLambdaSmall_aleph0` enters:
an `ℵ₀⁻`-small class has a finitely generated representative, so `surj` applies to it. -/
theorem BergmanDicksData.exists_isLMonoidHom_bijective {k : Type u} [Field k] {M : Type u}
    [LMonoid (ℵ₀ : Cardinal.{u}) M] {u : M} (bd : BergmanDicksData k M u) (κ : Cardinal.{u})
    (hκ : ℵ₀ ≤ κ) :
    letI := (projClass bd.R κ hκ).instKMonoid hκ
    letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
      ((projClass bd.R κ hκ).lambdaSmallPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 hκ)
    ∃ Φ : M → ↥((projClass bd.R κ hκ).lambdaSmallPart ℵ₀),
      IsLMonoidHom ℵ₀ Φ ∧ Function.Injective Φ ∧ Function.Surjective Φ := by
  letI := (projClass bd.R κ hκ).instKMonoid hκ
  letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
    ((projClass bd.R κ hκ).lambdaSmallPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 hκ)
  classical
  -- each `P a` is a finitely generated projective module, hence an `ℵ₀⁻`-small class
  have hclass : ∀ a : M, ∃ c : (projClass bd.R κ hκ).carrier,
      c ∈ (projClass bd.R κ hκ).lambdaSmallPart ℵ₀ ∧
        Nonempty ((projClass bd.R κ hκ).rep c ≃ₗ[bd.R] bd.P a) := fun a =>
    exists_class_of_fg_projective bd.R κ hκ (bd.P a) (bd.proj a) (bd.fin a)
  choose Φ₀ hmem hiso using hclass
  have h0 : Φ₀ 0 = 0 := by
    haveI := bd.iso_zero
    haveI : Subsingleton ((projClass bd.R κ hκ).rep (Φ₀ 0)) :=
      Equiv.subsingleton (hiso 0).some.toEquiv
    exact ((projClass bd.R κ hκ).eq_zero_of_subsingleton this).trans
      ((projClass bd.R κ hκ).instKMonoid_zero hκ).symm
  have hadd : ∀ a b : M, Φ₀ (a + b) = Φ₀ a + Φ₀ b := fun a b =>
    (projClass bd.R κ hκ).eq_of_iso ((hiso (a + b)).some.trans ((bd.iso_add a b).some.trans
      ((LinearEquiv.prodCongr (hiso a).some.symm (hiso b).some.symm).trans
        ((projClass bd.R κ hκ).rep_add hκ (Φ₀ a) (Φ₀ b)).some.symm)))
  -- `IsLMonoidHom` is a plain `def`, so the map has to be pinned by an ascription (trap 7)
  have hhom : IsLMonoidHom (ℵ₀ : Cardinal.{u})
      (fun a : M => (⟨Φ₀ a, hmem a⟩ : ↥((projClass bd.R κ hκ).lambdaSmallPart ℵ₀))) :=
    isLMonoidHom_aleph0_of_add
      (g := fun a : M => (⟨Φ₀ a, hmem a⟩ : ↥((projClass bd.R κ hκ).lambdaSmallPart ℵ₀)))
      (Subtype.ext h0) fun a b => Subtype.ext (hadd a b)
  refine ⟨fun a : M => (⟨Φ₀ a, hmem a⟩ : ↥((projClass bd.R κ hκ).lambdaSmallPart ℵ₀)), hhom,
    fun a b hab => ?_, ?_⟩
  · -- injectivity is `inj`
    exact bd.inj a b ⟨(hiso a).some.symm.trans
      (((projClass bd.R κ hκ).iso_of_eq (congrArg Subtype.val hab)).some.trans (hiso b).some)⟩
  · -- surjectivity is `surj`, applied to the representative of an `ℵ₀⁻`-small class
    rintro ⟨c, hc⟩
    have hfin : Module.Finite bd.R ((projClass bd.R κ hκ).rep c) :=
      finite_of_isLambdaSmall_aleph0 bd.R κ c.out
        ((projClass bd.R κ hκ).isLambdaSmall_of_mem hc)
    obtain ⟨a, ha⟩ := bd.surj ((projClass bd.R κ hκ).rep c) inferInstance inferInstance
      (summand_projective bd.R κ c.out) hfin
    exact ⟨a, Subtype.ext ((projClass bd.R κ hκ).eq_of_iso ((hiso a).some.trans ha.some.symm))⟩

/-- **Corollary 4.7(1)**, (i) ⇒ (ii), the direction that needs Bergman–Dicks (axiom A5).

Given `x ∈ H` with `H` braided over `add x`, and a field `k`, the monoid `add x` is reduced with
order-unit `x` — steps 1 and 2 of the plan — so A5 supplies a hereditary `k`-algebra `R` with
`V(R) ≅ add x`.  `BergmanDicksData.sumOfFG` feeds `corollary_4_5_three`, making `V^κ(R)` braided
over `V(R)`; `isKIso_of_braidedOver_same` then identifies `V^κ(R)` with `H`. -/
theorem corollary_4_7_one_forward {H : Type u} [KMonoid κ H] (hκ : ℵ₀ ≤ κ)
    (k : Type u) [Field k] (x : H)
    (hbr : letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0 (KMonoid.addOf_isLSubset hκ x)
      IsBraidedOver ℵ₀ κ ↥(KMonoid.addOf (κ := κ) x) H hκ (fun y => (y : H))) :
    ∃ (R : Type u) (_ : Ring R) (_ : Algebra k R) (_ : ∀ I : Ideal R, Module.Projective R I),
      EveryProjectiveIsSumOfFG R ∧
      letI := (projClass R κ hκ).instKMonoid hκ
      ∃ e : (projClass R κ hκ).carrier → H, KMonoid.IsKHom κ e ∧ Function.Bijective e := by
  classical
  letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0 (KMonoid.addOf_isLSubset hκ x)
  -- Step 1: `add x` is reduced (Lemma 2.8, through the inclusion) with order-unit `x`
  have hcoe : ∀ a b : ↥(KMonoid.addOf (κ := κ) x),
      ((a + b : ↥(KMonoid.addOf (κ := κ) x)) : H) = (a : H) + (b : H) := fun _ _ => rfl
  have hred : ∀ a b : ↥(KMonoid.addOf (κ := κ) x), a + b = 0 → a = 0 := fun a b hab =>
    (LMonoid.isConical_of_injective (fun y : ↥(KMonoid.addOf (κ := κ) x) => (y : H))
      Subtype.val_injective rfl hcoe a b hab).1
  have hxmem : x ∈ KMonoid.addOf (κ := κ) x := KMonoid.self_mem_addOf x
  haveI : Nonempty ↥(KMonoid.addOf (κ := κ) x) := ⟨⟨x, hxmem⟩⟩
  have hnsmul : ∀ (m : ℕ) (u : ↥(KMonoid.addOf (κ := κ) x)),
      ((m • u : ↥(KMonoid.addOf (κ := κ) x)) : H) = m • (u : H) := by
    intro m u
    induction m with
    | zero => rw [zero_nsmul, zero_nsmul]; rfl
    | succ p hp => rw [succ_nsmul, succ_nsmul, hcoe, hp]
  have hunit : ∀ y : ↥(KMonoid.addOf (κ := κ) x),
      ∃ (z : ↥(KMonoid.addOf (κ := κ) x)) (n : ℕ), y + z = n • (⟨x, hxmem⟩ :
        ↥(KMonoid.addOf (κ := κ) x)) := by
    refine fun y => ?_
    obtain ⟨z, n, hzn⟩ := y.2
    -- the complementary summand is again a summand of a multiple of `x`
    refine ⟨⟨z, ⟨(y : H), n, by rw [add_comm]; exact hzn⟩⟩, n, Subtype.ext ?_⟩
    show (y : H) + z = _
    rw [hnsmul, ← KMonoid.cmul_natCast]
    exact hzn
  -- Step 2: Bergman–Dicks (axiom A5) realises `add x` as `V(R)` for a hereditary `k`-algebra `R`
  have bd := bergmanDicksData k ↥(KMonoid.addOf (κ := κ) x) ⟨x, hxmem⟩ hred hunit
  refine ⟨bd.R, bd.ring, bd.algebra, bd.hereditary, bd.sumOfFG, ?_⟩
  letI := (projClass bd.R κ hκ).instKMonoid hκ
  letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
    ((projClass bd.R κ hκ).lambdaSmallPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 hκ)
  -- Step 3: `BergmanDicksData.sumOfFG` is the hypothesis of Corollary 4.5(3)
  obtain ⟨hbr₂, -⟩ := corollary_4_5_three.{u, u} bd.R κ hκ bd.sumOfFG
  -- Step 4: transport that braiding along `add x ≅ V(R)`
  obtain ⟨Φ, hΦhom, hΦinj, hΦsurj⟩ := bd.exists_isLMonoidHom_bijective κ hκ
  have hΦΦ' : ∀ a, Function.invFun Φ (Φ a) = a := Function.leftInverse_invFun hΦinj
  have hΦ'Φ : ∀ c, Φ (Function.invFun Φ c) = c := fun c => Function.invFun_eq (hΦsurj c)
  have hΦ'hom : IsLMonoidHom ℵ₀ (Function.invFun Φ) := hΦhom.inv hΦΦ' hΦ'Φ
  have hbr₁ : IsBraidedOver ℵ₀ κ ↥(KMonoid.addOf (κ := κ) x) (projClass bd.R κ hκ).carrier hκ
      (fun a => ((Φ a : ↥((projClass bd.R κ hκ).lambdaSmallPart ℵ₀)) :
        (projClass bd.R κ hκ).carrier)) :=
    hbr₂.of_base_iso hκ (g := Φ) (g' := Function.invFun Φ) hΦhom hΦ'hom hΦΦ' hΦ'Φ
  -- Step 5: two `κ`-monoids braided over `add x` are isomorphic
  obtain ⟨e, hehom, -, hebij⟩ := isKIso_of_braidedOver_same hκ hbr₁ hbr
  exact ⟨e, hehom, hebij⟩

end Cor47

/-! ## Example 4.8(1): ascent of KRSA

If every module in `C` is a direct sum of `λ⁻`-small ones and `V^{λ⁻}(C_{λ⁻})` is a *free*
`λ⁻`-monoid on `B`, then `V^κ(C)` is the free `κ`-monoid on `B`.  Theorem 4.3 makes `V^κ(C)`
`λ⁻`-braided over `V^{λ⁻}(C_{λ⁻})`, hence its universal `κ`-extension (Theorem 3.11(2)), and
transporting that along the isomorphism of bases says exactly that `V^κ(C)` is the universal
`κ`-extension of `F_{λ⁻}(B)`.

**A universe remark on the statement.**  One would like to conclude `V^κ(C) ≅ F_κ(B)` by combining
this with Lemma 3.13(1) and uniqueness.  That comparison is not available: `F_κ(B)` is cut out of
`B → F_κ` and so lives in `Type (u+1)`, while `V^κ(C)` lives in `Type u`, and
`isUniversalKExtension_unique` — like the universal property itself, which quantifies over test
objects in the *same* universe as the extension — compares two extensions in one universe only.
The universal property below is the universe-correct form of "is the free `κ`-monoid on `B`", and
composing it with the `λ⁻`-level universal property of `F_{λ⁻}(B)` (`Free.exists_unique_lift`,
whose target universe *is* free) recovers the usual `B`-indexed formulation. -/

section KRSA

variable {R : Type u} [Ring R] {κ : Cardinal.{u}}

/-- **Example 4.8(1)**: finite KRSA ascends to infinite KRSA — if `V^{λ⁻}(C_{λ⁻})` is free on `B`,
then `V^κ(C)` is the universal `κ`-extension of the free `λ⁻`-monoid on `B`. -/
theorem krsa_ascent (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ κ) (B : Type u)
    (hfree : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      letI := IsLSubset.lmonoid hlam (C.lambdaSmallPart_isLSubset hκ lam hlam hlk)
      ∃ e : ↥(C.lambdaSmallPart lam) → ↥(FreeL lam B),
        IsLMonoidHom lam e ∧ Function.Bijective e)
    (hbr : letI := C.instKMonoid hκ
      letI := IsLSubset.lmonoid hlam (C.lambdaSmallPart_isLSubset hκ lam hlam hlk)
      IsBraidedOver lam κ ↥(C.lambdaSmallPart lam) C.carrier hlk (fun a => (a : C.carrier))) :
    letI : Fact lam.IsRegular := ⟨hlam⟩
    letI := C.instKMonoid hκ
    ∃ f : ↥(FreeL lam B) → C.carrier,
      IsBraidedOver lam κ ↥(FreeL lam B) C.carrier hlk f := by
  letI : Fact lam.IsRegular := ⟨hlam⟩
  letI := C.instKMonoid hκ
  letI := IsLSubset.lmonoid hlam (C.lambdaSmallPart_isLSubset hκ lam hlam hlk)
  classical
  obtain ⟨e, hehom, hebij⟩ := hfree
  -- the inverse of the isomorphism of bases is again a `λ⁻`-homomorphism
  set e' : ↥(FreeL lam B) → ↥(C.lambdaSmallPart lam) := Function.invFun e with he'def
  have hee' : ∀ a, e' (e a) = a := Function.leftInverse_invFun hebij.injective
  have he'e : ∀ b, e (e' b) = b := fun b => Function.invFun_eq (hebij.surjective b)
  have he'hom : IsLMonoidHom lam e' := hehom.inv hee' he'e
  -- `V^κ(C)` is the universal `κ`-extension of `V^{λ⁻}(C_{λ⁻})`, hence of `F_{λ⁻}(B)`
  refine ⟨fun b => ((e' b : ↥(C.lambdaSmallPart lam)) : C.carrier), ?_⟩
  exact IsBraidedOver.of_base_iso hlk hbr he'hom hehom he'e hee'

/-- The `B`-indexed form: `V^κ(C)` has the universal property of the free `κ`-monoid on `B`.  Every
map from `B` into a `κ`-monoid extends uniquely along the generators `ι(b)`. -/
theorem krsa_ascent_free (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ κ) (B : Type u)
    {f : letI : Fact lam.IsRegular := ⟨hlam⟩; ↥(FreeL lam B) → C.carrier}
    (huniv : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      IsUniversalKExtension.{u, u + 1, u, t} lam κ ↥(FreeL lam B) C.carrier hlk f) :
    letI : Fact lam.IsRegular := ⟨hlam⟩
    letI := C.instKMonoid hκ
    ∀ (K : Type t) [KMonoid κ K] (g : B → K),
      ∃! ψ : C.carrier → K, KMonoid.IsKHom κ ψ ∧ ∀ b, ψ (f (iota b)) = g b := by
  letI : Fact lam.IsRegular := ⟨hlam⟩
  letI := C.instKMonoid hκ
  intro K _ g
  letI := KMonoid.toLMonoidOfLE K hlam hlk
  -- lift `g` to the free `λ⁻`-monoid, then extend along the universal property
  have hlift : LMonoid.IsLHom hlk (lift (lam := lam) g) :=
    isLHom_of_isLMonoidHom hlam hlk (isLMonoidHom_lift (lam := lam) g)
  obtain ⟨ψ, ⟨hψhom, hψ⟩, hψu⟩ := huniv.universal K (lift (lam := lam) g) hlift
  refine ⟨ψ, ⟨hψhom, fun b => ?_⟩, fun ψ' ⟨hψ'hom, hψ'⟩ => ?_⟩
  · rw [hψ (iota b), lift_iota]
  refine hψu ψ' ⟨hψ'hom, fun x => ?_⟩
  -- two extensions agreeing on the generators agree, by uniqueness at the `λ⁻` level
  have hcomp0 : LMonoid.IsLHom hlk (fun y : ↥(FreeL lam B) => ψ' (f y)) := by
    refine ⟨by show ψ' (f 0) = 0; rw [huniv.isLHom.1, hψ'hom.1], fun {ι} hι y => ?_⟩
    show ψ' (f (LMonoid.lsumOf hι y)) = _
    rw [huniv.isLHom.2 hι y, hψ'hom.map_sumOf (hι.le.trans hlk) (f ∘ y)]
    rfl
  have hcomp : IsLMonoidHom lam (fun y : ↥(FreeL lam B) => ψ' (f y)) :=
    isLMonoidHom_of_isLHom hlam hlk hcomp0
  have heq : (fun y : ↥(FreeL lam B) => ψ' (f y)) = lift (lam := lam) g :=
    hom_ext (lam := lam) hcomp (isLMonoidHom_lift (lam := lam) g)
      fun b => by show ψ' (f (iota b)) = lift g (iota b); rw [hψ' b, lift_iota]
  exact congrFun heq x

end KRSA

/-- **Examples 4.8(1)**, as the paper states it: `V^κ(C) ≅ F_κ(B)`.

This is the isomorphism that could not be expressed before step 9 of `REFACTOR-PLAN.md`.  `F_κ(B)`
is cut out of `B → F_κ` and so lives in `Type (u+1)`, while `V^κ(C)` lives in `Type u`; the
`universal` field of `IsUniversalKExtension` used to quantify over test objects in the extension's
*own* universe, so `isUniversalKExtension_unique` could only compare two extensions in one universe
and the two sides were incomparable.  With the test universe a parameter, both sides are universal
at both universes — `krsa_ascent` gives a braiding, and a braiding is universal at every test
universe — and `isUniversalKExtension_unique'` compares them.

So the deviation recorded in `README.md` under "The statement corrected in Examples 4.8(1)" is
gone: what remains is the *stronger* pair, this isomorphism and the `B`-indexed universal property
`krsa_ascent_free`. -/
theorem krsa_ascent_iso {R : Type u} [Ring R] {κ : Cardinal.{u}}
    (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ κ) (B : Type u)
    {f : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      ↥(FreeL lam B) → C.carrier}
    (hbrF : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      IsBraidedOver lam κ ↥(FreeL lam B) C.carrier hlk f) :
    letI : Fact lam.IsRegular := ⟨hlam⟩
    letI : Fact (Order.succ κ).IsRegular := ⟨Cardinal.isRegular_succ hκ⟩
    letI := C.instKMonoid hκ
    letI := instKMonoidFreeK κ hκ B
    ∃! e : C.carrier → ↥(FreeK κ B),
      KMonoid.IsKHom κ e ∧ (∀ x, e (f x) = freeIncl hlam hκ hlk x) ∧ Function.Bijective e := by
  letI : Fact lam.IsRegular := ⟨hlam⟩
  letI : Fact (Order.succ κ).IsRegular := ⟨Cardinal.isRegular_succ hκ⟩
  letI := C.instKMonoid hκ
  letI := instKMonoidFreeK κ hκ B
  exact isUniversalKExtension_unique'.{u, u + 1, u, u + 1} hlk
    (hbrF.isUniversalKExtension hlk) (hbrF.isUniversalKExtension hlk)
    (lemma_3_13_free hlam hκ hlk) (lemma_3_13_free hlam hκ hlk)

end KappaMonoid
