/-
`V(R) = add [R]`, **Corollary 4.7** (both directions; the forward one is the only use of the
Bergman–Dicks axiom) and **Examples 4.8(1)**, the ascent of KRSA.
-/
import KappaMonoid.Modules
import KappaMonoid.Core.AddOf
import KappaMonoid.Core.Free
import KappaMonoid.Core.OrderUnit
import KappaMonoid.Modules.Rings.ProjOrderUnit
import KappaMonoid.Braiding.Saturated
import KappaMonoid.ForMathlib.Albrecht

universe u v t

open Cardinal Function Set DirectSum

namespace KappaMonoid

/-! ## `ℵ₀⁻`-small classes are finitely generated

The one module-theoretic input Corollary 4.7(1) needs beyond what `Modules/Projective.lean` has.  Both
directions of the corollary want to move between *finitely generated* projective modules — which is
what Bergman–Dicks realises and what `EveryProjectiveIsSumOfFG` produces — and the `ℵ₀⁻`-small
classes of `V^κ(R)`, which is the base Corollary 4.5(3) braids over.  Example 4.2(2) gives one
direction (finitely generated ⟹ `ℵ₀⁻`-small); this is the converse for a class of `V^κ(R)`.

The argument: `ℵ₀⁻`-smallness applied to the inclusion of the representative into `R^{(κ)}` confines
it to finitely many coordinates, so it lies in the span `N` of the corresponding finitely many
standard generators; the projection of `R^{(κ)}` onto the representative is then already surjective
on `N`, and a quotient of a finitely generated module is finitely generated. -/

section FgSmall

variable (R : Type u) [Ring R] (κ : Cardinal.{u})

open DirectSum

/-- **An `ℵ₀⁻`-small summand of `R^{(κ)}` is finitely generated.** -/
theorem finite_of_isLambdaSmall_aleph0 (P : Summand R κ) (h : IsLambdaSmall R ℵ₀ ↥P.1) :
    Module.Finite R ↥P.1 := by
  classical
  -- `ℵ₀⁻`-smallness of the inclusion confines `P` to finitely many coordinates
  obtain ⟨s, hs, hzero⟩ := h (fun _ : Idx κ => R) (fun _ => inferInstance) (fun _ => inferInstance)
    P.1.subtype
  have hsfin : s.Finite := Cardinal.lt_aleph0_iff_set_finite.mp hs
  -- the span of the corresponding generators is finitely generated and contains `P`
  set N : Submodule R (freeMod R κ) := Submodule.span R (freeGen R κ '' s) with hNdef
  have hNfin : Module.Finite R ↥N := by
    rw [hNdef, show freeGen R κ '' s = ((hsfin.image (freeGen R κ)).toFinset : Set (freeMod R κ)) by
      rw [Set.Finite.coe_toFinset]]
    exact Module.Finite.span_finset R _
  have hPN : ∀ y : ↥P.1, (y : freeMod R κ) ∈ N :=
    fun y => mem_span_freeGen_of_component_eq_zero R κ fun i hi => hzero y i hi
  -- the projection of `R^{(κ)}` onto `P` is already surjective on that span
  set q : freeMod R κ →ₗ[R] ↥P.1 :=
    Submodule.projectionOnto P.1 (Summand.compl R κ P) (Summand.isCompl R κ P) with hqdef
  have hq : ∀ y : ↥P.1, q (y : freeMod R κ) = y := fun y =>
    congrFun (congrArg (fun f : ↥P.1 →ₗ[R] ↥P.1 => (f : ↥P.1 → ↥P.1))
      (Submodule.projectionOnto_comp_subtype (p := P.1) (q := Summand.compl R κ P)
        (h := Summand.isCompl R κ P))) y
  refine Module.Finite.of_surjective (q.comp N.subtype) fun y => ?_
  exact ⟨⟨(y : freeMod R κ), hPN y⟩, hq y⟩

/-- **A finitely generated projective module is a direct summand of a finitely generated free
module.**  If `M` is projective and generated by a family `g : ι → M`, then `R^{(ι)}` splits as
`M ⊕ ker π` along the surjection `π : R^{(ι)} → M` sending the `i`-th generator to `g i`.

This is the argument of `exists_summand_of_projective` with the fixed index type `Idx κ` replaced by
an arbitrary one, which is what makes a *finitely generated* free module available. -/
theorem exists_isCompl_of_projective {M : Type u} [AddCommGroup M] [Module R M]
    (hproj : Module.Projective R M) {ι : Type u} (g : ι → M)
    (hspan : Submodule.span R (Set.range g) = ⊤) :
    ∃ Y Z : Submodule R (⨁ _ : ι, R), IsCompl Y Z ∧ Nonempty (↥Y ≃ₗ[R] M) := by
  classical
  have := hproj
  set π : (⨁ _ : ι, R) →ₗ[R] M :=
    DirectSum.toModule R ι M (fun i => LinearMap.toSpanSingleton R M (g i)) with hπdef
  have hπgen : ∀ i, π (lof R ι (fun _ => R) i 1) = g i := by
    intro i
    rw [hπdef, DirectSum.toModule_lof (M := fun _ : ι => R) R i (1 : R)]
    show (1 : R) • g i = g i
    rw [one_smul]
  have hπsurj : Function.Surjective π := by
    rw [← LinearMap.range_eq_top, eq_top_iff, ← hspan, Submodule.span_le]
    rintro y ⟨i, rfl⟩
    exact ⟨lof R ι (fun _ => R) i 1, hπgen i⟩
  obtain ⟨σ, -, hσinj, hcompl⟩ := ForMathlib.exists_isCompl_range_of_surjective π hπsurj
  exact ⟨LinearMap.range σ, LinearMap.ker π, hcompl, ⟨(LinearEquiv.ofInjective σ hσinj).symm⟩⟩

/-- A finitely generated projective module is the representative of an `ℵ₀⁻`-small class of
`V^κ(R)`: being finitely generated it is generated by at most `κ` elements, hence a summand of
`R^{(κ)}`, and finitely generated modules are `ℵ₀⁻`-small (Example 4.2(2)). -/
theorem exists_class_of_fg_projective (hκ : ℵ₀ ≤ κ) (Q : Type u) [AddCommGroup Q] [Module R Q]
    (hproj : Module.Projective R Q) (hfin : Module.Finite R Q) :
    ∃ a : (projClass R κ hκ).carrier, a ∈ (projClass R κ hκ).lambdaGenPart ℵ₀ ∧
      Nonempty ((projClass R κ hκ).rep a ≃ₗ[R] Q) := by
  have := hproj
  obtain ⟨s, hs⟩ := hfin.fg_top
  have hlt : #(↑s : Set Q) < ℵ₀ := by
    rw [Cardinal.lt_aleph0_iff_set_finite]
    exact s.finite_toSet
  obtain ⟨P, hP⟩ := exists_summand_of_projective R κ Q ↑s (hlt.le.trans hκ) hs
  -- state the isomorphism at the summand rather than at `rep ⟦P⟧`: instance search does not see
  -- through `projClass` (trap 1), so `⟦P⟧` must not appear in an index of a class
  have e : ↥((⟦P⟧ : Quotient (summandSetoid R κ)).out.1) ≃ₗ[R] Q :=
    (Quotient.mk_out (s := summandSetoid R κ) P).some.trans hP.some
  have hgen : IsLambdaGenerated R ℵ₀ ↥((⟦P⟧ : Quotient (summandSetoid R κ)).out.1) :=
    (isLambdaGenerated_aleph0_of_finite hfin).of_equiv e.symm
  exact ⟨⟦P⟧, hgen, ⟨e⟩⟩

end FgSmall

/-! ## `V(R) = add [R]`

The identification behind both directions of Corollary 4.7(1).  The `ℵ₀⁻`-small classes of
`V^κ(R)` are — by `finite_of_isLambdaSmall_aleph0` and Example 4.2(2) — the finitely generated
projective modules, and those are exactly the summands of the finite multiples `n·[R]` of the class
of `R`.  Neither inclusion needs a hypothesis on `R`. -/

section AddUnit

variable (R : Type u) [Ring R] (κ : Cardinal.{u}) (hκ : ℵ₀ ≤ κ)

/-- `#ι` copies of `[R]` are represented by the free module `R^{(ι)}`, for any index type of
cardinality at most `κ`: the form of `rep_cmul_unitClass` that does not go through `Idx`. -/
theorem rep_cmul_mk_unitClass {ι : Type u} (hι : #ι ≤ κ) (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    Nonempty ((projClass R κ hκ).rep
      (KMonoid.cmul (κ := κ) #ι hι (Projective.unitClass R κ hκ k)) ≃ₗ[R] ⨁ _ : ι, R) := by
  let := (projClass R κ hκ).instKMonoid hκ
  have he : Idx (#ι) ≃ ι := (Cardinal.eq.mp (mk_Idx #ι)).some
  exact ⟨(Projective.rep_cmul_unitClass R κ hκ hι k).some.trans (DirectSum.lequivCongrLeft R he)⟩

/-- A class of `V^κ(R)` with finitely generated representative is a summand of a finite multiple of
`[R]`: a finitely generated projective module is a direct summand of some `R^n`. -/
theorem exists_add_eq_cmul_unitClass (k : Idx κ) (a : (projClass R κ hκ).carrier)
    (hfin : Module.Finite R ((projClass R κ hκ).rep a)) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ (c : (projClass R κ hκ).carrier) (n : ℕ),
      a + c = KMonoid.cmul (κ := κ) ((n : ℕ) : Cardinal.{u})
        (le_trans (le_of_lt Cardinal.natCast_lt_aleph0) hκ) (Projective.unitClass R κ hκ k) := by
  let := (projClass R κ hκ).instKMonoid hκ
  classical
  -- a finite generating set of the representative, and the free module on it
  obtain ⟨s, hs⟩ := hfin.fg_top
  have hlt : #(↑s : Set ((projClass R κ hκ).rep a)) < ℵ₀ := by
    rw [Cardinal.lt_aleph0_iff_set_finite]
    exact s.finite_toSet
  obtain ⟨Y, Z, hYZ, hY⟩ := exists_isCompl_of_projective R (summand_projective R κ a.out)
    (fun i : (↑s : Set ((projClass R κ hκ).rep a)) => (i : (projClass R κ hκ).rep a))
    (by rw [Subtype.range_coe]; exact hs)
  -- `R^{(s)}` is `#s` copies of `[R]`, and `Z` is again a class
  have hA := rep_cmul_mk_unitClass R κ hκ (hlt.le.trans hκ) k
  obtain ⟨c, hc⟩ := (projClass R κ hκ).exists_class_of_summand _ hA.some hYZ.symm
  obtain ⟨n, hn⟩ := Cardinal.lt_aleph0.mp hlt
  refine ⟨c, n, ?_⟩
  have hsum : a + c = KMonoid.cmul (κ := κ) #(↑s : Set ((projClass R κ hκ).rep a))
      (hlt.le.trans hκ) (Projective.unitClass R κ hκ k) :=
    (projClass R κ hκ).add_eq_of_relCompl hκ hYZ.disjoint (codisjoint_iff.mp hYZ.codisjoint)
      ⟨hY.some.symm⟩ hc ⟨hA.some.trans Submodule.topEquiv.symm⟩
  rw [hsum]
  exact KMonoid.cmul_congr hn _ _ (Projective.unitClass R κ hκ k)

/-- **`V(R) = add([R])`**: the `ℵ₀⁻`-small part of `V^κ(R)` — the classes of finitely generated
projective modules — is the set of summands of the finite multiples of the class of `R`. -/
theorem addOf_unitClass_eq (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KMonoid.addOf (κ := κ) (Projective.unitClass R κ hκ k)
      = (projClass R κ hκ).lambdaGenPart ℵ₀ := by
  let := (projClass R κ hκ).instKMonoid hκ
  refine Set.Subset.antisymm (fun y hy => ?_) (fun y hy => ?_)
  · -- a summand of `R^n` is finitely generated, hence `ℵ₀⁻`-small
    obtain ⟨z, n, hzn⟩ := hy
    have : Finite (Idx ((n : ℕ) : Cardinal.{u})) := by
      rw [← Cardinal.lt_aleph0_iff_finite, mk_Idx]
      exact Cardinal.natCast_lt_aleph0
    have hiso : Nonempty (((projClass R κ hκ).rep y × (projClass R κ hκ).rep z)
        ≃ₗ[R] ⨁ _ : Idx ((n : ℕ) : Cardinal.{u}), R) :=
      ⟨((projClass R κ hκ).rep_add hκ y z).some.symm.trans
        (((projClass R κ hκ).iso_of_eq hzn).some.trans
          (Projective.rep_cmul_unitClass R κ hκ _ k).some)⟩
    have : Module.Finite R ((projClass R κ hκ).rep y × (projClass R κ hκ).rep z) :=
      Module.Finite.equiv hiso.some.symm
    have : Nonempty ((projClass R κ hκ).rep z) := ⟨0⟩
    have hfiny : Module.Finite R ((projClass R κ hκ).rep y) :=
      Module.Finite.of_surjective (LinearMap.fst R ((projClass R κ hκ).rep y)
        ((projClass R κ hκ).rep z)) Prod.fst_surjective
    obtain ⟨t, ht⟩ := hfiny.fg_top
    exact ⟨(↑t : Set ((projClass R κ hκ).rep y)),
      by rw [Cardinal.lt_aleph0_iff_set_finite]; exact t.finite_toSet, ht⟩
  · -- an `ℵ₀⁻`-small class has a finitely generated representative, hence divides some `n·[R]`
    obtain ⟨t, htlt, htspan⟩ := (projClass R κ hκ).isLambdaGenerated_of_mem hy
    have hfin : Module.Finite R ((projClass R κ hκ).rep y) :=
      ⟨Submodule.fg_def.mpr ⟨t, Cardinal.lt_aleph0_iff_set_finite.mp htlt, htspan⟩⟩
    obtain ⟨c, n, hcn⟩ := exists_add_eq_cmul_unitClass R κ hκ k y hfin
    exact ⟨c, n, hcn⟩

/-! ### `add_{ℵ₀} [R] = V^{ℵ₀}(R)`

The countable analogue of `V(R) = add [R]`: the summands of `R^{(ℵ₀)}` are exactly the countably
generated — that is, `<ℵ₁`-generated — projective modules.  This is the identification behind both
directions of Corollary 4.7(2). -/

/-- The generating-family form of `exists_add_eq_cmul_unitClass`: if the representative of `a` is
spanned by a family indexed by `ι` with `#ι ≤ κ`, then `a` is a summand of `#ι · [R]`. -/
theorem exists_add_eq_cmul_unitClass_family (k : Idx κ) (a : (projClass R κ hκ).carrier)
    {ι : Type u} (hι : #ι ≤ κ) (g : ι → (projClass R κ hκ).rep a)
    (hg : Submodule.span R (Set.range g) = ⊤) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ c : (projClass R κ hκ).carrier,
      a + c = KMonoid.cmul (κ := κ) #ι hι (Projective.unitClass R κ hκ k) := by
  let := (projClass R κ hκ).instKMonoid hκ
  classical
  obtain ⟨Y, Z, hYZ, hY⟩ := exists_isCompl_of_projective R (summand_projective R κ a.out) g hg
  have hA := rep_cmul_mk_unitClass R κ hκ hι k
  obtain ⟨c, hc⟩ := (projClass R κ hκ).exists_class_of_summand _ hA.some hYZ.symm
  exact ⟨c, (projClass R κ hκ).add_eq_of_relCompl hκ hYZ.disjoint
    (codisjoint_iff.mp hYZ.codisjoint) ⟨hY.some.symm⟩ hc
    ⟨hA.some.trans Submodule.topEquiv.symm⟩⟩

/-- **`add_{ℵ₀} [R] = V^{ℵ₀}(R)`**: the summands of `R^{(ℵ₀)}` are exactly the countably generated
projective modules.

Paper proof: a summand of `R^{(ℵ₀)}` is a quotient of `R^{(ℵ₀)}`, hence generated by `ℵ₀` elements;
conversely a projective module with a countable generating family is a summand of the free module
on that family, which — after padding the family out to one indexed by `Idx ℵ₀` — is `R^{(ℵ₀)}`. -/
theorem addOfCard_unitClass_eq (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KMonoid.addOfCard (κ := κ) hκ (Projective.unitClass R κ hκ k)
      = (projClass R κ hκ).lambdaGenPart ℵ₁ := by
  let := (projClass R κ hκ).instKMonoid hκ
  classical
  have hR : IsLambdaGenerated R ℵ₁ R :=
    (isLambdaGenerated_aleph0_of_finite (M := R) inferInstance).mono
      Cardinal.isRegular_aleph_one.aleph0_le
  refine Set.Subset.antisymm (fun y hy => ?_) (fun y hy => ?_)
  · -- a summand of `R^{(ℵ₀)}` is countably generated
    obtain ⟨z, hzn⟩ := hy
    have hiso : Nonempty (((projClass R κ hκ).rep y × (projClass R κ hκ).rep z)
        ≃ₗ[R] ⨁ _ : Idx (ℵ₀ : Cardinal.{u}), R) :=
      ⟨((projClass R κ hκ).rep_add hκ y z).some.symm.trans
        (((projClass R κ hκ).iso_of_eq hzn).some.trans
          (Projective.rep_cmul_unitClass R κ hκ hκ k).some)⟩
    have hfree : IsLambdaGenerated R ℵ₁ (⨁ _ : Idx (ℵ₀ : Cardinal.{u}), R) :=
      isLambdaGenerated_dsum Cardinal.isRegular_aleph_one
        (by rw [mk_Idx]; exact Cardinal.aleph0_lt_aleph_one) _ fun _ => hR
    exact ((hfree.of_equiv (hiso.some.symm)).of_surjective
      (LinearMap.fst R ((projClass R κ hκ).rep y) ((projClass R κ hκ).rep z))
      Prod.fst_surjective : IsLambdaGenerated R ℵ₁ ((projClass R κ hκ).rep y))
  · -- a countably generated class is a summand of `R^{(ℵ₀)}`
    obtain ⟨t, htlt, htspan⟩ := (projClass R κ hκ).isLambdaGenerated_of_mem hy
    have hmk : #(↑t : Set ((projClass R κ hκ).rep y)) ≤ #(Idx (ℵ₀ : Cardinal.{u})) := by
      rw [mk_Idx]
      exact Order.lt_succ_iff.mp (lt_of_lt_of_le htlt
        (Cardinal.aleph_one_le_iff.mpr (Order.lt_succ_iff.mpr le_rfl)))
    obtain ⟨f⟩ := Cardinal.le_def _ _ |>.mp hmk
    set g : Idx (ℵ₀ : Cardinal.{u}) → (projClass R κ hκ).rep y :=
      Function.extend f (fun i => (i : (projClass R κ hκ).rep y)) 0 with hgdef
    have hsub : (↑t : Set ((projClass R κ hκ).rep y)) ⊆ Set.range g := by
      rintro v hv
      exact ⟨f ⟨v, hv⟩, by rw [hgdef, f.injective.extend_apply]⟩
    have hgspan : Submodule.span R (Set.range g) = ⊤ :=
      top_le_iff.mp (htspan ▸ Submodule.span_mono hsub)
    obtain ⟨c, hc⟩ := exists_add_eq_cmul_unitClass_family R κ hκ k y
      (le_of_eq_of_le (mk_Idx (ℵ₀ : Cardinal.{u})) hκ) g hgspan
    exact ⟨c, hc.trans (KMonoid.cmul_congr (mk_Idx (ℵ₀ : Cardinal.{u})) _ hκ
      (Projective.unitClass R κ hκ k))⟩

end AddUnit

/-! ## Corollary 4.6

Each of the six conditions — weakly semihereditary, one-sided semihereditary, exchange,
semiperfect, weakly noetherian commutative, Bézout with one-sided Krull dimension — implies that
every projective module is a direct sum of finitely generated modules, and the corollary then
follows from `corollary_4_5_three`, which is *proved*.

Those six implications are the quoted results (Bergman; Warfield; Mueller; Hinohara;
McGovern–Puninski–Rothmaler), and Corollary 4.6 is exactly `corollary_4_5_three` plus those
citations, so there is no declaration for it: the corollary is recorded among the deliberate
omissions in `Paper/Section4.lean` and in `README.md` instead.  `EveryProjectiveIsSumOfFG` below
names the hypothesis the six results supply — and the one case this development needs, the
*hereditary* one, is not quoted but proved: `Albrecht.exists_directSum_fg` in
`ForMathlib/Albrecht.lean`. -/

/-- The property quoted from the literature for each of the six classes of Corollary 4.6. -/
def EveryProjectiveIsSumOfFG (R : Type u) [Ring R] : Prop :=
  ∀ (P : Type u) (_ : AddCommGroup P) (_ : Module R P), Module.Projective R P →
    ∃ (ι : Type u) (Q : ι → Type u) (_ : ∀ i, AddCommGroup (Q i)) (_ : ∀ i, Module R (Q i)),
      (∀ i, Module.Projective R (Q i)) ∧ (∀ i, Module.Finite R (Q i)) ∧
        Nonempty (P ≃ₗ[R] ⨁ i, Q i)

/-- **Freeness of the countably (non finitely) generated projectives implies
`EveryProjectiveIsSumOfFG`.**  This is `Module.Projective.exists_directSum_fg_of_free` — Kaplansky's
theorem plus the observation that a free module is a direct sum of copies of `R` — phrased for the
classes of `V^{ℵ₀}(R)`, which are exactly the countably generated projectives.

It is what makes Corollary 5.5(2) the paper's statement: the realizability clause there names only
the freeness, and the hypothesis Theorem 5.3's forward direction needs comes from it. -/
theorem everyProjectiveIsSumOfFG_of_free (R : Type u) [Ring R]
    (hfree : ∀ q : V(R).carrier,
        ¬ Module.Finite R (V(R).rep q) →
        ∃ ι : Type u, #ι ≤ ℵ₀ ∧
          Nonempty (V(R).rep q ≃ₗ[R] ⨁ _ : ι, R)) :
    EveryProjectiveIsSumOfFG R := by
  intro P _ _ hP
  have := hP
  refine Module.Projective.exists_directSum_fg_of_free ?_ P
  intro Q _ _ hQproj hQcnt hQfin
  have := hQproj
  obtain ⟨s, hs, hspan⟩ := hQcnt
  -- a countably generated projective is a class of `V^{ℵ₀}(R)`
  obtain ⟨Pw, ⟨eP⟩⟩ := exists_summand_of_projective R ℵ₀ Q s hs hspan
  set q : V(R).carrier := (⟦Pw⟧ : Quotient (summandSetoid R ℵ₀)) with hq
  have e0 : V(R).rep q ≃ₗ[R] Q :=
    (Quotient.mk_out (s := summandSetoid R ℵ₀) Pw).some.trans eP
  obtain ⟨ι, _, ⟨e1⟩⟩ := hfree q fun _ => hQfin (Module.Finite.equiv e0)
  exact ⟨ι, ⟨e0.symm.trans e1⟩⟩

/-- **Generation by finitely generated classes implies `EveryProjectiveIsSumOfFG`.**  If
`V^{ℵ₀}(R)` is generated, as an `ℵ₀`-monoid, by classes of finitely generated modules, then every
countably generated projective module is a countable direct sum of finitely generated projectives,
and Kaplansky's theorem lifts that to every projective module.

This is what makes the third clause of Corollary 5.5(3) — realizability by a ring with two
finitely generated projective generators — imply the others without a separate hypothesis on
decompositions. -/
theorem everyProjectiveIsSumOfFG_of_kGenerates_finite (R : Type u) [Ring R]
    (S : Set V(R).carrier)
    (hfin : ∀ p ∈ S, Module.Finite R (V(R).rep p))
    (hgen : letI := V(R).instKMonoid le_rfl;
      KMonoid.KGenerates ℵ₀ S) :
    EveryProjectiveIsSumOfFG R := by
  classical
  -- adjoin `0`, so that `mem_kclosure_iff` applies
  have h0 : (0 : V(R).carrier) ∈ insert 0 S := Set.mem_insert _ _
  have hgen' : KMonoid.KGenerates (ℵ₀ : Cardinal.{u}) (insert 0 S) :=
    Set.eq_univ_of_univ_subset (hgen ▸ KMonoid.kclosure_mono (Set.subset_insert _ _))
  have hfin' : ∀ p ∈ insert 0 S, Module.Finite R (V(R).rep p) := by
    rintro p (rfl | hp)
    · have : Subsingleton (V(R).rep
        (0 : V(R).carrier)) := by
        refine V(R).subsingleton_rep_of_eq_zero ?_
        exact (V(R).instKMonoid_zero le_rfl).symm
      exact Module.Finite.of_finite
    · exact hfin p hp
  refine Module.Projective.exists_directSum_fg_of_countablyGenerated ?_
  intro Q _ _ hQproj hQcnt
  have := hQproj
  obtain ⟨s, hs, hspan⟩ := hQcnt
  obtain ⟨Pw, ⟨eP⟩⟩ := exists_summand_of_projective R ℵ₀ Q s hs hspan
  set q : V(R).carrier := (⟦Pw⟧ : Quotient (summandSetoid R ℵ₀)) with hq
  have e0 : V(R).rep q ≃ₗ[R] Q :=
    (Quotient.mk_out (s := summandSetoid R ℵ₀) Pw).some.trans eP
  -- write the class of `Q` as a countable sum of finitely generated classes
  obtain ⟨w, hwS, hqw⟩ := (KMonoid.mem_kclosure_iff h0 q).mp (hgen' ▸ Set.mem_univ q)
  have edsum : V(R).rep q ≃ₗ[R]
      ⨁ i : Idx (ℵ₀ : Cardinal.{u}), V(R).rep (w i) := by
    rw [hqw, V(R).instKMonoid_ksum le_rfl w]
    exact (V(R).dsum_iso w).some
  refine ⟨Idx (ℵ₀ : Cardinal.{u}), fun i => V(R).rep (w i),
    fun _ => inferInstance, fun _ => inferInstance, fun i => summand_projective R ℵ₀ (w i).out,
    fun i => hfin' (w i) (hwS i), ⟨e0.symm.trans edsum⟩⟩

/-! ## Corollary 4.7

Part (2) is provable with what is already here.  Part (1) needs the Bergman–Dicks realisation
theorem, `bergmanDicksData` in `KappaMonoid/Axioms.lean`. -/

section Cor47

variable {κ : Cardinal.{u}}

/-- **The engine of Corollary 4.7(2)**: two `κ`-monoids braided over the same `λ⁻`-monoid are
isomorphic.  Both are universal `κ`-extensions of it (Theorem 3.12(2)), and a universal
`κ`-extension is unique up to a unique isomorphism.

This needs no external input, which is what keeps Corollary 4.7(2) axiom-free. -/
theorem isKIso_of_braidedOver_same {lam : Cardinal.{u}} {S : Type u} [LMonoid lam S]
    {H₁ H₂ : Type u} [KMonoid κ H₁] [KMonoid κ H₂] (hlk : lam ≤ Order.succ κ)
    {f : S → H₁} {g : S → H₂}
    (hbr₁ : IsBraidedOver lam κ S H₁ hlk f) (hbr₂ : IsBraidedOver lam κ S H₂ hlk g) :
    ∃ e : H₁ → H₂, KMonoid.IsKHom κ e ∧ (∀ s, e (f s) = g s) ∧ Function.Bijective e :=
  -- the test universe of the universal property is a parameter, so it has to be pinned:
  -- here both extensions live in `Type u` and are compared against test objects there.
  have h₁ : IsUniversalKExtension.{u, u, u, u} lam κ S H₁ hlk f := hbr₁.isUniversalKExtension hlk
  have h₂ : IsUniversalKExtension.{u, u, u, u} lam κ S H₂ hlk g := hbr₂.isUniversalKExtension hlk
  (isUniversalKExtension_unique hlk h₁ h₂).exists

/-- **Corollary 4.7(2)**: for a ring `R` and a `κ`-monoid `H`, if `H` is `ℵ₁⁻`-braided over a
`λ⁻`-monoid `S` and `V^{ℵ₀}(R)` is too — which is Corollary 4.5(2) — then `V^κ(R) ≅ H`.

The `S` of the paper is `add_{ℵ₀} x` for a suitable `x ∈ H`; the statement is given for a general
`S` because that is what the proof uses, and `addOfCard` supplies the paper's instance. -/
theorem corollary_4_7_two {lam : Cardinal.{u}} {S : Type u} [LMonoid lam S] {H : Type u}
    [KMonoid κ H] (R : Type u) [Ring R] (hκ : ℵ₀ ≤ κ) (hlk : lam ≤ Order.succ κ) {f : S → H}
    (hbr : IsBraidedOver lam κ S H hlk f)
    {g : S → (projClass R κ hκ).carrier}
    (hbr' : letI := (projClass R κ hκ).instKMonoid hκ
      IsBraidedOver lam κ S (projClass R κ hκ).carrier hlk g) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ e : H → (projClass R κ hκ).carrier,
      KMonoid.IsKHom κ e ∧ (∀ s, e (f s) = g s) ∧ Function.Bijective e := by
  let := (projClass R κ hκ).instKMonoid hκ
  exact isKIso_of_braidedOver_same hlk hbr hbr'

/-- **Corollary 4.7(1)**, (iii) ⇒ (i): if `V^κ(R) ≅ H` for a ring `R` all of whose projectives
are direct sums of finitely generated modules — in particular a hereditary ring, by Albrecht's
theorem — then `V^κ(R)` is `κ`-generated by `add [R]`, since `V(R) = add [R]`. -/
theorem corollary_4_7_one_backward (R : Type u) [Ring R] (hκ : ℵ₀ ≤ κ)
    (hfg : EveryProjectiveIsSumOfFG R) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ x : (projClass R κ hκ).carrier,
      KMonoid.KGenerates κ (KMonoid.addOf (κ := κ) x) := by
  let := (projClass R κ hκ).instKMonoid hκ
  let := IsLSubset.lmonoid Cardinal.isRegular_aleph0
    ((projClass R κ hκ).lambdaGenPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 (le_succ_of_le hκ))
  obtain ⟨k⟩ := nonempty_Idx hκ
  refine ⟨Projective.unitClass R κ hκ k, ?_⟩
  rw [addOf_unitClass_eq R κ hκ k]
  exact (corollary_4_5_three.{u, u} R κ hκ hfg).1.kGenerates_coe

/-- **Corollary 4.7(1)**, (iii) ⇒ (i) in the form the paper states it: `V^κ(R)` is `ℵ₀⁻`-braided
over `add [R]`.  This is Corollary 4.5(3) — which braids `V^κ(R)` over `V(R)` — moved along the
identification `V(R) = add [R]` of `addOf_unitClass_eq`.

It is this form, rather than the generation statement above, that feeds
`corollary_4_7_one_forward`, so that the two together are the equivalence (i) ⇔ (ii) of the
corollary. -/
theorem corollary_4_7_one_backward_braided (R : Type u) [Ring R] (hκ : ℵ₀ ≤ κ)
    (hfg : EveryProjectiveIsSumOfFG R) (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
      (KMonoid.addOf_isLSubset hκ (Projective.unitClass R κ hκ k))
    IsBraidedOver ℵ₀ κ ↥(KMonoid.addOf (κ := κ) (Projective.unitClass R κ hκ k))
      (projClass R κ hκ).carrier (le_succ_of_le hκ) (fun y => (y : (projClass R κ hκ).carrier)) := by
  let := (projClass R κ hκ).instKMonoid hκ
  exact IsBraidedOver.of_set_eq Cardinal.isRegular_aleph0
    (KMonoid.addOf_isLSubset hκ (Projective.unitClass R κ hκ k))
    ((projClass R κ hκ).lambdaGenPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 (le_succ_of_le hκ))
    (addOf_unitClass_eq R κ hκ k) (corollary_4_5_three.{u, u} R κ hκ hfg).1

/-- **The isomorphism `M ≅ V(R)` packaged by `BergmanDicksData`.**  The four conditions
`iso_zero`, `iso_add`, `inj`, `surj` say that `a ↦ [P a]` is a monoid isomorphism from `M` onto the
finitely generated projective modules; here it is read as an isomorphism of `ℵ₀⁻`-monoids from `M`
onto the `ℵ₀⁻`-small part of `V^κ(bd.R)`, which is the base Corollary 4.5(3) braids over.

Only `isLMonoidHom_aleph0_of_add` is needed for the multiplicativity: for `λ = ℵ₀` a homomorphism of
`λ⁻`-monoids is just an additive map.  Surjectivity is where `finite_of_isLambdaSmall_aleph0` enters:
an `ℵ₀⁻`-small class has a finitely generated representative, so `surj` applies to it. -/
theorem BergmanDicksData.exists_isLMonoidHom_bijective {k : Type u} [Field k] {M : Type u}
    [LMonoid (ℵ₀ : Cardinal.{u}) M] {u : M} (bd : BergmanDicksData k M u) (κ : Cardinal.{u})
    (hκ : ℵ₀ ≤ κ) :
    letI := (projClass bd.R κ hκ).instKMonoid hκ
    letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
      ((projClass bd.R κ hκ).lambdaGenPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 (le_succ_of_le hκ))
    ∃ Φ : M → ↥((projClass bd.R κ hκ).lambdaGenPart ℵ₀),
      IsLMonoidHom ℵ₀ Φ ∧ Function.Injective Φ ∧ Function.Surjective Φ := by
  let := (projClass bd.R κ hκ).instKMonoid hκ
  let := IsLSubset.lmonoid Cardinal.isRegular_aleph0
    ((projClass bd.R κ hκ).lambdaGenPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 (le_succ_of_le hκ))
  classical
  -- each `P a` is a finitely generated projective module, hence an `ℵ₀⁻`-small class
  have hclass : ∀ a : M, ∃ c : (projClass bd.R κ hκ).carrier,
      c ∈ (projClass bd.R κ hκ).lambdaGenPart ℵ₀ ∧
        Nonempty ((projClass bd.R κ hκ).rep c ≃ₗ[bd.R] bd.P a) := fun a =>
    exists_class_of_fg_projective bd.R κ hκ (bd.P a) (bd.proj a) (bd.fin a)
  choose Φ₀ hmem hiso using hclass
  have h0 : Φ₀ 0 = 0 := by
    have := bd.iso_zero
    have : Subsingleton ((projClass bd.R κ hκ).rep (Φ₀ 0)) :=
      Equiv.subsingleton (hiso 0).some.toEquiv
    exact ((projClass bd.R κ hκ).eq_zero_of_subsingleton this).trans
      ((projClass bd.R κ hκ).instKMonoid_zero hκ).symm
  have hadd : ∀ a b : M, Φ₀ (a + b) = Φ₀ a + Φ₀ b := fun a b =>
    (projClass bd.R κ hκ).eq_of_iso ((hiso (a + b)).some.trans ((bd.iso_add a b).some.trans
      ((LinearEquiv.prodCongr (hiso a).some.symm (hiso b).some.symm).trans
        ((projClass bd.R κ hκ).rep_add hκ (Φ₀ a) (Φ₀ b)).some.symm)))
  -- `IsLMonoidHom` is a plain `def`, so the map has to be pinned by an ascription (trap 7)
  have hhom : IsLMonoidHom (ℵ₀ : Cardinal.{u})
      (fun a : M => (⟨Φ₀ a, hmem a⟩ : ↥((projClass bd.R κ hκ).lambdaGenPart ℵ₀))) :=
    isLMonoidHom_aleph0_of_add
      (g := fun a : M => (⟨Φ₀ a, hmem a⟩ : ↥((projClass bd.R κ hκ).lambdaGenPart ℵ₀)))
      (Subtype.ext h0) fun a b => Subtype.ext (hadd a b)
  refine ⟨fun a : M => (⟨Φ₀ a, hmem a⟩ : ↥((projClass bd.R κ hκ).lambdaGenPart ℵ₀)), hhom,
    fun a b hab => ?_, ?_⟩
  · -- injectivity is `inj`
    exact bd.inj a b ⟨(hiso a).some.symm.trans
      (((projClass bd.R κ hκ).iso_of_eq (congrArg Subtype.val hab)).some.trans (hiso b).some)⟩
  · -- surjectivity is `surj`, applied to the representative of an `ℵ₀⁻`-small class
    rintro ⟨c, hc⟩
    have hfin : Module.Finite bd.R ((projClass bd.R κ hκ).rep c) :=
      IsLambdaGenerated.finite_aleph0 ((projClass bd.R κ hκ).isLambdaGenerated_of_mem hc)
    obtain ⟨a, ha⟩ := bd.surj ((projClass bd.R κ hκ).rep c) inferInstance inferInstance
      (summand_projective bd.R κ c.out) hfin
    exact ⟨a, Subtype.ext ((projClass bd.R κ hκ).eq_of_iso ((hiso a).some.trans ha.some.symm))⟩

/-- **Corollary 4.7(1)**, (i) ⇒ (ii), the direction that needs Bergman–Dicks.

Given `x ∈ H` with `H` braided over `add x`, and a field `k`, the monoid `add x` is reduced with
order-unit `x`, so the axiom supplies a hereditary `k`-algebra `R` with `V(R) ≅ add x`.
Albrecht's theorem feeds `corollary_4_5_three`, making `V^κ(R)` braided over `V(R)`;
`isKIso_of_braidedOver_same` then identifies `V^κ(R)` with `H`.

The conclusion is the paper's: a hereditary `k`-algebra realising `H`, with no further condition on
its projectives — Albrecht's theorem recovers `EveryProjectiveIsSumOfFG R` from
`IsLeftHereditary R`. -/
theorem corollary_4_7_one_forward {H : Type u} [KMonoid κ H] (hκ : ℵ₀ ≤ κ)
    (k : Type u) [Field k] (x : H)
    (hbr : letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0 (KMonoid.addOf_isLSubset hκ x)
      IsBraidedOver ℵ₀ κ ↥(KMonoid.addOf (κ := κ) x) H (le_succ_of_le hκ) (fun y => (y : H))) :
    ∃ (R : Type u) (_ : Ring R) (_ : Algebra k R) (_ : IsHereditary R),
      letI := (projClass R κ hκ).instKMonoid hκ
      ∃ e : (projClass R κ hκ).carrier → H, KMonoid.IsKHom κ e ∧ Function.Bijective e := by
  classical
  let := IsLSubset.lmonoid Cardinal.isRegular_aleph0 (KMonoid.addOf_isLSubset hκ x)
  -- Step 1: `add x` is reduced (Lemma 2.8, through the inclusion) with order-unit `x`
  have hcoe : ∀ a b : ↥(KMonoid.addOf (κ := κ) x),
      ((a + b : ↥(KMonoid.addOf (κ := κ) x)) : H) = (a : H) + (b : H) := fun _ _ => rfl
  have hred : ∀ a b : ↥(KMonoid.addOf (κ := κ) x), a + b = 0 → a = 0 := fun a b hab =>
    (LMonoid.isConical_of_injective (fun y : ↥(KMonoid.addOf (κ := κ) x) => (y : H))
      Subtype.val_injective rfl hcoe a b hab).1
  have hxmem : x ∈ KMonoid.addOf (κ := κ) x := KMonoid.self_mem_addOf x
  have : Nonempty ↥(KMonoid.addOf (κ := κ) x) := ⟨⟨x, hxmem⟩⟩
  have hnsmul : ∀ (m : ℕ) (u : ↥(KMonoid.addOf (κ := κ) x)),
      ((m • u : ↥(KMonoid.addOf (κ := κ) x)) : H) = m • (u : H) := by
    intro m u
    induction m with
    | zero => rw [zero_nsmul, zero_nsmul]; rfl
    | succ p hp => rw [succ_nsmul, succ_nsmul, hcoe, hp]
  have hunit : ∀ y : ↥(KMonoid.addOf (κ := κ) x),
      ∃ (z : ↥(KMonoid.addOf (κ := κ) x)) (n : ℕ), y + z = n • (⟨x, hxmem⟩ :
        ↥(KMonoid.addOf (κ := κ) x)) := by
    refine fun y => ?_
    obtain ⟨z, n, hzn⟩ := y.2
    -- the complementary summand is again a summand of a multiple of `x`
    refine ⟨⟨z, ⟨(y : H), n, by rw [add_comm]; exact hzn⟩⟩, n, Subtype.ext ?_⟩
    show (y : H) + z = _
    rw [hnsmul, ← KMonoid.cmul_natCast]
    exact hzn
  -- Step 2: Bergman–Dicks realises `add x` as `V(R)` for a hereditary `k`-algebra `R`
  have bd := bergmanDicksData k ↥(KMonoid.addOf (κ := κ) x) ⟨x, hxmem⟩ hred hunit
  have := bd.hereditary
  refine ⟨bd.R, bd.ring, bd.algebra, bd.hereditary, ?_⟩
  let := (projClass bd.R κ hκ).instKMonoid hκ
  let := IsLSubset.lmonoid Cardinal.isRegular_aleph0
    ((projClass bd.R κ hκ).lambdaGenPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 (le_succ_of_le hκ))
  -- Step 3: Albrecht's theorem for the hereditary `R` is the hypothesis of Corollary 4.5(3)
  obtain ⟨hbr₂, -⟩ := corollary_4_5_three.{u, u} bd.R κ hκ Albrecht.exists_directSum_fg
  -- Step 4: transport that braiding along `add x ≅ V(R)`
  obtain ⟨Φ, hΦhom, hΦinj, hΦsurj⟩ := bd.exists_isLMonoidHom_bijective κ hκ
  have hΦΦ' : ∀ a, Function.invFun Φ (Φ a) = a := Function.leftInverse_invFun hΦinj
  have hΦ'Φ : ∀ c, Φ (Function.invFun Φ c) = c := fun c => Function.invFun_eq (hΦsurj c)
  have hΦ'hom : IsLMonoidHom ℵ₀ (Function.invFun Φ) := hΦhom.inv hΦΦ' hΦ'Φ
  have hbr₁ : IsBraidedOver ℵ₀ κ ↥(KMonoid.addOf (κ := κ) x) (projClass bd.R κ hκ).carrier (le_succ_of_le hκ)
      (fun a => ((Φ a : ↥((projClass bd.R κ hκ).lambdaGenPart ℵ₀)) :
        (projClass bd.R κ hκ).carrier)) :=
    hbr₂.of_base_iso (le_succ_of_le hκ) (g := Φ) (g' := Function.invFun Φ) hΦhom hΦ'hom hΦΦ' hΦ'Φ
  -- Step 5: two `κ`-monoids braided over `add x` are isomorphic
  obtain ⟨e, hehom, -, hebij⟩ := isKIso_of_braidedOver_same (le_succ_of_le hκ) hbr₁ hbr
  exact ⟨e, hehom, hebij⟩

end Cor47

/-! ## Corollary 4.7(1) as an equivalence

For a `κ`-monoid `H` the three statements

* `(i)`   there is an `x ∈ H` over which `H` is braided;
* `(ii)`  for every field `k` there is a hereditary `k`-algebra `R` with `V^κ(R) ≅ H`;
* `(iii)` there is a hereditary ring `R` with `V^κ(R) ≅ H`

are equivalent.  `(i) ⇒ (ii)` is `corollary_4_7_one_forward`, the direction that rests on
Bergman–Dicks realisation; `(ii) ⇒ (iii)` instantiates the field; and `(iii) ⇒ (i)` is Albrecht's
theorem — over a hereditary ring every projective module is a direct sum of finitely generated
ones — followed by `corollary_4_7_one_backward_braided` and transport along the isomorphism. -/

section Cor47Equiv

variable {κ : Cardinal.{u}}

/-- A `κ`-isomorphism carries `add x` onto `add (e x)`. -/
theorem image_addOf_of_kIso {H K : Type u} [KMonoid κ H] [KMonoid κ K] {e : H → K}
    (he : KMonoid.IsKHom κ e) (hbij : Function.Bijective e) (x : H) :
    e '' (KMonoid.addOf (κ := κ) x) = KMonoid.addOf (κ := κ) (e x) := by
  have hnsmul : ∀ (n : ℕ) (a : H), e (n • a) = n • e a := by
    intro n a
    induction n with
    | zero => rw [zero_nsmul, zero_nsmul, he.1]
    | succ m ih => rw [succ_nsmul, succ_nsmul, he.map_add, ih]
  have hmem : ∀ (y z : H) (n : ℕ), (y + z = n • x) ↔ (e y + e z = n • e x) := by
    intro y z n
    constructor
    · intro h; rw [← he.map_add, h, hnsmul]
    · intro h; exact hbij.1 (by rw [he.map_add, h, hnsmul])
  refine Set.eq_of_subset_of_subset ?_ ?_
  · rintro _ ⟨y, ⟨z, n, hzn⟩, rfl⟩
    rw [KMonoid.cmul_natCast] at hzn
    exact ⟨e z, n, by rw [KMonoid.cmul_natCast]; exact (hmem y z n).mp hzn⟩
  · rintro y' ⟨z', n, hzn⟩
    obtain ⟨y, rfl⟩ := hbij.2 y'
    obtain ⟨z, rfl⟩ := hbij.2 z'
    rw [KMonoid.cmul_natCast] at hzn
    exact ⟨y, ⟨z, n, by rw [KMonoid.cmul_natCast]; exact (hmem y z n).mpr hzn⟩, rfl⟩

/-- **Corollary 4.7(1)**, `(iii) ⇒ (i)`: if `H ≅ V^κ(R)` for a ring over which every projective
module is a direct sum of finitely generated ones — a hereditary ring, by Albrecht's theorem —
then `H` is braided over `add x` for `x` the image of the class of `R`. -/
theorem corollary_4_7_one_backward_iso {H : Type u} [KMonoid κ H] (R : Type u) [Ring R]
    (hκ : ℵ₀ ≤ κ) (hfg : EveryProjectiveIsSumOfFG R)
    (e : letI := (projClass R κ hκ).instKMonoid hκ; (projClass R κ hκ).carrier → H)
    (he : letI := (projClass R κ hκ).instKMonoid hκ; KMonoid.IsKHom κ e)
    (hbij : Function.Bijective e) :
    ∃ x : H, letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0 (KMonoid.addOf_isLSubset hκ x)
      IsBraidedOver ℵ₀ κ ↥(KMonoid.addOf (κ := κ) x) H (le_succ_of_le hκ)
        (fun y => (y : H)) := by
  classical
  let := (projClass R κ hκ).instKMonoid hκ
  obtain ⟨k⟩ := nonempty_Idx hκ
  set u : (projClass R κ hκ).carrier := Projective.unitClass R κ hκ k with hu
  refine ⟨e u, ?_⟩
  -- the inverse isomorphism, and the two facts it transports
  set E : (projClass R κ hκ).carrier ≃ H := Equiv.ofBijective e hbij with hE
  have hEinv : Function.RightInverse E.symm e := E.apply_symm_apply
  have hsymhom : KMonoid.IsKHom κ E.symm := he.inv hbij hEinv
  have hsymbij : Function.Bijective E.symm := E.symm.bijective
  have himg : E.symm '' (KMonoid.addOf (κ := κ) (e u)) = KMonoid.addOf (κ := κ) u := by
    rw [image_addOf_of_kIso hsymhom hsymbij (e u)]
    exact congrArg _ (E.symm_apply_apply u)
  -- `V^κ(R)` is braided over `add u`, and `add (e u)` generates `H`
  let := IsLSubset.lmonoid Cardinal.isRegular_aleph0 (KMonoid.addOf_isLSubset hκ u)
  have hbrV : IsBraidedOver ℵ₀ κ ↥(KMonoid.addOf (κ := κ) u) (projClass R κ hκ).carrier
      (le_succ_of_le hκ) (fun y => (y : (projClass R κ hκ).carrier)) :=
    corollary_4_7_one_backward_braided R hκ hfg k
  have hgenU : KMonoid.KGenerates κ (KMonoid.addOf (κ := κ) u) := by
    let := IsLSubset.lmonoid Cardinal.isRegular_aleph0
      ((projClass R κ hκ).lambdaGenPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0
        (le_succ_of_le hκ))
    rw [addOf_unitClass_eq R κ hκ k]
    exact (corollary_4_5_three.{u, u} R κ hκ hfg).1.kGenerates_coe
  have hgenX : KMonoid.KGenerates κ (KMonoid.addOf (κ := κ) (e u)) := by
    have := KMonoid.KGenerates.map he hbij.2 hgenU
    rwa [image_addOf_of_kIso he hbij u] at this
  exact IsBraidedOver.of_kIso_subset Cardinal.isRegular_aleph0
    (KMonoid.addOf_isLSubset hκ u) (KMonoid.addOf_isLSubset hκ (e u)) hbrV hsymhom hsymbij
    (fun a ha => himg ▸ ⟨a, ha, rfl⟩)
    (fun a ha b c habc => KMonoid.addOf_isSaturated (e u) a ha b c habc) hgenX

/-- **Corollary 4.7(1)**: for a `κ`-monoid `H`, being braided over some `add x`, being `V^κ(R)`
for a hereditary `k`-algebra for every field `k`, and being `V^κ(R)` for some right hereditary ring
are equivalent.

As in the paper, (ii) asks for a *hereditary* algebra — left and right, `IsHereditary` — and (iii)
only for a one-sided one.  The modules here are left modules, so the paper's "right hereditary" in
(iii) is `IsLeftHereditary` (every ideal on the side of the modules is projective); passing to the
opposite ring turns one reading into the other. -/
theorem corollary_4_7_one {H : Type u} [KMonoid κ H] (hκ : ℵ₀ ≤ κ) :
    ((∃ x : H, letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0 (KMonoid.addOf_isLSubset hκ x)
      IsBraidedOver ℵ₀ κ ↥(KMonoid.addOf (κ := κ) x) H (le_succ_of_le hκ) (fun y => (y : H)))
      ↔ (∀ (k : Type u) [Field k], ∃ (R : Type u) (_ : Ring R) (_ : Algebra k R)
          (_ : IsHereditary R),
          letI := (projClass R κ hκ).instKMonoid hκ
          ∃ e : (projClass R κ hκ).carrier → H, KMonoid.IsKHom κ e ∧ Function.Bijective e))
    ∧ ((∀ (k : Type u) [Field k], ∃ (R : Type u) (_ : Ring R) (_ : Algebra k R)
          (_ : IsHereditary R),
          letI := (projClass R κ hκ).instKMonoid hκ
          ∃ e : (projClass R κ hκ).carrier → H, KMonoid.IsKHom κ e ∧ Function.Bijective e)
      ↔ (∃ (R : Type u) (_ : Ring R) (_ : IsLeftHereditary R),
          letI := (projClass R κ hκ).instKMonoid hκ
          ∃ e : (projClass R κ hκ).carrier → H, KMonoid.IsKHom κ e ∧ Function.Bijective e)) := by
  classical
  constructor
  · constructor
    · rintro ⟨x, hbr⟩ k _
      exact corollary_4_7_one_forward hκ k x hbr
    · intro h
      obtain ⟨R, hring, -, hher, e, he, hbij⟩ := h (ULift.{u} ℚ)
      exact corollary_4_7_one_backward_iso R hκ Albrecht.exists_directSum_fg e he hbij
  · constructor
    · intro h
      obtain ⟨R, hring, -, hher, e, he, hbij⟩ := h (ULift.{u} ℚ)
      exact ⟨R, hring, hher.toIsLeftHereditary, e, he, hbij⟩
    · rintro ⟨R, hring, hher, e, he, hbij⟩ k _
      obtain ⟨x, hbr⟩ :=
        corollary_4_7_one_backward_iso R hκ Albrecht.exists_directSum_fg e he hbij
      exact corollary_4_7_one_forward hκ k x hbr

/-! ### Corollary 4.7(2)

For a ring `R` and a `κ`-monoid `H` the two statements

* `(i)` there is an `x ∈ H` with `H` `ℵ₁⁻`-braided over `add_{ℵ₀}(x)` and
  `V^{ℵ₀}(R) ≅ add_{ℵ₀}(x)` as `ℵ₁⁻`-monoids;
* `(ii)` `V^κ(R) ≅ H`

are equivalent.  Here `V^{ℵ₀}(R)` is the `ℵ₁⁻`-monoid of countably generated projective modules,
that is, `V^κ(R)_{ℵ₁⁻}`.  No axiom is involved in either direction: `(i) ⇒ (ii)` is Corollary
4.5(2) plus uniqueness of the universal `κ`-extension, and `(ii) ⇒ (i)` is Corollary 4.5(2) plus
the identification `add_{ℵ₀} [R] = V^{ℵ₀}(R)`. -/

/-- A `κ`-isomorphism carries `add_λ x` onto `add_λ (e x)`. -/
theorem image_addOfCard_of_kIso {H K : Type u} [KMonoid κ H] [KMonoid κ K] {lam : Cardinal.{u}}
    (hlk : lam ≤ κ) {e : H → K} (he : KMonoid.IsKHom κ e) (hbij : Function.Bijective e) (x : H) :
    e '' (KMonoid.addOfCard (κ := κ) hlk x) = KMonoid.addOfCard (κ := κ) hlk (e x) := by
  refine Set.eq_of_subset_of_subset ?_ ?_
  · rintro _ ⟨y, ⟨z, hz⟩, rfl⟩
    exact ⟨e z, by rw [← he.map_add, hz, he.map_cmul]⟩
  · rintro y' ⟨z', hz⟩
    obtain ⟨y, rfl⟩ := hbij.2 y'
    obtain ⟨z, rfl⟩ := hbij.2 z'
    exact ⟨y, ⟨z, hbij.1 (by rw [he.map_add, hz, he.map_cmul])⟩, rfl⟩

/-- `add_{ℵ₀} x` is an `ℵ₁⁻`-submonoid of `H`: the `ℵ₁ ≤ ℵ₀⁺` case of
`KMonoid.addOfCard_isLSubset_succ`. -/
theorem addOfCard_aleph0_isLSubset {H : Type u} [KMonoid κ H] (hκ : ℵ₀ ≤ κ) (x : H) :
    IsLSubset ℵ₁ (aleph_one_le_succ κ hκ) (KMonoid.addOfCard (κ := κ) hκ x) :=
  KMonoid.addOfCard_isLSubset_succ le_rfl hκ (aleph_one_le_succ (ℵ₀ : Cardinal.{u}) le_rfl) x

/-- **Corollary 4.7(2)**: for a ring `R` and a `κ`-monoid `H`,

    (∃ x, H is ℵ₁⁻-braided over add_{ℵ₀}(x) and V^{ℵ₀}(R) ≅ add_{ℵ₀}(x))  ↔  V^κ(R) ≅ H.

`V^{ℵ₀}(R)` is `(projClass R κ hκ).lambdaGenPart ℵ₁`, the classes of the countably generated
projective modules, and the isomorphism on the left is one of `ℵ₁⁻`-monoids — which is what an
isomorphism of `ℵ₀`-monoids is, since `ℵ₁ = ℵ₀⁺`. -/
theorem corollary_4_7_two_iff {H : Type u} [KMonoid κ H] (R : Type u) [Ring R] (hκ : ℵ₀ ≤ κ) :
    (letI := (projClass R κ hκ).instKMonoid hκ
     letI := IsLSubset.lmonoid Cardinal.isRegular_aleph_one
       ((projClass R κ hκ).lambdaGenPart_isLSubset hκ ℵ₁ Cardinal.isRegular_aleph_one
         (aleph_one_le_succ κ hκ))
     ∃ x : H,
       letI := IsLSubset.lmonoid Cardinal.isRegular_aleph_one (addOfCard_aleph0_isLSubset hκ x)
       IsBraidedOver ℵ₁ κ ↥(KMonoid.addOfCard (κ := κ) hκ x) H (aleph_one_le_succ κ hκ)
           (fun y => (y : H)) ∧
         ∃ φ : ↥((projClass R κ hκ).lambdaGenPart ℵ₁) → ↥(KMonoid.addOfCard (κ := κ) hκ x),
           IsLMonoidHom ℵ₁ φ ∧ Function.Bijective φ)
    ↔ (letI := (projClass R κ hκ).instKMonoid hκ
       ∃ e : H → (projClass R κ hκ).carrier, KMonoid.IsKHom κ e ∧ Function.Bijective e) := by
  classical
  let := (projClass R κ hκ).instKMonoid hκ
  let hV : IsLSubset ℵ₁ (aleph_one_le_succ κ hκ) ((projClass R κ hκ).lambdaGenPart ℵ₁) :=
    (projClass R κ hκ).lambdaGenPart_isLSubset hκ ℵ₁ Cardinal.isRegular_aleph_one
      (aleph_one_le_succ κ hκ)
  let := IsLSubset.lmonoid Cardinal.isRegular_aleph_one hV
  have hbrV : IsBraidedOver ℵ₁ κ ↥((projClass R κ hκ).lambdaGenPart ℵ₁)
      (projClass R κ hκ).carrier (aleph_one_le_succ κ hκ)
      (fun a => (a : (projClass R κ hκ).carrier)) := (corollary_4_5_two.{u, u} R κ hκ).1
  constructor
  · -- `(i) ⇒ (ii)`: both `H` and `V^κ(R)` are `ℵ₁⁻`-braided over `add_{ℵ₀}(x)`
    rintro ⟨x, hbrH, φ, hφ, hφbij⟩
    let := IsLSubset.lmonoid Cardinal.isRegular_aleph_one (addOfCard_aleph0_isLSubset hκ x)
    set Φ := Equiv.ofBijective φ hφbij with hΦ
    have hψ : IsLMonoidHom ℵ₁ Φ.symm :=
      hφ.inv (fun a => Φ.symm_apply_apply a) (fun a => Φ.apply_symm_apply a)
    have hbrV' : IsBraidedOver ℵ₁ κ ↥(KMonoid.addOfCard (κ := κ) hκ x)
        (projClass R κ hκ).carrier (aleph_one_le_succ κ hκ)
        (fun y => ((Φ.symm y : ↥((projClass R κ hκ).lambdaGenPart ℵ₁)) :
          (projClass R κ hκ).carrier)) :=
      hbrV.of_base_iso (aleph_one_le_succ κ hκ) hψ hφ
        (fun a => Φ.apply_symm_apply a) (fun a => Φ.symm_apply_apply a)
    obtain ⟨e, he, -, hbij⟩ :=
      isKIso_of_braidedOver_same (aleph_one_le_succ κ hκ) hbrH hbrV'
    exact ⟨e, he, hbij⟩
  · -- `(ii) ⇒ (i)`: take `x` to be the preimage of the class of `R`
    rintro ⟨e, he, hbij⟩
    obtain ⟨k⟩ := nonempty_Idx hκ
    set u : (projClass R κ hκ).carrier := Projective.unitClass R κ hκ k with hu
    set E : H ≃ (projClass R κ hκ).carrier := Equiv.ofBijective e hbij with hE
    have hsymhom : KMonoid.IsKHom κ E.symm := he.inv hbij E.apply_symm_apply
    have hsymbij : Function.Bijective E.symm := E.symm.bijective
    set x : H := E.symm u with hx
    let := IsLSubset.lmonoid Cardinal.isRegular_aleph_one (addOfCard_aleph0_isLSubset hκ x)
    -- `V^κ(R)` is `ℵ₁⁻`-braided over `add_{ℵ₀} [R] = V^{ℵ₀}(R)`
    let := IsLSubset.lmonoid Cardinal.isRegular_aleph_one (addOfCard_aleph0_isLSubset hκ u)
    have hbrU : IsBraidedOver ℵ₁ κ ↥(KMonoid.addOfCard (κ := κ) hκ u)
        (projClass R κ hκ).carrier (aleph_one_le_succ κ hκ)
        (fun y => (y : (projClass R κ hκ).carrier)) :=
      IsBraidedOver.of_set_eq Cardinal.isRegular_aleph_one (addOfCard_aleph0_isLSubset hκ u) hV
        (addOfCard_unitClass_eq R κ hκ k) hbrV
    -- transport it to `H` along `e`
    have himg : E.symm '' (KMonoid.addOfCard (κ := κ) hκ u) = KMonoid.addOfCard (κ := κ) hκ x :=
      image_addOfCard_of_kIso hκ hsymhom hsymbij u
    have hgenU : KMonoid.KGenerates κ (KMonoid.addOfCard (κ := κ) hκ u) := hbrU.kGenerates_coe
    have hgenX : KMonoid.KGenerates κ (KMonoid.addOfCard (κ := κ) hκ x) := by
      have := KMonoid.KGenerates.map hsymhom hsymbij.2 hgenU
      rwa [himg] at this
    have hmapsE : ∀ a ∈ KMonoid.addOfCard (κ := κ) hκ x, e a ∈ KMonoid.addOfCard (κ := κ) hκ u := by
      intro a ha
      rw [← himg] at ha
      obtain ⟨b, hb, rfl⟩ := ha
      have hEb : e (E.symm b) = b := E.apply_symm_apply b
      rwa [hEb]
    refine ⟨x, IsBraidedOver.of_kIso_subset Cardinal.isRegular_aleph_one
        (addOfCard_aleph0_isLSubset hκ u) (addOfCard_aleph0_isLSubset hκ x) hbrU he hbij hmapsE
        (fun a ha b c habc => KMonoid.addOfCard_isSaturated hκ x a ha b c habc) hgenX, ?_⟩
    -- and `E.symm` restricts to an isomorphism `V^{ℵ₀}(R) ≅ add_{ℵ₀}(x)`
    have hmaps : ∀ a ∈ (projClass R κ hκ).lambdaGenPart ℵ₁,
        E.symm a ∈ KMonoid.addOfCard (κ := κ) hκ x := by
      intro a ha
      rw [← addOfCard_unitClass_eq R κ hκ k] at ha
      exact himg ▸ ⟨a, ha, rfl⟩
    refine ⟨fun a => ⟨E.symm a, hmaps a a.2⟩,
      hsymhom.restrict_isLMonoidHom Cardinal.isRegular_aleph_one hV
        (addOfCard_aleph0_isLSubset hκ x) hmaps, ?_, ?_⟩
    · exact fun a b hab => Subtype.ext (E.symm.injective (Subtype.ext_iff.mp hab))
    · rintro ⟨b, hb⟩
      rw [← himg] at hb
      obtain ⟨a, ha, hab⟩ := hb
      rw [addOfCard_unitClass_eq R κ hκ k] at ha
      exact ⟨⟨a, ha⟩, Subtype.ext hab⟩

end Cor47Equiv

/-! ## Example 4.8(1): ascent of KRSA

If every module in `C` is a direct sum of `λ⁻`-small ones and `V^{λ⁻}(C_{λ⁻})` is a *free*
`λ⁻`-monoid on `B`, then `V^κ(C)` is the free `κ`-monoid on `B`.  Theorem 4.3 makes `V^κ(C)`
`λ⁻`-braided over `V^{λ⁻}(C_{λ⁻})`, hence its universal `κ`-extension (Theorem 3.12(2)), and
transporting that along the isomorphism of bases says exactly that `V^κ(C)` is the universal
`κ`-extension of `F_{λ⁻}(B)`.

**A universe remark on the statement.**  One would like to conclude `V^κ(C) ≅ F_κ(B)` by combining
this with Lemma 3.14(1) and uniqueness.  That comparison is not available: `F_κ(B)` is cut out of
`B → F_κ` and so lives in `Type (u+1)`, while `V^κ(C)` lives in `Type u`, and
`isUniversalKExtension_unique` — like the universal property itself, which quantifies over test
objects in the *same* universe as the extension — compares two extensions in one universe only.
The universal property below is the universe-correct form of "is the free `κ`-monoid on `B`", and
composing it with the `λ⁻`-level universal property of `F_{λ⁻}(B)` (`Free.exists_unique_lift`,
whose target universe *is* free) recovers the usual `B`-indexed formulation. -/

section KRSA

variable {R : Type u} [Ring R] {κ : Cardinal.{u}}

/-- **Example 4.8(1)**: finite KRSA ascends to infinite KRSA — if `V^κ(C)` is `λ⁻`-braided over a
`λ⁻`-closed subset `S` which is free on `B`, then `V^κ(C)` is the universal `κ`-extension of the
free `λ⁻`-monoid on `B`.

Stated for an arbitrary `λ⁻`-closed `S` because the two readings of the paper's `C_{λ⁻}` both
occur: Theorem 4.3 braids over the `λ⁻`-*small* classes (`lambdaSmallPart`) and Corollary 4.4 over
the `<λ`-*generated* ones (`lambdaGenPart`), and the example is about the latter — see
`krsa_ascent_lambdaGen`. -/
theorem krsa_ascent (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ Order.succ κ) (B : Type u)
    (S : Set C.carrier)
    (hS : letI := C.instKMonoid hκ; IsLSubset lam hlk S)
    (hfree : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      letI := IsLSubset.lmonoid hlam hS
      ∃ e : ↥S → ↥(FreeL lam B), IsLMonoidHom lam e ∧ Function.Bijective e)
    (hbr : letI := C.instKMonoid hκ
      letI := IsLSubset.lmonoid hlam hS
      IsBraidedOver lam κ ↥S C.carrier hlk (fun a => (a : C.carrier))) :
    letI : Fact lam.IsRegular := ⟨hlam⟩
    letI := C.instKMonoid hκ
    ∃ f : ↥(FreeL lam B) → C.carrier,
      IsBraidedOver lam κ ↥(FreeL lam B) C.carrier hlk f := by
  let : Fact lam.IsRegular := ⟨hlam⟩
  let := C.instKMonoid hκ
  let := IsLSubset.lmonoid hlam hS
  classical
  obtain ⟨e, hehom, hebij⟩ := hfree
  -- the inverse of the isomorphism of bases is again a `λ⁻`-homomorphism
  set e' : ↥(FreeL lam B) → ↥S := Function.invFun e with he'def
  have hee' : ∀ a, e' (e a) = a := Function.leftInverse_invFun hebij.injective
  have he'e : ∀ b, e (e' b) = b := fun b => Function.invFun_eq (hebij.surjective b)
  have he'hom : IsLMonoidHom lam e' := hehom.inv hee' he'e
  -- `V^κ(C)` is the universal `κ`-extension of `S`, hence of `F_{λ⁻}(B)`
  refine ⟨fun b => ((e' b : ↥S) : C.carrier), ?_⟩
  exact IsBraidedOver.of_base_iso hlk hbr he'hom hehom he'e hee'

/-- **Example 4.8(1)** as the paper states it: if every module in `C` is a direct sum of at most
`κ` many `<λ`-generated modules and `V^{λ⁻}(C_{λ⁻})` is free on `B`, then `V^κ(C)` is the
universal `κ`-extension of the free `λ⁻`-monoid on `B`.  The braiding comes from Corollary
4.4(2). -/
theorem krsa_ascent_lambdaGen (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ Order.succ κ) (B : Type u)
    (hdec : ∀ a : C.carrier, ∃ (ι : Type u) (Q : ι → Type u) (_ : ∀ i, AddCommGroup (Q i))
      (_ : ∀ i, Module R (Q i)), #ι ≤ κ ∧ (∀ i, IsLambdaGenerated R lam (Q i)) ∧
        Nonempty (C.rep a ≃ₗ[R] ⨁ i, Q i))
    (hfree : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      letI := IsLSubset.lmonoid hlam (C.lambdaGenPart_isLSubset hκ lam hlam hlk)
      ∃ e : ↥(C.lambdaGenPart lam) → ↥(FreeL lam B),
        IsLMonoidHom lam e ∧ Function.Bijective e) :
    letI : Fact lam.IsRegular := ⟨hlam⟩
    letI := C.instKMonoid hκ
    ∃ f : ↥(FreeL lam B) → C.carrier,
      IsBraidedOver lam κ ↥(FreeL lam B) C.carrier hlk f := by
  let : Fact lam.IsRegular := ⟨hlam⟩
  let := C.instKMonoid hκ
  exact krsa_ascent C hκ hlam hlk B (C.lambdaGenPart lam)
    (C.lambdaGenPart_isLSubset hκ lam hlam hlk) hfree
    (corollary_4_4_two.{u, u} C hκ lam hlam hlk hdec).1

/-- The `B`-indexed form: `V^κ(C)` has the universal property of the free `κ`-monoid on `B`.  Every
map from `B` into a `κ`-monoid extends uniquely along the generators `ι(b)`. -/
theorem krsa_ascent_free (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ Order.succ κ) (B : Type u)
    {f : letI : Fact lam.IsRegular := ⟨hlam⟩; ↥(FreeL lam B) → C.carrier}
    (huniv : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      IsUniversalKExtension.{u, u + 1, u, t} lam κ ↥(FreeL lam B) C.carrier hlk f) :
    letI : Fact lam.IsRegular := ⟨hlam⟩
    letI := C.instKMonoid hκ
    ∀ (K : Type t) [KMonoid κ K] (g : B → K),
      ∃! ψ : C.carrier → K, KMonoid.IsKHom κ ψ ∧ ∀ b, ψ (f (iota b)) = g b := by
  let : Fact lam.IsRegular := ⟨hlam⟩
  let := C.instKMonoid hκ
  intro K _ g
  let := KMonoid.toLMonoidOfLE K hlam hlk
  -- lift `g` to the free `λ⁻`-monoid, then extend along the universal property
  have hlift : LMonoid.IsLHom hlk (lift (lam := lam) g) :=
    isLHom_of_isLMonoidHom hlam hlk (isLMonoidHom_lift (lam := lam) g)
  obtain ⟨ψ, ⟨hψhom, hψ⟩, hψu⟩ := huniv.universal K (lift (lam := lam) g) hlift
  refine ⟨ψ, ⟨hψhom, fun b => ?_⟩, fun ψ' ⟨hψ'hom, hψ'⟩ => ?_⟩
  · rw [hψ (iota b), lift_iota]
  refine hψu ψ' ⟨hψ'hom, fun x => ?_⟩
  -- two extensions agreeing on the generators agree, by uniqueness at the `λ⁻` level
  have hcomp0 : LMonoid.IsLHom hlk (fun y : ↥(FreeL lam B) => ψ' (f y)) := by
    refine ⟨by show ψ' (f 0) = 0; rw [huniv.isLHom.1, hψ'hom.1], fun {ι} hι y => ?_⟩
    show ψ' (f (LMonoid.lsumOf hι y)) = _
    rw [huniv.isLHom.2 hι y, hψ'hom.map_sumOf (le_of_lt_of_le_succ hlk hι) (f ∘ y)]
    rfl
  have hcomp : IsLMonoidHom lam (fun y : ↥(FreeL lam B) => ψ' (f y)) :=
    isLMonoidHom_of_isLHom hlam hlk hcomp0
  have heq : (fun y : ↥(FreeL lam B) => ψ' (f y)) = lift (lam := lam) g :=
    hom_ext (lam := lam) hcomp (isLMonoidHom_lift (lam := lam) g)
      fun b => by show ψ' (f (iota b)) = lift g (iota b); rw [hψ' b, lift_iota]
  exact congrFun heq x

end KRSA

/-- **Examples 4.8(1)**, as the paper states it: `V^κ(C) ≅ F_κ(B)`.

The two sides live in different universes: `F_κ(B)` is cut out of `B → F_κ` and so lives in
`Type (u+1)`, while `V^κ(C)` lives in `Type u`.  That is why the test universe of
`IsUniversalKExtension` is a parameter — both sides are then universal at both universes
(`krsa_ascent` gives a braiding, and a braiding is universal at every test universe), and
`isUniversalKExtension_unique'` compares them.  `krsa_ascent_free`, the `B`-indexed universal
property, is the companion statement. -/
theorem krsa_ascent_iso {R : Type u} [Ring R] {κ : Cardinal.{u}}
    (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ Order.succ κ) (B : Type u)
    {f : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      ↥(FreeL lam B) → C.carrier}
    (hbrF : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      IsBraidedOver lam κ ↥(FreeL lam B) C.carrier hlk f) :
    letI : Fact lam.IsRegular := ⟨hlam⟩
    letI : Fact (Order.succ κ).IsRegular := ⟨Cardinal.isRegular_succ hκ⟩
    letI := C.instKMonoid hκ
    letI := instKMonoidFreeK κ hκ B
    ∃! e : C.carrier → ↥(FreeK κ B),
      KMonoid.IsKHom κ e ∧ (∀ x, e (f x) = freeIncl hlam hκ hlk x) ∧ Function.Bijective e := by
  let : Fact lam.IsRegular := ⟨hlam⟩
  let : Fact (Order.succ κ).IsRegular := ⟨Cardinal.isRegular_succ hκ⟩
  let := C.instKMonoid hκ
  let := instKMonoidFreeK κ hκ B
  exact isUniversalKExtension_unique'.{u, u + 1, u, u + 1} hlk
    (hbrF.isUniversalKExtension hlk) (hbrF.isUniversalKExtension hlk)
    (lemma_3_14_free hlam hκ hlk) (lemma_3_14_free hlam hκ hlk)

/-! ## `ℵ₀` copies of a class

Two facts about `ℵ₀ [P]` in `V^{ℵ₀}(R)` used by both Lemma 5.1 and Proposition 5.4: its
representative is the countable direct sum of the representatives, and it is finitely generated
only when the class is zero. -/

section CmulTop

variable (R : Type u) [Ring R]

/-- `ℵ₀` copies of a class are represented by the countable direct sum of its representative. -/
theorem rep_cmul_top_dsum (p : V(R).carrier) :
    Nonempty (V(R).rep (ℵ₀∙p)
      ≃ₗ[R] DirectSum (Idx (ℵ₀ : Cardinal.{u})) (fun _ => V(R).rep p)) := by
  rw [show ℵ₀∙p
      = KMonoid.sumOf (κ := ℵ₀) (le_of_eq (mk_Idx (ℵ₀ : Cardinal.{u})))
        (fun _ : Idx (ℵ₀ : Cardinal.{u}) => p) from
    (KMonoid.cmul_congr (mk_Idx (ℵ₀ : Cardinal.{u})).symm le_rfl
        (le_of_eq (mk_Idx (ℵ₀ : Cardinal.{u}))) p).trans
      (KMonoid.cmul_eq_sumOf (le_of_eq (mk_Idx (ℵ₀ : Cardinal.{u}))) p)]
  exact V(R).rep_sumOf le_rfl (le_of_eq (mk_Idx _))
    (fun _ : Idx (ℵ₀ : Cardinal.{u}) => p)

/-- **`ℵ₀` copies of a nonzero class are never finitely generated.**

If `rep (ℵ₀ p)` were finitely generated it would be `ℵ₀⁻`-small, so in its decomposition as
`⨁_{Idx ℵ₀} rep p` only finitely many components could ever be nonzero; but every component is
hit, so `rep p` is trivial.  This is what makes `ℵ₀ [P₁]` an admissible input to the "every
countably but not finitely generated projective is free" hypothesis. -/
theorem eq_zero_of_finite_cmul_top {p : V(R).carrier}
    (h : letI := V(R).instKMonoid le_rfl
      Module.Finite R (V(R).rep (ℵ₀∙p))) :
    p = 0 := by
  classical
  -- the decomposition of `ℵ₀ p`
  have e : V(R).rep (ℵ₀∙p)
      ≃ₗ[R] DirectSum (Idx (ℵ₀ : Cardinal.{u})) (fun _ => V(R).rep p) := by
    exact (rep_cmul_top_dsum R p).some
  obtain ⟨s, hs, hzero⟩ := isLambdaSmall_aleph0_of_fg R _ h
    (fun _ : Idx (ℵ₀ : Cardinal.{u}) => V(R).rep p)
    (fun _ => inferInstance) (fun _ => inferInstance) (e : _ →ₗ[R] _)
  -- some index escapes the finite support
  have hsfin : s.Finite := Cardinal.lt_aleph0_iff_set_finite.mp hs
  have : Infinite (Idx (ℵ₀ : Cardinal.{u})) :=
    Cardinal.infinite_iff.mpr (le_of_eq (mk_Idx (ℵ₀ : Cardinal.{u})).symm)
  obtain ⟨i₀, hi₀⟩ := hsfin.infinite_compl.nonempty
  -- so that component of `rep p` vanishes identically
  refine V(R).eq_zero_of_subsingleton ⟨fun y z => ?_⟩
  have hval : ∀ w : V(R).rep p, w = 0 := by
    intro w
    have := hzero (e.symm (DirectSum.lof R _
      (fun _ : Idx (ℵ₀ : Cardinal.{u}) => V(R).rep p) i₀ w)) i₀ hi₀
    rwa [show (e : _ →ₗ[R] _) (e.symm (DirectSum.lof R _ _ i₀ w))
        = DirectSum.lof R _ (fun _ : Idx (ℵ₀ : Cardinal.{u}) =>
          V(R).rep p) i₀ w from e.apply_symm_apply _,
      DirectSum.component.lof_self] at this
  rw [hval y, hval z]


end CmulTop

end KappaMonoid
