/-
**Corollary 4.5**: `V^κ(R)` as the direct summands of `R^{(κ)}`, Kaplansky's theorem in its
`κ`-monoid form (the classical statement is `ForMathlib/Kaplansky.lean`).
-/
import KappaMonoid.Modules.SmallPart
import KappaMonoid.Bergman.Realization
import KappaMonoid.ForMathlib.Kaplansky
import KappaMonoid.ForMathlib.ProjectiveSplit

universe u v w t

open Cardinal Function Set DirectSum
open scoped Classical

namespace KappaMonoid

open KMonoid LMonoid

variable (R : Type u) [Ring R]


section Projective

variable (κ : Cardinal.{u})

/-! ### `V^κ(R)` as the direct summands of the free module `R^{(κ)}` -/

/-- The free module `R^{(κ)}`. -/
abbrev freeMod : Type u := ⨁ _ : Idx κ, R

/-- The `k`-th standard generator of `R^{(κ)}`. -/
noncomputable def freeGen (k : Idx κ) : freeMod R κ := lof R (Idx κ) (fun _ => R) k 1

/-- An element of `R^{(κ)}` whose coordinates vanish off `s` lies in the span of the standard
generators indexed by `s`. -/
theorem mem_span_freeGen_of_component_eq_zero {x : freeMod R κ} {s : Set (Idx κ)}
    (h : ∀ i ∉ s, (DirectSum.component R (Idx κ) (fun _ => R) i) x = 0) :
    x ∈ Submodule.span R (freeGen R κ '' s) := by
  classical
  rw [← DFinsupp.sum_single (f := x)]
  refine Submodule.sum_mem _ fun i hi => ?_
  have hmem : i ∈ s := by
    by_contra hns
    exact (DFinsupp.mem_support_iff.mp hi) (h i hns)
  have hsingle : (DFinsupp.single i (x i) : freeMod R κ) = (x i) • freeGen R κ i := by
    show (DirectSum.lof R (Idx κ) (fun _ => R) i) (x i) = _
    rw [freeGen, ← LinearMap.map_smul]
    simp
  rw [hsingle]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, hmem, rfl⟩)

theorem freeMod_span : Submodule.span R (Set.range (freeGen R κ)) = ⊤ := by
  rw [eq_top_iff]
  intro x _
  rw [← DirectSum.sum_support_of x]
  refine Submodule.sum_mem _ fun k _ => ?_
  have hk : (of (fun _ : Idx κ => R) k) (x k) = (x k) • freeGen R κ k := by
    rw [← lof_eq_of R, freeGen, ← LinearMap.map_smul]
    congr 1
    rw [smul_eq_mul, mul_one]
  rw [hk]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨k, rfl⟩)

/-- The direct summands of `R^{(κ)}`; these are exactly the projective modules generated by at
most `κ` elements. -/
def Summand : Type u := {P : Submodule R (freeMod R κ) // ∃ Q, IsCompl P Q}

/-- Two summands are identified when they are isomorphic. -/
instance summandSetoid : Setoid (Summand R κ) where
  r P P' := Nonempty (↥P.1 ≃ₗ[R] ↥P'.1)
  iseqv := ⟨fun _ => ⟨LinearEquiv.refl R _⟩, fun ⟨e⟩ => ⟨e.symm⟩, fun ⟨e⟩ ⟨e'⟩ => ⟨e.trans e'⟩⟩

/-- A chosen complement of a summand. -/
noncomputable def Summand.compl (P : Summand R κ) : Submodule R (freeMod R κ) := P.2.choose

theorem Summand.isCompl (P : Summand R κ) : IsCompl P.1 (Summand.compl R κ P) := P.2.choose_spec

/-- `κ` copies of `R^{(κ)}` form `R^{(κ)}`. -/
noncomputable def freeSelfIso (hκ : ℵ₀ ≤ κ) :
    (⨁ _ : Idx κ, freeMod R κ) ≃ₗ[R] freeMod R κ :=
  (DirectSum.sigmaLcurryEquiv (R := R) (ι := Idx κ) (α := fun _ => Idx κ)
      (δ := fun _ _ => R)).symm.trans
    (DirectSum.lequivCongrLeft R
      ((Equiv.sigmaEquivProd (Idx κ) (Idx κ)).trans (pairEquiv hκ)))

/-- The direct sum of a `κ`-indexed family of summands of `R^{(κ)}`, again as a summand. -/
noncomputable def projDsum (hκ : ℵ₀ ≤ κ) (f : Idx κ → Quotient (summandSetoid R κ)) :
    Summand R κ :=
  ⟨Submodule.map (freeSelfIso R κ hκ).toLinearMap
      (dsSub R (fun _ : Idx κ => freeMod R κ) fun i => (f i).out.1),
    ⟨Submodule.map (freeSelfIso R κ hκ).toLinearMap
        (dsSub R (fun _ : Idx κ => freeMod R κ) fun i => Summand.compl R κ (f i).out),
      isCompl_map_equiv _ (dsSub_isCompl R _ fun i => Summand.isCompl R κ (f i).out)⟩⟩

/-- **Definition 2.4(2)**: `V^κ(R)`, the class of projective right `R`-modules generated by at
most `κ` elements, presented as the direct summands of `R^{(κ)}` up to isomorphism. -/
noncomputable def projClass (hκ : ℵ₀ ≤ κ) : ModuleClass R κ where
  aleph0_le := hκ
  carrier := Quotient (summandSetoid R κ)
  rep := fun a => ↥(a.out.1)
  addCommGroup := fun _ => inferInstance
  module := fun _ => inferInstance
  eq_of_iso := fun {a b} e => by
    rw [← Quotient.out_eq a, ← Quotient.out_eq b]
    exact Quotient.sound ⟨e⟩
  zero := ⟦⟨⊥, ⟨⊤, isCompl_bot_top⟩⟩⟧
  subsingleton_rep_zero := by
    have : Subsingleton ↥(⊥ : Submodule R (freeMod R κ)) := inferInstance
    exact Equiv.subsingleton
      (Quotient.mk_out (s := summandSetoid R κ) ⟨⊥, ⟨⊤, isCompl_bot_top⟩⟩).some.toEquiv
  dsum := fun f => ⟦projDsum R κ hκ f⟧
  dsum_iso := fun f => by
    have e1 : ↥(((⟦projDsum R κ hκ f⟧ : Quotient (summandSetoid R κ)).out).1) ≃ₗ[R]
        ↥((projDsum R κ hκ f).1) :=
      (Quotient.mk_out (s := summandSetoid R κ) (projDsum R κ hκ f)).some
    have e2 : ↥(dsSub R (fun _ : Idx κ => freeMod R κ) fun i => (f i).out.1) ≃ₗ[R]
        ↥((projDsum R κ hκ f).1) :=
      (freeSelfIso R κ hκ).submoduleMap
        (dsSub R (fun _ : Idx κ => freeMod R κ) fun i => (f i).out.1)
    exact ⟨e1.trans (e2.symm.trans
      (dsSubIso R (fun _ : Idx κ => freeMod R κ) fun i => (f i).out.1))⟩

/-- A direct summand of a summand of `R^{(κ)}` is again a summand of `R^{(κ)}`. -/
theorem exists_class_of_summand_projClass (a : Quotient (summandSetoid R κ))
    (N K : Submodule R ↥(a.out.1)) (hNK : IsCompl N K) :
    ∃ b : Quotient (summandSetoid R κ), Nonempty (↥(b.out.1) ≃ₗ[R] ↥N) := by
  obtain ⟨Qa, hQa⟩ := a.out.2
  have hNle : Submodule.map a.out.1.subtype N ≤ a.out.1 := Submodule.map_subtype_le _ N
  have hKle : Submodule.map a.out.1.subtype K ≤ a.out.1 := Submodule.map_subtype_le _ K
  have hsup : Submodule.map a.out.1.subtype N ⊔ Submodule.map a.out.1.subtype K
      = a.out.1 := by
    rw [← Submodule.map_sup, hNK.sup_eq_top, Submodule.map_top, Submodule.range_subtype]
  have hdisj : Disjoint (Submodule.map a.out.1.subtype N)
      (Submodule.map a.out.1.subtype K ⊔ Qa) := by
    rw [Submodule.disjoint_def]
    intro x hxN hx
    obtain ⟨k, hk, q, hq, hkq⟩ := Submodule.mem_sup.mp hx
    have hqP : q ∈ a.out.1 := by
      have hxP : x ∈ a.out.1 := hNle hxN
      have : q = x - k := by rw [← hkq]; abel
      rw [this]
      exact Submodule.sub_mem _ hxP (hKle hk)
    have hq0 : q = 0 := Submodule.disjoint_def.mp hQa.disjoint q hqP hq
    have hxk : x = k := by rw [← hkq, hq0, add_zero]
    -- now `x` lies in both images, so it comes from `N ⊓ K = ⊥`
    obtain ⟨n, hn, hnx⟩ := hxN
    obtain ⟨k', hk', hk'x⟩ := (hxk ▸ hk : x ∈ Submodule.map a.out.1.subtype K)
    have hnk : n = k' := Subtype.ext (by rw [show (n : freeMod R κ) = x from hnx,
      show (k' : freeMod R κ) = x from hk'x])
    have : n ∈ N ⊓ K := ⟨hn, hnk ▸ hk'⟩
    rw [hNK.inf_eq_bot] at this
    rw [← hnx, (Submodule.mem_bot R).mp this]
    rfl
  have hcompl : IsCompl (Submodule.map a.out.1.subtype N)
      (Submodule.map a.out.1.subtype K ⊔ Qa) := by
    refine ⟨hdisj, ?_⟩
    rw [codisjoint_iff, ← sup_assoc, hsup, ← codisjoint_iff]
    exact hQa.codisjoint
  refine ⟨⟦⟨Submodule.map a.out.1.subtype N, ⟨_, hcompl⟩⟩⟧, ?_⟩
  have e1 : ↥(((⟦(⟨Submodule.map a.out.1.subtype N, ⟨_, hcompl⟩⟩ : Summand R κ)⟧ :
        Quotient (summandSetoid R κ)).out).1) ≃ₗ[R] ↥(Submodule.map a.out.1.subtype N) :=
    (Quotient.mk_out (s := summandSetoid R κ)
      ⟨Submodule.map a.out.1.subtype N, ⟨_, hcompl⟩⟩).some
  have e2 : ↥N ≃ₗ[R] ↥(Submodule.map a.out.1.subtype N) :=
    Submodule.equivMapOfInjective a.out.1.subtype a.out.1.injective_subtype N
  exact ⟨e1.trans e2.symm⟩

/-- **`V^κ(R)` is closed under direct summands.**  This is the property §4 needs and the class
of free modules of §2.3 lacks. -/
instance instIsSummandClosed (hκ : ℵ₀ ≤ κ) : (projClass R κ hκ).IsSummandClosed where
  exists_of_isCompl := exists_class_of_summand_projClass R κ

/-- `V(R)` is `V^{ℵ₀}(R)`, the monoid of §4 and §5.  Notation, not a definition: it expands to
`projClass R ℵ₀ le_rfl`, so `V(R).carrier` and `V(R).rep p` are the carrier and the representative
module of a class. -/
scoped notation:max "V(" R ")" => KappaMonoid.projClass R Cardinal.aleph0 le_rfl

/-- A projective module generated by at most `κ` elements is a direct summand of `R^{(κ)}`. -/
theorem exists_summand_of_projective (Q : Type u) [AddCommGroup Q] [Module R Q]
    [Module.Projective R Q] (s : Set Q) (hs : #s ≤ κ) (hspan : Submodule.span R s = ⊤) :
    ∃ P : Summand R κ, Nonempty (↥P.1 ≃ₗ[R] Q) := by
  -- a surjection `R^{(κ)} → Q`
  set g : Idx κ → Q := Function.extend (emb hs)
    (fun x : s => (x : Q)) (0 : Idx κ → Q) with hgdef
  have hgs : ∀ x : s, g (emb hs x) = (x : Q) :=
    fun x => (emb hs).injective.extend_apply _ _ x
  set π : freeMod R κ →ₗ[R] Q :=
    DirectSum.toModule R (Idx κ) Q (fun k => LinearMap.toSpanSingleton R Q (g k)) with hπdef
  have hπgen : ∀ k, π (freeGen R κ k) = g k := by
    intro k
    show π (lof R (Idx κ) (fun _ => R) k 1) = g k
    rw [hπdef, DirectSum.toModule_lof (M := fun _ : Idx κ => R) R k (1 : R)]
    show (1 : R) • g k = g k
    rw [one_smul]
  have hπsurj : Function.Surjective π := by
    rw [← LinearMap.range_eq_top, eq_top_iff, ← hspan, Submodule.span_le]
    intro x hx
    exact ⟨freeGen R κ (emb hs ⟨x, hx⟩), by
      rw [hπgen, hgs ⟨x, hx⟩]⟩
  obtain ⟨σ, -, hσinj, hcompl⟩ := ForMathlib.exists_isCompl_range_of_surjective π hπsurj
  exact ⟨⟨LinearMap.range σ, ⟨LinearMap.ker π, hcompl⟩⟩,
    ⟨(LinearEquiv.ofInjective σ hσinj).symm⟩⟩

/-- Direct summands of `R^{(κ)}` are projective. -/
theorem summand_projective (P : Summand R κ) : Module.Projective R ↥P.1 :=
  Module.Projective.of_split (R := R) (M := freeMod R κ) P.1.subtype
    (Submodule.projectionOnto P.1 (Summand.compl R κ P) (Summand.isCompl R κ P))
    (Submodule.projectionOnto_comp_subtype _)

/-- A summand of `R^{(κ)}` is generated by at most `κ` elements, so if it is written as a
direct sum then at most `κ` of the summands are non-trivial. -/
theorem exists_small_support (hκ : ℵ₀ ≤ κ) (P : Summand R κ) {ι : Type u} (Q : ι → Type u)
    [∀ i, AddCommGroup (Q i)] [∀ i, Module R (Q i)] (e : ↥P.1 ≃ₗ[R] ⨁ i, Q i) :
    ∃ T : Set ι, #T ≤ κ ∧ ∀ i ∉ T, Subsingleton (Q i) := by
  set σ : freeMod R κ →ₗ[R] ⨁ i, Q i :=
    (e : ↥P.1 →ₗ[R] ⨁ i, Q i).comp
      (Submodule.projectionOnto P.1 (Summand.compl R κ P) (Summand.isCompl R κ P)) with hσdef
  have hsurj : Function.Surjective σ :=
    e.surjective.comp (Submodule.projectionOnto_surjective _)
  refine ⟨⋃ k, {i | (σ (freeGen R κ k)) i ≠ 0}, ?_, ?_⟩
  · have hfin : ∀ k, #({i | (σ (freeGen R κ k)) i ≠ 0} : Set ι) ≤ ℵ₀ := by
      intro k
      refine le_of_lt ?_
      rw [Cardinal.lt_aleph0_iff_set_finite]
      refine Set.Finite.subset (σ (freeGen R κ k)).support.finite_toSet fun i hi => ?_
      exact Finset.mem_coe.mpr (DFinsupp.mem_support_iff.mpr hi)
    calc #(⋃ k, {i | (σ (freeGen R κ k)) i ≠ 0} : Set ι)
        ≤ #(Idx κ) * ⨆ k, #({i | (σ (freeGen R κ k)) i ≠ 0} : Set ι) := Cardinal.mk_iUnion_le _
      _ ≤ κ * ℵ₀ := mul_le_mul' (le_of_eq (mk_Idx κ)) (ciSup_le' hfin)
      _ ≤ κ * κ := mul_le_mul' le_rfl hκ
      _ = κ := Cardinal.mul_eq_self hκ
  · -- everything in the direct sum is supported in the union
    intro i hi
    have htop : (⊤ : Submodule R (⨁ i, Q i)) ≤ dsPart R Q (⋃ k, {i | (σ (freeGen R κ k)) i ≠ 0}) := by
      rw [← LinearMap.range_eq_top.mpr hsurj, LinearMap.range_eq_map, ← freeMod_span R κ,
        Submodule.map_span, Submodule.span_le]
      rintro y ⟨x, ⟨k, rfl⟩, rfl⟩ i' hi'
      by_contra hne
      exact hi' (Set.mem_iUnion.mpr ⟨k, hne⟩)
    have hz : ∀ q : Q i, q = 0 := by
      intro q
      have hmem := htop (Submodule.mem_top (x := lof R ι Q i q))
      have := hmem i hi
      rwa [lof_eq_of R, DirectSum.of_eq_same] at this
    exact ⟨fun q q' => by rw [hz q, hz q']⟩


/-! ### `λ⁻`-small and `< λ`-generated agree for summands of `R^{(κ)}`

Corollary 4.5 is stated for `V^{λ⁻}(R)`, the classes *generated by* fewer than `λ` elements; the
braiding of Theorem 4.3 runs over the `λ⁻`-*small* ones (Definition 4.1).  Example 4.2(2) gives one
inclusion, and for a direct summand of a free module the converse holds: smallness confines the
summand to fewer than `λ` coordinates, and the projection onto it turns the corresponding standard
generators into a generating set. -/

/-- **A `λ⁻`-small summand of `R^{(κ)}` is generated by fewer than `λ` elements.** -/
theorem isLambdaGenerated_of_isLambdaSmall {lam : Cardinal.{u}} (P : Summand R κ)
    (h : IsLambdaSmall R lam ↥P.1) : IsLambdaGenerated R lam ↥P.1 := by
  classical
  obtain ⟨s, hs, hzero⟩ := h (fun _ : Idx κ => R) (fun _ => inferInstance) (fun _ => inferInstance)
    P.1.subtype
  set q : freeMod R κ →ₗ[R] ↥P.1 :=
    Submodule.projectionOnto P.1 (Summand.compl R κ P) (Summand.isCompl R κ P) with hqdef
  have hq : ∀ y : ↥P.1, q (y : freeMod R κ) = y := fun y =>
    congrFun (congrArg (fun f : ↥P.1 →ₗ[R] ↥P.1 => (f : ↥P.1 → ↥P.1))
      (Submodule.projectionOnto_comp_subtype (p := P.1) (q := Summand.compl R κ P)
        (h := Summand.isCompl R κ P))) y
  refine ⟨q '' (freeGen R κ '' s), lt_of_le_of_lt Cardinal.mk_image_le
    (lt_of_le_of_lt Cardinal.mk_image_le hs), ?_⟩
  refine eq_top_iff.mpr fun y _ => ?_
  have hyN : (y : freeMod R κ) ∈ Submodule.span R (freeGen R κ '' s) :=
    mem_span_freeGen_of_component_eq_zero R κ fun i hi => hzero y i hi
  have himg := Submodule.apply_mem_span_image_of_mem_span (f := q) hyN
  rwa [hq y] at himg

/-- For `V^κ(R)` the two subclasses coincide: `V^{λ⁻}(R)` is unambiguous. -/
theorem projClass_lambdaSmallPart_eq_lambdaGenPart (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u})
    (hlam : lam.IsRegular) :
    (projClass R κ hκ).lambdaSmallPart lam = (projClass R κ hκ).lambdaGenPart lam := by
  refine Set.eq_of_subset_of_subset (fun a ha => ?_) (fun a ha => ?_)
  · exact isLambdaGenerated_of_isLambdaSmall R κ a.out ha
  · exact IsLambdaGenerated.isLambdaSmall hlam.aleph0_le ha

/-! ### Kaplansky's theorem and Corollary 4.5 -/

/-- If every projective module is a direct sum of projective modules generated by fewer than
`λ` elements, then `V^κ(R)` is generated as a `κ`-monoid by its `λ⁻`-small part. -/
theorem kGenerates_of_decomposition (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u}) (hlam : lam.IsRegular)
    (hdec : ∀ (P : Type u) (_ : AddCommGroup P) (_ : Module R P), Module.Projective R P →
      ∃ (ι : Type u) (Q : ι → Type u) (_ : ∀ i, AddCommGroup (Q i)) (_ : ∀ i, Module R (Q i)),
        (∀ i, Module.Projective R (Q i)) ∧
          (∀ i, ∃ s : Set (Q i), #s < lam ∧ #s ≤ κ ∧ Submodule.span R s = ⊤) ∧
            Nonempty (P ≃ₗ[R] ⨁ i, Q i)) :
    KGenerates κ ((projClass R κ hκ).lambdaSmallPart lam) := by
  apply Set.eq_univ_of_forall
  intro a
  -- Kaplansky's theorem applied to the projective module `rep a`
  have : Module.Projective R ((projClass R κ hκ).rep a) := summand_projective R κ a.out
  obtain ⟨ι, Q, iAG, iMod, hproj, hgen, ⟨e⟩⟩ :=
    hdec ((projClass R κ hκ).rep a) inferInstance inferInstance inferInstance
  -- at most `κ` of the summands are non-trivial
  obtain ⟨T, hT, hTsub⟩ := exists_small_support R κ hκ a.out Q e
  -- each non-trivial summand is a summand of `R^{(κ)}`
  have hQi : ∀ i : T, ∃ P : Summand R κ, Nonempty (↥P.1 ≃ₗ[R] Q i.1) := by
    intro i
    obtain ⟨s, _, hsκ, hsp⟩ := hgen i.1
    have := hproj i.1
    exact exists_summand_of_projective R κ (Q i.1) s hsκ hsp
  choose Pfam hPfam using hQi
  -- the corresponding family of classes, padded by zeros
  set c : T → (projClass R κ hκ).carrier := fun i => ⟦Pfam i⟧ with hcdef
  set b : Idx κ → (projClass R κ hκ).carrier :=
    Function.extend (emb hT) c (0 : Idx κ → (projClass R κ hκ).carrier) with hbdef
  have hbc : ∀ i : T, b (emb hT i) = c i :=
    fun i => (emb hT).injective.extend_apply c (0 : Idx κ → (projClass R κ hκ).carrier) i
  have hb0 : ∀ k, k ∉ Set.range (emb hT) → b k = 0 := fun k hk =>
    Function.extend_apply' c (0 : Idx κ → (projClass R κ hκ).carrier) k
      fun ⟨i, hi⟩ => hk ⟨i, hi⟩
  have hrepc : ∀ i : T, Nonempty ((projClass R κ hκ).rep (c i) ≃ₗ[R] Q i.1) := by
    intro i
    exact ⟨(Quotient.mk_out (s := summandSetoid R κ) (Pfam i)).some.trans (hPfam i).some⟩
  have hbsub : ∀ k, k ∉ Set.range (emb hT) →
      Subsingleton ((projClass R κ hκ).rep (b k)) := by
    intro k hk
    refine (projClass R κ hκ).subsingleton_rep_of_eq_zero ?_
    rw [hb0 k hk]
    exact (projClass R κ hκ).instKMonoid_zero
  -- the two decompositions of `rep a` agree, so `a` is the `κ`-sum of the family
  have hdsum : (projClass R κ hκ).dsum b = a := by
    have e1 : (projClass R κ hκ).rep ((projClass R κ hκ).dsum b) ≃ₗ[R]
        ⨁ k, (projClass R κ hκ).rep (b k) := ((projClass R κ hκ).dsum_iso b).some
    have e2 : (⨁ k, (projClass R κ hκ).rep (b k)) ≃ₗ[R]
        ⨁ i : T, (projClass R κ hκ).rep (b (emb hT i)) :=
      ((projClass R κ hκ).restrict_iso b (emb hT) hbsub).some
    have e3 : (⨁ i : T, (projClass R κ hκ).rep (b (emb hT i))) ≃ₗ[R] ⨁ i : T, Q i.1 :=
      DirectSum.congrLinearEquiv fun i : T =>
        ((projClass R κ hκ).iso_of_eq (hbc i)).some.trans (hrepc i).some
    have e4 : (⨁ i : T, Q i.1) ≃ₗ[R] ⨁ i : ι, Q i := (dsum_restrict_iso R Q T hTsub).some.symm
    exact (projClass R κ hκ).eq_of_iso (e1.trans (e2.trans (e3.trans (e4.trans e.symm))))
  have hmemS : ∀ k, b k ∈ (projClass R κ hκ).lambdaSmallPart lam := by
    intro k
    by_cases hk : k ∈ Set.range (emb hT)
    · obtain ⟨i, rfl⟩ := hk
      obtain ⟨s, hs, _, hsp⟩ := hgen i.1
      have hsmall : IsLambdaSmall R lam (Q i.1) :=
        isLambdaSmall_of_span R hlam.aleph0_le (Q i.1) s hs hsp
      have hfinal : IsLambdaSmall R lam ((projClass R κ hκ).rep (b (emb hT i))) := by
        rw [hbc i]
        exact IsLambdaSmall.of_equiv hsmall (hrepc i).some.symm
      exact hfinal
    · have := hbsub k hk
      exact isLambdaSmall_of_subsingleton hlam.pos ((projClass R κ hκ).rep (b k))
  have hksum : a = ksum (κ := κ) b := by
    rw [(projClass R κ hκ).instKMonoid_ksum b, hdsum]
  rw [hksum]
  exact (KMonoid.isKSubmonoid_kclosure κ _).ksum_mem b fun k => subset_kclosure (hmemS k)

/-- **Kaplansky's Theorem**, `κ`-monoid form: `V^κ(R)` is generated as a `κ`-monoid by the
classes of countably generated projective modules.  Countably generated modules are
`ℵ₁⁻`-small by Example 4.2(2) (note that `ℵ₀⁻`-small would mean finitely generated). -/
theorem kaplansky (hκ : ℵ₀ ≤ κ) :
    KGenerates κ ((projClass R κ hκ).lambdaSmallPart ℵ₁) := by
  refine kGenerates_of_decomposition R κ hκ ℵ₁ Cardinal.isRegular_aleph_one ?_
  intro P _ _ hP
  obtain ⟨ι, Q, iAG, iMod, hproj, hgen, he⟩ :=
    Module.Projective.exists_directSum_countablyGenerated (R := R) P
  refine ⟨ι, Q, iAG, iMod, hproj, fun i => ?_, he⟩
  obtain ⟨s, hs, hsp⟩ := hgen i
  exact ⟨s, lt_of_le_of_lt hs Cardinal.aleph0_lt_aleph_one, hs.trans hκ, hsp⟩


/-- `ℵ₁ ≤ κ⁺` for every infinite `κ`: the instance of the standing bound `λ ≤ κ⁺` that
Corollary 4.5(2) runs at. -/
theorem aleph_one_le_succ (hκ : ℵ₀ ≤ κ) : (ℵ₁ : Cardinal.{u}) ≤ Order.succ κ :=
  Cardinal.aleph_one_le_iff.mpr (Order.lt_succ_iff.mpr hκ)

/-- **Corollary 4.5(1)**
: for every regular `λ` with `ℵ₁ ≤ λ ≤ κ⁺` the `κ`-monoid `V^κ(R)`
is `λ⁻`-braided over, and hence is the universal `κ`-extension of, the `λ⁻`-monoid `V^{λ⁻}(R)`
of projective modules generated by strictly fewer than `λ` elements.

The bound is the paper's `λ ≤ κ⁺`, not `λ ≤ κ`: at `κ = ℵ₀` it is `λ = ℵ₁` that Kaplansky's
theorem supplies, and `λ ≤ κ` would exclude it. -/
theorem corollary_4_5 (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u}) (hlam : lam.IsRegular)
    (h₁ : ℵ₁ ≤ lam) (hlk : lam ≤ Order.succ κ) :
    letI := IsLSubset.lmonoid hlam ((projClass R κ hκ).lambdaGenPart_isLSubset lam hlam hlk)
    IsBraidedOver lam κ ((projClass R κ hκ).lambdaGenPart lam)
        (projClass R κ hκ).carrier hlk (fun a => (a : (projClass R κ hκ).carrier)) ∧
      IsUniversalKExtension.{u, u, u, t} lam κ ((projClass R κ hκ).lambdaGenPart lam)
        (projClass R κ hκ).carrier hlk (fun a => (a : (projClass R κ hκ).carrier)) := by
  have : Fact lam.IsRegular := ⟨hlam⟩
  refine corollary_4_4 ((projClass R κ hκ).lambdaGenSubclass lam hlk)
    (KMonoid.KGenerates.mono ((projClass R κ hκ).lambdaGenPart_mono h₁) ?_)
  rw [← projClass_lambdaSmallPart_eq_lambdaGenPart R κ hκ ℵ₁ Cardinal.isRegular_aleph_one]
  exact kaplansky R κ hκ

/-- **Corollary 4.5(2)**: `V^κ(R)` is the universal `κ`-extension of the `ℵ₀`-monoid
`V^{ℵ₀}(R)` of countably generated projective modules — the case `λ = ℵ₁` of part (1), which
`λ ≤ κ⁺` makes available for *every* infinite `κ`. -/
theorem corollary_4_5_two (hκ : ℵ₀ ≤ κ) :
    IsBraidedOver ℵ₁ κ ((projClass R κ hκ).lambdaGenPart ℵ₁)
        (projClass R κ hκ).carrier (aleph_one_le_succ κ hκ)
        (fun a => (a : (projClass R κ hκ).carrier)) ∧
      IsUniversalKExtension.{u, u, u, t} ℵ₁ κ ((projClass R κ hκ).lambdaGenPart ℵ₁)
        (projClass R κ hκ).carrier (aleph_one_le_succ κ hκ)
        (fun a => (a : (projClass R κ hκ).carrier)) :=
  corollary_4_5 R κ hκ ℵ₁ Cardinal.isRegular_aleph_one le_rfl (aleph_one_le_succ κ hκ)

/-- **Corollary 4.5(3)**: if every projective `R`-module is a direct sum of finitely generated
modules, then `V^κ(R)` is the universal `κ`-extension of the monoid `V(R)` of finitely
generated projective modules (an `ℵ₀⁻`-monoid is an ordinary commutative monoid). -/
theorem corollary_4_5_three (hκ : ℵ₀ ≤ κ)
    (hfg : ∀ (P : Type u) (_ : AddCommGroup P) (_ : Module R P), Module.Projective R P →
      ∃ (ι : Type u) (Q : ι → Type u) (_ : ∀ i, AddCommGroup (Q i)) (_ : ∀ i, Module R (Q i)),
        (∀ i, Module.Projective R (Q i)) ∧ (∀ i, Module.Finite R (Q i)) ∧
          Nonempty (P ≃ₗ[R] ⨁ i, Q i)) :
    IsBraidedOver ℵ₀ κ ((projClass R κ hκ).lambdaGenPart ℵ₀)
        (projClass R κ hκ).carrier (le_succ_of_le hκ) (fun a => (a : (projClass R κ hκ).carrier)) ∧
      IsUniversalKExtension.{u, u, u, t} ℵ₀ κ ((projClass R κ hκ).lambdaGenPart ℵ₀)
        (projClass R κ hκ).carrier (le_succ_of_le hκ)
        (fun a => (a : (projClass R κ hκ).carrier)) := by
  have : Fact (ℵ₀ : Cardinal.{u}).IsRegular := ⟨Cardinal.isRegular_aleph0⟩
  refine corollary_4_4 ((projClass R κ hκ).lambdaGenSubclass ℵ₀ (le_succ_of_le hκ)) ?_
  rw [ModuleClass.coe_lambdaGenSubclass,
    ← projClass_lambdaSmallPart_eq_lambdaGenPart R κ hκ ℵ₀ Cardinal.isRegular_aleph0]
  refine kGenerates_of_decomposition R κ hκ ℵ₀ Cardinal.isRegular_aleph0 ?_
  intro P _ _ hP
  obtain ⟨ι, Q, iAG, iMod, hproj, hfin, he⟩ := hfg P inferInstance inferInstance hP
  refine ⟨ι, Q, iAG, iMod, hproj, fun i => ?_, he⟩
  obtain ⟨s, hs⟩ := (hfin i).fg_top
  have hlt : #(↑s : Set (Q i)) < ℵ₀ := by
    rw [Cardinal.lt_aleph0_iff_set_finite]
    exact s.finite_toSet
  exact ⟨↑s, hlt, hlt.le.trans hκ, hs⟩

end Projective

end KappaMonoid
