/-
**Corollary 4.5**: `V^κ(R)` as the direct summands of `R^{(κ)}`, Kaplansky's theorem in its
`κ`-monoid form (the classical statement is `ForMathlib/Kaplansky.lean`), and the stub for
Corollary 4.6.
-/
import KappaMonoid.Modules.SmallPart
import KappaMonoid.Axioms.Modules
import KappaMonoid.ForMathlib.Kaplansky

universe u v w t

open Cardinal Function Set DirectSum
open scoped Classical

namespace KappaMonoid

open KMonoid LMonoid

variable (R : Type u) [Ring R]


section Projective

variable (κ : Cardinal.{u})

/-! ### `V^κ(R)` as the direct summands of the free module `R^{(κ)}` -/

/-- The free module `R^{(κ)}`. -/
abbrev freeMod : Type u := ⨁ _ : Idx κ, R

/-- The `k`-th standard generator of `R^{(κ)}`. -/
noncomputable def freeGen (k : Idx κ) : freeMod R κ := lof R (Idx κ) (fun _ => R) k 1

theorem freeMod_span : Submodule.span R (Set.range (freeGen R κ)) = ⊤ := by
  rw [eq_top_iff]
  intro x _
  rw [← DirectSum.sum_support_of x]
  refine Submodule.sum_mem _ fun k _ => ?_
  have hk : (of (fun _ : Idx κ => R) k) (x k) = (x k) • freeGen R κ k := by
    rw [← lof_eq_of R, freeGen, ← LinearMap.map_smul]
    congr 1
    rw [smul_eq_mul, mul_one]
  rw [hk]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨k, rfl⟩)

/-- The direct summands of `R^{(κ)}`; these are exactly the projective modules generated by at
most `κ` elements. -/
def Summand : Type u := {P : Submodule R (freeMod R κ) // ∃ Q, IsCompl P Q}

/-- Two summands are identified when they are isomorphic. -/
instance summandSetoid : Setoid (Summand R κ) where
  r P P' := Nonempty (↥P.1 ≃ₗ[R] ↥P'.1)
  iseqv := ⟨fun _ => ⟨LinearEquiv.refl R _⟩, fun ⟨e⟩ => ⟨e.symm⟩, fun ⟨e⟩ ⟨e'⟩ => ⟨e.trans e'⟩⟩

/-- A chosen complement of a summand. -/
noncomputable def Summand.compl (P : Summand R κ) : Submodule R (freeMod R κ) := P.2.choose

theorem Summand.isCompl (P : Summand R κ) : IsCompl P.1 (Summand.compl R κ P) := P.2.choose_spec

/-- `κ` copies of `R^{(κ)}` form `R^{(κ)}`. -/
noncomputable def freeSelfIso (hκ : ℵ₀ ≤ κ) :
    (⨁ _ : Idx κ, freeMod R κ) ≃ₗ[R] freeMod R κ :=
  (DirectSum.sigmaLcurryEquiv (R := R) (ι := Idx κ) (α := fun _ => Idx κ)
      (δ := fun _ _ => R)).symm.trans
    (DirectSum.lequivCongrLeft R
      ((Equiv.sigmaEquivProd (Idx κ) (Idx κ)).trans (pairEquiv hκ)))

/-- The direct sum of a `κ`-indexed family of summands of `R^{(κ)}`, again as a summand. -/
noncomputable def projDsum (hκ : ℵ₀ ≤ κ) (f : Idx κ → Quotient (summandSetoid R κ)) :
    Summand R κ :=
  ⟨Submodule.map (freeSelfIso R κ hκ).toLinearMap
      (dsSub R (fun _ : Idx κ => freeMod R κ) fun i => (f i).out.1),
    ⟨Submodule.map (freeSelfIso R κ hκ).toLinearMap
        (dsSub R (fun _ : Idx κ => freeMod R κ) fun i => Summand.compl R κ (f i).out),
      isCompl_map_equiv _ (dsSub_isCompl R _ fun i => Summand.isCompl R κ (f i).out)⟩⟩

/-- **Definition 2.4(2)**: `V^κ(R)`, the class of projective right `R`-modules generated by at
most `κ` elements, presented as the direct summands of `R^{(κ)}` up to isomorphism. -/
noncomputable def projClass (hκ : ℵ₀ ≤ κ) : ModuleClass R κ where
  carrier := Quotient (summandSetoid R κ)
  rep := fun a => ↥(a.out.1)
  addCommGroup := fun _ => inferInstance
  module := fun _ => inferInstance
  eq_of_iso := fun {a b} e => by
    rw [← Quotient.out_eq a, ← Quotient.out_eq b]
    exact Quotient.sound ⟨e⟩
  zero := ⟦⟨⊥, ⟨⊤, isCompl_bot_top⟩⟩⟧
  subsingleton_rep_zero := by
    have : Subsingleton ↥(⊥ : Submodule R (freeMod R κ)) := inferInstance
    exact Equiv.subsingleton
      (Quotient.mk_out (s := summandSetoid R κ) ⟨⊥, ⟨⊤, isCompl_bot_top⟩⟩).some.toEquiv
  dsum := fun f => ⟦projDsum R κ hκ f⟧
  dsum_iso := fun f => by
    have e1 : ↥(((⟦projDsum R κ hκ f⟧ : Quotient (summandSetoid R κ)).out).1) ≃ₗ[R]
        ↥((projDsum R κ hκ f).1) :=
      (Quotient.mk_out (s := summandSetoid R κ) (projDsum R κ hκ f)).some
    have e2 : ↥(dsSub R (fun _ : Idx κ => freeMod R κ) fun i => (f i).out.1) ≃ₗ[R]
        ↥((projDsum R κ hκ f).1) :=
      (freeSelfIso R κ hκ).submoduleMap
        (dsSub R (fun _ : Idx κ => freeMod R κ) fun i => (f i).out.1)
    exact ⟨e1.trans (e2.symm.trans
      (dsSubIso R (fun _ : Idx κ => freeMod R κ) fun i => (f i).out.1))⟩

/-- A direct summand of a summand of `R^{(κ)}` is again a summand of `R^{(κ)}`. -/
theorem exists_class_of_summand_projClass (a : Quotient (summandSetoid R κ))
    (N K : Submodule R ↥(a.out.1)) (hNK : IsCompl N K) :
    ∃ b : Quotient (summandSetoid R κ), Nonempty (↥(b.out.1) ≃ₗ[R] ↥N) := by
  obtain ⟨Qa, hQa⟩ := a.out.2
  have hNle : Submodule.map a.out.1.subtype N ≤ a.out.1 := Submodule.map_subtype_le _ N
  have hKle : Submodule.map a.out.1.subtype K ≤ a.out.1 := Submodule.map_subtype_le _ K
  have hsup : Submodule.map a.out.1.subtype N ⊔ Submodule.map a.out.1.subtype K
      = a.out.1 := by
    rw [← Submodule.map_sup, hNK.sup_eq_top, Submodule.map_top, Submodule.range_subtype]
  have hdisj : Disjoint (Submodule.map a.out.1.subtype N)
      (Submodule.map a.out.1.subtype K ⊔ Qa) := by
    rw [Submodule.disjoint_def]
    intro x hxN hx
    obtain ⟨k, hk, q, hq, hkq⟩ := Submodule.mem_sup.mp hx
    have hqP : q ∈ a.out.1 := by
      have hxP : x ∈ a.out.1 := hNle hxN
      have : q = x - k := by rw [← hkq]; abel
      rw [this]
      exact Submodule.sub_mem _ hxP (hKle hk)
    have hq0 : q = 0 := Submodule.disjoint_def.mp hQa.disjoint q hqP hq
    have hxk : x = k := by rw [← hkq, hq0, add_zero]
    -- now `x` lies in both images, so it comes from `N ⊓ K = ⊥`
    obtain ⟨n, hn, hnx⟩ := hxN
    obtain ⟨k', hk', hk'x⟩ := (hxk ▸ hk : x ∈ Submodule.map a.out.1.subtype K)
    have hnk : n = k' := Subtype.ext (by rw [show (n : freeMod R κ) = x from hnx,
      show (k' : freeMod R κ) = x from hk'x])
    have : n ∈ N ⊓ K := ⟨hn, hnk ▸ hk'⟩
    rw [hNK.inf_eq_bot] at this
    rw [← hnx, (Submodule.mem_bot R).mp this]
    rfl
  have hcompl : IsCompl (Submodule.map a.out.1.subtype N)
      (Submodule.map a.out.1.subtype K ⊔ Qa) := by
    refine ⟨hdisj, ?_⟩
    rw [codisjoint_iff, ← sup_assoc, hsup, ← codisjoint_iff]
    exact hQa.codisjoint
  refine ⟨⟦⟨Submodule.map a.out.1.subtype N, ⟨_, hcompl⟩⟩⟧, ?_⟩
  have e1 : ↥(((⟦(⟨Submodule.map a.out.1.subtype N, ⟨_, hcompl⟩⟩ : Summand R κ)⟧ :
        Quotient (summandSetoid R κ)).out).1) ≃ₗ[R] ↥(Submodule.map a.out.1.subtype N) :=
    (Quotient.mk_out (s := summandSetoid R κ)
      ⟨Submodule.map a.out.1.subtype N, ⟨_, hcompl⟩⟩).some
  have e2 : ↥N ≃ₗ[R] ↥(Submodule.map a.out.1.subtype N) :=
    Submodule.equivMapOfInjective a.out.1.subtype a.out.1.injective_subtype N
  exact ⟨e1.trans e2.symm⟩

/-- **`V^κ(R)` is closed under direct summands.**  This is the property §4 needs and the class
of free modules of §2.3 lacks. -/
instance instIsSummandClosed (hκ : ℵ₀ ≤ κ) : (projClass R κ hκ).IsSummandClosed where
  exists_of_isCompl := exists_class_of_summand_projClass R κ

/-- `V(R)` is `V^{ℵ₀}(R)`, the monoid of §4 and §5.  Notation, not a definition: it expands to
`projClass R ℵ₀ le_rfl`, so `V(R).carrier` and `V(R).rep p` are the carrier and the representative
module of a class. -/
scoped notation:max "V(" R ")" => KappaMonoid.projClass R Cardinal.aleph0 le_rfl

/-- `V^{ℵ₀}(R)` is an `ℵ₀`-monoid.  This is `ModuleClass.instKMonoid` at the class and the
cardinal that §4 and §5 work with throughout, promoted to an instance so that their statements
need not carry it. -/
noncomputable instance instKMonoidProjClassAleph0 :
    KMonoid (ℵ₀ : Cardinal.{u}) (projClass R (ℵ₀ : Cardinal.{u}) le_rfl).carrier :=
  (projClass R ℵ₀ le_rfl).instKMonoid le_rfl

/-- A projective module generated by at most `κ` elements is a direct summand of `R^{(κ)}`. -/
theorem exists_summand_of_projective (Q : Type u) [AddCommGroup Q] [Module R Q]
    [Module.Projective R Q] (s : Set Q) (hs : #s ≤ κ) (hspan : Submodule.span R s = ⊤) :
    ∃ P : Summand R κ, Nonempty (↥P.1 ≃ₗ[R] Q) := by
  -- a surjection `R^{(κ)} → Q`
  set g : Idx κ → Q := Function.extend (emb hs)
    (fun x : s => (x : Q)) (0 : Idx κ → Q) with hgdef
  have hgs : ∀ x : s, g (emb hs x) = (x : Q) :=
    fun x => (emb hs).injective.extend_apply _ _ x
  set π : freeMod R κ →ₗ[R] Q :=
    DirectSum.toModule R (Idx κ) Q (fun k => LinearMap.toSpanSingleton R Q (g k)) with hπdef
  have hπgen : ∀ k, π (freeGen R κ k) = g k := by
    intro k
    show π (lof R (Idx κ) (fun _ => R) k 1) = g k
    rw [hπdef, DirectSum.toModule_lof (M := fun _ : Idx κ => R) R k (1 : R)]
    show (1 : R) • g k = g k
    rw [one_smul]
  have hπsurj : Function.Surjective π := by
    rw [← LinearMap.range_eq_top, eq_top_iff, ← hspan, Submodule.span_le]
    intro x hx
    exact ⟨freeGen R κ (emb hs ⟨x, hx⟩), by
      rw [hπgen, hgs ⟨x, hx⟩]⟩
  obtain ⟨σ, hσ⟩ := Module.projective_lifting_property π LinearMap.id hπsurj
  have hσπ : ∀ q, π (σ q) = q := fun q => LinearMap.congr_fun hσ q
  have hσinj : Function.Injective σ := by
    intro q q' h
    rw [← hσπ q, ← hσπ q', h]
  refine ⟨⟨LinearMap.range σ, ⟨LinearMap.ker π, ?_⟩⟩,
    ⟨(LinearEquiv.ofInjective σ hσinj).symm⟩⟩
  constructor
  · rw [Submodule.disjoint_def]
    rintro x ⟨q, rfl⟩ hker
    have : q = 0 := by rw [← hσπ q]; exact hker
    rw [this, map_zero]
  · rw [codisjoint_iff, eq_top_iff]
    intro x _
    refine Submodule.mem_sup.mpr ⟨σ (π x), ⟨π x, rfl⟩, x - σ (π x), ?_, by abel⟩
    show π (x - σ (π x)) = 0
    rw [map_sub, hσπ, sub_self]

/-- Direct summands of `R^{(κ)}` are projective. -/
theorem summand_projective (P : Summand R κ) : Module.Projective R ↥P.1 :=
  Module.Projective.of_split (R := R) (M := freeMod R κ) P.1.subtype
    (Submodule.projectionOnto P.1 (Summand.compl R κ P) (Summand.isCompl R κ P))
    (Submodule.projectionOnto_comp_subtype _)

/-- A summand of `R^{(κ)}` is generated by at most `κ` elements, so if it is written as a
direct sum then at most `κ` of the summands are non-trivial. -/
theorem exists_small_support (hκ : ℵ₀ ≤ κ) (P : Summand R κ) {ι : Type u} (Q : ι → Type u)
    [∀ i, AddCommGroup (Q i)] [∀ i, Module R (Q i)] (e : ↥P.1 ≃ₗ[R] ⨁ i, Q i) :
    ∃ T : Set ι, #T ≤ κ ∧ ∀ i ∉ T, Subsingleton (Q i) := by
  set σ : freeMod R κ →ₗ[R] ⨁ i, Q i :=
    (e : ↥P.1 →ₗ[R] ⨁ i, Q i).comp
      (Submodule.projectionOnto P.1 (Summand.compl R κ P) (Summand.isCompl R κ P)) with hσdef
  have hsurj : Function.Surjective σ :=
    e.surjective.comp (Submodule.projectionOnto_surjective _)
  refine ⟨⋃ k, {i | (σ (freeGen R κ k)) i ≠ 0}, ?_, ?_⟩
  · have hfin : ∀ k, #({i | (σ (freeGen R κ k)) i ≠ 0} : Set ι) ≤ ℵ₀ := by
      intro k
      refine le_of_lt ?_
      rw [Cardinal.lt_aleph0_iff_set_finite]
      refine Set.Finite.subset (σ (freeGen R κ k)).support.finite_toSet fun i hi => ?_
      exact Finset.mem_coe.mpr (DFinsupp.mem_support_iff.mpr hi)
    calc #(⋃ k, {i | (σ (freeGen R κ k)) i ≠ 0} : Set ι)
        ≤ #(Idx κ) * ⨆ k, #({i | (σ (freeGen R κ k)) i ≠ 0} : Set ι) := Cardinal.mk_iUnion_le _
      _ ≤ κ * ℵ₀ := mul_le_mul' (le_of_eq (mk_Idx κ)) (ciSup_le' hfin)
      _ ≤ κ * κ := mul_le_mul' le_rfl hκ
      _ = κ := Cardinal.mul_eq_self hκ
  · -- everything in the direct sum is supported in the union
    intro i hi
    have htop : (⊤ : Submodule R (⨁ i, Q i)) ≤ dsPart R Q (⋃ k, {i | (σ (freeGen R κ k)) i ≠ 0}) := by
      rw [← LinearMap.range_eq_top.mpr hsurj, LinearMap.range_eq_map, ← freeMod_span R κ,
        Submodule.map_span, Submodule.span_le]
      rintro y ⟨x, ⟨k, rfl⟩, rfl⟩ i' hi'
      by_contra hne
      exact hi' (Set.mem_iUnion.mpr ⟨k, hne⟩)
    have hz : ∀ q : Q i, q = 0 := by
      intro q
      have hmem := htop (Submodule.mem_top (x := lof R ι Q i q))
      have := hmem i hi
      rwa [lof_eq_of R, DirectSum.of_eq_same] at this
    exact ⟨fun q q' => by rw [hz q, hz q']⟩


/-! ### Kaplansky's theorem and Corollary 4.5 -/

/-- If every projective module is a direct sum of projective modules generated by fewer than
`λ` elements, then `V^κ(R)` is generated as a `κ`-monoid by its `λ⁻`-small part. -/
theorem kGenerates_of_decomposition (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u}) (hlam : lam.IsRegular)
    (hdec : ∀ (P : Type u) (_ : AddCommGroup P) (_ : Module R P), Module.Projective R P →
      ∃ (ι : Type u) (Q : ι → Type u) (_ : ∀ i, AddCommGroup (Q i)) (_ : ∀ i, Module R (Q i)),
        (∀ i, Module.Projective R (Q i)) ∧
          (∀ i, ∃ s : Set (Q i), #s < lam ∧ #s ≤ κ ∧ Submodule.span R s = ⊤) ∧
            Nonempty (P ≃ₗ[R] ⨁ i, Q i)) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KGenerates κ ((projClass R κ hκ).lambdaSmallPart lam) := by
  let := (projClass R κ hκ).instKMonoid hκ
  apply Set.eq_univ_of_forall
  intro a
  -- Kaplansky's theorem applied to the projective module `rep a`
  have : Module.Projective R ((projClass R κ hκ).rep a) := summand_projective R κ a.out
  obtain ⟨ι, Q, iAG, iMod, hproj, hgen, ⟨e⟩⟩ :=
    hdec ((projClass R κ hκ).rep a) inferInstance inferInstance inferInstance
  -- at most `κ` of the summands are non-trivial
  obtain ⟨T, hT, hTsub⟩ := exists_small_support R κ hκ a.out Q e
  -- each non-trivial summand is a summand of `R^{(κ)}`
  have hQi : ∀ i : T, ∃ P : Summand R κ, Nonempty (↥P.1 ≃ₗ[R] Q i.1) := by
    intro i
    obtain ⟨s, _, hsκ, hsp⟩ := hgen i.1
    have := hproj i.1
    exact exists_summand_of_projective R κ (Q i.1) s hsκ hsp
  choose Pfam hPfam using hQi
  -- the corresponding family of classes, padded by zeros
  set c : T → (projClass R κ hκ).carrier := fun i => ⟦Pfam i⟧ with hcdef
  set b : Idx κ → (projClass R κ hκ).carrier :=
    Function.extend (emb hT) c (0 : Idx κ → (projClass R κ hκ).carrier) with hbdef
  have hbc : ∀ i : T, b (emb hT i) = c i :=
    fun i => (emb hT).injective.extend_apply c (0 : Idx κ → (projClass R κ hκ).carrier) i
  have hb0 : ∀ k, k ∉ Set.range (emb hT) → b k = 0 := fun k hk =>
    Function.extend_apply' c (0 : Idx κ → (projClass R κ hκ).carrier) k
      fun ⟨i, hi⟩ => hk ⟨i, hi⟩
  have hrepc : ∀ i : T, Nonempty ((projClass R κ hκ).rep (c i) ≃ₗ[R] Q i.1) := by
    intro i
    exact ⟨(Quotient.mk_out (s := summandSetoid R κ) (Pfam i)).some.trans (hPfam i).some⟩
  have hbsub : ∀ k, k ∉ Set.range (emb hT) →
      Subsingleton ((projClass R κ hκ).rep (b k)) := by
    intro k hk
    refine (projClass R κ hκ).subsingleton_rep_of_eq_zero ?_
    rw [hb0 k hk]
    exact (projClass R κ hκ).instKMonoid_zero hκ
  -- the two decompositions of `rep a` agree, so `a` is the `κ`-sum of the family
  have hdsum : (projClass R κ hκ).dsum b = a := by
    have e1 : (projClass R κ hκ).rep ((projClass R κ hκ).dsum b) ≃ₗ[R]
        ⨁ k, (projClass R κ hκ).rep (b k) := ((projClass R κ hκ).dsum_iso b).some
    have e2 : (⨁ k, (projClass R κ hκ).rep (b k)) ≃ₗ[R]
        ⨁ i : T, (projClass R κ hκ).rep (b (emb hT i)) :=
      ((projClass R κ hκ).restrict_iso b (emb hT) hbsub).some
    have e3 : (⨁ i : T, (projClass R κ hκ).rep (b (emb hT i))) ≃ₗ[R] ⨁ i : T, Q i.1 :=
      DirectSum.congrLinearEquiv fun i : T =>
        ((projClass R κ hκ).iso_of_eq (hbc i)).some.trans (hrepc i).some
    have e4 : (⨁ i : T, Q i.1) ≃ₗ[R] ⨁ i : ι, Q i := (dsum_restrict_iso R Q T hTsub).some.symm
    exact (projClass R κ hκ).eq_of_iso (e1.trans (e2.trans (e3.trans (e4.trans e.symm))))
  have hmemS : ∀ k, b k ∈ (projClass R κ hκ).lambdaSmallPart lam := by
    intro k
    by_cases hk : k ∈ Set.range (emb hT)
    · obtain ⟨i, rfl⟩ := hk
      obtain ⟨s, hs, _, hsp⟩ := hgen i.1
      have hsmall : IsLambdaSmall R lam (Q i.1) :=
        isLambdaSmall_of_span R hlam (Q i.1) s hs hsp
      have hfinal : IsLambdaSmall R lam ((projClass R κ hκ).rep (b (emb hT i))) := by
        rw [hbc i]
        exact IsLambdaSmall.of_equiv hsmall (hrepc i).some.symm
      exact hfinal
    · have := hbsub k hk
      exact isLambdaSmall_of_subsingleton hlam.pos ((projClass R κ hκ).rep (b k))
  have hksum : a = ksum (κ := κ) b := by
    rw [(projClass R κ hκ).instKMonoid_ksum hκ b, hdsum]
  rw [hksum]
  exact (KMonoid.isKSubmonoid_kclosure κ _).ksum_mem b fun k => subset_kclosure (hmemS k)

/-- **Kaplansky's Theorem**, `κ`-monoid form: `V^κ(R)` is generated as a `κ`-monoid by the
classes of countably generated projective modules.  Countably generated modules are
`ℵ₁⁻`-small by Example 4.2(2) (note that `ℵ₀⁻`-small would mean finitely generated). -/
theorem kaplansky (hκ : ℵ₀ ≤ κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KGenerates κ ((projClass R κ hκ).lambdaSmallPart ℵ₁) := by
  refine kGenerates_of_decomposition R κ hκ ℵ₁ Cardinal.isRegular_aleph_one ?_
  intro P _ _ hP
  obtain ⟨ι, Q, iAG, iMod, hproj, hgen, he⟩ :=
    Module.Projective.exists_directSum_countablyGenerated (R := R) P
  refine ⟨ι, Q, iAG, iMod, hproj, fun i => ?_, he⟩
  obtain ⟨s, hs, hsp⟩ := hgen i
  exact ⟨s, lt_of_le_of_lt hs Cardinal.aleph0_lt_aleph_one, hs.trans hκ, hsp⟩


/-- **Corollary 4.5(1)(2)**: for every regular `λ` with `ℵ₁ ≤ λ ≤ κ` the `κ`-monoid `V^κ(R)`
is `λ⁻`-braided over, and hence is the universal `κ`-extension of, the `λ⁻`-monoid
`V^{λ⁻}(R)` of `λ⁻`-small projective modules.  For `λ = ℵ₁` this is `V^{ℵ₀}(R)`, the countably
generated projective modules: `V^{ℵ₀}(R)` determines `V^κ(R)`. -/
theorem corollary_4_5 (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u}) (hlam : lam.IsRegular)
    (h₁ : ℵ₁ ≤ lam) (hlk : lam ≤ κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    letI := IsLSubset.lmonoid hlam ((projClass R κ hκ).lambdaSmallPart_isLSubset hκ lam hlam hlk)
    IsBraidedOver lam κ ((projClass R κ hκ).lambdaSmallPart lam)
        (projClass R κ hκ).carrier hlk (fun a => (a : (projClass R κ hκ).carrier)) ∧
      IsUniversalKExtension.{u, u, u, t} lam κ ((projClass R κ hκ).lambdaSmallPart lam)
        (projClass R κ hκ).carrier hlk (fun a => (a : (projClass R κ hκ).carrier)) := by
  let := (projClass R κ hκ).instKMonoid hκ
  exact corollary_4_4 (projClass R κ hκ) hκ lam hlam hlk _
    ((projClass R κ hκ).lambdaSmallPart_small lam)
    ((projClass R κ hκ).lambdaSmallPart_isLSubset hκ lam hlam hlk)
    ((projClass R κ hκ).lambdaSmallPart_summand hκ lam)
    (KMonoid.KGenerates.mono ((projClass R κ hκ).lambdaSmallPart_mono h₁) (kaplansky R κ hκ))

/-- **Corollary 4.5(3)**: if every projective `R`-module is a direct sum of finitely generated
modules, then `V^κ(R)` is the universal `κ`-extension of the monoid `V(R)` of finitely
generated projective modules (an `ℵ₀⁻`-monoid is an ordinary commutative monoid). -/
theorem corollary_4_5_three (hκ : ℵ₀ ≤ κ)
    (hfg : ∀ (P : Type u) (_ : AddCommGroup P) (_ : Module R P), Module.Projective R P →
      ∃ (ι : Type u) (Q : ι → Type u) (_ : ∀ i, AddCommGroup (Q i)) (_ : ∀ i, Module R (Q i)),
        (∀ i, Module.Projective R (Q i)) ∧ (∀ i, Module.Finite R (Q i)) ∧
          Nonempty (P ≃ₗ[R] ⨁ i, Q i)) :
    letI := (projClass R κ hκ).instKMonoid hκ
    letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
      ((projClass R κ hκ).lambdaSmallPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 hκ)
    IsBraidedOver ℵ₀ κ ((projClass R κ hκ).lambdaSmallPart ℵ₀)
        (projClass R κ hκ).carrier hκ (fun a => (a : (projClass R κ hκ).carrier)) ∧
      IsUniversalKExtension.{u, u, u, t} ℵ₀ κ ((projClass R κ hκ).lambdaSmallPart ℵ₀)
        (projClass R κ hκ).carrier hκ (fun a => (a : (projClass R κ hκ).carrier)) := by
  refine corollary_4_4 (projClass R κ hκ) hκ ℵ₀ Cardinal.isRegular_aleph0 hκ _
    ((projClass R κ hκ).lambdaSmallPart_small ℵ₀)
    ((projClass R κ hκ).lambdaSmallPart_isLSubset hκ ℵ₀ Cardinal.isRegular_aleph0 hκ)
    ((projClass R κ hκ).lambdaSmallPart_summand hκ ℵ₀) ?_
  refine kGenerates_of_decomposition R κ hκ ℵ₀ Cardinal.isRegular_aleph0 ?_
  intro P _ _ hP
  obtain ⟨ι, Q, iAG, iMod, hproj, hfin, he⟩ := hfg P inferInstance inferInstance hP
  refine ⟨ι, Q, iAG, iMod, hproj, fun i => ?_, he⟩
  obtain ⟨s, hs⟩ := (hfin i).fg_top
  have hlt : #(↑s : Set (Q i)) < ℵ₀ := by
    rw [Cardinal.lt_aleph0_iff_set_finite]
    exact s.finite_toSet
  exact ⟨↑s, hlt, hlt.le.trans hκ, hs⟩


/-- **Corollary 4.6**: classes of rings over which the hypothesis of Corollary 4.5(3) holds
(weakly semihereditary, one-sided semihereditary, exchange, semiperfect, weakly noetherian
commutative, Bézout with Krull dimension).  These are quoted results from the literature and
are not formalised here. -/
theorem corollary_4_6 : True := trivial

/-- **Corollary 4.7(1)**: for a `κ`-monoid `H` the following are equivalent: (i) `H` is
braided over `add x` for some `x ∈ H`; (ii) for every field `k` there is a hereditary
`k`-algebra `R` with `V^κ(R) ≅ H`; (iii) there is a right hereditary ring `R` with
`V^κ(R) ≅ H`.

Both parts of the corollary are proved in `Modules/Corollary47.lean`, which needs `add x` and so
comes after this file: `corollary_4_7_one_forward` is (i) ⇒ (ii) — the direction resting on
Bergman–Dicks realisation — `corollary_4_7_one_backward_braided` is (iii) ⇒ (i), and
(ii) ⇒ (iii) is trivial.  Part (2) is `corollary_4_7_two`.  This stub only marks the place. -/
theorem corollary_4_7 : True := trivial

end Projective

end KappaMonoid
