/-
The `λ⁻`-small part of a class of modules, and generation.
-/
import KappaMonoid.Modules.Theorem43

universe u v w

open Cardinal Function Set DirectSum
open scoped Classical

namespace KappaMonoid

open KMonoid LMonoid

variable (R : Type u) [Ring R]

variable {R}

section SmallPart

variable {κ : Cardinal.{u}} (C : ModuleClass R κ)

theorem ModuleClass.mem_lambdaSmallPart {a : C.carrier} {lam : Cardinal.{u}}
    (h : IsLambdaSmall R lam (C.rep a)) : a ∈ C.lambdaSmallPart lam := h

theorem ModuleClass.isLambdaSmall_of_mem {a : C.carrier} {lam : Cardinal.{u}}
    (h : a ∈ C.lambdaSmallPart lam) : IsLambdaSmall R lam (C.rep a) := h

theorem ModuleClass.lambdaSmallPart_isLSubset (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u})
    (hlam : lam.IsRegular) (hlk : lam ≤ Order.succ κ) :
    letI := C.instKMonoid hκ
    IsLSubset lam hlk (C.lambdaSmallPart lam) := by
  let := C.instKMonoid hκ
  constructor
  · -- the zero module is `λ⁻`-small
    have := C.subsingleton_rep_of_eq_zero (C.instKMonoid_zero hκ)
    intro ι N iAG iMod f
    exact isLambdaSmall_of_subsingleton (R := R) hlam.pos (C.rep 0) N iAG iMod f
  · -- a direct sum of `< λ` many `λ⁻`-small modules is `λ⁻`-small
    intro ι h x hx
    have hsmall : IsLambdaSmall R lam (⨁ i, C.rep (x i)) :=
      isLambdaSmall_dsum hlam h (fun i => C.rep (x i)) fun i => C.isLambdaSmall_of_mem (hx i)
    intro ι₂ N iAG iMod f
    exact IsLambdaSmall.of_equiv hsmall
      (C.rep_sumOf hκ (le_of_lt_of_le_succ hlk h) x).some.symm N iAG iMod f

theorem ModuleClass.lambdaSmallPart_summand (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u}) :
    letI := C.instKMonoid hκ
    ∀ a ∈ C.lambdaSmallPart lam, ∀ b : C.carrier, (∃ c, b + c = a) →
      b ∈ C.lambdaSmallPart lam := by
  let := C.instKMonoid hκ
  intro a ha b ⟨c, hc⟩
  have hprod : IsLambdaSmall R lam (C.rep b × C.rep c) :=
    IsLambdaSmall.of_equiv (C.isLambdaSmall_of_mem ha)
      ((C.iso_of_eq hc).some.symm.trans (C.rep_add hκ b c).some)
  intro ι N iAG iMod f
  exact hprod.of_prod_left N iAG iMod f

theorem ModuleClass.lambdaSmallPart_small (lam : Cardinal.{u}) :
    ∀ a ∈ C.lambdaSmallPart lam, IsLambdaSmall R lam (C.rep a) := by
  intro a ha ι N iAG iMod f
  exact ha N iAG iMod f

/-! ### Example 4.2(3): `Cλ⁻` is a class of `λ⁻`-small modules closed under `< λ` sums and summands

These are the three hypotheses Theorem 4.3 asks of the subclass, verified for the subclass of
modules generated by strictly fewer than `λ` elements — which is the `Cλ⁻` of Corollaries 4.4
and 4.5. -/

theorem ModuleClass.isLambdaGenerated_of_mem {a : C.carrier} {lam : Cardinal.{u}}
    (h : a ∈ C.lambdaGenPart lam) : IsLambdaGenerated R lam (C.rep a) := h

/-- **Example 4.2(3)**, first half: a `< λ`-generated module is `λ⁻`-small. -/
theorem ModuleClass.lambdaGenPart_subset_lambdaSmallPart {lam : Cardinal.{u}}
    (hlam : lam.IsRegular) : C.lambdaGenPart lam ⊆ C.lambdaSmallPart lam :=
  fun _ ha => IsLambdaGenerated.isLambdaSmall hlam ha

/-- **Example 4.2(3)**: `Cλ⁻` is closed under direct sums on index sets of cardinality `< λ`. -/
theorem ModuleClass.lambdaGenPart_isLSubset (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u})
    (hlam : lam.IsRegular) (hlk : lam ≤ Order.succ κ) :
    letI := C.instKMonoid hκ
    IsLSubset lam hlk (C.lambdaGenPart lam) := by
  let := C.instKMonoid hκ
  constructor
  · -- the zero module is generated by the empty set
    have hsub := C.subsingleton_rep_of_eq_zero (C.instKMonoid_zero hκ)
    refine ⟨∅, by simpa using hlam.pos, ?_⟩
    refine eq_top_iff.mpr fun m _ => ?_
    rw [Subsingleton.elim m 0]
    exact Submodule.zero_mem _
  · -- a direct sum of `< λ` many `< λ`-generated modules is `< λ`-generated
    intro ι h x hx
    have hgen : IsLambdaGenerated R lam (⨁ i, C.rep (x i)) :=
      isLambdaGenerated_dsum hlam h (fun i => C.rep (x i)) fun i => C.isLambdaGenerated_of_mem (hx i)
    exact hgen.of_equiv (C.rep_sumOf hκ (le_of_lt_of_le_succ hlk h) x).some.symm

/-- **Example 4.2(3)**: `Cλ⁻` is closed under direct summands. -/
theorem ModuleClass.lambdaGenPart_summand (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u}) :
    letI := C.instKMonoid hκ
    ∀ a ∈ C.lambdaGenPart lam, ∀ b : C.carrier, (∃ c, b + c = a) →
      b ∈ C.lambdaGenPart lam := by
  let := C.instKMonoid hκ
  rintro a ha b ⟨c, hc⟩
  have hprod : IsLambdaGenerated R lam (C.rep b × C.rep c) :=
    (C.isLambdaGenerated_of_mem ha).of_equiv
      ((C.iso_of_eq hc).some.symm.trans (C.rep_add hκ b c).some)
  exact hprod.of_surjective (LinearMap.fst R (C.rep b) (C.rep c)) Prod.fst_surjective

/-! ### Corollary 4.4

Theorem 4.3 applied to `Cλ⁻`, the subclass of `< λ`-generated modules.  Part (2) takes the
paper's module-level hypothesis — every member of `C` is a direct sum of *at most `κ` many*
members of `Cλ⁻` — and turns it into generation of `V^κ(C)` by `V^{λ⁻}(Cλ⁻)`. -/

/-- The `i`-th summand of a direct sum is complemented by the others. -/
theorem isCompl_dsPart_singleton {ι : Type u} (Q : ι → Type u) [∀ i, AddCommGroup (Q i)]
    [∀ i, Module R (Q i)] (i : ι) : IsCompl (dsPart R Q {i}) (dsPart R Q {i}ᶜ) := by
  refine ⟨dsPart_disjoint R Q disjoint_compl_right, ?_⟩
  rw [codisjoint_iff, ← dsPart_union, Set.union_compl_self, dsPart_univ]

/-- … and it is `Q i`. -/
noncomputable def dsPartSingletonIso {ι : Type u} (Q : ι → Type u) [∀ i, AddCommGroup (Q i)]
    [∀ i, Module R (Q i)] (i : ι) : ↥(dsPart R Q {i}) ≃ₗ[R] Q i := by
  classical
  letI : Unique ({i} : Set ι) := Set.uniqueSingleton i
  exact (dsPartIso R Q {i}).trans
    (directSumEquivOfSubsingleton R (fun j : ({i} : Set ι) => Q j.1) default
      fun j hj => absurd (Subsingleton.elim j default) hj)

/-- **A direct-sum decomposition of a representative, read at the level of classes.**  If `C` is
closed under direct summands and `C.rep a ≅ ⨁_{i ∈ ι} Q i` with `#ι ≤ κ`, then there are classes
`b i` represented by the `Q i` whose `κ`-sum is `a`. -/
theorem ModuleClass.exists_sumOf_of_dsum_iso (C : ModuleClass R κ) [C.IsSummandClosed]
    (hκ : ℵ₀ ≤ κ) (a : C.carrier) {ι : Type u} (hι : #ι ≤ κ) (Q : ι → Type u)
    [∀ i, AddCommGroup (Q i)] [∀ i, Module R (Q i)] (e : C.rep a ≃ₗ[R] ⨁ i, Q i) :
    letI := C.instKMonoid hκ
    ∃ b : ι → C.carrier, (∀ i, Nonempty (C.rep (b i) ≃ₗ[R] Q i)) ∧ a = sumOf (κ := κ) hι b := by
  classical
  let := C.instKMonoid hκ
  have hb : ∀ i : ι, ∃ b : C.carrier, Nonempty (C.rep b ≃ₗ[R] Q i) := by
    intro i
    obtain ⟨b, hb⟩ := C.exists_class_of_summand a e (isCompl_dsPart_singleton Q i)
    exact ⟨b, ⟨hb.some.trans (dsPartSingletonIso Q i)⟩⟩
  choose b hbiso using hb
  refine ⟨b, hbiso, (C.eq_of_iso ?_).symm⟩
  exact (C.rep_sumOf hκ hι b).some.trans
    ((DFinsupp.mapRange.linearEquiv fun i => (hbiso i).some).trans e.symm)

/-- **The hypothesis of Corollary 4.4(2), at the level of the monoid.**  If every member of `C` is
a direct sum of at most `κ` many `< λ`-generated modules, then `V^{λ⁻}(Cλ⁻)` generates
`V^κ(C)`. -/
theorem ModuleClass.kGenerates_lambdaGenPart (C : ModuleClass R κ) [C.IsSummandClosed]
    (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u})
    (hdec : ∀ a : C.carrier, ∃ (ι : Type u) (Q : ι → Type u) (_ : ∀ i, AddCommGroup (Q i))
      (_ : ∀ i, Module R (Q i)), #ι ≤ κ ∧ (∀ i, IsLambdaGenerated R lam (Q i)) ∧
        Nonempty (C.rep a ≃ₗ[R] ⨁ i, Q i)) :
    letI := C.instKMonoid hκ
    KMonoid.KGenerates κ (C.lambdaGenPart lam) := by
  let := C.instKMonoid hκ
  refine Set.eq_univ_of_forall fun a => ?_
  obtain ⟨ι, Q, iAG, iMod, hι, hgen, ⟨e⟩⟩ := hdec a
  obtain ⟨b, hbiso, hsum⟩ := C.exists_sumOf_of_dsum_iso hκ a hι Q e
  rw [hsum]
  refine (KMonoid.isKSubmonoid_kclosure κ _).sumOf_mem hι b fun i => KMonoid.subset_kclosure ?_
  exact (hgen i).of_equiv (hbiso i).some.symm

/-- **Corollary 4.4(1)**: the `κ`-submonoid of `V^κ(C)` generated by `V^{λ⁻}(Cλ⁻)` is
`λ⁻`-braided over `V^{λ⁻}(Cλ⁻)`, where `Cλ⁻` is the subclass of `< λ`-generated modules. -/
theorem corollary_4_4_one (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    (lam : Cardinal.{u}) (hlam : lam.IsRegular) (hlk : lam ≤ Order.succ κ) :
    letI := C.instKMonoid hκ
    letI := IsLSubset.lmonoid hlam (C.lambdaGenPart_isLSubset hκ lam hlam hlk)
    letI := (KMonoid.isKSubmonoid_kclosure κ (C.lambdaGenPart lam)).kmonoid
    IsBraidedOver lam κ (C.lambdaGenPart lam) (KMonoid.kclosure κ (C.lambdaGenPart lam)) hlk
      (fun a => ⟨(a : C.carrier), KMonoid.subset_kclosure a.2⟩) := by
  let := C.instKMonoid hκ
  let := IsLSubset.lmonoid hlam (C.lambdaGenPart_isLSubset hκ lam hlam hlk)
  let := (KMonoid.isKSubmonoid_kclosure κ (C.lambdaGenPart lam)).kmonoid
  exact theorem_4_3 C hκ lam hlam hlk (C.lambdaGenPart lam)
    (fun a ha => IsLambdaGenerated.isLambdaSmall hlam ha)
    (C.lambdaGenPart_isLSubset hκ lam hlam hlk) (C.lambdaGenPart_summand hκ lam)

/-- **Corollary 4.4(2)**: if every module in `C` is a direct sum of at most `κ` many modules
generated by strictly fewer than `λ` elements, then all of `V^κ(C)` is `λ⁻`-braided over
`V^{λ⁻}(Cλ⁻)`, hence is its universal `κ`-extension. -/
theorem corollary_4_4_two (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    (lam : Cardinal.{u}) (hlam : lam.IsRegular) (hlk : lam ≤ Order.succ κ)
    (hdec : ∀ a : C.carrier, ∃ (ι : Type u) (Q : ι → Type u) (_ : ∀ i, AddCommGroup (Q i))
      (_ : ∀ i, Module R (Q i)), #ι ≤ κ ∧ (∀ i, IsLambdaGenerated R lam (Q i)) ∧
        Nonempty (C.rep a ≃ₗ[R] ⨁ i, Q i)) :
    letI := C.instKMonoid hκ
    letI := IsLSubset.lmonoid hlam (C.lambdaGenPart_isLSubset hκ lam hlam hlk)
    IsBraidedOver lam κ (C.lambdaGenPart lam) C.carrier hlk (fun a => (a : C.carrier)) ∧
      IsUniversalKExtension.{u, u, u, t} lam κ (C.lambdaGenPart lam) C.carrier hlk
        (fun a => (a : C.carrier)) := by
  let := C.instKMonoid hκ
  let := IsLSubset.lmonoid hlam (C.lambdaGenPart_isLSubset hκ lam hlam hlk)
  exact corollary_4_4 C hκ lam hlam hlk (C.lambdaGenPart lam)
    (fun a ha => IsLambdaGenerated.isLambdaSmall hlam ha)
    (C.lambdaGenPart_isLSubset hκ lam hlam hlk) (C.lambdaGenPart_summand hκ lam)
    (C.kGenerates_lambdaGenPart hκ lam hdec)

theorem ModuleClass.lambdaGenPart_mono {lam lam' : Cardinal.{u}} (h : lam ≤ lam') :
    C.lambdaGenPart lam ⊆ C.lambdaGenPart lam' := by
  rintro a ⟨s, hs, hspan⟩
  exact ⟨s, lt_of_lt_of_le hs h, hspan⟩

theorem ModuleClass.lambdaSmallPart_mono
 {lam lam' : Cardinal.{u}} (h : lam ≤ lam') :
    C.lambdaSmallPart lam ⊆ C.lambdaSmallPart lam' := by
  intro a ha ι N iAG iMod f
  exact IsLambdaSmall.mono h (C.isLambdaSmall_of_mem ha) N iAG iMod f

end SmallPart

section Gen

variable {κ : Cardinal.{u}} {H : Type v} [KMonoid κ H]

theorem KMonoid.KGenerates.mono {S S' : Set H} (h : S ⊆ S') (hgen : KGenerates κ S) :
    KGenerates κ S' :=
  Set.eq_univ_of_univ_subset (hgen ▸ KMonoid.kclosure_mono h)

end Gen

/-! ## Projective modules: Corollaries 4.5–4.7 -/

end KappaMonoid
