/-
**The realising algebra, presented by generators and relations.**

A `RingPres G J` describes an algebra over a field `k` generated by

* for each `g : G`, a universal idempotent `size g × size g` matrix `E_g`, and
* for each `j : J`, mutually inverse matrices `A_j`, `B_j` identifying the projective modules
  `⊕_{α ∈ lhs j} P_α` and `⊕_{α ∈ rhs j} P_α`, where an *atom* `α` is `R` itself (`free`), the
  image of some `E_g` (`img g`) or of `1 - E_g` (`coimg g`).

This is the ring of **Bergman 1974, Theorem 6.2** (and of **Bergman–Dicks 1978, Theorem 3.4** when
`G`, `J` are infinite), written down in one piece.  Two facts about it are proved here:

* `RingPres.quasiFree`: it is quasi-free, since idempotents and isomorphisms between the images
  of idempotents lift along square-zero extensions; so it is hereditary
  (`Bergman/QuasiFree.lean`);
* `RingPres.presentedBy`: its `V` is presented by the atoms, subject to
  `[img g] + [coimg g] = size g • [free]` and `Σ lhs j = Σ rhs j`.  For finitely many generators
  and relations this is induction on Theorems 5.1 and 5.2 (`Bergman/Steps.lean`); in general
  every idempotent matrix and every equivalence between two of them only involves finitely many
  generators and relations (compactness of `RingQuot`).
-/
import KappaMonoid.Bergman.RingPres
import KappaMonoid.Bergman.Stages
import KappaMonoid.Bergman.QuasiFree
import KappaMonoid.Bergman.SqZero

universe u

namespace Bergman

open Matrix

namespace RingPres

variable {G J : Type u} (P : RingPres G J) (k : Type u) [Field k]

/-- **The realising algebra is quasi-free**, hence hereditary: the universal idempotents lift
along square-zero extensions (`SqZero.exists_idem_lift`), and then so do the universal
isomorphisms between their images (`SqZero.exists_iso_lift`). -/
theorem quasiFree : QuasiFree k (P.ring k) := by
  classical
  intro T T' _ _ _ _ π hπs hsq φ
  have hZ : SqZero π.toRingHom := ⟨hπs, hsq⟩
  set x' : P.Gen → T' := φ.toRingHom ∘ P.gen k with hx'def
  have hx' : P.Holds x' := Holds.map P (P.gen k) φ.toRingHom (P.holds_gen k)
  -- lift the idempotents
  have hE : ∀ g, ∃ E : Matrix (Fin (P.size g)) (Fin (P.size g)) T, E * E = E ∧
      E.map π.toRingHom = P.emat x' g := fun g => hZ.exists_idem_lift (hx'.idem g)
  choose E hEi hEπ using hE
  let x₀ : P.Gen → T
    | .e g a b => E g a b
    | _ => 0
  have hx₀e : ∀ g, P.emat x₀ g = E g := fun g => rfl
  have hx₀i : ∀ g, P.emat x₀ g * P.emat x₀ g = P.emat x₀ g := fun g => hEi g
  have hdπ : ∀ l, (P.dmat x₀ l).map π.toRingHom = P.dmat x' l := fun l => by
    rw [← dmat_map]
    refine P.dmat_congr _ (fun g a b => ?_) l
    exact congrFun (congrFun (hEπ g) a) b
  -- lift the isomorphisms
  have hAB : ∀ j, ∃ (A : Matrix (P.Idx (P.lhs j)) (P.Idx (P.rhs j)) T)
      (B : Matrix (P.Idx (P.rhs j)) (P.Idx (P.lhs j)) T),
      P.dmat x₀ (P.lhs j) * A * P.dmat x₀ (P.rhs j) = A ∧
      P.dmat x₀ (P.rhs j) * B * P.dmat x₀ (P.lhs j) = B ∧
      A * B = P.dmat x₀ (P.lhs j) ∧ B * A = P.dmat x₀ (P.rhs j) ∧
      A.map π.toRingHom = P.amat x' j ∧ B.map π.toRingHom = P.bmat x' j := fun j =>
    hZ.exists_iso_lift (P.dmat_idem x₀ hx₀i _) (P.dmat_idem x₀ hx₀i _)
      (by rw [hdπ, hdπ]; exact hx'.cornerA j) (by rw [hdπ, hdπ]; exact hx'.cornerB j)
      (by rw [hdπ]; exact hx'.mulAB j) (by rw [hdπ]; exact hx'.mulBA j)
  choose A B hA hB hAB' hBA hAπ hBπ using hAB
  let x : P.Gen → T
    | .e g a b => E g a b
    | .fwd j a b => A j a b
    | .bwd j a b => B j a b
  have hd : ∀ l, P.dmat x l = P.dmat x₀ l := fun l => P.dmat_congr _ (fun _ _ _ => rfl) l
  have hx : P.Holds x := by
    refine ⟨fun g => hEi g, fun j => ?_, fun j => ?_, fun j => ?_, fun j => ?_⟩ <;>
      simp only [hd]
    · exact hA j
    · exact hB j
    · exact hAB' j
    · exact hBA j
  obtain ⟨ψ, hψ⟩ := P.lift k x hx
  refine ⟨ψ, P.hom_ext k _ _ fun g => ?_⟩
  rw [AlgHom.comp_apply, hψ]
  change π (x g) = x' g
  cases g with
  | e g a b => exact congrFun (congrFun (hEπ g) a) b
  | fwd j a b => exact congrFun (congrFun (hAπ j) a) b
  | bwd j a b => exact congrFun (congrFun (hBπ j) a) b

/-- **`V` of the realising algebra** is presented by the atoms and `mrel`, provided some model
`ev` of the relations sees that `R`, and both sides of every relation, are nonzero. -/
theorem presentedBy {X : Type u} [AddCommMonoid X] (ev : Atom G → X)
    (hev : ∀ x y, P.mrel x y → msum ev x = msum ev y) (hfree : ev .free ≠ 0)
    (hsize : ∀ g, 1 ≤ P.size g) (hl : ∀ j, msum ev ↑(P.lhs j) ≠ 0)
    (hr : ∀ j, msum ev ↑(P.rhs j) ≠ 0) : PresentedBy (P.γ k) P.mrel := by
  classical
  exact P.presentedBy_of_stages k fun s hs =>
    P.stage_presentedBy k ev hev hfree hsize hl hr s hs

end RingPres

end Bergman
