/-
**Presentations of commutative monoids.**

`PresentedBy γ rel` says that `γ : A → X` generates the commutative monoid `X` and that the
relations among the generators are exactly those generated by `rel`: two formal sums of generators
have the same value iff they are related by `addConGen rel`.  This is the invariant that is
carried through the construction of the realising ring, one universal construction at a time.
-/
import Mathlib.Algebra.BigOperators.Group.Multiset.Basic
import Mathlib.GroupTheory.Congruence.Basic
import Mathlib.Order.ConditionallyCompleteLattice.Basic

universe u v w

namespace Bergman

variable {A : Type u} {B : Type w} {X : Type v} [AddCommMonoid X]

/-- The additive map `Multiset A → X` induced by `γ`: a formal sum of generators to its value. -/
def msum (γ : A → X) : Multiset A →+ X :=
  Multiset.sumAddMonoidHom.comp (Multiset.mapAddMonoidHom γ)

@[simp] theorem msum_apply (γ : A → X) (x : Multiset A) : msum γ x = (x.map γ).sum := rfl

/-- `γ` **presents** `X` with relations `rel`. -/
def PresentedBy (γ : A → X) (rel : Multiset A → Multiset A → Prop) : Prop :=
  Function.Surjective (msum γ) ∧ ∀ x y, msum γ x = msum γ y ↔ addConGen rel x y

namespace PresentedBy

variable {γ : A → X} {rel : Multiset A → Multiset A → Prop}

/-- Transport along an isomorphism of the target. -/
theorem map_equiv {Y : Type w} [AddCommMonoid Y] (h : PresentedBy γ rel) (e : X ≃+ Y) :
    PresentedBy (e ∘ γ) rel := by
  have hm : ∀ x, msum (e ∘ γ) x = e (msum γ x) := fun x => by
    simp [map_multiset_sum, Multiset.map_map]
  refine ⟨fun y => ?_, fun x y => ?_⟩
  · obtain ⟨x, hx⟩ := h.1 (e.symm y)
    exact ⟨x, by rw [hm, hx]; simp⟩
  · rw [hm, hm, e.injective.eq_iff]
    exact h.2 x y

/-- Only the congruence generated by the relations matters. -/
theorem congr_rel {rel' : Multiset A → Multiset A → Prop} (h : PresentedBy γ rel)
    (hr : addConGen rel = addConGen rel') : PresentedBy γ rel' := by
  rw [PresentedBy, ← hr]
  exact h

/-- Reindex the generators along a bijection. -/
theorem comp_equiv (h : PresentedBy γ rel) (σ : B ≃ A) :
    PresentedBy (γ ∘ σ) (fun x y => rel (x.map σ) (y.map σ)) := by
  let f : Multiset B ≃+ Multiset A :=
    { toFun := Multiset.map σ
      invFun := Multiset.map σ.symm
      left_inv := fun x => by simp [Multiset.map_map]
      right_inv := fun x => by simp [Multiset.map_map]
      map_add' := Multiset.map_add _ }
  have hm : ∀ x, msum (γ ∘ σ) x = msum γ (f x) := fun x => by
    simp [f, Multiset.map_map]
  have key : ∀ x y, addConGen (fun x y => rel (x.map σ) (y.map σ)) x y ↔
      addConGen rel (f x) (f y) := fun x y => by
    rw [← AddCon.comap_rel (f := f) (map_add f), AddCon.comap_addConGen_equiv f rel]
    rfl
  refine ⟨fun z => ?_, fun x y => ?_⟩
  · obtain ⟨x, hx⟩ := h.1 z
    exact ⟨f.symm x, by rw [hm, f.apply_symm_apply, hx]⟩
  · rw [hm, hm, key]
    exact h.2 _ _

/-- **Adding relations.**  If `γ` presents `X` with `rel`, and `ψ : X → Y` is onto with kernel
congruence generated by the values of the extra relations `s`, then `ψ ∘ γ` presents `Y` with
`rel ⊔ s`. -/
theorem comp_quotient (h : PresentedBy γ rel) {Y : Type w} [AddCommMonoid Y] (ψ : X →+ Y)
    (hψ : Function.Surjective ψ) (s : Multiset A → Multiset A → Prop)
    (hker : ∀ a b, ψ a = ψ b ↔
      addConGen (fun a b => ∃ x y, s x y ∧ msum γ x = a ∧ msum γ y = b) a b) :
    PresentedBy (ψ ∘ γ) (rel ⊔ s) := by
  set c := addConGen (rel ⊔ s)
  have hm : ∀ x, msum (ψ ∘ γ) x = ψ (msum γ x) := fun x => by
    simp [map_multiset_sum, Multiset.map_map]
  -- the kernel of `msum γ` is contained in `c`
  have h1 : ∀ x x', msum γ x = msum γ x' → c x x' := fun x x' e =>
    AddCon.addConGen_mono (r := rel) (s := rel ⊔ s) (fun _ _ hab => Or.inl hab)
      ((h.2 x x').1 e)
  refine ⟨fun z => ?_, fun x y => ?_⟩
  · obtain ⟨a, rfl⟩ := hψ z
    obtain ⟨x, rfl⟩ := h.1 a
    exact ⟨x, hm x⟩
  rw [hm, hm]
  constructor
  · intro hxy
    -- the congruence on `X` induced by `c`
    let d : AddCon X :=
      { r := fun a b => ∃ x y, msum γ x = a ∧ msum γ y = b ∧ c x y
        iseqv :=
          { refl := fun a => by
              obtain ⟨x, hx⟩ := h.1 a
              exact ⟨x, x, hx, hx, c.refl x⟩
            symm := fun ⟨x, y, hx, hy, hxy⟩ => ⟨y, x, hy, hx, c.symm hxy⟩
            trans := fun ⟨x, y, hx, hy, hxy⟩ ⟨y', z, hy', hz, hyz⟩ =>
              ⟨x, z, hx, hz, c.trans hxy (c.trans (h1 _ _ (hy.trans hy'.symm)) hyz)⟩ }
        add' := fun ⟨x, y, hx, hy, hxy⟩ ⟨x', y', hx', hy', hxy'⟩ =>
          ⟨x + x', y + y', by rw [map_add, hx, hx'], by rw [map_add, hy, hy'], c.add hxy hxy'⟩ }
    have hd : addConGen (fun a b => ∃ x y, s x y ∧ msum γ x = a ∧ msum γ y = b) ≤ d :=
      AddCon.addConGen_le.2 fun a b ⟨x, y, hs, ha, hb⟩ =>
        ⟨x, y, ha, hb, AddConGen.Rel.of _ _ (Or.inr hs)⟩
    obtain ⟨x', y', hx', hy', hc'⟩ := hd ((hker _ _).1 hxy)
    exact c.trans (h1 _ _ hx'.symm) (c.trans hc' (h1 _ _ hy'))
  · intro hxy
    have hle : c ≤ AddCon.ker (ψ.comp (msum γ)) := AddCon.addConGen_le.2 fun x y hr => by
      rw [AddCon.ker_rel]
      rcases (show rel x y ∨ s x y from hr) with hr | hr
      · show ψ (msum γ x) = ψ (msum γ y)
        rw [(h.2 x y).2 (AddConGen.Rel.of _ _ hr)]
      · exact (hker _ _).2 (AddConGen.Rel.of _ _ ⟨x, y, hr, rfl, rfl⟩)
    exact (AddCon.ker_rel _).1 (hle hxy)

/-- Presentations give isomorphisms onto the other models of the same presentation: if `γ`
presents `X` with `rel` and `ev : A → Y` respects `rel`, there is a unique additive map
`X → Y` through which `ev` factors. -/
theorem exists_lift (h : PresentedBy γ rel) {Y : Type w} [AddCommMonoid Y] (ev : A → Y)
    (hev : ∀ x y, rel x y → msum ev x = msum ev y) :
    ∃ f : X →+ Y, ∀ a, f (γ a) = ev a := by
  choose sec hsec using h.1
  have hle : addConGen rel ≤ AddCon.ker (msum ev) :=
    AddCon.addConGen_le.2 fun x y hr => (AddCon.ker_rel _).2 (hev x y hr)
  have hc : ∀ x y, msum γ x = msum γ y → msum ev x = msum ev y := fun x y e =>
    (AddCon.ker_rel _).1 (hle ((h.2 x y).1 e))
  refine ⟨{ toFun := fun a => msum ev (sec a), map_zero' := ?_, map_add' := ?_ }, fun a => ?_⟩
  · rw [hc (sec 0) 0 (by rw [hsec, map_zero]), map_zero]
  · intro a b
    rw [← map_add]
    exact hc _ _ (by rw [hsec, map_add, hsec, hsec])
  · change msum ev (sec (γ a)) = ev a
    rw [hc (sec (γ a)) {a} (by rw [hsec]; simp)]
    simp

end PresentedBy

end Bergman
