/-
**The two construction steps and their effect on `V`.**

**Bergman, *Coproducts and some universal ring constructions* (1974), Theorems 5.1 and 5.2**,
in the form needed here, as statements about presentations of `V`:

* adjoining a universal idempotent `n × n` matrix `E` (`n ≥ 1`, `R ≠ 0`) adds two generators
  `[E]`, `[1 - E]` and the one relation `[E] + [1 - E] = n [R]`;
* adjoining a universal isomorphism between two nonzero finitely generated projectives
  `P`, `Q` adds the one relation `[P] = [Q]`.

Both come from Bergman's coproduct theorem (`Bergman/Coprod.lean`) applied to the matrix-ring
descriptions of `Bergman/Morita.lean`, together with `V(M_n(S)) ≅ V(S)`, `V(k × k) = ℕ²` and
`V(M₂(k) × k) = ℕ²`.
-/
import KappaMonoid.Bergman.Morita
import KappaMonoid.Bergman.Coprod
import KappaMonoid.Bergman.StepsAux

universe u

namespace Bergman

open Matrix

variable {k : Type u} [Field k] {R S : Type u} [Ring R] [Ring S] [Algebra k R] [Algebra k S]
  {A : Type u} {γ : A → V R} {rel : Multiset A → Multiset A → Prop}

/-- The relations of `R`, read in `A ⊕ Bool`. -/
def liftRel (rel : Multiset A → Multiset A → Prop) (x y : Multiset (A ⊕ Bool)) : Prop :=
  ∃ x' y', rel x' y' ∧ x = x'.map Sum.inl ∧ y = y'.map Sum.inl

/-- The new relation `p + q = n • a₀` of a universal idempotent. -/
def idemRel (a₀ : A) (n : ℕ) (x y : Multiset (A ⊕ Bool)) : Prop :=
  x = {Sum.inr true, Sum.inr false} ∧ y = n • {Sum.inl a₀}

/-- The generators after adjoining a universal idempotent `E`: the old ones, `[E]` and
`[1 - E]`. -/
noncomputable def idemGen (j : R →ₐ[k] S) (γ : A → V R) {n : ℕ} {E : Matrix (Fin n) (Fin n) S}
    (hE : E * E = E) : A ⊕ Bool → V S :=
  Sum.elim (fun a => V.map j.toRingHom (γ a))
    (fun b => if b then cls E hE else
      cls (1 - E) (one_sub_idem hE))

/-- A family of additive maps out of the `V` of a `pair` of rings. -/
noncomputable def pairHomV {A B : Type u} [Ring A] [Ring B] {M : Type*} [AddCommMonoid M]
    (f : V A →+ M) (g : V B →+ M) : ∀ b, V (pair A B b) →+ M
  | true => f
  | false => g

/-- **Theorem 5.1** (on `V`): a universal idempotent adds `[E]`, `[1 - E]` and the relation
`[E] + [1 - E] = n [R]`.

Proof: `M_n(S) = M_n(R) ⊔_k (k × k)` (`IsIdemExt.isCoprod`), so by Bergman's coproduct theorem
`V(S) ≅ V(M_n(S))` is generated by `V(R)` and `[E]`, `[1 - E]` (`V(k × k) = ℕ²`), and the only
relations come from moving `[k]` into either factor, where it becomes `n [R]` resp.
`[E] + [1 - E]`.  The inverse map to the formal model is built on the factors
(`IsCoprod.exists_V_hom`), which gives the presentation (`PresentedBy.of_retract`). -/
theorem PresentedBy.idemExt (h : PresentedBy γ rel) (a₀ : A) (ha₀ : γ a₀ = V.one R)
    (hne : V.one R ≠ 0) {n : ℕ} (hn : 1 ≤ n) {j : R →ₐ[k] S} {E : Matrix (Fin n) (Fin n) S}
    (hS : IsIdemExt j n E) :
    PresentedBy (idemGen j γ hS.idem) (liftRel rel ⊔ idemRel a₀ n) := by
  classical
  have : Nonempty (Fin n) := ⟨⟨0, hn⟩⟩
  have : Nontrivial R := nontrivial_of_V_one_ne_zero hne
  have hE := hS.idem
  have hC := IsIdemExt.isCoprod n hS hn
  have h1 : ∀ i : Unit, (Pi.single i (1 : k) : Unit → k) = 1 := fun i =>
    funext fun u => by rw [Subsingleton.elim u i]; simp
  have hσ : ∀ l, Function.Injective (pairSigma (unitScalar n R) (diagTwo k) l) := by
    rintro (_ | _)
    · refine pi_algHom_injective (diagTwo k) fun i => ?_
      rw [h1, map_one]
      exact one_ne_zero
    · refine pi_algHom_injective (unitScalar n R) fun i => ?_
      rw [h1, map_one]
      exact one_ne_zero
  set c := addConGen (liftRel rel ⊔ idemRel a₀ n) with hc
  have hrelc : ∀ x y, (liftRel rel ⊔ idemRel a₀ n) x y → (x : c.Quotient) = y := fun x y hr =>
    (AddCon.eq c).2 (AddConGen.Rel.of _ _ hr)
  obtain ⟨ΨR, hΨR⟩ := h.exists_lift
    (fun a => ((({Sum.inl a} : Multiset (A ⊕ Bool))) : c.Quotient)) (fun x y hxy => by
      rw [msum_coe_singleton c Sum.inl, msum_coe_singleton c Sum.inl]
      exact hrelc _ _ (Or.inl ⟨x, y, hxy, rfl, rfl⟩))
  let Ψt : V (Matrix (Fin n) (Fin n) R) →+ c.Quotient :=
    ΨR.comp (V.matrixEquiv (Fin n)).toAddMonoidHom
  let t : Fin 2 → c.Quotient := ![(({Sum.inr true} : Multiset (A ⊕ Bool)) : c.Quotient),
    (({Sum.inr false} : Multiset (A ⊕ Bool)) : c.Quotient)]
  let Ψf : V (Fin 2 → k) →+ c.Quotient := V.piFieldLift k t
  let Ψ₀ : V (Unit → k) →+ c.Quotient := Ψt.comp (V.map (unitScalar n R).toRingHom)
  have hone : ∀ i : Unit, V.basis k i = V.one (Unit → k) := fun i => by
    rw [← cls1_one]; exact cls1_congr (h1 i) _ _
  obtain ⟨f, hf⟩ := hC.exists_V_hom hσ Ψ₀ (pairHomV Ψt Ψf) (by
    rintro (_ | _) a
    · show Ψf (V.map (diagTwo k).toRingHom a) = Ψ₀ a
      have : Ψf.comp (V.map (diagTwo k).toRingHom) = Ψ₀ := V.pi_field_hom_ext fun i => by
        simp only [Ψf, Ψ₀, Ψt, AddMonoidHom.comp_apply, hone, V.map_one, V.piFieldLift_one,
          AddEquiv.coe_toAddMonoidHom, V.matrixEquiv_one, map_nsmul, Fintype.card_fin,
          Fin.sum_univ_two]
        rw [← ha₀, hΨR]
        simp only [t, Matrix.cons_val_zero, Matrix.cons_val_one]
        rw [← AddCon.coe_add, hrelc _ (n • {Sum.inl a₀})
          (Or.inr ⟨by simp [Multiset.insert_eq_cons], rfl⟩)]
        exact map_nsmul (AddCon.mk' c) n _
      exact DFunLike.congr_fun this a
    · rfl)
  have hmap1 : ∀ b, V.matrixEquiv (Fin n)
      (V.map (pairHom
          (AlgHom.mapMatrix j : Matrix (Fin n) (Fin n) R →ₐ[k] Matrix (Fin n) (Fin n) S)
          (idemHom n hE) true).toRingHom b) =
        V.map j.toRingHom (V.matrixEquiv (Fin n) b) := fun b =>
    V.matrixEquiv_map j.toRingHom (Fin n) b
  have hjγ : ∀ z : Multiset A, msum (idemGen j γ hS.idem) (z.map Sum.inl) =
      V.map j.toRingHom (msum γ z) := fun z => by
    rw [msum_map, msum_hom]; rfl
  refine PresentedBy.of_retract ?_ ?_ (f.comp (V.matrixEquiv (Fin n)).symm.toAddMonoidHom) ?_
  · intro z
    obtain ⟨w, rfl⟩ := (V.matrixEquiv (Fin n) (R := S)).surjective z
    let T : AddSubmonoid (V (Matrix (Fin n) (Fin n) S)) :=
      (AddMonoidHom.mrange (msum (idemGen j γ hS.idem))).comap
        (V.matrixEquiv (Fin n)).toAddMonoidHom
    refine hC.V_mem hσ true T ?_ w
    rintro (_ | _) c'
    · have key : ∀ c'' : V (Fin 2 → k), V.map (idemHom n hE).toRingHom c'' ∈ T := by
        intro c''
        induction c'' using V.pi_field_induction with
        | h0 => rw [map_zero]; exact T.zero_mem
        | hadd x y hx hy => rw [map_add]; exact T.add_mem hx hy
        | hb i =>
          simp only [T, AddSubmonoid.mem_comap, AddMonoidHom.mem_mrange,
            AddEquiv.coe_toAddMonoidHom]
          rw [V.map_basis, V.matrixEquiv_cls1]
          fin_cases i
          · exact ⟨{Sum.inr true}, by
              simp only [msum_apply, Multiset.map_singleton, Multiset.sum_singleton]
              show cls E hE = _
              exact cls_congr (by simp [idemHom_apply]) _ _⟩
          · exact ⟨{Sum.inr false}, by
              simp only [msum_apply, Multiset.map_singleton, Multiset.sum_singleton]
              show cls (1 - E) (one_sub_idem hE) = _
              exact cls_congr (by simp [idemHom_apply]) _ _⟩
      exact key c'
    · show V.matrixEquiv (Fin n) (V.map (pairHom _ _ true).toRingHom c') ∈ AddMonoidHom.mrange _
      rw [hmap1]
      obtain ⟨x, hx⟩ := h.1 (V.matrixEquiv (Fin n) c')
      exact ⟨x.map Sum.inl, by rw [hjγ, hx]⟩
  · rintro x y (⟨x', y', hr, rfl, rfl⟩ | ⟨rfl, rfl⟩)
    · rw [hjγ, hjγ, (h.2 x' y').2 (AddConGen.Rel.of _ _ hr)]
    · have hE1 : E * (1 - E) = 0 := by rw [mul_sub, mul_one, hE, sub_self]
      have hE2 : (1 - E) * E = 0 := by rw [sub_mul, one_mul, hE, sub_self]
      simp only [msum_apply, Multiset.insert_eq_cons, Multiset.map_cons, Multiset.map_singleton,
        Multiset.sum_cons, Multiset.sum_singleton, Multiset.map_nsmul, Multiset.sum_nsmul]
      simp only [idemGen, Sum.elim_inr, Sum.elim_inl, if_true, Bool.false_eq_true, if_false,
        ha₀, V.map_one]
      rw [← cls_add_orth hE (one_sub_idem hE) hE1 hE2,
        cls_congr (add_sub_cancel E 1) _ (by simp), cls_one, Fintype.card_fin]
  · rintro (a | b)
    · show f ((V.matrixEquiv (Fin n)).symm (V.map j.toRingHom (γ a))) = _
      have e1 : (V.matrixEquiv (Fin n)).symm (V.map j.toRingHom (γ a)) =
          V.map (pairHom
          (AlgHom.mapMatrix j : Matrix (Fin n) (Fin n) R →ₐ[k] Matrix (Fin n) (Fin n) S)
          (idemHom n hE) true).toRingHom
            ((V.matrixEquiv (Fin n)).symm (γ a)) := by
        rw [AddEquiv.symm_apply_eq]
        refine Eq.symm ((hmap1 _).trans ?_)
        rw [AddEquiv.apply_symm_apply]
      rw [e1]
      refine (hf true _).trans ?_
      show ΨR (V.matrixEquiv (Fin n) ((V.matrixEquiv (Fin n)).symm (γ a))) = _
      rw [AddEquiv.apply_symm_apply, hΨR]
    · cases b
      · show f ((V.matrixEquiv (Fin n)).symm (cls (1 - E) (one_sub_idem hE))) = _
        have e1 : (V.matrixEquiv (Fin n)).symm (cls (1 - E) (one_sub_idem hE)) =
            V.map (idemHom n hE).toRingHom (V.basis k 1) := by
          rw [AddEquiv.symm_apply_eq, V.map_basis, V.matrixEquiv_cls1]
          exact cls_congr (by simp [idemHom_apply]) _ _
        rw [e1]
        exact (hf false _).trans (V.piFieldLift_basis t 1)
      · show f ((V.matrixEquiv (Fin n)).symm (cls E hE)) = _
        have e1 : (V.matrixEquiv (Fin n)).symm (cls E hE) =
            V.map (idemHom n hE).toRingHom (V.basis k 0) := by
          rw [AddEquiv.symm_apply_eq, V.map_basis, V.matrixEquiv_cls1]
          exact cls_congr (by simp [idemHom_apply]) _ _
        rw [e1]
        exact (hf false _).trans (V.piFieldLift_basis t 0)

/-- The structure maps `k³ → M_N(R)` and `k³ → M₂(k) × k` of `IsIsoExt.isCoprod` are injective
when `D` and `D'` are nonzero: the hypothesis under which Bergman's coproduct theorem applies. -/
theorem isoPairSigma_injective [Nontrivial R] {m m' : Type} [Fintype m] [Fintype m']
    [DecidableEq m] [DecidableEq m'] {D : Matrix m m R} {D' : Matrix m' m' R}
    (hD : D * D = D) (hD' : D' * D' = D') (hDne : D ≠ 0) (hD'ne : D' ≠ 0) :
    ∀ l, Function.Injective (pairSigma (isoSigma D D' hD hD') (isoTarget k) l) := by
  have hσ0 : isoSigma (k := k) D D' hD hD' (Pi.single 0 1) = fromBlocks D 0 0 0 := by
    rw [isoSigma_single]; rfl
  have hσ1 : isoSigma (k := k) D D' hD hD' (Pi.single 1 1) =
      fromBlocks 0 0 0 (fromBlocks D' 0 0 0) := by
    rw [isoSigma_single]; rfl
  have hσ2 : isoSigma (k := k) D D' hD hD' (Pi.single 2 1) =
      1 - fromBlocks D 0 0 0 - fromBlocks 0 0 0 (fromBlocks D' 0 0 0) := by
    rw [isoSigma_single]; rfl
  rintro (_ | _)
  · refine pi_algHom_injective (isoTarget k) fun i => ?_
    rw [isoTarget_single]
    fin_cases i
    · intro h0
      have := congrFun (congrFun (congrArg Prod.fst h0) 0) 0
      simp at this
    · intro h0
      have := congrFun (congrFun (congrArg Prod.fst h0) 1) 1
      simp at this
    · intro h0
      have := congrArg Prod.snd h0
      simp at this
  · refine pi_algHom_injective (isoSigma D D' hD hD') fun i => ?_
    fin_cases i
    · show isoSigma D D' hD hD' (Pi.single 0 1) ≠ 0
      rw [hσ0]
      exact fun h0 => hDne (Matrix.ext fun a b => by
        simpa using congrFun (congrFun h0 (Sum.inl a)) (Sum.inl b))
    · show isoSigma D D' hD hD' (Pi.single 1 1) ≠ 0
      rw [hσ1]
      exact fun h0 => hD'ne (Matrix.ext fun a b => by
        simpa using congrFun (congrFun h0 (Sum.inr (Sum.inl a))) (Sum.inr (Sum.inl b)))
    · show isoSigma D D' hD hD' (Pi.single 2 1) ≠ 0
      rw [hσ2]
      intro h0
      have := congrFun (congrFun h0 (Sum.inr (Sum.inr ()))) (Sum.inr (Sum.inr ()))
      simp at this

/-- `V` along `isoTarget : k³ → M₂(k) × k`, first factor: the first two coordinate idempotents
go to rank-one idempotents of `M₂(k)`, the third to `0`. -/
theorem V_isoTarget_fst (i : Fin 3) : V.matrixEquiv (Fin 2) (V.map (RingHom.fst _ _)
    (V.map (isoTarget k).toRingHom (V.basis k i))) = if i = 2 then 0 else V.one k := by
  rw [V.map_basis, V.map_cls1, V.matrixEquiv_cls1]
  fin_cases i
  · rw [if_neg (by decide), ← cls_single_one (0 : Fin 2)]
    refine cls_congr ?_ _ _
    ext a b
    fin_cases a <;> fin_cases b <;> simp [isoTarget_single]
  · rw [if_neg (by decide), ← cls_single_one (1 : Fin 2)]
    refine cls_congr ?_ _ _
    ext a b
    fin_cases a <;> fin_cases b <;> simp [isoTarget_single]
  · refine Eq.trans ?_ (if_pos rfl).symm
    rw [cls_eq_zero_iff]
    ext a b
    fin_cases a <;> fin_cases b <;> simp [isoTarget_single]

/-- `V` along `isoTarget : k³ → M₂(k) × k`, second factor: only the third coordinate idempotent
survives. -/
theorem V_isoTarget_snd (i : Fin 3) : V.map (RingHom.snd _ _)
    (V.map (isoTarget k).toRingHom (V.basis k i)) = if i = 2 then V.one k else 0 := by
  rw [V.map_basis, V.map_cls1]
  fin_cases i
  · rw [if_neg (by decide), ← cls1_zero]
    exact cls1_congr (by simp [isoTarget_single]) _ _
  · rw [if_neg (by decide), ← cls1_zero]
    exact cls1_congr (by simp [isoTarget_single]) _ _
  · refine Eq.trans ?_ (if_pos rfl).symm
    rw [← cls1_one]
    exact cls1_congr (by simp [isoTarget_single]) _ _


/-- **Theorem 5.2** (on `V`): a universal isomorphism between two nonzero projectives adds the
relation `[P] = [Q]`.

Proof: `M_N(S) = M_N(R) ⊔_{k³} (M₂(k) × k)` (`IsIsoExt.isCoprod`), with `k³ → M_N(R)` given by
`diag(D,0,0)`, `diag(0,D',0)`, `diag(1-D,1-D',1)` (injective since `[D]`, `[D']`, `[R]` are
nonzero).  `V(k³) → V(M₂(k) × k) = ℕ²` is onto, `(a, b, c) ↦ (a + b, c)`, so the second factor adds
no generators, and moving the classes of `k³` into it identifies `[D]` with `[D']` and nothing
else.  As for Theorem 5.1, the inverse map to the formal model is built on the factors. -/
theorem PresentedBy.isoExt (h : PresentedBy γ rel) {m m' : Type} [Fintype m] [Fintype m']
    [DecidableEq m] [DecidableEq m'] {D : Matrix m m R} {D' : Matrix m' m' R}
    (hD : D * D = D) (hD' : D' * D' = D') (x y : Multiset A)
    (hx : cls D hD = msum γ x) (hy : cls D' hD' = msum γ y)
    (hx0 : msum γ x ≠ 0) (hy0 : msum γ y ≠ 0) {j : R →ₐ[k] S} {Aₘ : Matrix m m' S}
    {Bₘ : Matrix m' m S} (hS : IsIsoExt j D D' Aₘ Bₘ) :
    PresentedBy (fun a => V.map j.toRingHom (γ a)) (rel ⊔ fun x' y' => x' = x ∧ y' = y) := by
  classical
  have hDne : D ≠ 0 := fun h0 => hx0 (hx ▸ (cls_eq_zero_iff hD).2 h0)
  have hD'ne : D' ≠ 0 := fun h0 => hy0 (hy ▸ (cls_eq_zero_iff hD').2 h0)
  have : Nontrivial R := by
    by_contra hR
    rw [not_nontrivial_iff_subsingleton] at hR
    exact hDne (Subsingleton.elim _ _)
  have hC := hS.isCoprod hD hD'
  -- the values of `isoSigma` and `isoTarget` on the coordinate idempotents
  have hσ0 : isoSigma (k := k) D D' hD hD' (Pi.single 0 1) = fromBlocks D 0 0 0 := by
    rw [isoSigma_single]; rfl
  have hσ1 : isoSigma (k := k) D D' hD hD' (Pi.single 1 1) =
      fromBlocks 0 0 0 (fromBlocks D' 0 0 0) := by
    rw [isoSigma_single]; rfl
  have hσ2 : isoSigma (k := k) D D' hD hD' (Pi.single 2 1) =
      1 - fromBlocks D 0 0 0 - fromBlocks 0 0 0 (fromBlocks D' 0 0 0) := by
    rw [isoSigma_single]; rfl
  have hσ := isoPairSigma_injective (k := k) hD hD' hDne hD'ne
  have hT1 := V_isoTarget_fst (k := k)
  have hT2 := V_isoTarget_snd (k := k)
  -- the model: the monoid presented by the old relations and `x = y`, with the maps to it from
  -- `V(M_N(R))` (through the old presentation) and from `V(M₂(k) × k)`
  set c := addConGen (rel ⊔ fun x' y' => x' = x ∧ y' = y) with hc
  have hrelc : ∀ x' y', (rel ⊔ fun x' y' => x' = x ∧ y' = y) x' y' →
      (x' : c.Quotient) = y' := fun x' y' hr =>
    (AddCon.eq c).2 (AddConGen.Rel.of _ _ hr)
  obtain ⟨ΨR, hΨR⟩ := h.exists_lift
    (fun a => ((({a} : Multiset A)) : c.Quotient)) (fun x' y' hxy => by
      rw [msum_coe_singleton c (fun a => a), msum_coe_singleton c (fun a => a),
        Multiset.map_id', Multiset.map_id']
      exact hrelc _ _ (Or.inl hxy))
  have hΨRm : ∀ z, ΨR (msum γ z) = (z : c.Quotient) := fun z => by
    rw [msum_hom, show ΨR ∘ γ = fun a => ((({a} : Multiset A)) : c.Quotient) from funext hΨR,
      msum_coe_singleton c (fun a => a), Multiset.map_id']
  let Ψt : V (Matrix (isoIdx m m') (isoIdx m m') R) →+ c.Quotient :=
    ΨR.comp (V.matrixEquiv (isoIdx m m')).toAddMonoidHom
  have he₂ : isoSigma (k := k) D D' hD hD' (Pi.single 2 1) *
      isoSigma (k := k) D D' hD hD' (Pi.single 2 1) =
      isoSigma (k := k) D D' hD hD' (Pi.single 2 1) := by
    rw [← map_mul, single_one_idem]
  let t₂ : c.Quotient := ΨR (cls _ he₂)
  let Ψf : V (Matrix (Fin 2) (Fin 2) k × k) →+ c.Quotient :=
    ((V.fieldLift k (x : c.Quotient)).comp ((V.matrixEquiv (Fin 2)).toAddMonoidHom.comp
      (V.map (RingHom.fst _ _)))) + (V.fieldLift k t₂).comp (V.map (RingHom.snd _ _))
  let Ψ₀ : V (Fin 3 → k) →+ c.Quotient := Ψt.comp (V.map (isoSigma D D' hD hD').toRingHom)
  have hΨ₀ : ∀ i : Fin 3, Ψ₀ (V.basis k i) =
      ΨR (cls (isoSigma (k := k) D D' hD hD' (Pi.single i 1))
        (by rw [← map_mul, single_one_idem])) := fun i => by
    simp only [Ψ₀, Ψt, AddMonoidHom.comp_apply, AddEquiv.coe_toAddMonoidHom]
    rw [V.map_basis, V.matrixEquiv_cls1]
    rfl
  -- the map `V(M_N(S)) → model`, glued from the factors by the coproduct theorem
  obtain ⟨f, hf⟩ := hC.exists_V_hom hσ Ψ₀ (pairHomV Ψt Ψf) (by
    rintro (_ | _) a
    · show Ψf (V.map (isoTarget k).toRingHom a) = Ψ₀ a
      have : Ψf.comp (V.map (isoTarget k).toRingHom) = Ψ₀ := V.pi_field_hom_ext fun i => by
        rw [hΨ₀]
        simp only [Ψf, AddMonoidHom.comp_apply, AddMonoidHom.add_apply,
          AddEquiv.coe_toAddMonoidHom]
        rw [hT1, hT2]
        fin_cases i
        · simp only [Fin.zero_eta, Fin.isValue, Fin.reduceEq, if_false, V.fieldLift_one,
            map_zero, add_zero]
          rw [cls_congr hσ0 _ (fromBlocks_idem hD (by simp)), cls_fromBlocks hD (by simp),
            cls_zero_matrix, add_zero, hx, hΨRm]
        · simp only [Fin.mk_one, Fin.isValue, Fin.reduceEq, if_false, V.fieldLift_one,
            map_zero, add_zero]
          rw [cls_congr hσ1 _ (fromBlocks_idem (by simp) (fromBlocks_idem hD' (by simp))),
            cls_fromBlocks (by simp) (fromBlocks_idem hD' (by simp)),
            cls_fromBlocks hD' (by simp), cls_zero_matrix, cls_zero_matrix, add_zero,
            zero_add, hy, hΨRm]
          exact hrelc _ _ (Or.inr ⟨rfl, rfl⟩)
        · simp only [Fin.reduceFinMk, Fin.isValue, if_true, V.fieldLift_one, map_zero,
            zero_add]
          rfl
      exact DFunLike.congr_fun this a
    · rfl)
  have hmap1 : ∀ b, V.matrixEquiv (isoIdx m m')
      (V.map (pairHom
          (AlgHom.mapMatrix j : Matrix (isoIdx m m') (isoIdx m m') R →ₐ[k]
            Matrix (isoIdx m m') (isoIdx m m') S)
          (isoHom hD hD' hS) true).toRingHom b) =
        V.map j.toRingHom (V.matrixEquiv (isoIdx m m') b) := fun b =>
    V.matrixEquiv_map j.toRingHom (isoIdx m m') b
  have hjγ : ∀ z : Multiset A, msum (fun a => V.map j.toRingHom (γ a)) z =
      V.map j.toRingHom (msum γ z) := fun z => by
    rw [msum_hom]; rfl
  refine PresentedBy.of_retract ?_ ?_
    (f.comp (V.matrixEquiv (isoIdx m m')).symm.toAddMonoidHom) ?_
  -- (1) the old generators generate `V(S)`: by the coproduct theorem, every class comes from
  -- `M_N(R)` or from `M₂(k) × k`, and `V(M₂(k) × k)` is spanned by images of `V(k³)`
  · intro z
    obtain ⟨w, rfl⟩ := (V.matrixEquiv (isoIdx m m') (R := S)).surjective z
    let T : AddSubmonoid (V (Matrix (isoIdx m m') (isoIdx m m') S)) :=
      (AddMonoidHom.mrange (msum (fun a => V.map j.toRingHom (γ a)))).comap
        (V.matrixEquiv (isoIdx m m')).toAddMonoidHom
    have htrue : ∀ c', V.map (pairHom
          (AlgHom.mapMatrix j : Matrix (isoIdx m m') (isoIdx m m') R →ₐ[k]
            Matrix (isoIdx m m') (isoIdx m m') S)
          (isoHom hD hD' hS) true).toRingHom
        c' ∈ T := fun c' => by
      show V.matrixEquiv _ (V.map (pairHom _ _ true).toRingHom c') ∈ AddMonoidHom.mrange _
      rw [hmap1]
      obtain ⟨x', hx'⟩ := h.1 (V.matrixEquiv (isoIdx m m') c')
      exact ⟨x', by rw [hjγ, hx']⟩
    refine hC.V_mem hσ true T ?_ w
    rintro (_ | _) c'
    · obtain ⟨p', hp'⟩ :=
        V.field_nsmul_one k (V.matrixEquiv (Fin 2) (V.map (RingHom.fst _ _) c'))
      obtain ⟨q', hq'⟩ := V.field_nsmul_one k (V.map (RingHom.snd _ _) c')
      have hc' : c' = V.map (isoTarget k).toRingHom (p' • V.basis k 0 + q' • V.basis k 2) := by
        refine V.prod_ext ?_ ?_
        · apply (V.matrixEquiv (Fin 2)).injective
          simp only [map_add, map_nsmul, hT1]
          simp
          exact hp'
        · simp only [map_add, map_nsmul, hT2]
          simp
          exact hq'
      rw [hc']
      have := hC.V_map_comm false true (p' • V.basis k 0 + q' • V.basis k 2)
      exact this ▸ htrue _
    · exact htrue c'
  -- (2) the relations hold in `V(S)`: the old ones, and `[D] = [D']` via `A`, `B`
  · rintro x' y' (hr | ⟨rfl, rfl⟩)
    · rw [hjγ, hjγ, (h.2 x' y').2 (AddConGen.Rel.of _ _ hr)]
    · rw [hjγ, hjγ, ← hx, ← hy, V.map_cls, V.map_cls, cls_eq_cls]
      exact ⟨Aₘ, Bₘ, hS.mulAB, hS.mulBA⟩
  -- (3) the map to the model sends each generator to itself
  · intro a
    show f ((V.matrixEquiv (isoIdx m m')).symm (V.map j.toRingHom (γ a))) = _
    have e1 : (V.matrixEquiv (isoIdx m m')).symm (V.map j.toRingHom (γ a)) =
        V.map (pairHom
          (AlgHom.mapMatrix j : Matrix (isoIdx m m') (isoIdx m m') R →ₐ[k]
            Matrix (isoIdx m m') (isoIdx m m') S)
          (isoHom hD hD' hS) true).toRingHom
          ((V.matrixEquiv (isoIdx m m')).symm (γ a)) := by
      rw [AddEquiv.symm_apply_eq]
      refine Eq.symm ((hmap1 _).trans ?_)
      rw [AddEquiv.apply_symm_apply]
    rw [e1]
    refine (hf true _).trans ?_
    show ΨR (V.matrixEquiv (isoIdx m m') ((V.matrixEquiv (isoIdx m m')).symm (γ a))) = _
    rw [AddEquiv.apply_symm_apply, hΨR]



end Bergman
