/-
**Tools for the two construction steps (`Bergman/Steps.lean`).**

* `PresentedBy.of_retract`: a presentation is established by a generating family together with
  an additive map *back* to the formal model `Multiset A / ⟨rel⟩`, sending each generator to its
  own class.
* `IsCoprod.exists_V_hom`, `IsCoprod.V_mem`: the two halves of Bergman's coproduct theorem in
  the form used here — additive maps out of `V(C)` are given by compatible maps out of the
  factors, and `V(C)` is generated by the images of the factors.
* `V` of the small rings that occur: `V(k^ι) = ℕ^ι` with basis the classes of the coordinate
  idempotents (`V.basis`), `V(k) = ℕ` (`V.fieldLift`), and `V(A × B) ↪ V(A) × V(B)`
  (`V.prod_ext`).
-/
import KappaMonoid.Bergman.Coprod

universe u v w

namespace Bergman

open Matrix

/-! ## Presentations from a retraction -/

section Retract

variable {A : Type u} {B : Type w} {X : Type v} [AddCommMonoid X]

theorem msum_map (γ : B → X) (g : A → B) (x : Multiset A) :
    msum γ (x.map g) = msum (γ ∘ g) x := by
  simp [Multiset.map_map]

theorem msum_hom {Y : Type*} [AddCommMonoid Y] (f : X →+ Y) (γ : A → X) (x : Multiset A) :
    f (msum γ x) = msum (f ∘ γ) x := by
  simp [map_multiset_sum, Multiset.map_map]

/-- The formal sum of the classes of singletons is the class of the formal sum. -/
theorem msum_coe_singleton (c : AddCon (Multiset B)) (g : A → B) (x : Multiset A) :
    msum (fun a => ((({g a} : Multiset B)) : c.Quotient)) x =
      ((x.map g : Multiset B) : c.Quotient) := by
  induction x using Multiset.induction_on with
  | empty => simp [AddCon.coe_zero]
  | cons a s ih =>
    rw [← Multiset.singleton_add, map_add, ih, Multiset.map_add, AddCon.coe_add]
    simp

/-- **Presentations from a retraction.**  If `γ` generates `X`, the relations `rel` hold in `X`,
and there is an additive map `X → Multiset A / ⟨rel⟩` sending each `γ a` to the class of `a`,
then `γ` presents `X` with `rel`. -/
theorem PresentedBy.of_retract {γ : A → X} {rel : Multiset A → Multiset A → Prop}
    (hsurj : Function.Surjective (msum γ))
    (hrel : ∀ x y, rel x y → msum γ x = msum γ y)
    (f : X →+ (addConGen rel).Quotient)
    (hf : ∀ a, f (γ a) = ((({a} : Multiset A)) : (addConGen rel).Quotient)) :
    PresentedBy γ rel := by
  refine ⟨hsurj, fun x y => ⟨fun hxy => ?_, fun hxy => ?_⟩⟩
  · have hx : ∀ z, f (msum γ z) = (z : (addConGen rel).Quotient) := fun z => by
      rw [msum_hom, show (f ∘ γ) = fun a => ((({id a} : Multiset A)) : (addConGen rel).Quotient)
        from funext hf, msum_coe_singleton, Multiset.map_id]
    have := congrArg f hxy
    rw [hx, hx] at this
    exact (AddCon.eq _).1 this
  · have hle : addConGen rel ≤ AddCon.ker (msum γ) :=
      AddCon.addConGen_le.2 fun x y hr => (AddCon.ker_rel _).2 (hrel x y hr)
    exact (AddCon.ker_rel _).1 (hle hxy)

end Retract

/-! ## Bergman's coproduct theorem, in usable form -/

section Coprod

variable {k : Type u} [Field k] {ι : Type} [Fintype ι] [DecidableEq ι]
  {Λ : Type} [Fintype Λ] [DecidableEq Λ]
  {R : Λ → Type u} [∀ l, Ring (R l)] [∀ l, Algebra k (R l)]
  {σ : ∀ l, (ι → k) →ₐ[k] R l} {C : Type u} [Ring C] [Algebra k C]
  {σC : (ι → k) →ₐ[k] C} {inc : ∀ l, R l →ₐ[k] C}

omit [Fintype ι] [DecidableEq ι] in
theorem coprodV_single (l : Λ) (c : V (R l)) :
    coprodV σC inc (0, Pi.single l c) = V.map (inc l).toRingHom c := by
  simp only [coprodV, AddMonoidHom.coe_mk, ZeroHom.coe_mk, map_zero, zero_add]
  rw [Fintype.sum_eq_single l (fun l' hl' => by rw [Pi.single_eq_of_ne hl', map_zero]),
    Pi.single_eq_same]

omit [Fintype ι] [DecidableEq ι] [DecidableEq Λ] in
theorem coprodV_fst (a : V (ι → k)) : coprodV σC inc (a, 0) = V.map σC.toRingHom a := by
  simp [coprodV]

/-- **Maps out of `V` of a coproduct**: compatible additive maps out of the `V` of the factors
induce one out of `V(C)`. -/
theorem IsCoprod.exists_V_hom (hC : IsCoprod k σ C σC inc)
    (hσ : ∀ l, Function.Injective (σ l)) {M : Type*} [AddCommMonoid M]
    (Ψ₀ : V (ι → k) →+ M) (Ψ : ∀ l, V (R l) →+ M)
    (hΨ : ∀ l a, Ψ l (V.map (σ l).toRingHom a) = Ψ₀ a) :
    ∃ f : V C →+ M, ∀ l c, f (V.map (inc l).toRingHom c) = Ψ l c := by
  classical
  let Φ : V (ι → k) × (∀ l, V (R l)) →+ M :=
    Ψ₀.comp (AddMonoidHom.fst _ _) +
      ∑ l, (Ψ l).comp ((Pi.evalAddMonoidHom (fun l => V (R l)) l).comp (AddMonoidHom.snd _ _))
  have hΦ : ∀ p : V (ι → k) × (∀ l, V (R l)), Φ p = Ψ₀ p.1 + ∑ l, Ψ l (p.2 l) := fun p => by
    simp [Φ]
  have hle : addConGen (transferRel σ) ≤ AddCon.ker Φ := AddCon.addConGen_le.2 fun p q hr => by
    obtain ⟨a, l, rfl, rfl⟩ := hr
    rw [AddCon.ker_rel, hΦ, hΦ]
    simp only [Pi.zero_apply, map_zero, Finset.sum_const_zero, add_zero, zero_add]
    rw [Fintype.sum_eq_single l (fun l' hl' => by rw [Pi.single_eq_of_ne hl', map_zero]),
      Pi.single_eq_same, hΨ]
  have hc : ∀ p q, coprodV σC inc p = coprodV σC inc q → Φ p = Φ q := fun p q e =>
    (AddCon.ker_rel _).1 (hle ((hC.coprodV_eq_iff hσ p q).1 e))
  choose sec hsec using hC.coprodV_surjective hσ
  refine ⟨{ toFun := fun z => Φ (sec z), map_zero' := ?_, map_add' := ?_ }, fun l c => ?_⟩
  · rw [hc (sec 0) 0 (by rw [hsec, map_zero]), map_zero]
  · intro a b
    rw [← map_add]
    exact hc _ _ (by rw [hsec, map_add, hsec, hsec])
  · change Φ (sec _) = _
    rw [hc (sec _) (0, Pi.single l c) (by rw [hsec, coprodV_single]), hΦ]
    simp only [map_zero, zero_add]
    rw [Fintype.sum_eq_single l (fun l' hl' => by rw [Pi.single_eq_of_ne hl', map_zero]),
      Pi.single_eq_same]

/-- **`V` of a coproduct is generated by the factors.** -/
theorem IsCoprod.V_mem (hC : IsCoprod k σ C σC inc) (hσ : ∀ l, Function.Injective (σ l))
    (l₀ : Λ) (T : AddSubmonoid (V C)) (hT : ∀ l c, V.map (inc l).toRingHom c ∈ T) (z : V C) :
    z ∈ T := by
  obtain ⟨⟨a, b⟩, rfl⟩ := hC.coprodV_surjective hσ z
  refine T.add_mem ?_ (T.sum_mem fun l _ => hT l _)
  rw [← hC.comm l₀]
  have : V.map ((inc l₀).comp (σ l₀)).toRingHom a =
      V.map (inc l₀).toRingHom (V.map (σ l₀).toRingHom a) := V.map_comp _ _ a
  rw [this]
  exact hT _ _

omit [Fintype ι] [DecidableEq ι] [Fintype Λ] [DecidableEq Λ] in
/-- The two factors' maps agree on `V(k^ι)`. -/
theorem IsCoprod.V_map_comm (hC : IsCoprod k σ C σC inc) (l l' : Λ) (a : V (ι → k)) :
    V.map (inc l).toRingHom (V.map (σ l).toRingHom a) =
      V.map (inc l').toRingHom (V.map (σ l').toRingHom a) := by
  rw [← V.map_comp, ← V.map_comp]
  change V.map ((inc l).comp (σ l)).toRingHom a = V.map ((inc l').comp (σ l')).toRingHom a
  rw [hC.comm, hC.comm]

end Coprod

/-! ## Classes of `1 × 1` matrices, orthogonal sums -/

section One

variable {R : Type u} [Ring R] {T : Type v} [Ring T]

theorem idem1 {r : R} (hr : r * r = r) :
    (of fun _ _ : Fin 1 => r) * (of fun _ _ : Fin 1 => r) = of fun _ _ : Fin 1 => r := by
  ext i j
  simp [Matrix.mul_apply, hr]

/-- The class of the cyclic projective `r R`, for an idempotent `r`. -/
noncomputable def cls1 (r : R) (hr : r * r = r) : V R := cls _ (idem1 hr)

theorem cls1_congr {r r' : R} (h : r = r') (hr : r * r = r) (hr' : r' * r' = r') :
    cls1 r hr = cls1 r' hr' := by
  subst h; rfl

theorem V.map_cls1 (φ : R →+* T) {r : R} (hr : r * r = r) :
    V.map φ (cls1 r hr) = cls1 (φ r) (by rw [← map_mul, hr]) := by
  rw [cls1, V.map_cls]
  exact cls_congr (by ext; simp) _ _

theorem cls1_zero : cls1 (0 : R) (by simp) = 0 := by
  rw [cls1, cls_eq_zero_iff]
  ext; simp

theorem cls1_one : cls1 (1 : R) (by simp) = V.one R := by
  rw [cls1, V.one]
  refine cls_congr ?_ _ _
  ext i j
  rw [Subsingleton.elim i j]
  simp

theorem V.matrixEquiv_cls1 (n : Type) [Fintype n] [DecidableEq n] [Nonempty n]
    {e : Matrix n n R} (he : e * e = e) : V.matrixEquiv n (cls1 e he) = cls e he := by
  rw [cls1, V.matrixEquiv_apply, V.flat_cls, ← cls_submatrix he (Equiv.uniqueProd n (Fin 1))]
  apply cls_congr
  ext ⟨i, a⟩ ⟨j, b⟩
  simp [Matrix.comp_apply]

theorem cls_single_one {n : Type*} [Fintype n] [DecidableEq n] (i : n) :
    cls (Matrix.single i i (1 : R)) (by rw [Matrix.single_mul_single_same, one_mul]) =
      V.one R := by
  rw [V.one, cls_eq_cls]
  refine ⟨Matrix.single i 0 1, Matrix.single 0 i 1, ?_, ?_⟩
  · rw [Matrix.single_mul_single_same, one_mul]
  · rw [Matrix.single_mul_single_same, one_mul]
    ext a b
    rw [Subsingleton.elim a 0, Subsingleton.elim b 0]
    simp

/-- Orthogonal idempotents: the class of the sum is the sum of the classes. -/
theorem cls_add_orth {m : Type*} [Fintype m] [DecidableEq m] {e f : Matrix m m R}
    (he : e * e = e) (hf : f * f = f) (hef : e * f = 0) (hfe : f * e = 0) :
    cls (e + f) (by rw [add_mul, mul_add, mul_add, he, hf, hef, hfe, add_zero, zero_add]) =
      cls e he + cls f hf := by
  rw [← cls_fromBlocks he hf, cls_eq_cls]
  refine ⟨Matrix.fromCols e f, Matrix.fromRows e f, ?_, ?_⟩
  · rw [Matrix.fromCols_mul_fromRows, he, hf]
  · rw [Matrix.fromRows_mul_fromCols, he, hf, hef, hfe]

/-- A ring with `[R] ≠ 0` is nontrivial. -/
theorem nontrivial_of_V_one_ne_zero (h : V.one R ≠ 0) : Nontrivial R := by
  by_contra hR
  rw [not_nontrivial_iff_subsingleton] at hR
  exact h ((cls_eq_zero_iff _).2 (Subsingleton.elim _ _))

end One

/-! ## `V` of products of copies of a field -/

section Field

variable (k : Type u) [Field k] {ι : Type} [Fintype ι] [DecidableEq ι]

omit [Fintype ι] in
theorem single_one_idem (i : ι) :
    (Pi.single i (1 : k) : ι → k) * Pi.single i 1 = Pi.single i 1 := by
  rw [← Pi.single_mul, one_mul]

/-- The class of the coordinate idempotent `e_i ∈ k^ι`. -/
noncomputable def V.basis (i : ι) : V (ι → k) := cls1 (Pi.single i 1) (single_one_idem k i)

variable {k}

omit [Fintype ι] in
theorem V.map_basis {T : Type v} [Ring T] (φ : (ι → k) →+* T) (i : ι) :
    V.map φ (V.basis k i) = cls1 (φ (Pi.single i 1))
      (by rw [← map_mul, single_one_idem]) :=
  V.map_cls1 φ _

omit [Fintype ι] in
theorem V.map_eval_basis (i j : ι) :
    V.map (Pi.evalRingHom (fun _ => k) j) (V.basis k i) = if i = j then V.one k else 0 := by
  rw [V.map_basis]
  split_ifs with h
  · subst h
    rw [← cls1_one]
    exact cls1_congr (by simp) _ _
  · rw [← cls1_zero]
    exact cls1_congr (by simp [Pi.single_eq_of_ne' h]) _ _

/-- **`V(k^ι) = ℕ^ι`**: every class is a combination of the coordinate classes. -/
theorem V.pi_field_eq_sum (x : V (ι → k)) : ∃ m : ι → ℕ, x = ∑ i, m i • V.basis k i := by
  choose m hm using fun j => V.field_nsmul_one k (V.map (Pi.evalRingHom (fun _ => k) j) x)
  refine ⟨m, V.pi_injective (fun _ : ι => k) (funext fun j => ?_)⟩
  simp only [AddMonoidHom.pi_apply, map_sum, map_nsmul, V.map_eval_basis]
  rw [hm j, Finset.sum_eq_single j (fun i _ hij => by simp [hij]) (by simp)]
  simp

theorem V.pi_field_induction {P : V (ι → k) → Prop} (h0 : P 0)
    (hadd : ∀ x y, P x → P y → P (x + y)) (hb : ∀ i, P (V.basis k i)) (x : V (ι → k)) : P x := by
  obtain ⟨m, rfl⟩ := V.pi_field_eq_sum x
  let T : AddSubmonoid (V (ι → k)) :=
    { carrier := {x | P x}, zero_mem' := h0, add_mem' := fun {a b} ha hb => hadd a b ha hb }
  exact T.sum_mem fun i _ => T.nsmul_mem (hb i) _

theorem V.pi_field_hom_ext {M : Type*} [AddCommMonoid M] {f g : V (ι → k) →+ M}
    (h : ∀ i, f (V.basis k i) = g (V.basis k i)) : f = g := by
  ext x
  induction x using V.pi_field_induction with
  | h0 => simp
  | hadd x y hx hy => simp [hx, hy]
  | hb i => exact h i

variable (k) in
/-- **`V(k) = ℕ`.** -/
noncomputable def V.fieldEquiv : V k ≃+ ℕ :=
  (AddEquiv.ofBijective (multiplesHom (V k) (V.one k))
    (show Function.Bijective _ from
      ⟨V.field_nsmul_one_injective k, fun x => (V.field_nsmul_one k x).imp fun _ h => h.symm⟩)).symm

theorem V.fieldEquiv_one : V.fieldEquiv k (V.one k) = 1 := by
  rw [V.fieldEquiv, AddEquiv.symm_apply_eq]
  show V.one k = 1 • V.one k
  rw [one_nsmul]

variable (k) in
/-- The additive map `V(k) → M` sending `[k]` to `t`. -/
noncomputable def V.fieldLift {M : Type*} [AddCommMonoid M] (t : M) : V k →+ M :=
  (multiplesHom M t).comp (V.fieldEquiv k).toAddMonoidHom

theorem V.fieldLift_one {M : Type*} [AddCommMonoid M] (t : M) : V.fieldLift k t (V.one k) = t := by
  simp [V.fieldLift, V.fieldEquiv_one]

variable (k) in
/-- The additive map `V(k^ι) → M` sending `[e_i]` to `t i`. -/
noncomputable def V.piFieldLift {M : Type*} [AddCommMonoid M] (t : ι → M) : V (ι → k) →+ M :=
  ∑ i, (V.fieldLift k (t i)).comp (V.map (Pi.evalRingHom (fun _ => k) i))

omit [DecidableEq ι] in
theorem V.piFieldLift_apply {M : Type*} [AddCommMonoid M] (t : ι → M) (x : V (ι → k)) :
    V.piFieldLift k t x = ∑ i, V.fieldLift k (t i) (V.map (Pi.evalRingHom (fun _ => k) i) x) := by
  simp [V.piFieldLift]

theorem V.piFieldLift_basis {M : Type*} [AddCommMonoid M] (t : ι → M) (i : ι) :
    V.piFieldLift k t (V.basis k i) = t i := by
  rw [V.piFieldLift_apply, Finset.sum_eq_single i (fun j _ hj => by
    rw [V.map_eval_basis, if_neg (Ne.symm hj), map_zero]) (by simp), V.map_eval_basis, if_pos rfl,
    V.fieldLift_one]

omit [DecidableEq ι] in
theorem V.piFieldLift_one {M : Type*} [AddCommMonoid M] (t : ι → M) :
    V.piFieldLift k t (V.one _) = ∑ i, t i := by
  simp [V.piFieldLift_apply, V.map_one, V.fieldLift_one]

omit [Fintype ι] in
/-- An algebra map out of `k^ι` is injective as soon as it kills no coordinate idempotent. -/
theorem pi_algHom_injective {T : Type v} [Ring T] [Algebra k T] (φ : (ι → k) →ₐ[k] T)
    (h : ∀ i, φ (Pi.single i 1) ≠ 0) : Function.Injective φ := by
  intro v w hvw
  funext i
  by_contra hne
  have key : ∀ u : ι → k, φ (Pi.single i 1) * φ u = u i • φ (Pi.single i 1) := fun u => by
    rw [← map_mul, ← map_smul]
    congr 1
    funext j
    by_cases hj : j = i
    · subst hj; simp
    · simp [Pi.single_eq_of_ne hj]
  have h0 : (v i - w i) • φ (Pi.single i 1) = 0 := by
    rw [sub_smul, ← key, ← key, hvw, sub_self]
  exact h i ((smul_eq_zero.1 h0).resolve_left (sub_ne_zero.2 hne))

end Field

/-! ## `V` of a product of two rings -/

theorem V.prod_ext {A B : Type u} [Ring A] [Ring B] {x y : V (A × B)}
    (h1 : V.map (RingHom.fst A B) x = V.map (RingHom.fst A B) y)
    (h2 : V.map (RingHom.snd A B) x = V.map (RingHom.snd A B) y) : x = y := by
  induction x using Quotient.inductionOn with | h x => ?_
  induction y using Quotient.inductionOn with | h y => ?_
  rw [← cls_mk x, ← cls_mk y] at h1 h2 ⊢
  rw [V.map_cls, V.map_cls, cls_eq_cls] at h1 h2
  rw [cls_eq_cls]
  obtain ⟨a, b, hab, hba⟩ := h1
  obtain ⟨a', b', hab', hba'⟩ := h2
  refine ⟨of fun s t => (a s t, a' s t), of fun s t => (b s t, b' s t), ?_, ?_⟩
  · ext s t
    · have := congrFun (congrFun hab s) t
      simpa [Matrix.mul_apply, Prod.fst_sum] using this
    · have := congrFun (congrFun hab' s) t
      simpa [Matrix.mul_apply, Prod.snd_sum] using this
  · ext s t
    · have := congrFun (congrFun hba s) t
      simpa [Matrix.mul_apply, Prod.fst_sum] using this
    · have := congrFun (congrFun hba' s) t
      simpa [Matrix.mul_apply, Prod.snd_sum] using this

end Bergman
