/-
The classical results assumed by this development.

Three theorems of ordinary mathematics are taken as axioms rather than proved.  Assuming true
statements cannot make the development inconsistent, but a *mis-stated* axiom is false and a
false axiom proves everything, so each statement below is accompanied by the standard proof
sketch it stands for and should be checked against the literature before it is relied on.

Audit their use with `#print axioms`: every result outside Example 2.13 and §2.3 must report
only `propext`, `Quot.sound` and `Classical.choice`.

Universe conventions match the rest of the development — everything lives in `Type u`, so no
`Cardinal.lift` appears.
-/
import Mathlib

universe u

open Cardinal DirectSum

namespace KappaMonoid

/-! ## A1: invariance of infinite rank -/

/-- **Assumed** (invariance of infinite rank).  Over a nontrivial ring, a free module with an
infinite basis cannot be generated by fewer elements than its rank.

Standard proof, not formalised here: every element of a generating set `S` has finite support in
the basis, so `S` lies in the span of a subfamily of the basis of cardinality at most `#S ⊔ ℵ₀`;
a basis element outside that subfamily would then lie in the span of the others, contradicting
linear independence.  Hence the subfamily is everything.

The conclusion is `#ι ≤ #S` with no `⊔ ℵ₀`: when `S` is finite the hypothesis is itself
contradictory, so nothing false is asserted, and the sharp form is what lets the application in
Example 2.13 avoid a case split.

This *generation* form, rather than the two-bases form `mk_eq_mk_of_infinite` below, is what the
application needs: the complement appearing in Example 2.13 is merely projective, not free, so
there is no second basis to compare against. -/
axiom mk_le_of_span_eq_top {R : Type u} [Ring R] [Nontrivial R] {M : Type u} [AddCommGroup M]
    [Module R M] {ι : Type u} (_b : Module.Basis ι R M) [Infinite ι] {S : Set M}
    (_hS : Submodule.span R S = ⊤) : #ι ≤ #S

/-- Invariance of infinite rank in its familiar form: two bases of the same module, one of them
infinite, have the same cardinality.  Derived from `mk_le_of_span_eq_top`. -/
theorem mk_eq_mk_of_infinite {R : Type u} [Ring R] [Nontrivial R] {M : Type u} [AddCommGroup M]
    [Module R M] {ι ι' : Type u} (b : Module.Basis ι R M) (b' : Module.Basis ι' R M) [Infinite ι] :
    #ι = #ι' := by
  have h₁ : #ι ≤ #(Set.range (b' : ι' → M)) := mk_le_of_span_eq_top b b'.span_eq
  have h₁' : #ι ≤ #ι' := h₁.trans (Cardinal.mk_range_le)
  -- `ι'` is infinite too, so the argument may be repeated with the roles exchanged
  haveI : Infinite ι' :=
    Cardinal.infinite_iff.mpr ((Cardinal.infinite_iff.mp ‹Infinite ι›).trans h₁')
  have h₂ : #ι' ≤ #(Set.range (b : ι → M)) := mk_le_of_span_eq_top b' b.span_eq
  exact le_antisymm h₁' (h₂.trans Cardinal.mk_range_le)

/-! ## A2: Leavitt's realisation theorem -/

/-- The congruence `∼_{m,n}` on `ℕ₀` defining the cyclic monoid `C_{m,n}`: `k` and `l` are
identified iff they are equal, or both are at least `m` and differ by a multiple of `n`. -/
def CyclicRel (m n k l : ℕ) : Prop := k = l ∨ (m ≤ k ∧ m ≤ l ∧ (n : ℤ) ∣ (k : ℤ) - l)

/-- A ring realising the cyclic monoid `C_{m,n}` as its monoid of finitely generated free
modules: `R^k ≅ R^l` exactly when `k ∼_{m,n} l`. -/
structure LeavittData (m n : ℕ) where
  /-- The realising ring. -/
  R : Type u
  [ring : Ring R]
  [nontrivial : Nontrivial R]
  /-- Isomorphism of finitely generated free modules is exactly `∼_{m,n}`. -/
  iso_iff : ∀ k l : ℕ,
    Nonempty ((⨁ _ : Fin k, R) ≃ₗ[R] (⨁ _ : Fin l, R)) ↔ CyclicRel m n k l

attribute [instance] LeavittData.ring LeavittData.nontrivial

/-- **Assumed** (Leavitt, 1962).  Every cyclic monoid `C_{m,n}` with `n ≥ 1` is the monoid of
finitely generated free modules over some ring.

The remaining cyclic monoid, `ℕ₀` itself, needs no axiom: every ring with invariant basis
number realises it. -/
axiom leavittData (m n : ℕ) (_hn : 1 ≤ n) : LeavittData.{u} m n

/-! ## A3: uniqueness of the multiplicities of simple modules -/

/-- **Assumed**: in a decomposition into simple modules the multiplicity of each isomorphism
class is uniquely determined, infinite multiplicities included.

Jordan–Hölder gives the finite case; the infinite case is the classical cardinal-counting
extension.  Only *uniqueness* is assumed here — the companion existence statement, that every
module over a semisimple ring is a direct sum of simple modules, is available in Mathlib. -/
axiom mk_multiplicity_eq {R : Type u} [Ring R] {I J : Type u} {A : I → Type u} {B : J → Type u}
    [∀ i, AddCommGroup (A i)] [∀ i, Module R (A i)]
    [∀ j, AddCommGroup (B j)] [∀ j, Module R (B j)]
    (_hA : ∀ i, IsSimpleModule R (A i)) (_hB : ∀ j, IsSimpleModule R (B j))
    (_e : (⨁ i, A i) ≃ₗ[R] (⨁ j, B j)) (S : Type u) [AddCommGroup S] [Module R S] :
    #{i // Nonempty (A i ≃ₗ[R] S)} = #{j // Nonempty (B j ≃ₗ[R] S)}

end KappaMonoid
