/-
The classical results assumed by this development.

Four theorems of ordinary mathematics are taken as axioms rather than proved.  Assuming true
statements cannot make the development inconsistent, but a *mis-stated* axiom is false and a
false axiom proves everything, so each statement below is accompanied by the standard proof
sketch it stands for and should be checked against the literature before it is relied on.

Audit their use with `#print axioms`: every result outside Example 2.13 and §2.3 must report
only `propext`, `Quot.sound` and `Classical.choice`.

Universe conventions match the rest of the development — everything lives in `Type u`, so no
`Cardinal.lift` appears.
-/
import Mathlib

universe u

open Cardinal DirectSum

namespace KappaMonoid

/-! ## A1: invariance of infinite rank -/

/-- **Assumed** (invariance of infinite rank).  Over a nontrivial ring, a free module with an
infinite basis cannot be generated by fewer elements than its rank.

Standard proof, not formalised here: every element of a generating set `S` has finite support in
the basis, so `S` lies in the span of a subfamily of the basis of cardinality at most `#S ⊔ ℵ₀`;
a basis element outside that subfamily would then lie in the span of the others, contradicting
linear independence.  Hence the subfamily is everything.

The conclusion is `#ι ≤ #S` with no `⊔ ℵ₀`: when `S` is finite the hypothesis is itself
contradictory, so nothing false is asserted, and the sharp form is what lets the application in
Example 2.13 avoid a case split.

This *generation* form, rather than the two-bases form `mk_eq_mk_of_infinite` below, is what the
application needs: the complement appearing in Example 2.13 is merely projective, not free, so
there is no second basis to compare against. -/
axiom mk_le_of_span_eq_top {R : Type u} [Ring R] [Nontrivial R] {M : Type u} [AddCommGroup M]
    [Module R M] {ι : Type u} (_b : Module.Basis ι R M) [Infinite ι] {S : Set M}
    (_hS : Submodule.span R S = ⊤) : #ι ≤ #S

/-- Invariance of infinite rank in its familiar form: two bases of the same module, one of them
infinite, have the same cardinality.  Derived from `mk_le_of_span_eq_top`. -/
theorem mk_eq_mk_of_infinite {R : Type u} [Ring R] [Nontrivial R] {M : Type u} [AddCommGroup M]
    [Module R M] {ι ι' : Type u} (b : Module.Basis ι R M) (b' : Module.Basis ι' R M) [Infinite ι] :
    #ι = #ι' := by
  have h₁ : #ι ≤ #(Set.range (b' : ι' → M)) := mk_le_of_span_eq_top b b'.span_eq
  have h₁' : #ι ≤ #ι' := h₁.trans (Cardinal.mk_range_le)
  -- `ι'` is infinite too, so the argument may be repeated with the roles exchanged
  haveI : Infinite ι' :=
    Cardinal.infinite_iff.mpr ((Cardinal.infinite_iff.mp ‹Infinite ι›).trans h₁')
  have h₂ : #ι' ≤ #(Set.range (b : ι → M)) := mk_le_of_span_eq_top b' b.span_eq
  exact le_antisymm h₁' (h₂.trans Cardinal.mk_range_le)

/-! ## A2: Leavitt's realisation theorem -/

/-- The congruence `∼_{m,n}` on `ℕ₀` defining the cyclic monoid `C_{m,n}`: `k` and `l` are
identified iff they are equal, or both are at least `m` and differ by a multiple of `n`. -/
def CyclicRel (m n k l : ℕ) : Prop := k = l ∨ (m ≤ k ∧ m ≤ l ∧ (n : ℤ) ∣ (k : ℤ) - l)

/-- A ring realising the cyclic monoid `C_{m,n}` as its monoid of finitely generated free
modules: `R^k ≅ R^l` exactly when `k ∼_{m,n} l`. -/
structure LeavittData (m n : ℕ) where
  /-- The realising ring. -/
  R : Type u
  [ring : Ring R]
  [nontrivial : Nontrivial R]
  /-- Isomorphism of finitely generated free modules is exactly `∼_{m,n}`. -/
  iso_iff : ∀ k l : ℕ,
    Nonempty ((⨁ _ : Fin k, R) ≃ₗ[R] (⨁ _ : Fin l, R)) ↔ CyclicRel m n k l

attribute [instance] LeavittData.ring LeavittData.nontrivial

/-- **Assumed** (Leavitt, 1962).  Every cyclic monoid `C_{m,n}` with `n ≥ 1` is the monoid of
finitely generated free modules over some ring.

The remaining cyclic monoid, `ℕ₀` itself, needs no axiom: every ring with invariant basis
number realises it. -/
axiom leavittData (m n : ℕ) (_hn : 1 ≤ n) : LeavittData.{u} m n

/-- **Assumed**: the classification of cyclic monoids.  A monoid generated by a single element
`u` is either free on `u` — so `n ↦ n • u` is injective, and the monoid is `ℕ₀` — or else it is
`C_{m,n}` for some `m ≥ 0`, `n ≥ 1`, meaning that `k • u = l • u` holds exactly when
`k ∼_{m,n} l`.

Standard proof, not formalised here: if `n ↦ n • u` is not injective, take the least `m` with
`m • u = l • u` for some `l > m`, and the least such `l`; then `n = l - m` and the relation
generated by `m ∼ m + n` is all of the kernel.

Mathlib has no classification of cyclic monoids (`IsCyclic` is about groups). -/
axiom cyclicMonoidClassification {M : Type u} [AddCommMonoid M] (u : M)
    (_hgen : ∀ x : M, ∃ n : ℕ, x = n • u) :
    (∀ k l : ℕ, k • u = l • u ↔ k = l) ∨
      ∃ m n : ℕ, 1 ≤ n ∧ ∀ k l : ℕ, k • u = l • u ↔ CyclicRel m n k l

/-! ## A3: uniqueness of the multiplicities of simple modules -/

/-- **Assumed**: in a decomposition into simple modules the multiplicity of each isomorphism
class is uniquely determined, infinite multiplicities included.

Jordan–Hölder gives the finite case; the infinite case is the classical cardinal-counting
extension.  Only *uniqueness* is assumed here — the companion existence statement, that every
module over a semisimple ring is a direct sum of simple modules, is available in Mathlib. -/
axiom mk_multiplicity_eq {R : Type u} [Ring R] {I J : Type u} {A : I → Type u} {B : J → Type u}
    [∀ i, AddCommGroup (A i)] [∀ i, Module R (A i)]
    [∀ j, AddCommGroup (B j)] [∀ j, Module R (B j)]
    (_hA : ∀ i, IsSimpleModule R (A i)) (_hB : ∀ j, IsSimpleModule R (B j))
    (_e : (⨁ i, A i) ≃ₗ[R] (⨁ j, B j)) (S : Type u) [AddCommGroup S] [Module R S] :
    #{i // Nonempty (A i ≃ₗ[R] S)} = #{j // Nonempty (B j ≃ₗ[R] S)}

/-! ## A5: the Bergman–Dicks realisation theorem -/

/-- A hereditary `k`-algebra realising a given reduced commutative monoid `M` as its monoid of
finitely generated projective modules.

`P a` is the module realising `a ∈ M`; the four conditions `iso_zero`, `iso_add`, `inj` and
`surj` say exactly that `a ↦ [P a]` is a monoid isomorphism `M ≅ V(R)`. -/
structure BergmanDicksData (k : Type u) [Field k] (M : Type u) [AddCommMonoid M] where
  /-- The realising algebra. -/
  R : Type u
  [ring : Ring R]
  [algebra : Algebra k R]
  /-- `R` is hereditary: every left ideal is projective. -/
  hereditary : ∀ I : Ideal R, Module.Projective R I
  /-- Every projective `R`-module is a direct sum of finitely generated ones.
  This is Corollary 4.6 for hereditary rings, and is bundled here because it too is a quoted
  result (Albrecht 1961; Bergman 1972) with no counterpart in Mathlib.  Its shape matches the
  hypothesis of `corollary_4_5_three` verbatim, so it plugs straight in. -/
  sumOfFG : ∀ (Q : Type u) (_ : AddCommGroup Q) (_ : Module R Q), Module.Projective R Q →
    ∃ (ι : Type u) (S : ι → Type u) (_ : ∀ i, AddCommGroup (S i)) (_ : ∀ i, Module R (S i)),
      (∀ i, Module.Projective R (S i)) ∧ (∀ i, Module.Finite R (S i)) ∧
        Nonempty (Q ≃ₗ[R] ⨁ i, S i)
  /-- The finitely generated projective module realising `a ∈ M`. -/
  P : M → Type u
  [addCommGroup : ∀ a, AddCommGroup (P a)]
  [module : ∀ a, Module R (P a)]
  proj : ∀ a, Module.Projective R (P a)
  fin : ∀ a, Module.Finite R (P a)
  /-- `P 0 = 0`. -/
  iso_zero : Subsingleton (P 0)
  /-- `P (a + b) ≅ P a ⊕ P b`. -/
  iso_add : ∀ a b, Nonempty (P (a + b) ≃ₗ[R] P a × P b)
  /-- `a ↦ [P a]` is injective. -/
  inj : ∀ a b, Nonempty (P a ≃ₗ[R] P b) → a = b
  /-- `a ↦ [P a]` is onto the finitely generated projectives. -/
  surj : ∀ (Q : Type u) (_ : AddCommGroup Q) (_ : Module R Q), Module.Projective R Q →
    Module.Finite R Q → ∃ a, Nonempty (Q ≃ₗ[R] P a)

attribute [instance] BergmanDicksData.ring BergmanDicksData.algebra
  BergmanDicksData.addCommGroup BergmanDicksData.module

/-- **Assumed** (Bergman 1974; Bergman–Dicks 1978).  For every field `k`, every reduced
commutative monoid with an order-unit is `V(R)` for a hereditary `k`-algebra `R`.

*Reduced* is the paper's term for conical: `a + b = 0` forces `a = 0`.  An *order-unit* is a `u`
such that every element divides some multiple of `u`.

The proof is a construction by universal localisation and is far out of reach here; Mathlib has
neither hereditary rings nor universal localisation.  The statement bundles the realisation
theorem with the hereditary case of Corollary 4.6 — see `BergmanDicksData.sumOfFG` — because both
are quoted results and Corollary 4.7(1) uses them together. -/
axiom bergmanDicksData (k : Type u) [Field k] (M : Type u) [AddCommMonoid M]
    (_hred : ∀ a b : M, a + b = 0 → a = 0)
    (_hunit : ∃ u : M, ∀ y : M, ∃ (z : M) (n : ℕ), y + z = n • u) :
    BergmanDicksData.{u} k M

end KappaMonoid
