/-
Section 2.3 of

  Zahra Nazemian and Daniel Smertnig,
  *A monoid-theoretical approach to infinite direct-sum decompositions of modules*,

first half: the `κ`-monoid `V^κ(𝓕^κ)` of free modules generated by at most `κ` elements.

This is a `ModuleClass` in the sense of Definition 2.4 — closed under isomorphism and `κ`-indexed
direct sums — but *not* closed under direct summands, a summand of a free module being merely
projective.  That is exactly why `ModuleClass.IsSummandClosed` is a separate class.

A free module generated by at most `κ` elements is `R^{(s)}` for a subset `s ⊆ Idx κ`, and the
isomorphism classes are those subsets modulo `R^{(s)} ≅ R^{(t)}`.  Ranks are indexed by subsets
rather than by cardinals because `ModuleClass.carrier` must live in `Type u`, whereas the
cardinals `≤ κ` live in `Type (u+1)`.
-/
import KappaMonoid.Modules
import KappaMonoid.Examples

universe u

open Cardinal Function Set DirectSum

namespace KappaMonoid

namespace FreeMod

variable (R : Type u) [Ring R] (κ : Cardinal.{u})

/-- The free module on a set of generators `s ⊆ Idx κ`. -/
abbrev ofSet (s : Set (Idx κ)) : Type u := ⨁ _ : s, R

/-- Two generating sets give the same class when the free modules on them are isomorphic. -/
def rankSetoid : Setoid (Set (Idx κ)) where
  r s t := Nonempty (ofSet R κ s ≃ₗ[R] ofSet R κ t)
  iseqv :=
    ⟨fun _ => ⟨LinearEquiv.refl R _⟩, fun ⟨e⟩ => ⟨e.symm⟩, fun ⟨e⟩ ⟨e'⟩ => ⟨e.trans e'⟩⟩

/-- `V^κ(𝓕^κ)`: the isomorphism classes of free modules generated by at most `κ` elements. -/
def Carrier : Type u := Quotient (rankSetoid R κ)

variable {R κ}

/-- The class of the free module on `s`. -/
def mk (s : Set (Idx κ)) : Carrier R κ := Quotient.mk (rankSetoid R κ) s

/-- A chosen generating set representing a class. -/
noncomputable def basis (a : Carrier R κ) : Set (Idx κ) := Quotient.out (s := rankSetoid R κ) a

theorem mk_eq_mk {s t : Set (Idx κ)} :
    (mk s : Carrier R κ) = mk t ↔ Nonempty (ofSet R κ s ≃ₗ[R] ofSet R κ t) :=
  Quotient.eq (r := rankSetoid R κ)

@[simp] theorem mk_basis (a : Carrier R κ) : (mk (basis a) : Carrier R κ) = a :=
  Quotient.out_eq (s := rankSetoid R κ) a

/-- The free module on the chosen basis of `mk s` is `R^{(s)}`. -/
theorem basis_mk_equiv (s : Set (Idx κ)) :
    Nonempty (ofSet R κ (basis (mk s : Carrier R κ)) ≃ₗ[R] ofSet R κ s) :=
  Quotient.mk_out (s := rankSetoid R κ) s

/-! ## The `κ`-indexed direct sum -/

variable (R κ)

/-- The disjoint union of `κ` many generating sets is still of size `≤ κ`. -/
theorem mk_sigma_basis_le (hκ : ℵ₀ ≤ κ) (f : Idx κ → Carrier R κ) :
    #((i : Idx κ) × ↥(basis (f i))) ≤ κ := by
  rw [Cardinal.mk_sigma]
  refine le_trans (Cardinal.sum_le_sum _ (fun _ => κ) fun i =>
    le_of_le_of_eq (Cardinal.mk_le_mk_of_subset (Set.subset_univ _))
      (by rw [Cardinal.mk_univ, mk_Idx])) ?_
  rw [Cardinal.sum_const', mk_Idx, Cardinal.mul_eq_self hκ]

/-- A generating set for the direct sum: a copy of the disjoint union of the pieces inside
`Idx κ`. -/
noncomputable def sumSet (hκ : ℵ₀ ≤ κ) (f : Idx κ → Carrier R κ) : Set (Idx κ) :=
  Set.range (emb (mk_sigma_basis_le R κ hκ f))

theorem sumSet_def (hκ : ℵ₀ ≤ κ) (f : Idx κ → Carrier R κ) :
    sumSet R κ hκ f = Set.range (emb (mk_sigma_basis_le R κ hκ f)) := rfl

/-- `R^{(⨿ᵢ sᵢ)}` is the direct sum of the `R^{(sᵢ)}`. -/
noncomputable def sumSetIso (hκ : ℵ₀ ≤ κ) (f : Idx κ → Carrier R κ) :
    ofSet R κ (sumSet R κ hκ f) ≃ₗ[R] ⨁ i : Idx κ, ofSet R κ (basis (f i)) :=
  (DirectSum.lequivCongrLeft R
      (Equiv.ofInjective _ (emb (mk_sigma_basis_le R κ hκ f)).injective).symm).trans
    (DirectSum.sigmaLcurryEquiv (R := R) (ι := Idx κ)
      (α := fun i => ↥(basis (f i))) (δ := fun _ _ => R))

/-! ## `V^κ(𝓕^κ)` as a class of modules -/

/-- **Definition 2.4(1)** for the class of free modules: `V^κ(𝓕^κ)`.

Note that this class carries *no* `ModuleClass.IsSummandClosed` instance, and cannot: a direct
summand of a free module is projective but need not be free.  That is what the split of
`ModuleClass` was for. -/
noncomputable def freeClass (hκ : ℵ₀ ≤ κ) : ModuleClass R κ where
  carrier := Carrier R κ
  rep a := ofSet R κ (basis a)
  addCommGroup _ := inferInstance
  module _ := inferInstance
  eq_of_iso := fun {a b} e => by
    rw [← mk_basis a, ← mk_basis b]
    exact mk_eq_mk.mpr ⟨e⟩
  zero := mk (∅ : Set (Idx κ))
  subsingleton_rep_zero := by
    haveI : IsEmpty ↥(∅ : Set (Idx κ)) := Set.isEmpty_coe_sort.mpr rfl
    haveI : Subsingleton (ofSet R κ (∅ : Set (Idx κ))) :=
      ⟨fun x y => DFinsupp.ext fun i => (IsEmpty.false i).elim⟩
    exact Equiv.subsingleton (basis_mk_equiv (∅ : Set (Idx κ))).some.toEquiv
  dsum f := mk (sumSet R κ hκ f)
  dsum_iso f :=
    ⟨((basis_mk_equiv (sumSet R κ hκ f)).some).trans (sumSetIso R κ hκ f)⟩

end FreeMod

end KappaMonoid
