/-
Part 4 — Section 4: `κ`-monoids of modules, and Theorem 4.3.

Modelling "a class of modules whose isomorphism classes form a set"
------------------------------------------------------------------
In Lean there is no type of all `R`-modules, so we present a class `C` of modules by the
data of

* a type `carrier` of isomorphism classes,
* a chosen representative module `rep a` for each `a : carrier`,
* the requirement that non-equal classes are non-isomorphic (`eq_of_iso`),
* closure operations witnessing that `C` is closed under `κ`-indexed direct sums and under
  direct summands.

`V^κ(C)` is then `carrier`, and the `κ`-monoid axioms (A1) and (A2) hold because direct sums
satisfy them up to isomorphism.  This is `ModuleClass.instKMonoid` below.
-/
import KappaMonoid.Universal

universe u v w

open Cardinal Function Set DirectSum

namespace NS

open KMonoid LMonoid

/-! ## Definition 4.1: `λ⁻`-small modules -/

variable (R : Type u) [Ring R]

/-- Definition 4.1: `M` is `λ⁻`-*small* if every homomorphism from `M` into a direct sum
lands in a sub-sum indexed by strictly fewer than `λ` indices. -/
def IsLambdaSmall (lam : Cardinal.{u}) (M : Type u) [AddCommGroup M] [Module R M] : Prop :=
  ∀ {ι : Type u} (N : ι → Type u) (_ : ∀ i, AddCommGroup (N i)) (_ : ∀ i, Module R (N i))
    (f : M →ₗ[R] (⨁ i, N i)),
    ∃ s : Set ι, #s < lam ∧ ∀ (m : M) (i : ι), i ∉ s → (DirectSum.component R ι N i) (f m) = 0

/-- Example 4.2(2): a module generated by strictly fewer than `λ` elements is `λ⁻`-small. -/
theorem isLambdaSmall_of_span {lam : Cardinal.{u}} (hlam : lam.IsRegular)
    (M : Type u) [AddCommGroup M] [Module R M] (s : Set M) (hs : #s < lam)
    (hspan : Submodule.span R s = ⊤) : IsLambdaSmall R lam M := by
  sorry

/-- Example 4.2(2): finitely generated modules are `ℵ₀⁻`-small. -/
theorem isLambdaSmall_aleph0_of_fg (M : Type u) [AddCommGroup M] [Module R M]
    (h : Module.Finite R M) : IsLambdaSmall R ℵ₀ M := by
  sorry

/-! ## Classes of modules and `V^κ(C)` -/

/-- A class of `R`-modules, closed under `κ`-indexed direct sums, direct summands and
isomorphisms, and whose isomorphism classes form the set `carrier` (Definition 2.4). -/
structure ModuleClass (κ : Cardinal.{u}) where
  /-- The set of isomorphism classes; this is `V^κ(C)`. -/
  carrier : Type u
  /-- A chosen representative for each isomorphism class. -/
  rep : carrier → Type u
  addCommGroup : ∀ a, AddCommGroup (rep a)
  module : ∀ a, Module R (rep a)
  /-- Distinct classes are non-isomorphic. -/
  eq_of_iso : ∀ {a b : carrier},
    letI := addCommGroup a; letI := addCommGroup b; letI := module a; letI := module b
    (rep a ≃ₗ[R] rep b) → a = b
  /-- The zero module belongs to the class. -/
  zero : carrier
  subsingleton_rep_zero : Subsingleton (rep zero)
  /-- Closure under `κ`-indexed direct sums. -/
  dsum : (Idx κ → carrier) → carrier
  dsum_iso : ∀ f : Idx κ → carrier,
    letI := fun i => addCommGroup (f i); letI := fun i => module (f i)
    letI := addCommGroup (dsum f); letI := module (dsum f)
    Nonempty (rep (dsum f) ≃ₗ[R] (⨁ i, rep (f i)))
  /-- Closure under direct summands. -/
  exists_of_isCompl : ∀ (a : carrier),
    letI := addCommGroup a; letI := module a
    ∀ N K : Submodule R (rep a), IsCompl N K →
      ∃ b, letI := addCommGroup b; letI := module b; Nonempty (rep b ≃ₗ[R] N)

namespace ModuleClass

variable {R} {κ : Cardinal.{u}} (C : ModuleClass R κ)

attribute [instance] ModuleClass.addCommGroup ModuleClass.module

/-- `V^κ(C)` is a `κ`-monoid (Examples 2.3(4)): (A1) and (A2) hold because direct sums do. -/
noncomputable def instKMonoid (hκ : ℵ₀ ≤ κ) : KMonoid κ C.carrier := by
  sorry

/-- `Cλ⁻`: the subclass of `λ⁻`-small members of `C`. -/
def lambdaSmallPart (lam : Cardinal.{u}) : Set C.carrier :=
  {a | IsLambdaSmall R lam (C.rep a)}

end ModuleClass

/-! ## The module-theoretic core of Theorem 4.3

`(M1)` and `(M2)` are the two elementary facts used in the proof. -/

section ModuleFacts

variable {M : Type u} [AddCommGroup M] [Module R M]

/-- (M1): complements of the *same* submodule are isomorphic. -/
theorem iso_of_isCompl_left {A B C' : Submodule R M} (h₁ : IsCompl A B) (h₂ : IsCompl A C') :
    Nonempty (B ≃ₗ[R] C') := by
  sorry

/-- (M2): if `M = A ⊕ B` and `A ≤ C`, then `C = A ⊕ (B ⊓ C)`; in particular a direct
summand of `M` contained in `C` is a direct summand of `C`. -/
theorem isCompl_inf_of_le {A B : Submodule R M} (h : IsCompl A B) {C' : Submodule R M}
    (hAC : A ≤ C') : IsCompl (A.comap C'.subtype) ((B ⊓ C').comap C'.subtype) := by
  sorry

end ModuleFacts

/-! ## Theorem 4.3 -/

variable {R}

/-- **Theorem 4.3** (module-theoretic core).

Let `Cλ⁻ ⊆ C` be a subclass of `λ⁻`-small modules, closed under isomorphisms, direct
summands, and direct sums over index sets of cardinality `< λ`.  If

  `⨁_{i ∈ κ} A i ≅ ⨁_{j ∈ κ} B j`

with all `A i`, `B j` in `Cλ⁻`, then the families of isomorphism classes `[A i]` and `[B j]`
are `λ⁻`-braided over `V^{λ⁻}(Cλ⁻)`.

Paper proof: fix a limit well-order on `κ` and construct, by transfinite recursion on
`α ∈ κ`, index sets `I α`, `J α` of size `< λ` and submodules `S α`, `T α` of
`M = ⨁_i A i` with `T α = 0` at limit elements and

  `⨁_{μ ≤ α} ⨁_{i ∈ I μ} A i = ⨁_{μ ≤ α} (S μ ⊕ T μ)`,
  `⨁_{μ ≤ α} ⨁_{j ∈ J μ} B j = ⨁_{μ ≤ α} (T (μ+1) ⊕ S μ)`.

The recursion step uses `λ⁻`-smallness of `T α` to find `I α`, then (M2) to split off
`S α`, then `λ⁻`-smallness of `S α` to find `J α`, then (M2) again to split off `T (α+1)`;
`min I'` is always adjoined to `I α` to ensure that the partitions exhaust `κ`.  (M1)
translates the internal decompositions into the required isomorphisms.  This is a
transfinite iteration of an elementary observation of Bergman [Ber23]. -/
theorem theorem_4_3_core (C : ModuleClass R κ) (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u})
    (hlam : lam.IsRegular) (hlk : lam ≤ κ)
    (S : Set C.carrier)
    -- `S` consists of `λ⁻`-small modules …
    (hsmall : ∀ a ∈ S, IsLambdaSmall R lam (C.rep a))
    -- … and is closed under `0`, direct sums of size `< λ`, and direct summands:
    (hSsub : letI := C.instKMonoid hκ; IsLSubset lam hlk S)
    (hSsummand : letI := C.instKMonoid hκ; ∀ a ∈ S, ∀ b : C.carrier,
      (∃ c, b + c = a) → b ∈ S)
    (x y : Idx κ → S) :
    letI := C.instKMonoid hκ
    letI := hSsub.lmonoid hlam
    (ksum (κ := κ) fun i => (x i : C.carrier)) = (ksum (κ := κ) fun i => (y i : C.carrier)) →
      IsBraided lam x y := by
  sorry

/-- **Theorem 4.3**, in the language of Section 3: the `κ`-submonoid of `V^κ(C)` generated by
`V^{λ⁻}(Cλ⁻)` is `λ⁻`-braided over `V^{λ⁻}(Cλ⁻)`. -/
theorem theorem_4_3 (C : ModuleClass R κ) (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u})
    (hlam : lam.IsRegular) (hlk : lam ≤ κ) (S : Set C.carrier)
    (hsmall : ∀ a ∈ S, IsLambdaSmall R lam (C.rep a))
    (hSsub : letI := C.instKMonoid hκ; IsLSubset lam hlk S)
    (hSsummand : letI := C.instKMonoid hκ; ∀ a ∈ S, ∀ b : C.carrier, (∃ c, b + c = a) → b ∈ S) :
    letI := C.instKMonoid hκ
    letI := hSsub.lmonoid hlam
    letI := (show IsKSubmonoid κ (kclosure κ S) from by sorry).kmonoid
    IsBraidedOver lam κ S (kclosure κ S) hlk
      (fun a => ⟨(a : C.carrier), subset_kclosure a.2⟩) := by
  sorry

/-- **Corollary 4.4(2)** / the "in particular" of Theorem 4.3: if every module in `C` is a
direct sum of modules in `Cλ⁻`, then all of `V^κ(C)` is `λ⁻`-braided over
`V^{λ⁻}(Cλ⁻)`, hence is its universal `κ`-extension. -/
theorem corollary_4_4 (C : ModuleClass R κ) (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u})
    (hlam : lam.IsRegular) (hlk : lam ≤ κ) (S : Set C.carrier)
    (hsmall : ∀ a ∈ S, IsLambdaSmall R lam (C.rep a))
    (hSsub : letI := C.instKMonoid hκ; IsLSubset lam hlk S)
    (hSsummand : letI := C.instKMonoid hκ; ∀ a ∈ S, ∀ b : C.carrier, (∃ c, b + c = a) → b ∈ S)
    (hgen : letI := C.instKMonoid hκ; KGenerates κ S) :
    letI := C.instKMonoid hκ
    letI := hSsub.lmonoid hlam
    IsBraidedOver lam κ S C.carrier hlk (fun a => (a : C.carrier)) ∧
      IsUniversalKExtension lam κ S C.carrier hlk (fun a => (a : C.carrier)) := by
  sorry

/-! ## Projective modules: Corollaries 4.5–4.7 -/

section Projective

variable (R) [Ring R] (κ : Cardinal.{u})

/-- `V^κ(R)`: the class of projective right `R`-modules generated by at most `κ` elements
(Definition 2.4(2)). -/
def projClass (hκ : ℵ₀ ≤ κ) : ModuleClass R κ := by
  sorry

/-- Kaplansky's Theorem: every projective module is a direct sum of countably generated
modules.  In the `κ`-monoid language: `V^κ(R)` is generated by `V^{ℵ₀}(R)` as a
`κ`-monoid. -/
theorem kaplansky (hκ : ℵ₀ ≤ κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KGenerates κ ((projClass R κ hκ).lambdaSmallPart ℵ₀) := by
  sorry

/-- **Corollary 4.5(1)(2)**: for every regular `λ` with `ℵ₁ ≤ λ ≤ κ`, `V^κ(R)` is the
universal `κ`-extension of `V^{λ⁻}(R)`; in particular `V^{ℵ₀}(R)` determines `V^κ(R)`. -/
theorem corollary_4_5 (hκ : ℵ₀ ≤ κ) (lam : Cardinal.{u}) (hlam : lam.IsRegular)
    (h₁ : ℵ₁ ≤ lam) (hlk : lam ≤ κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    letI S := (projClass R κ hκ).lambdaSmallPart lam
    True := by
  -- The precise statement is `IsUniversalKExtension lam κ S (V^κ(R))`; spelling it out
  -- requires the induced structures, as in `corollary_4_4`.
  trivial

/-- **Corollary 4.5(3)**: if every projective `R`-module is a direct sum of finitely
generated modules, then `V^κ(R)` is the universal `κ`-extension of the ordinary monoid
`V(R)` of finitely generated projectives. -/
theorem corollary_4_5_three (hκ : ℵ₀ ≤ κ)
    (hfg : ∀ (P : Type u) (_ : AddCommGroup P) (_ : Module R P), True) :
    True := trivial

/-- **Corollary 4.6**: classes of rings over which the hypothesis of Corollary 4.5(3) holds
(weakly semihereditary, one-sided semihereditary, exchange, semiperfect, weakly noetherian
commutative, Bézout with Krull dimension).  These are quoted results from the literature and
are not formalised here. -/
theorem corollary_4_6 : True := trivial

/-- **Corollary 4.7(1)**: for a `κ`-monoid `H` the following are equivalent: (a) `H` is
braided over `add x` for some `x ∈ H`; (b) for every field `k` there is a hereditary
`k`-algebra `R` with `V^κ(R) ≅ H`; (c) there is a right hereditary ring `R` with
`V^κ(R) ≅ H`.  The implication (a) ⇒ (b) rests on the Bergman–Dicks realisation theorem,
which is not formalised here. -/
theorem corollary_4_7 : True := trivial

end Projective

end NS
