/-
**Scaffolding for the unformalised part of Section 4** of

  Zahra Nazemian and Daniel Smertnig,
  *A monoid-theoretical approach to infinite direct-sum decompositions of modules*.

Every proof here is `sorry`.  The file is deliberately **not** imported by `KappaMonoid.lean`, so
`lake build` continues to check a `sorry`-free development; build it on its own with

    lake build KappaMonoid.Section4

Section 4 is formalised through Corollary 4.5.  What remains is Corollaries 4.6 and 4.7 — which
`Modules.lean` currently carries as documented `True := trivial` stubs — and the worked examples.
The important observation, and the reason this file exists, is that **Corollary 4.7(2) is fully
provable with what is already in the development**: it needs only Corollary 4.5(2), which is
proved, plus uniqueness of universal `κ`-extensions.  Corollary 4.7(1) rests on Bergman–Dicks
realisation, assumed as axiom A5 (`bergmanDicksData`), and Corollary 4.6 is Corollary 4.5(3)
together with six results quoted from the literature.

See `SECTION4-PLAN.md`.
-/
import KappaMonoid.Modules
import KappaMonoid.Free
import KappaMonoid.OrderUnit

universe u v

open Cardinal Function Set DirectSum

namespace KappaMonoid

/-! ## `add x` and `add_λ x`

For `x` in a `κ`-monoid, `add x` is the set of summands of multiples of `x` — the divisor-closed
submonoid generated by `x` — and `add_λ x` is the set of summands of `λ x`. -/

namespace KMonoid

variable {κ : Cardinal.{u}} {H : Type u} [KMonoid κ H]

/-- `add x`: the summands of the finite multiples of `x`. -/
def addOf (x : H) : Set H :=
  {y | ∃ (z : H) (n : ℕ), y + z = cmul (κ := κ) (n : Cardinal.{u})
    (le_trans (le_of_lt Cardinal.natCast_lt_aleph0) (aleph0_le (κ := κ) (H := H))) x}

/-- `add_λ x`: the summands of `λ x`, for an infinite `λ ≤ κ`. -/
def addOfCard {lam : Cardinal.{u}} (hlam : lam ≤ κ) (x : H) : Set H :=
  {y | ∃ z : H, y + z = cmul (κ := κ) lam hlam x}

/-- `add x` is a submonoid: it contains `0` and is closed under finite sums.  Stated as
`IsLSubset ℵ₀`, which is exactly closure under sums over index types of cardinality `< ℵ₀`, so
that the subtype picks up an `LMonoid ℵ₀` instance through `IsLSubset.lmonoid`. -/
theorem addOf_isLSubset (hκ : ℵ₀ ≤ κ) (x : H) : IsLSubset ℵ₀ hκ (addOf (κ := κ) x) := by
  sorry

/-- `add x` is divisor-closed: a summand of an element of `add x` is again in `add x`. -/
theorem addOf_isSaturated (x : H) :
    ∀ a ∈ addOf (κ := κ) x, ∀ b c : H, a = b + c → b ∈ addOf (κ := κ) x := by
  sorry

/-- `add_λ x` is a `λ⁻`-submonoid of `H`. -/
theorem addOfCard_isLSubset {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ κ) (x : H) :
    IsLSubset lam hlk (addOfCard hlk x) := by
  sorry

end KMonoid

/-! ## Corollary 4.6

Each of the six conditions — weakly semihereditary, one-sided semihereditary, exchange,
semiperfect, weakly noetherian commutative, Bézout with one-sided Krull dimension — implies that
every projective module is a direct sum of finitely generated modules, and the corollary then
follows from `corollary_4_5_three`, which is *proved*.

Those six implications are the quoted results (Bergman; Warfield; Mueller; Hinohara;
McGovern–Puninski–Rothmaler).  There is nothing further to formalise: Corollary 4.6 is exactly
`corollary_4_5_three` plus six citations, so the documented stub in `Modules.lean` is the right
treatment and this file adds nothing for it.  `EveryProjectiveIsSumOfFG` names the hypothesis so
that the six implications can be stated if that module theory ever lands in Mathlib. -/

/-- The property quoted from the literature for each of the six classes of Corollary 4.6. -/
def EveryProjectiveIsSumOfFG (R : Type u) [Ring R] : Prop :=
  ∀ (P : Type u) (_ : AddCommGroup P) (_ : Module R P), Module.Projective R P →
    ∃ (ι : Type u) (Q : ι → Type u) (_ : ∀ i, AddCommGroup (Q i)) (_ : ∀ i, Module R (Q i)),
      (∀ i, Module.Projective R (Q i)) ∧ (∀ i, Module.Finite R (Q i)) ∧
        Nonempty (P ≃ₗ[R] ⨁ i, Q i)

/-! ## Corollary 4.7

Part (2) is provable with what is already here.  Part (1) needs the Bergman–Dicks realisation
theorem, which is axiom A5 — `bergmanDicksData` in `KappaMonoid/Axioms.lean`. -/

section Cor47

variable {κ : Cardinal.{u}}

/-- **The engine of Corollary 4.7(2)**: two `κ`-monoids braided over the same `λ⁻`-monoid are
isomorphic.  Both are universal `κ`-extensions of it (Theorem 3.11(2)), and a universal
`κ`-extension is unique up to a unique isomorphism.

This needs no external input, and it is what makes Corollary 4.7(2) reachable now. -/
theorem isKIso_of_braidedOver_same {lam : Cardinal.{u}} {S : Type u} [LMonoid lam S]
    {H₁ H₂ : Type u} [KMonoid κ H₁] [KMonoid κ H₂] (hlk : lam ≤ κ)
    {f : S → H₁} {g : S → H₂}
    (hbr₁ : IsBraidedOver lam κ S H₁ hlk f) (hbr₂ : IsBraidedOver lam κ S H₂ hlk g) :
    ∃ e : H₁ → H₂, KMonoid.IsKHom κ e ∧ (∀ s, e (f s) = g s) ∧ Function.Bijective e := by
  sorry

/-- **Corollary 4.7(2)**: for a ring `R` and a `κ`-monoid `H`, if `H` is `ℵ₁⁻`-braided over a
`λ⁻`-monoid `S` and `V^{ℵ₀}(R)` is too — which is Corollary 4.5(2) — then `V^κ(R) ≅ H`.

The `S` of the paper is `add_{ℵ₀} x` for a suitable `x ∈ H`; the statement is given for a general
`S` because that is what the proof uses, and `addOfCard` supplies the paper's instance. -/
theorem corollary_4_7_two {S : Type u} [LMonoid ℵ₀ S] {H : Type u} [KMonoid κ H]
    (R : Type u) [Ring R] (hκ : ℵ₀ ≤ κ) {f : S → H}
    (hbr : IsBraidedOver ℵ₀ κ S H hκ f)
    {g : S → (projClass R κ hκ).carrier}
    (hbr' : letI := (projClass R κ hκ).instKMonoid hκ
      IsBraidedOver ℵ₀ κ S (projClass R κ hκ).carrier hκ g) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ e : H → (projClass R κ hκ).carrier,
      KMonoid.IsKHom κ e ∧ (∀ s, e (f s) = g s) ∧ Function.Bijective e := by
  sorry

/-- **Corollary 4.7(1)**, (iii) ⇒ (i): if `V^κ(R) ≅ H` for a ring `R` all of whose projectives
are direct sums of finitely generated modules — in particular a hereditary ring, by Corollary 4.6
— then `V^κ(R)` is `κ`-generated by `add [R]`, since `V(R) = add [R]`. -/
theorem corollary_4_7_one_backward (R : Type u) [Ring R] (hκ : ℵ₀ ≤ κ)
    (hfg : EveryProjectiveIsSumOfFG R) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ x : (projClass R κ hκ).carrier,
      KMonoid.KGenerates κ (KMonoid.addOf (κ := κ) x) := by
  sorry

/-- **Corollary 4.7(1)**, (i) ⇒ (ii), the direction that needs Bergman–Dicks (axiom A5).

Given `x ∈ H` with `H` braided over `add x`, and a field `k`, the monoid `add x` is reduced with
order-unit `x` — steps 1 and 2 of the plan — so A5 supplies a hereditary `k`-algebra `R` with
`V(R) ≅ add x`.  `BergmanDicksData.sumOfFG` feeds `corollary_4_5_three`, making `V^κ(R)` braided
over `V(R)`; `isKIso_of_braidedOver_same` then identifies `V^κ(R)` with `H`. -/
theorem corollary_4_7_one_forward {H : Type u} [KMonoid κ H] (hκ : ℵ₀ ≤ κ)
    (k : Type u) [Field k] (x : H)
    (hbr : letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0 (KMonoid.addOf_isLSubset hκ x)
      IsBraidedOver ℵ₀ κ ↥(KMonoid.addOf (κ := κ) x) H hκ (fun y => (y : H))) :
    ∃ (R : Type u) (_ : Ring R) (_ : Algebra k R) (hR : ∀ I : Ideal R, Module.Projective R I),
      letI := (projClass R κ hκ).instKMonoid hκ
      ∃ e : (projClass R κ hκ).carrier → H, KMonoid.IsKHom κ e ∧ Function.Bijective e := by
  sorry

end Cor47

/-! ## Example 4.8(1): ascent of KRSA

If every module in `C` is a direct sum of `λ⁻`-small ones and `V^{λ⁻}(C_{λ⁻})` is a *free*
`λ⁻`-monoid on `B`, then `V^κ(C)` is the free `κ`-monoid on `B`.  Theorem 4.3 makes `V^κ(C)`
`λ⁻`-braided over `V^{λ⁻}(C_{λ⁻})`, hence its universal `κ`-extension; Lemma 3.13(1) identifies
the universal `κ`-extension of `F_{λ⁻}(B)` as `F_κ(B)`; uniqueness finishes.

This is the one worked example of §4 that needs no literature — only Lemma 3.13(1) from the §3
scaffold. -/

section KRSA

variable {R : Type u} [Ring R] {κ : Cardinal.{u}}

/-- **Example 4.8(1)**: finite KRSA ascends to infinite KRSA. -/
theorem krsa_ascent (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ κ) (B : Type u)
    (hfree : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      letI := IsLSubset.lmonoid hlam (C.lambdaSmallPart_isLSubset hκ lam hlam hlk)
      ∃ e : ↥(C.lambdaSmallPart lam) → ↥(FreeL lam B),
        IsLMonoidHom lam e ∧ Function.Bijective e)
    (hbr : letI := C.instKMonoid hκ
      letI := IsLSubset.lmonoid hlam (C.lambdaSmallPart_isLSubset hκ lam hlam hlk)
      IsBraidedOver lam κ ↥(C.lambdaSmallPart lam) C.carrier hlk (fun a => (a : C.carrier))) :
    letI : Fact (Order.succ κ).IsRegular := ⟨Cardinal.isRegular_succ hκ⟩
    letI := C.instKMonoid hκ
    letI := instKMonoidFreeK κ hκ B
    ∃ e : C.carrier → ↥(FreeK κ B), KMonoid.IsKHom κ e ∧ Function.Bijective e := by
  sorry

end KRSA

end KappaMonoid
