/-
**Scaffolding for the unformalised part of Section 4** of

  Zahra Nazemian and Daniel Smertnig,
  *A monoid-theoretical approach to infinite direct-sum decompositions of modules*.

Every proof here is `sorry`.  The file is deliberately **not** imported by `KappaMonoid.lean`, so
`lake build` continues to check a `sorry`-free development; build it on its own with

    lake build KappaMonoid.Section4

Section 4 is formalised through Corollary 4.5.  What remains is Corollaries 4.6 and 4.7 — which
`Modules.lean` currently carries as documented `True := trivial` stubs — and the worked examples.
The important observation, and the reason this file exists, is that **Corollary 4.7(2) is fully
provable with what is already in the development**: it needs only Corollary 4.5(2), which is
proved, plus uniqueness of universal `κ`-extensions.  Corollary 4.7(1) rests on Bergman–Dicks
realisation, assumed as axiom A5 (`bergmanDicksData`), and Corollary 4.6 is Corollary 4.5(3)
together with six results quoted from the literature.

See `SECTION4-PLAN.md`.
-/
import KappaMonoid.Modules
import KappaMonoid.Free
import KappaMonoid.OrderUnit
import KappaMonoid.Section32

universe u v

open Cardinal Function Set DirectSum

namespace KappaMonoid

/-! ## `add x` and `add_λ x`

For `x` in a `κ`-monoid, `add x` is the set of summands of multiples of `x` — the divisor-closed
submonoid generated by `x` — and `add_λ x` is the set of summands of `λ x`. -/

namespace KMonoid

variable {κ : Cardinal.{u}} {H : Type u} [KMonoid κ H]

/-- `add x`: the summands of the finite multiples of `x`. -/
def addOf (x : H) : Set H :=
  {y | ∃ (z : H) (n : ℕ), y + z = cmul (κ := κ) (n : Cardinal.{u})
    (le_trans (le_of_lt Cardinal.natCast_lt_aleph0) (aleph0_le (κ := κ) (H := H))) x}

/-- `add_λ x`: the summands of `λ x`, for an infinite `λ ≤ κ`. -/
def addOfCard {lam : Cardinal.{u}} (hlam : lam ≤ κ) (x : H) : Set H :=
  {y | ∃ z : H, y + z = cmul (κ := κ) lam hlam x}

/-- `add x` is a submonoid: it contains `0` and is closed under finite sums.  Stated as
`IsLSubset ℵ₀`, which is exactly closure under sums over index types of cardinality `< ℵ₀`, so
that the subtype picks up an `LMonoid ℵ₀` instance through `IsLSubset.lmonoid`. -/
theorem addOf_isLSubset (hκ : ℵ₀ ≤ κ) (x : H) : IsLSubset ℵ₀ hκ (addOf (κ := κ) x) := by
  classical
  constructor
  · -- `0 = 0 + 0` is a summand of `0 · x`
    refine ⟨0, 0, ?_⟩
    rw [add_zero]
    exact ((cmul_congr (Nat.cast_zero (R := Cardinal.{u})) _
      (zero_le (a := κ)) x).trans (cmul_zero_cardinal x)).symm
  · -- add the witnesses: `Σ y i + Σ z i = Σ (n i) · x = (Σ n i) · x`
    intro ι hι y hy
    choose z n hzn using hy
    have hidx : #ι ≤ κ := hι.le.trans hκ
    have hlt : Cardinal.sum (fun i => ((n i : ℕ) : Cardinal.{u})) < ℵ₀ :=
      Cardinal.sum_lt_of_isRegular Cardinal.isRegular_aleph0 hι fun _ => Cardinal.natCast_lt_aleph0
    obtain ⟨m, hm⟩ := Cardinal.lt_aleph0.mp hlt
    have hmκ : ((m : ℕ) : Cardinal.{u}) ≤ κ :=
      le_trans (le_of_lt Cardinal.natCast_lt_aleph0) hκ
    refine ⟨sumOf (κ := κ) hidx z, m, ?_⟩
    rw [← sumOf_add hidx y z, funext hzn,
      ← cmul_sumOf_cardinal hidx (fun i => ((n i : ℕ) : Cardinal.{u}))
        (fun _ => le_trans (le_of_lt Cardinal.natCast_lt_aleph0) hκ) (le_trans hlt.le hκ) x]
    exact cmul_congr hm _ hmκ x

/-- `add x` is divisor-closed: a summand of an element of `add x` is again in `add x`. -/
theorem addOf_isSaturated (x : H) :
    ∀ a ∈ addOf (κ := κ) x, ∀ b c : H, a = b + c → b ∈ addOf (κ := κ) x := by
  rintro a ⟨z, n, hzn⟩ b c rfl
  exact ⟨c + z, n, by rw [← add_assoc]; exact hzn⟩

/-- `add_λ x` is a `λ⁻`-submonoid of `H`. -/
theorem addOfCard_isLSubset {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ κ) (x : H) :
    IsLSubset lam hlk (addOfCard hlk x) := by
  classical
  constructor
  · exact ⟨cmul (κ := κ) lam hlk x, zero_add _⟩
  · intro ι hι y hy
    choose z hz using hy
    have hidx : #ι ≤ κ := hι.le.trans hlk
    rcases isEmpty_or_nonempty ι with hemp | hne
    · -- an empty sum is `0`, which is a summand of `λ · x`
      haveI := hemp
      refine ⟨cmul (κ := κ) lam hlk x, ?_⟩
      rw [show sumOf (κ := κ) hidx y = 0 from LMonoid.lsumOf_isEmpty _ y, zero_add]
    · -- otherwise `#ι · λ = λ`, so the witnesses again add up to `λ · x`
      have hmk : #ι * lam = lam :=
        Cardinal.mul_eq_right hlam.aleph0_le hι.le (Cardinal.mk_ne_zero_iff.mpr hne)
      have hsum : Cardinal.sum (fun _ : ι => lam) = lam :=
        (Cardinal.sum_const' ι lam).trans hmk
      refine ⟨sumOf (κ := κ) hidx z, ?_⟩
      rw [← sumOf_add hidx y z, funext hz,
        ← cmul_sumOf_cardinal hidx (fun _ : ι => lam) (fun _ => hlk)
          (le_of_eq_of_le hsum hlk) x]
      exact cmul_congr hsum _ hlk x

end KMonoid

/-! ## `ℵ₀⁻`-small classes are finitely generated

The one module-theoretic input Corollary 4.7(1) needs beyond what `Modules.lean` has.  Both
directions of the corollary want to move between *finitely generated* projective modules — which is
what Bergman–Dicks realises and what `EveryProjectiveIsSumOfFG` produces — and the `ℵ₀⁻`-small
classes of `V^κ(R)`, which is the base Corollary 4.5(3) braids over.  Example 4.2(2) gives one
direction (finitely generated ⟹ `ℵ₀⁻`-small); this is the converse for a class of `V^κ(R)`.

The argument: `ℵ₀⁻`-smallness applied to the inclusion of the representative into `R^{(κ)}` confines
it to finitely many coordinates, so it lies in the span `N` of the corresponding finitely many
standard generators; the projection of `R^{(κ)}` onto the representative is then already surjective
on `N`, and a quotient of a finitely generated module is finitely generated. -/

section FgSmall

variable (R : Type u) [Ring R] (κ : Cardinal.{u})

open DirectSum

/-- An element of `R^{(κ)}` whose coordinates vanish off `s` lies in the span of the standard
generators indexed by `s`. -/
theorem mem_span_freeGen_of_component_eq_zero {x : freeMod R κ} {s : Set (Idx κ)}
    (h : ∀ i ∉ s, (DirectSum.component R (Idx κ) (fun _ => R) i) x = 0) :
    x ∈ Submodule.span R (freeGen R κ '' s) := by
  classical
  rw [← DFinsupp.sum_single (f := x)]
  refine Submodule.sum_mem _ fun i hi => ?_
  have hmem : i ∈ s := by
    by_contra hns
    exact (DFinsupp.mem_support_iff.mp hi) (h i hns)
  have hsingle : (DFinsupp.single i (x i) : freeMod R κ) = (x i) • freeGen R κ i := by
    show (DirectSum.lof R (Idx κ) (fun _ => R) i) (x i) = _
    rw [freeGen, ← LinearMap.map_smul]
    simp
  rw [hsingle]
  exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, hmem, rfl⟩)

/-- **An `ℵ₀⁻`-small summand of `R^{(κ)}` is finitely generated.** -/
theorem finite_of_isLambdaSmall_aleph0 (P : Summand R κ) (h : IsLambdaSmall R ℵ₀ ↥P.1) :
    Module.Finite R ↥P.1 := by
  classical
  -- `ℵ₀⁻`-smallness of the inclusion confines `P` to finitely many coordinates
  obtain ⟨s, hs, hzero⟩ := h (fun _ : Idx κ => R) (fun _ => inferInstance) (fun _ => inferInstance)
    P.1.subtype
  have hsfin : s.Finite := Cardinal.lt_aleph0_iff_set_finite.mp hs
  -- the span of the corresponding generators is finitely generated and contains `P`
  set N : Submodule R (freeMod R κ) := Submodule.span R (freeGen R κ '' s) with hNdef
  have hNfin : Module.Finite R ↥N := by
    rw [hNdef, show freeGen R κ '' s = ((hsfin.image (freeGen R κ)).toFinset : Set (freeMod R κ)) by
      rw [Set.Finite.coe_toFinset]]
    exact Module.Finite.span_finset R _
  have hPN : ∀ y : ↥P.1, (y : freeMod R κ) ∈ N :=
    fun y => mem_span_freeGen_of_component_eq_zero R κ fun i hi => hzero y i hi
  -- the projection of `R^{(κ)}` onto `P` is already surjective on that span
  set q : freeMod R κ →ₗ[R] ↥P.1 :=
    Submodule.projectionOnto P.1 (Summand.compl R κ P) (Summand.isCompl R κ P) with hqdef
  have hq : ∀ y : ↥P.1, q (y : freeMod R κ) = y := fun y =>
    congrFun (congrArg (fun f : ↥P.1 →ₗ[R] ↥P.1 => (f : ↥P.1 → ↥P.1))
      (Submodule.projectionOnto_comp_subtype (p := P.1) (q := Summand.compl R κ P)
        (h := Summand.isCompl R κ P))) y
  refine Module.Finite.of_surjective (q.comp N.subtype) fun y => ?_
  exact ⟨⟨(y : freeMod R κ), hPN y⟩, hq y⟩

end FgSmall

/-! ## Corollary 4.6

Each of the six conditions — weakly semihereditary, one-sided semihereditary, exchange,
semiperfect, weakly noetherian commutative, Bézout with one-sided Krull dimension — implies that
every projective module is a direct sum of finitely generated modules, and the corollary then
follows from `corollary_4_5_three`, which is *proved*.

Those six implications are the quoted results (Bergman; Warfield; Mueller; Hinohara;
McGovern–Puninski–Rothmaler).  There is nothing further to formalise: Corollary 4.6 is exactly
`corollary_4_5_three` plus six citations, so the documented stub in `Modules.lean` is the right
treatment and this file adds nothing for it.  `EveryProjectiveIsSumOfFG` names the hypothesis so
that the six implications can be stated if that module theory ever lands in Mathlib. -/

/-- The property quoted from the literature for each of the six classes of Corollary 4.6. -/
def EveryProjectiveIsSumOfFG (R : Type u) [Ring R] : Prop :=
  ∀ (P : Type u) (_ : AddCommGroup P) (_ : Module R P), Module.Projective R P →
    ∃ (ι : Type u) (Q : ι → Type u) (_ : ∀ i, AddCommGroup (Q i)) (_ : ∀ i, Module R (Q i)),
      (∀ i, Module.Projective R (Q i)) ∧ (∀ i, Module.Finite R (Q i)) ∧
        Nonempty (P ≃ₗ[R] ⨁ i, Q i)

/-! ## Corollary 4.7

Part (2) is provable with what is already here.  Part (1) needs the Bergman–Dicks realisation
theorem, which is axiom A5 — `bergmanDicksData` in `KappaMonoid/Axioms.lean`. -/

section Cor47

variable {κ : Cardinal.{u}}

/-- **The engine of Corollary 4.7(2)**: two `κ`-monoids braided over the same `λ⁻`-monoid are
isomorphic.  Both are universal `κ`-extensions of it (Theorem 3.11(2)), and a universal
`κ`-extension is unique up to a unique isomorphism.

This needs no external input, and it is what makes Corollary 4.7(2) reachable now. -/
theorem isKIso_of_braidedOver_same {lam : Cardinal.{u}} {S : Type u} [LMonoid lam S]
    {H₁ H₂ : Type u} [KMonoid κ H₁] [KMonoid κ H₂] (hlk : lam ≤ κ)
    {f : S → H₁} {g : S → H₂}
    (hbr₁ : IsBraidedOver lam κ S H₁ hlk f) (hbr₂ : IsBraidedOver lam κ S H₂ hlk g) :
    ∃ e : H₁ → H₂, KMonoid.IsKHom κ e ∧ (∀ s, e (f s) = g s) ∧ Function.Bijective e :=
  (isUniversalKExtension_unique hlk (hbr₁.isUniversalKExtension hlk)
    (hbr₂.isUniversalKExtension hlk)).exists

/-- **Corollary 4.7(2)**: for a ring `R` and a `κ`-monoid `H`, if `H` is `ℵ₁⁻`-braided over a
`λ⁻`-monoid `S` and `V^{ℵ₀}(R)` is too — which is Corollary 4.5(2) — then `V^κ(R) ≅ H`.

The `S` of the paper is `add_{ℵ₀} x` for a suitable `x ∈ H`; the statement is given for a general
`S` because that is what the proof uses, and `addOfCard` supplies the paper's instance. -/
theorem corollary_4_7_two {S : Type u} [LMonoid ℵ₀ S] {H : Type u} [KMonoid κ H]
    (R : Type u) [Ring R] (hκ : ℵ₀ ≤ κ) {f : S → H}
    (hbr : IsBraidedOver ℵ₀ κ S H hκ f)
    {g : S → (projClass R κ hκ).carrier}
    (hbr' : letI := (projClass R κ hκ).instKMonoid hκ
      IsBraidedOver ℵ₀ κ S (projClass R κ hκ).carrier hκ g) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ e : H → (projClass R κ hκ).carrier,
      KMonoid.IsKHom κ e ∧ (∀ s, e (f s) = g s) ∧ Function.Bijective e := by
  letI := (projClass R κ hκ).instKMonoid hκ
  exact isKIso_of_braidedOver_same hκ hbr hbr'

/-- **Corollary 4.7(1)**, (iii) ⇒ (i): if `V^κ(R) ≅ H` for a ring `R` all of whose projectives
are direct sums of finitely generated modules — in particular a hereditary ring, by Corollary 4.6
— then `V^κ(R)` is `κ`-generated by `add [R]`, since `V(R) = add [R]`. -/
theorem corollary_4_7_one_backward (R : Type u) [Ring R] (hκ : ℵ₀ ≤ κ)
    (hfg : EveryProjectiveIsSumOfFG R) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ x : (projClass R κ hκ).carrier,
      KMonoid.KGenerates κ (KMonoid.addOf (κ := κ) x) := by
  sorry

/-- **Corollary 4.7(1)**, (i) ⇒ (ii), the direction that needs Bergman–Dicks (axiom A5).

Given `x ∈ H` with `H` braided over `add x`, and a field `k`, the monoid `add x` is reduced with
order-unit `x` — steps 1 and 2 of the plan — so A5 supplies a hereditary `k`-algebra `R` with
`V(R) ≅ add x`.  `BergmanDicksData.sumOfFG` feeds `corollary_4_5_three`, making `V^κ(R)` braided
over `V(R)`; `isKIso_of_braidedOver_same` then identifies `V^κ(R)` with `H`. -/
theorem corollary_4_7_one_forward {H : Type u} [KMonoid κ H] (hκ : ℵ₀ ≤ κ)
    (k : Type u) [Field k] (x : H)
    (hbr : letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0 (KMonoid.addOf_isLSubset hκ x)
      IsBraidedOver ℵ₀ κ ↥(KMonoid.addOf (κ := κ) x) H hκ (fun y => (y : H))) :
    ∃ (R : Type u) (_ : Ring R) (_ : Algebra k R) (hR : ∀ I : Ideal R, Module.Projective R I),
      letI := (projClass R κ hκ).instKMonoid hκ
      ∃ e : (projClass R κ hκ).carrier → H, KMonoid.IsKHom κ e ∧ Function.Bijective e := by
  sorry

end Cor47

/-! ## Example 4.8(1): ascent of KRSA

If every module in `C` is a direct sum of `λ⁻`-small ones and `V^{λ⁻}(C_{λ⁻})` is a *free*
`λ⁻`-monoid on `B`, then `V^κ(C)` is the free `κ`-monoid on `B`.  Theorem 4.3 makes `V^κ(C)`
`λ⁻`-braided over `V^{λ⁻}(C_{λ⁻})`, hence its universal `κ`-extension (Theorem 3.11(2)), and
transporting that along the isomorphism of bases says exactly that `V^κ(C)` is the universal
`κ`-extension of `F_{λ⁻}(B)`.

**A universe remark on the statement.**  One would like to conclude `V^κ(C) ≅ F_κ(B)` by combining
this with Lemma 3.13(1) and uniqueness.  That comparison is not available: `F_κ(B)` is cut out of
`B → F_κ` and so lives in `Type (u+1)`, while `V^κ(C)` lives in `Type u`, and
`isUniversalKExtension_unique` — like the universal property itself, which quantifies over test
objects in the *same* universe as the extension — compares two extensions in one universe only.
The universal property below is the universe-correct form of "is the free `κ`-monoid on `B`", and
composing it with the `λ⁻`-level universal property of `F_{λ⁻}(B)` (`Free.exists_unique_lift`,
whose target universe *is* free) recovers the usual `B`-indexed formulation. -/

section KRSA

variable {R : Type u} [Ring R] {κ : Cardinal.{u}}

/-- **Example 4.8(1)**: finite KRSA ascends to infinite KRSA — if `V^{λ⁻}(C_{λ⁻})` is free on `B`,
then `V^κ(C)` is the universal `κ`-extension of the free `λ⁻`-monoid on `B`. -/
theorem krsa_ascent (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ κ) (B : Type u)
    (hfree : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      letI := IsLSubset.lmonoid hlam (C.lambdaSmallPart_isLSubset hκ lam hlam hlk)
      ∃ e : ↥(C.lambdaSmallPart lam) → ↥(FreeL lam B),
        IsLMonoidHom lam e ∧ Function.Bijective e)
    (hbr : letI := C.instKMonoid hκ
      letI := IsLSubset.lmonoid hlam (C.lambdaSmallPart_isLSubset hκ lam hlam hlk)
      IsBraidedOver lam κ ↥(C.lambdaSmallPart lam) C.carrier hlk (fun a => (a : C.carrier))) :
    letI : Fact lam.IsRegular := ⟨hlam⟩
    letI := C.instKMonoid hκ
    ∃ f : ↥(FreeL lam B) → C.carrier,
      IsUniversalKExtension lam κ ↥(FreeL lam B) C.carrier hlk f := by
  letI : Fact lam.IsRegular := ⟨hlam⟩
  letI := C.instKMonoid hκ
  letI := IsLSubset.lmonoid hlam (C.lambdaSmallPart_isLSubset hκ lam hlam hlk)
  classical
  obtain ⟨e, hehom, hebij⟩ := hfree
  -- the inverse of the isomorphism of bases is again a `λ⁻`-homomorphism
  set e' : ↥(FreeL lam B) → ↥(C.lambdaSmallPart lam) := Function.invFun e with he'def
  have hee' : ∀ a, e' (e a) = a := Function.leftInverse_invFun hebij.injective
  have he'e : ∀ b, e (e' b) = b := fun b => Function.invFun_eq (hebij.surjective b)
  have he'hom : IsLMonoidHom lam e' := hehom.inv hee' he'e
  -- `V^κ(C)` is the universal `κ`-extension of `V^{λ⁻}(C_{λ⁻})`, hence of `F_{λ⁻}(B)`
  refine ⟨fun b => ((e' b : ↥(C.lambdaSmallPart lam)) : C.carrier), ?_⟩
  exact IsUniversalKExtension.of_base_iso hlk (hbr.isUniversalKExtension hlk) e' e he'hom hehom
    he'e hee'

/-- The `B`-indexed form: `V^κ(C)` has the universal property of the free `κ`-monoid on `B`.  Every
map from `B` into a `κ`-monoid extends uniquely along the generators `ι(b)`. -/
theorem krsa_ascent_free (C : ModuleClass R κ) [C.IsSummandClosed] (hκ : ℵ₀ ≤ κ)
    {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ κ) (B : Type u)
    {f : letI : Fact lam.IsRegular := ⟨hlam⟩; ↥(FreeL lam B) → C.carrier}
    (huniv : letI : Fact lam.IsRegular := ⟨hlam⟩
      letI := C.instKMonoid hκ
      IsUniversalKExtension lam κ ↥(FreeL lam B) C.carrier hlk f) :
    letI : Fact lam.IsRegular := ⟨hlam⟩
    letI := C.instKMonoid hκ
    ∀ (K : Type u) [KMonoid κ K] (g : B → K),
      ∃! ψ : C.carrier → K, KMonoid.IsKHom κ ψ ∧ ∀ b, ψ (f (iota b)) = g b := by
  letI : Fact lam.IsRegular := ⟨hlam⟩
  letI := C.instKMonoid hκ
  intro K _ g
  letI := KMonoid.toLMonoidOfLE K hlam hlk
  -- lift `g` to the free `λ⁻`-monoid, then extend along the universal property
  have hlift : LMonoid.IsLHom hlk (lift (lam := lam) g) :=
    isLHom_of_isLMonoidHom hlam hlk (isLMonoidHom_lift (lam := lam) g)
  obtain ⟨ψ, ⟨hψhom, hψ⟩, hψu⟩ := huniv.universal K (lift (lam := lam) g) hlift
  refine ⟨ψ, ⟨hψhom, fun b => ?_⟩, fun ψ' ⟨hψ'hom, hψ'⟩ => ?_⟩
  · rw [hψ (iota b), lift_iota]
  refine hψu ψ' ⟨hψ'hom, fun x => ?_⟩
  -- two extensions agreeing on the generators agree, by uniqueness at the `λ⁻` level
  have hcomp0 : LMonoid.IsLHom hlk (fun y : ↥(FreeL lam B) => ψ' (f y)) := by
    refine ⟨by show ψ' (f 0) = 0; rw [huniv.isLHom.1, hψ'hom.1], fun {ι} hι y => ?_⟩
    show ψ' (f (LMonoid.lsumOf hι y)) = _
    rw [huniv.isLHom.2 hι y, hψ'hom.map_sumOf (hι.le.trans hlk) (f ∘ y)]
    rfl
  have hcomp : IsLMonoidHom lam (fun y : ↥(FreeL lam B) => ψ' (f y)) :=
    isLMonoidHom_of_isLHom hlam hlk hcomp0
  have heq : (fun y : ↥(FreeL lam B) => ψ' (f y)) = lift (lam := lam) g :=
    hom_ext (lam := lam) hcomp (isLMonoidHom_lift (lam := lam) g)
      fun b => by show ψ' (f (iota b)) = lift g (iota b); rw [hψ' b, lift_iota]
  exact congrFun heq x

end KRSA

end KappaMonoid
