/-
**Examples 3.3(3)**: `ℚ≥0 ∪ ℝ̃>0 ∪ {∞}` is `ℵ₀⁻`-braided over `ℚ≥0`.
-/
import KappaMonoid.Examples.Reals

universe u

open Cardinal Function Set
open scoped NNReal

namespace KappaMonoid

/-- **Examples 3.3(3)**: the `ℵ₀`-monoid `ℚ≥0 ∪ ℝ̃>0 ∪ {∞}` — the plain rationals, every tilded
positive real, and `∞`, inside `H = ℝ≥0 ∪ ℝ̃>0 ∪ {∞}` — is `ℵ₀⁻`-braided over `ℚ≥0`.

Paper proof: `H` is `ℵ₀⁻`-braided over `ℝ≥0` (Examples 3.3(2)) and `ℚ≥0` is a saturated
submonoid of `ℝ≥0`, so the braidings of families in `ℚ≥0` can be taken inside `ℚ≥0` (the proof of
Lemma 3.14(2)); and the `ℵ₀`-submonoid generated by `ℚ≥0` is `ℚ≥0 ∪ ℝ̃>0 ∪ {∞}`
(`kclosure_ofReal_ratSet`).  The universal-extension form is `isUniversalKExtension_ratSet`. -/
theorem isBraidedOver_ratReachable :
    letI := LMonoid.ofAddCommMonoid ℝ≥0
    letI : KMonoid (ℵ₀ : Cardinal.{u}) RTilde := RTilde.instKMonoid
    letI := (isLSubmonoid_ratSet : IsLSubmonoid (ℵ₀ : Cardinal.{u}) ratSet).lmonoid
    letI := (isKSubmonoid_ratReachable : KMonoid.IsKSubmonoid (ℵ₀ : Cardinal.{u})
      ratReachable).kmonoid
    IsBraidedOver (ℵ₀ : Cardinal.{u}) ℵ₀ ↥ratSet ↥ratReachable (Order.le_succ ℵ₀)
      (fun s => ⟨RTilde.ofReal (s : ℝ≥0), Or.inr (Or.inr ⟨(s : ℝ≥0), s.2, rfl⟩)⟩) := by
  let := LMonoid.ofAddCommMonoid ℝ≥0
  let : KMonoid (ℵ₀ : Cardinal.{u}) RTilde := RTilde.instKMonoid
  exact isBraidedOver_of_isLSubmonoid (Order.le_succ ℵ₀) RTilde.isBraidedOver_rtilde ratSet
    isLSubmonoid_ratSet (Or.inr isSaturated_ratSet) isKSubmonoid_ratReachable
    (fun s hs => Or.inr (Or.inr ⟨s, hs, rfl⟩)) (kclosure_ofReal_ratSet.symm ▸ subset_rfl)

end KappaMonoid
