/-
**The classification of cyclic monoids.**

For an element `u` of a commutative monoid, the map `n ↦ n • u` is either injective — the submonoid
generated by `u` is free, that is `ℕ₀` — or else the kernel is the congruence `∼_{m,n}` of the
cyclic monoid `C_{m,n}`: `k ∼ l` iff `k = l`, or both are at least `m` and `n ∣ k - l`.

Mathlib has no classification of cyclic monoids — `IsCyclic` is about groups — and this was assumed
as axiom A4 of this development until proved here.

Paper proof.  Suppose `n ↦ n • u` is not injective.  Let `m` be least such that `m • u = (m + d) • u`
for some `d ≥ 1`, and `n` least with `m • u = (m + n) • u`.  Everything then follows from two
observations about `N = {d | m • u = (m + d) • u}`:

* `N` is closed under differences — add `d' - d` to `m • u = (m + d) • u` — and contains `n`, so
  by division with remainder and the minimality of `n` it is exactly the multiples of `n`;
* an equality `k • u = (k + d) • u` above `m` descends to `m`: push `m` up past `k` along a multiple
  `n * k` of `n`, where the equality applies, and come back down.

The first is what makes `N` the multiples of `n` rather than merely a submonoid of `ℕ` containing
`n`, which is where the argument would otherwise fail.
-/
import Mathlib.Algebra.Group.Defs
import Mathlib.Data.Nat.Find
import Mathlib.Data.Int.Basic
import Mathlib.GroupTheory.Congruence.Defs
import Mathlib.Algebra.Ring.Int.Defs
import Mathlib.Algebra.Ring.Divisibility.Basic
import Mathlib.Algebra.Group.Nat.Defs
import Mathlib.Algebra.Group.ULift

universe u

/-- The congruence `∼_{m,n}` on `ℕ₀` defining the cyclic monoid `C_{m,n}`: `k` and `l` are
identified iff they are equal, or both are at least `m` and differ by a multiple of `n`. -/
def CyclicRel (m n k l : ℕ) : Prop := k = l ∨ (m ≤ k ∧ m ≤ l ∧ (n : ℤ) ∣ (k : ℤ) - l)

/-! ## Divisibility bookkeeping -/

/-- The difference in `CyclicRel` may be taken in either order. -/
theorem natCast_dvd_sub_comm {n k l : ℕ} : ((n : ℤ) ∣ (k : ℤ) - l) ↔ ((n : ℤ) ∣ (l : ℤ) - k) := by
  rw [← Int.natAbs_dvd_natAbs, ← Int.natAbs_dvd_natAbs (a := (n : ℤ)) (b := (l : ℤ) - k),
    show ((k : ℤ) - l).natAbs = ((l : ℤ) - k).natAbs by omega]

/-- Below the diagonal the integer divisibility of `CyclicRel` is a divisibility of naturals. -/
theorem natCast_dvd_sub_iff {n k l : ℕ} (h : k ≤ l) : ((n : ℤ) ∣ (k : ℤ) - l) ↔ n ∣ l - k := by
  rw [← Int.natAbs_dvd_natAbs, Int.natAbs_natCast, show ((k : ℤ) - l).natAbs = l - k by omega]

theorem CyclicRel.symm {m n k l : ℕ} (h : CyclicRel m n k l) : CyclicRel m n l k := by
  obtain rfl | ⟨hk, hl, hd⟩ := h
  · exact Or.inl rfl
  · exact Or.inr ⟨hl, hk, natCast_dvd_sub_comm.mp hd⟩

/-! ## `C_{m,n}` as a monoid

`∼_{m,n}` is an additive congruence on `ℕ`, so the cyclic monoid it defines is a quotient monoid.
This is what gets handed to a realisation theorem, which wants a monoid rather than a relation. -/

theorem CyclicRel.refl (m n k : ℕ) : CyclicRel m n k k := Or.inl rfl

theorem CyclicRel.trans {m n a b c : ℕ} (hab : CyclicRel m n a b) (hbc : CyclicRel m n b c) :
    CyclicRel m n a c := by
  obtain rfl | ⟨ha, hb, hd⟩ := hab
  · exact hbc
  obtain rfl | ⟨hb', hc, hd'⟩ := hbc
  · exact Or.inr ⟨ha, hb, hd⟩
  refine Or.inr ⟨ha, hc, ?_⟩
  have h := dvd_add hd hd'
  rwa [sub_add_sub_cancel] at h

theorem CyclicRel.add {m n a b c d : ℕ} (hab : CyclicRel m n a b) (hcd : CyclicRel m n c d) :
    CyclicRel m n (a + c) (b + d) := by
  obtain rfl | ⟨ha, hb, hd⟩ := hab
  · obtain rfl | ⟨hc, hd, hdd⟩ := hcd
    · exact Or.inl rfl
    · exact Or.inr ⟨by omega, by omega, by push_cast; rwa [add_sub_add_left_eq_sub]⟩
  · obtain rfl | ⟨hc, hd', hdd⟩ := hcd
    · exact Or.inr ⟨by omega, by omega, by push_cast; rwa [add_sub_add_right_eq_sub]⟩
    · refine Or.inr ⟨by omega, by omega, ?_⟩
      push_cast
      rw [← sub_add_sub_comm]
      exact dvd_add hd hdd

/-- `∼_{m,n}` as an additive congruence on `ℕ`. -/
def cyclicCon (m n : ℕ) : AddCon ℕ where
  r := CyclicRel m n
  iseqv := ⟨CyclicRel.refl m n, CyclicRel.symm, CyclicRel.trans⟩
  add' := CyclicRel.add

/-- **The cyclic monoid `C_{m,n}`**: `ℕ₀` modulo `∼_{m,n}`. -/
abbrev CyclicMonoid (m n : ℕ) : Type := (cyclicCon m n).Quotient

/-- The class of `k` in `C_{m,n}`. -/
def CyclicMonoid.mk (m n : ℕ) (k : ℕ) : CyclicMonoid m n := (cyclicCon m n).toQuotient k

@[simp] theorem CyclicMonoid.mk_eq_mk_iff {m n k l : ℕ} :
    CyclicMonoid.mk m n k = CyclicMonoid.mk m n l ↔ CyclicRel m n k l :=
  AddCon.eq _

theorem CyclicMonoid.mk_add (m n k l : ℕ) :
    CyclicMonoid.mk m n (k + l) = CyclicMonoid.mk m n k + CyclicMonoid.mk m n l := rfl

/-- Every class is a multiple of the class of `1`, which is therefore an order-unit. -/
theorem CyclicMonoid.nsmul_mk_one (m n k : ℕ) :
    k • CyclicMonoid.mk m n 1 = CyclicMonoid.mk m n k := by
  induction k with
  | zero => rfl
  | succ k ih => rw [succ_nsmul, ih, ← CyclicMonoid.mk_add]

theorem CyclicMonoid.surjective_mk (m n : ℕ) (y : CyclicMonoid m n) :
    ∃ k : ℕ, y = CyclicMonoid.mk m n k :=
  Quotient.inductionOn y fun k => ⟨k, rfl⟩

/-- `C_{m,n}` is conical for `m ≥ 1`: nothing but `0` is a summand of `0`.  This is where `m ≥ 1`
is needed — `C_{0,n}` is a group. -/
theorem CyclicMonoid.eq_zero_of_add_eq_zero {m n : ℕ} (hm : 1 ≤ m) (a b : CyclicMonoid m n)
    (h : a + b = 0) : a = 0 := by
  obtain ⟨k, rfl⟩ := CyclicMonoid.surjective_mk m n a
  obtain ⟨l, rfl⟩ := CyclicMonoid.surjective_mk m n b
  rw [← CyclicMonoid.mk_add] at h
  have h0 : CyclicMonoid.mk m n 0 = 0 := rfl
  rw [← h0, CyclicMonoid.mk_eq_mk_iff] at h ⊢
  obtain h | ⟨-, h2, -⟩ := h
  · exact Or.inl (by omega)
  · omega

/-- `0 ≠ 1` in `C_{m,n}` for `m ≥ 1`: the monoid is not trivial. -/
theorem CyclicMonoid.mk_one_ne_zero {m n : ℕ} (hm : 1 ≤ m) :
    CyclicMonoid.mk m n 1 ≠ CyclicMonoid.mk m n 0 := by
  rw [Ne, CyclicMonoid.mk_eq_mk_iff]
  rintro (h | ⟨-, h2, -⟩) <;> omega

/-! ## `C_{m,n}` in an arbitrary universe

A realisation theorem wants the monoid in the universe of the ring it produces, and the quotient of
`ℕ` lives in `Type 0`. -/

/-- `C_{m,n}`, lifted to `Type u`. -/
abbrev CyclicMonoidU (m n : ℕ) : Type u := ULift.{u} (CyclicMonoid m n)

/-- The class of `k` in the lifted `C_{m,n}`. -/
def CyclicMonoidU.mk (m n k : ℕ) : CyclicMonoidU.{u} m n := ULift.up (CyclicMonoid.mk m n k)

@[simp] theorem CyclicMonoidU.mk_eq_mk_iff {m n k l : ℕ} :
    CyclicMonoidU.mk.{u} m n k = CyclicMonoidU.mk.{u} m n l ↔ CyclicRel m n k l := by
  rw [CyclicMonoidU.mk, CyclicMonoidU.mk, ULift.up_inj, CyclicMonoid.mk_eq_mk_iff]

theorem CyclicMonoidU.zero_def (m n : ℕ) :
    (0 : CyclicMonoidU.{u} m n) = CyclicMonoidU.mk m n 0 := rfl

theorem CyclicMonoidU.mk_add (m n k l : ℕ) :
    CyclicMonoidU.mk.{u} m n (k + l) = CyclicMonoidU.mk m n k + CyclicMonoidU.mk m n l := rfl

/-- The class of `1` is an order-unit: every class is a multiple of it. -/
theorem CyclicMonoidU.nsmul_mk_one (m n : ℕ) :
    ∀ k : ℕ, k • CyclicMonoidU.mk.{u} m n 1 = CyclicMonoidU.mk m n k
  | 0 => rfl
  | (k + 1) => by rw [succ_nsmul, CyclicMonoidU.nsmul_mk_one m n k, ← CyclicMonoidU.mk_add]

theorem CyclicMonoidU.surjective_mk (m n : ℕ) (y : CyclicMonoidU.{u} m n) :
    ∃ k : ℕ, y = CyclicMonoidU.mk m n k := by
  obtain ⟨y⟩ := y
  obtain ⟨k, hk⟩ := CyclicMonoid.surjective_mk m n y
  exact ⟨k, congrArg ULift.up hk⟩

/-- Conical for `m ≥ 1`, which is what a realisation theorem needs. -/
theorem CyclicMonoidU.eq_zero_of_add_eq_zero {m n : ℕ} (hm : 1 ≤ m) (a b : CyclicMonoidU.{u} m n)
    (h : a + b = 0) : a = 0 := by
  obtain ⟨k, rfl⟩ := CyclicMonoidU.surjective_mk m n a
  obtain ⟨l, rfl⟩ := CyclicMonoidU.surjective_mk m n b
  rw [← CyclicMonoidU.mk_add, CyclicMonoidU.zero_def, CyclicMonoidU.mk_eq_mk_iff] at h
  rw [CyclicMonoidU.zero_def, CyclicMonoidU.mk_eq_mk_iff]
  obtain h | ⟨-, h2, -⟩ := h
  · exact Or.inl (by omega)
  · omega

theorem CyclicMonoidU.mk_one_ne_zero {m n : ℕ} (hm : 1 ≤ m) :
    CyclicMonoidU.mk.{u} m n 1 ≠ 0 := by
  rw [CyclicMonoidU.zero_def, Ne, CyclicMonoidU.mk_eq_mk_iff]
  rintro (h | ⟨-, h2, -⟩) <;> omega

/-! ## The kernel of `n ↦ n • u` -/

section Monoid

variable {M : Type u} [AddCommMonoid M] (u : M)

/-- An equality between multiples of `u` may be shifted up. -/
theorem nsmul_eq_shift {a b : ℕ} (h : a • u = b • u) (c : ℕ) : (a + c) • u = (b + c) • u := by
  rw [add_nsmul, add_nsmul, h]

/-- **The kernel of `n ↦ n • u`, given its two minimal data.**  If `m • u = (m + n) • u` with `m`
the least point at which a repetition occurs and `n` the least period there, then `k • u = l • u`
is exactly `k ∼_{m,n} l`. -/
theorem cyclicRel_iff_of_min {m n : ℕ} (hn1 : 1 ≤ n) (hmn : m • u = (m + n) • u)
    (hmmin : ∀ a d : ℕ, 1 ≤ d → a • u = (a + d) • u → m ≤ a)
    (hnmin : ∀ d : ℕ, 1 ≤ d → m • u = (m + d) • u → n ≤ d) (k l : ℕ) :
    k • u = l • u ↔ CyclicRel m n k l := by
  -- multiples of `n` may be added at `m`
  have hmul : ∀ t : ℕ, m • u = (m + n * t) • u := by
    intro t
    induction t with
    | zero => simp
    | succ t ih =>
      have hshift : (m + n * t) • u = (m + n + n * t) • u := nsmul_eq_shift u hmn (n * t)
      rw [ih, hshift, show m + n + n * t = m + n * (t + 1) by rw [Nat.mul_succ]; omega]
  -- the periods at `m` are closed under differences
  have hsub : ∀ d d' : ℕ, m • u = (m + d) • u → m • u = (m + d') • u → d ≤ d' →
      m • u = (m + (d' - d)) • u := by
    intro d d' hd hd' hle
    rw [nsmul_eq_shift u hd (d' - d), show m + d + (d' - d) = m + d' by omega, ← hd']
  -- hence they are exactly the multiples of `n`
  have hdvd : ∀ d : ℕ, m • u = (m + d) • u → n ∣ d := by
    intro d hd
    have hmod := Nat.mod_add_div d n
    have hrem : m • u = (m + d % n) • u := by
      have := hsub _ _ (hmul (d / n)) hd (by omega)
      rwa [show d - n * (d / n) = d % n by omega] at this
    by_contra hnd
    exact absurd (hnmin _ (by omega) hrem) (by have := Nat.mod_lt d (show 0 < n by omega); omega)
  -- an equality above `m` descends to `m`
  have hdescent : ∀ a d : ℕ, m ≤ a → a • u = (a + d) • u → n ∣ d := by
    intro a d hma had
    have hge : a ≤ n * a := Nat.le_mul_of_pos_left a (by omega)
    have h1 : (m + n * a) • u = (m + n * a + d) • u := by
      have := nsmul_eq_shift u had (m + n * a - a)
      rwa [show a + (m + n * a - a) = m + n * a by omega,
        show a + d + (m + n * a - a) = m + n * a + d by omega] at this
    have h2 : (m + d) • u = (m + n * a + d) • u := nsmul_eq_shift u (hmul a) d
    exact hdvd d (by rw [h2, ← h1]; exact hmul a)
  constructor
  · -- `k • u = l • u` forces a repetition at `min k l`, hence above `m` and with period `n`
    intro heq
    have hlt : ∀ a b : ℕ, a < b → a • u = b • u → CyclicRel m n a b := by
      intro a b hab hs
      have hd : a • u = (a + (b - a)) • u := by rwa [show a + (b - a) = b by omega]
      have hma : m ≤ a := hmmin a (b - a) (by omega) hd
      exact Or.inr ⟨hma, by omega, (natCast_dvd_sub_iff (by omega)).mpr (hdescent a _ hma hd)⟩
    rcases lt_trichotomy k l with h | h | h
    · exact hlt k l h heq
    · exact Or.inl h
    · exact (hlt l k h heq.symm).symm
  · -- conversely, a multiple of `n` may be added anywhere above `m`
    have hge : ∀ a b : ℕ, m ≤ a → a ≤ b → n ∣ b - a → a • u = b • u := by
      intro a b hma hab ⟨t, ht⟩
      have := nsmul_eq_shift u (hmul t) (a - m)
      rw [show m + (a - m) = a by omega, show m + n * t + (a - m) = a + n * t by omega] at this
      rw [this, show a + n * t = b by omega]
    rintro (rfl | ⟨hk, hl, hd⟩)
    · rfl
    · rcases le_total k l with h | h
      · exact hge k l hk h ((natCast_dvd_sub_iff h).mp hd)
      · exact (hge l k hl h ((natCast_dvd_sub_iff h).mp (natCast_dvd_sub_comm.mp hd))).symm

/-- **The classification of cyclic monoids** (axiom A4 of this development until proved here).
A monoid generated by a single element `u` is either free on `u` — so `n ↦ n • u` is injective,
and the monoid is `ℕ₀` — or else it is `C_{m,n}` for some `m ≥ 0`, `n ≥ 1`, meaning that
`k • u = l • u` holds exactly when `k ∼_{m,n} l`.

No generation hypothesis is needed: the statement is about the kernel of `n ↦ n • u`, and holds for
any element of any commutative monoid. -/
theorem cyclicMonoidClassification {M : Type u} [AddCommMonoid M] (u : M) :
    (∀ k l : ℕ, k • u = l • u ↔ k = l) ∨
      ∃ m n : ℕ, 1 ≤ n ∧ ∀ k l : ℕ, k • u = l • u ↔ CyclicRel m n k l := by
  classical
  by_cases hinj : ∀ k l : ℕ, k • u = l • u → k = l
  · exact Or.inl fun k l => ⟨hinj k l, fun h => by rw [h]⟩
  right
  -- a repetition exists somewhere
  have hP : ∃ a : ℕ, ∃ d : ℕ, 1 ≤ d ∧ a • u = (a + d) • u := by
    push Not at hinj
    obtain ⟨k, l, heq, hne⟩ := hinj
    rcases Nat.lt_or_ge k l with h | h
    · exact ⟨k, l - k, by omega, by rwa [show k + (l - k) = l by omega]⟩
    · exact ⟨l, k - l, by omega, by rw [show l + (k - l) = k by omega]; exact heq.symm⟩
  -- take the least point at which one occurs, and the least period there
  have hQ : ∃ d : ℕ, 1 ≤ d ∧ (Nat.find hP) • u = (Nat.find hP + d) • u := Nat.find_spec hP
  obtain ⟨hn1, hmn⟩ := Nat.find_spec hQ
  exact ⟨Nat.find hP, Nat.find hQ, hn1,
    cyclicRel_iff_of_min u hn1 hmn
      (fun a d hd h => Nat.find_le ⟨d, hd, h⟩)
      (fun d hd h => not_lt.mp fun hlt => Nat.find_min hQ hlt ⟨hd, h⟩)⟩

end Monoid
