/-
**Invariance of infinite rank, without a rank condition.**

Mathlib has `Module.Basis.le_span`: the cardinality of a basis is bounded by that of any spanning
set — but only for a ring satisfying `RankCondition`, because the statement covers finite bases,
where it is genuinely a statement about invariant basis number.

For an *infinite* basis no such hypothesis is needed: nontriviality of the ring is enough, and the
argument is the support one.  Every element of a spanning set `S` has finite support in the basis,
so the whole of `S` — hence all of `M` — lies in the span of the basis elements occurring in those
supports.  A basis element outside that subfamily would then lie in the span of the others, which
linear independence forbids; so the subfamily is everything, and counting gives `#ι ≤ #S · ℵ₀`.
When `S` is infinite that is `#S`; when `S` is finite the subfamily is finite, contradicting the
infinitude of the basis.

It is stated in the *generation* form rather than the two-bases form because the application
(Example 2.13) has only a projective complement, not a second basis; `mk_eq_mk_of_infinite`
derives the familiar form.

Both proofs are adapted from the infinite branch of Mathlib's `Module.Basis.le_span`, which is
where this belongs upstream.
-/
import Mathlib.LinearAlgebra.Dimension.StrongRankCondition
import Mathlib.SetTheory.Cardinal.Arithmetic

universe u

open Cardinal Set Submodule Finsupp

/-- The basis elements occurring in the support of some member of `S`. -/
private def spanSupport {R : Type u} [Ring R] {M : Type u} [AddCommGroup M] [Module R M]
    {ι : Type u} (b : Module.Basis ι R M) (S : Set M) : Set ι :=
  ⋃ s : S, ((b.repr (s : M)).support : Set ι)

/-- A spanning set's supports cover the basis: every basis vector occurs in the support of some
element of `S`.  This is the heart of the argument, and needs no hypothesis on `R` beyond
nontriviality. -/
private theorem range_subset_spanSupport {R : Type u} [Ring R] [Nontrivial R] {M : Type u}
    [AddCommGroup M] [Module R M] {ι : Type u} (b : Module.Basis ι R M) {S : Set M}
    (hS : span R S = ⊤) : (univ : Set ι) ⊆ spanSupport b S := by
  intro i _
  -- everything spanned by `S` has its `b`-support inside the union of the supports of `S`
  have hspan : span R S ≤ comap b.repr.toLinearMap (Finsupp.supported R R (spanSupport b S)) :=
    span_le.2 fun s hs x hx => ⟨_, ⟨⟨s, hs⟩, rfl⟩, hx⟩
  rw [hS] at hspan
  have hi : b.repr (b i) ∈ Finsupp.supported R R (spanSupport b S) := hspan trivial
  rw [b.repr_self, Finsupp.mem_supported, Finsupp.support_single _ one_ne_zero] at hi
  exact hi (Finset.mem_singleton_self _)

/-- **Invariance of infinite rank**, in generation form: over a nontrivial ring, a free module with
an infinite basis is not generated by fewer elements than its rank.

No rank condition on `R` — see the module docstring.  The conclusion is `#ι ≤ #S` with no `⊔ ℵ₀`:
for finite `S` the hypotheses are contradictory, so nothing false is asserted, and the sharp form is
what lets Example 2.13 avoid a case split. -/
theorem mk_le_of_span_eq_top {R : Type u} [Ring R] [Nontrivial R] {M : Type u} [AddCommGroup M]
    [Module R M] {ι : Type u} (b : Module.Basis ι R M) [Infinite ι] {S : Set M}
    (hS : span R S = ⊤) : #ι ≤ #S := by
  have hcover : (univ : Set ι) ⊆ spanSupport b S := range_subset_spanSupport b hS
  rcases finite_or_infinite S with hfin | hinf
  · -- a finite spanning set gives a finite union of finite supports, so `ι` would be finite
    have : Finite S := hfin
    have hfinite : (spanSupport b S).Finite :=
      Set.finite_iUnion fun s => (b.repr (s : M)).support.finite_toSet
    exact absurd (hfinite.subset hcover) (Set.infinite_univ (α := ι)).not_finite
  · -- otherwise count: a `#S`-indexed union of finite sets has size at most `#S · ℵ₀ = #S`
    have hle : #(spanSupport b S) ≤ #S * ℵ₀ := by
      refine le_trans Cardinal.mk_iUnion_le_sum_mk ?_
      refine le_trans (Cardinal.sum_le_sum _ (fun _ => ℵ₀) fun s =>
        (Cardinal.lt_aleph0_of_finite _).le) ?_
      simp [Cardinal.sum_const]
    have huniv : #ι ≤ #(spanSupport b S) := by
      rw [← Cardinal.mk_univ (α := ι)]
      exact Cardinal.mk_le_mk_of_subset hcover
    have hS' : ℵ₀ ≤ #S := Cardinal.infinite_iff.mp hinf
    exact huniv.trans (hle.trans (le_of_eq (Cardinal.mul_aleph0_eq hS')))

/-- Invariance of infinite rank in its familiar form: two bases of the same module, one of them
infinite, have the same cardinality. -/
theorem mk_eq_mk_of_infinite {R : Type u} [Ring R] [Nontrivial R] {M : Type u} [AddCommGroup M]
    [Module R M] {ι ι' : Type u} (b : Module.Basis ι R M) (b' : Module.Basis ι' R M)
    [Infinite ι] : #ι = #ι' := by
  have h₁ : #ι ≤ #(Set.range (b' : ι' → M)) := mk_le_of_span_eq_top b b'.span_eq
  have h₁' : #ι ≤ #ι' := h₁.trans Cardinal.mk_range_le
  have : Infinite ι' :=
    Cardinal.infinite_iff.mpr ((Cardinal.infinite_iff.mp ‹Infinite ι›).trans h₁')
  have h₂ : #ι' ≤ #(Set.range (b : ι → M)) := mk_le_of_span_eq_top b' b.span_eq
  exact le_antisymm h₁' (h₂.trans Cardinal.mk_range_le)
