/-
**Isomorphic free modules have the same rank modulo commutators.**

If `R^k ≅ R^l` as left `R`-modules then `(k - l) · 1` lies in the additive subgroup generated by
the commutators `ab - ba`.  This is the Hattori–Stallings trace, restricted to free modules, where
it needs no projective-module theory: an isomorphism is a pair of matrices with `AB = Iₖ`,
`BA = I_l`, and

    tr(AB) - tr(BA) = Σᵢⱼ (aᵢⱼ bⱼᵢ - bⱼᵢ aᵢⱼ)

is visibly a sum of commutators, while the two traces are `k · 1` and `l · 1`.

Over a commutative ring this says nothing new (it is `k = l`, invariant basis number).  Its use is
for rings that are far from commutative: a ring whose `1` has additive order exactly `n` in
`R / [R,R]` can only have `R^k ≅ R^l` when `n ∣ k - l`.  That is the mod-`n` half of the module
type, and unlike the other half it needs no structure theory at all.

Left modules act on the right: `R`-linear maps `R^k → R^l` are matrices under `vecMul`, because
left multiplication by a scalar commutes with right multiplication by the entries.
-/
import Mathlib.LinearAlgebra.Matrix.Trace

universe u

namespace FreeTrace

variable {R : Type u} [Ring R]

/-- The additive subgroup generated by the commutators `a * b - b * a`. -/
def commutators (R : Type u) [Ring R] : AddSubgroup R :=
  AddSubgroup.closure {z | ∃ a b : R, z = a * b - b * a}

theorem commutator_mem (a b : R) : a * b - b * a ∈ commutators R :=
  AddSubgroup.subset_closure ⟨a, b, rfl⟩

/-- The matrix of a linear map between free left modules. -/
def toMat {k l : ℕ} (f : (Fin k → R) →ₗ[R] (Fin l → R)) : Matrix (Fin k) (Fin l) R :=
  Matrix.of fun i j => f (Pi.single i 1) j

theorem apply_eq_vecMul {k l : ℕ} (f : (Fin k → R) →ₗ[R] (Fin l → R)) (v : Fin k → R) :
    f v = Matrix.vecMul v (toMat f) := by
  have hv : v = ∑ i, v i • (Pi.single i 1 : Fin k → R) := by
    ext i; simp [Pi.single_apply]
  ext j
  conv_lhs => rw [hv]
  rw [map_sum]
  simp [Matrix.vecMul, dotProduct, toMat]

theorem toMat_comp {k l p : ℕ} (f : (Fin k → R) →ₗ[R] (Fin l → R))
    (g : (Fin l → R) →ₗ[R] (Fin p → R)) : toMat (g.comp f) = toMat f * toMat g := by
  ext i j
  rw [toMat, Matrix.of_apply, LinearMap.comp_apply, apply_eq_vecMul g]
  simp [Matrix.mul_apply, Matrix.vecMul, dotProduct, toMat]

theorem toMat_id {k : ℕ} : toMat (LinearMap.id : (Fin k → R) →ₗ[R] (Fin k → R)) = 1 := by
  ext i j
  simp [toMat, Matrix.one_apply, Pi.single_apply, eq_comm]

/-- Conversely, mutually inverse rectangular matrices give an isomorphism of free left modules.
This is the direction that *builds* `R^k ≅ R^l` from a presentation. -/
def equivOfMatrices {k l : ℕ} (A : Matrix (Fin k) (Fin l) R) (B : Matrix (Fin l) (Fin k) R)
    (hAB : A * B = 1) (hBA : B * A = 1) : (Fin k → R) ≃ₗ[R] (Fin l → R) where
  toFun v := Matrix.vecMul v A
  invFun w := Matrix.vecMul w B
  map_add' _ _ := by simp [Matrix.add_vecMul]
  map_smul' r v := by simp [Matrix.smul_vecMul]
  left_inv v := by simp [Matrix.vecMul_vecMul, hAB]
  right_inv w := by simp [Matrix.vecMul_vecMul, hBA]

/-- **Leavitt's matrix criterion** (p. 115: "well known and easily shown"): a module with bases of
length `k` and `l` exists exactly when there are matrices `A`, `B` over the ring with `AB = Iₖ` and
`BA = I_l`.  Being symmetric in the two sides, it is also why left and right module types agree. -/
theorem nonempty_equiv_iff_exists_matrices {k l : ℕ} :
    Nonempty ((Fin k → R) ≃ₗ[R] (Fin l → R)) ↔
      ∃ (A : Matrix (Fin k) (Fin l) R) (B : Matrix (Fin l) (Fin k) R), A * B = 1 ∧ B * A = 1 := by
  constructor
  · rintro ⟨e⟩
    refine ⟨toMat (e : (Fin k → R) →ₗ[R] (Fin l → R)),
      toMat (e.symm : (Fin l → R) →ₗ[R] (Fin k → R)), ?_, ?_⟩
    · rw [← toMat_comp]
      rw [show (e.symm : (Fin l → R) →ₗ[R] (Fin k → R)).comp (e : (Fin k → R) →ₗ[R] (Fin l → R))
        = LinearMap.id from by ext v; simp, toMat_id]
    · rw [← toMat_comp]
      rw [show (e : (Fin k → R) →ₗ[R] (Fin l → R)).comp (e.symm : (Fin l → R) →ₗ[R] (Fin k → R))
        = LinearMap.id from by ext v; simp, toMat_id]
  · rintro ⟨A, B, hAB, hBA⟩
    exact ⟨equivOfMatrices A B hAB hBA⟩

/-- **Leavitt, Theorem 3** — the `∪` of the type lattice, in the form used to reduce type `(m,n)`
to types `(m,1)` and `(1,n)`.  Free modules over a product ring are isomorphic exactly when they
are isomorphic over each factor, so the product realises the *intersection* of the two relations:
`(m,1) ∪ (1,n) = (m,n)`. -/
theorem nonempty_prod_iff {S : Type u} [Ring S] {k l : ℕ} :
    Nonempty ((Fin k → R × S) ≃ₗ[R × S] (Fin l → R × S)) ↔
      Nonempty ((Fin k → R) ≃ₗ[R] (Fin l → R)) ∧ Nonempty ((Fin k → S) ≃ₗ[S] (Fin l → S)) := by
  simp only [nonempty_equiv_iff_exists_matrices]
  constructor
  · rintro ⟨A, B, hAB, hBA⟩
    refine ⟨⟨A.map (RingHom.fst R S), B.map (RingHom.fst R S), ?_, ?_⟩,
      ⟨A.map (RingHom.snd R S), B.map (RingHom.snd R S), ?_, ?_⟩⟩
    · rw [← Matrix.map_mul, hAB, Matrix.map_one _ (map_zero _) (map_one _)]
    · rw [← Matrix.map_mul, hBA, Matrix.map_one _ (map_zero _) (map_one _)]
    · rw [← Matrix.map_mul, hAB, Matrix.map_one _ (map_zero _) (map_one _)]
    · rw [← Matrix.map_mul, hBA, Matrix.map_one _ (map_zero _) (map_one _)]
  · rintro ⟨⟨A₁, B₁, hAB₁, hBA₁⟩, ⟨A₂, B₂, hAB₂, hBA₂⟩⟩
    refine ⟨Matrix.of fun i j => (A₁ i j, A₂ i j), Matrix.of fun i j => (B₁ i j, B₂ i j), ?_, ?_⟩
    · ext i j
      · simpa [Matrix.mul_apply, Prod.fst_sum, Matrix.one_apply, apply_ite Prod.fst] using congrFun₂ hAB₁ i j
      · simpa [Matrix.mul_apply, Prod.snd_sum, Matrix.one_apply, apply_ite Prod.snd] using congrFun₂ hAB₂ i j
    · ext i j
      · simpa [Matrix.mul_apply, Prod.fst_sum, Matrix.one_apply, apply_ite Prod.fst] using congrFun₂ hBA₁ i j
      · simpa [Matrix.mul_apply, Prod.snd_sum, Matrix.one_apply, apply_ite Prod.snd] using congrFun₂ hBA₂ i j

/-- `tr(AB)` and `tr(BA)` differ by a sum of commutators, for rectangular `A` and `B`. -/
theorem trace_mul_sub_mem {k l : ℕ} (A : Matrix (Fin k) (Fin l) R) (B : Matrix (Fin l) (Fin k) R) :
    (A * B).trace - (B * A).trace ∈ commutators R := by
  have h1 : (A * B).trace = ∑ i : Fin k, ∑ j : Fin l, A i j * B j i := by
    simp [Matrix.trace, Matrix.mul_apply]
  have h2 : (B * A).trace = ∑ i : Fin k, ∑ j : Fin l, B j i * A i j := by
    rw [Matrix.trace]
    simp only [Matrix.diag_apply, Matrix.mul_apply]
    exact Finset.sum_comm
  rw [h1, h2, ← Finset.sum_sub_distrib]
  refine sum_mem fun i _ => ?_
  rw [← Finset.sum_sub_distrib]
  exact sum_mem fun j _ => commutator_mem _ _

/-- **The rank of a free module, modulo commutators.** -/
theorem natCast_sub_mem_of_equiv {k l : ℕ} (e : (Fin k → R) ≃ₗ[R] (Fin l → R)) :
    (k : R) - (l : R) ∈ commutators R := by
  have hAB : toMat (e : (Fin k → R) →ₗ[R] (Fin l → R))
      * toMat (e.symm : (Fin l → R) →ₗ[R] (Fin k → R)) = 1 := by
    rw [← toMat_comp]
    have : (e.symm : (Fin l → R) →ₗ[R] (Fin k → R)).comp (e : (Fin k → R) →ₗ[R] (Fin l → R))
        = LinearMap.id := by ext v; simp
    rw [this, toMat_id]
  have hBA : toMat (e.symm : (Fin l → R) →ₗ[R] (Fin k → R))
      * toMat (e : (Fin k → R) →ₗ[R] (Fin l → R)) = 1 := by
    rw [← toMat_comp]
    have : (e : (Fin k → R) →ₗ[R] (Fin l → R)).comp (e.symm : (Fin l → R) →ₗ[R] (Fin k → R))
        = LinearMap.id := by ext v; simp
    rw [this, toMat_id]
  have h := trace_mul_sub_mem (toMat (e : (Fin k → R) →ₗ[R] (Fin l → R)))
    (toMat (e.symm : (Fin l → R) →ₗ[R] (Fin k → R)))
  rw [hAB, hBA, Matrix.trace_one, Matrix.trace_one] at h
  simpa using h

end FreeTrace
