/-
`add x` and `add_λ x`: the divisor-closed `λ⁻`-submonoid generated by the multiples of an
element.  Monoid theory — §4 uses it for `V(R) = add [R]`, §5 throughout.
-/
import KappaMonoid.Core

universe u v

open Cardinal Function Set

namespace KappaMonoid

/-! ## `add x` and `add_λ x`

For `x` in a `κ`-monoid, `add x` is the set of summands of multiples of `x` — the divisor-closed
submonoid generated by `x` — and `add_λ x` is the set of summands of `λ x`. -/

namespace KMonoid

variable {κ : Cardinal.{u}} {H : Type u} [KMonoid κ H]

/-- `add x`: the summands of the finite multiples of `x`. -/
def addOf (x : H) : Set H :=
  {y | ∃ (z : H) (n : ℕ), y + z = cmul (κ := κ) (n : Cardinal.{u})
    (le_trans (le_of_lt Cardinal.natCast_lt_aleph0) (aleph0_le (κ := κ) (H := H))) x}

/-- `add_λ x`: the summands of `λ x`, for an infinite `λ ≤ κ`. -/
def addOfCard {lam : Cardinal.{u}} (hlam : lam ≤ κ) (x : H) : Set H :=
  {y | ∃ z : H, y + z = cmul (κ := κ) lam hlam x}

/-- `add x` is a submonoid: it contains `0` and is closed under finite sums.  Stated as
`IsLSubset ℵ₀`, which is exactly closure under sums over index types of cardinality `< ℵ₀`, so
that the subtype picks up an `LMonoid ℵ₀` instance through `IsLSubset.lmonoid`. -/
theorem addOf_isLSubset (hκ : ℵ₀ ≤ κ) (x : H) :
    IsLSubset ℵ₀ (le_succ_of_le hκ) (addOf (κ := κ) x) := by
  classical
  constructor
  · -- `0 = 0 + 0` is a summand of `0 · x`
    refine ⟨0, 0, ?_⟩
    rw [add_zero]
    exact ((cmul_congr (Nat.cast_zero (R := Cardinal.{u})) _
      (zero_le (a := κ)) x).trans (cmul_zero_cardinal x)).symm
  · -- add the witnesses: `Σ y i + Σ z i = Σ (n i) · x = (Σ n i) · x`
    intro ι hι y hy
    choose z n hzn using hy
    have hidx : #ι ≤ κ := hι.le.trans hκ
    have hlt : Cardinal.sum (fun i => ((n i : ℕ) : Cardinal.{u})) < ℵ₀ :=
      Cardinal.sum_lt_of_isRegular Cardinal.isRegular_aleph0 hι fun _ => Cardinal.natCast_lt_aleph0
    obtain ⟨m, hm⟩ := Cardinal.lt_aleph0.mp hlt
    have hmκ : ((m : ℕ) : Cardinal.{u}) ≤ κ :=
      le_trans (le_of_lt Cardinal.natCast_lt_aleph0) hκ
    refine ⟨∑[≤ κ] i, z i, m, ?_⟩
    rw [← sumOf_add (h := CardLE.mk' hidx) y z, funext hzn,
      ← cmul_sumOf_cardinal (hI := CardLE.mk' hidx) (fun i => ((n i : ℕ) : Cardinal.{u})) (fun _ => le_trans (le_of_lt Cardinal.natCast_lt_aleph0) hκ) (le_trans hlt.le hκ) x]
    exact cmul_congr hm _ hmκ x

/-- The `ℵ₀⁻`-monoid structure on `add x`, as an instance.

Section 5 states nearly everything over `add (x₁ + x₂)`, and without this instance every such
statement has to open with

    letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
      (KMonoid.addOf_isLSubset (κ := ℵ₀) le_rfl (x₁ + x₂))

repeated verbatim in the statement and again at the top of the proof.  Since `IsLSubset` is a
`Prop` (trap 13), any two such structures are *definitionally* equal, so making this an instance
changes nothing about the mathematics and lets instance search carry it instead. -/
noncomputable instance instLMonoidAddOf {H : Type u} [KMonoid (ℵ₀ : Cardinal.{u}) H] (x : H) :
    LMonoid ℵ₀ ↥(addOf (κ := (ℵ₀ : Cardinal.{u})) x) :=
  IsLSubset.lmonoid Cardinal.isRegular_aleph0 (addOf_isLSubset le_rfl x)


/-- `x ∈ add x`: take one copy of `x` and the summand `0`. -/
theorem self_mem_addOf (x : H) : x ∈ addOf (κ := κ) x :=
  ⟨0, 1, by rw [add_zero, cmul_natCast, one_nsmul]⟩

/-- `add x` is divisor-closed: a summand of an element of `add x` is again in `add x`. -/
theorem addOf_isSaturated (x : H) :
    ∀ a ∈ addOf (κ := κ) x, ∀ b c : H, a = b + c → b ∈ addOf (κ := κ) x := by
  rintro a ⟨z, n, hzn⟩ b c rfl
  exact ⟨c + z, n, by rw [← add_assoc]; exact hzn⟩

/-- `add_λ x` is a `λ⁻`-submonoid of `H`. -/
theorem addOfCard_isLSubset {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ κ) (x : H) :
    IsLSubset lam (hlk.trans (Order.le_succ κ)) (addOfCard hlk x) := by
  classical
  constructor
  · exact ⟨cmul (κ := κ) lam hlk x, zero_add _⟩
  · intro ι hι y hy
    choose z hz using hy
    have hidx : #ι ≤ κ := hι.le.trans hlk
    rcases isEmpty_or_nonempty ι with hemp | hne
    · -- an empty sum is `0`, which is a summand of `λ · x`
      have := hemp
      refine ⟨cmul (κ := κ) lam hlk x, ?_⟩
      rw [show ∑[≤ κ] i, y i = 0 from LMonoid.lsumOf_isEmpty (h := cardLT_succ hidx) y,
        zero_add]
    · -- otherwise `#ι · λ = λ`, so the witnesses again add up to `λ · x`
      have hmk : #ι * lam = lam :=
        Cardinal.mul_eq_right hlam.aleph0_le hι.le (Cardinal.mk_ne_zero_iff.mpr hne)
      have hsum : Cardinal.sum (fun _ : ι => lam) = lam :=
        (Cardinal.sum_const' ι lam).trans hmk
      refine ⟨∑[≤ κ] i, z i, ?_⟩
      rw [← sumOf_add (h := CardLE.mk' hidx) y z, funext hz,
        ← cmul_sumOf_cardinal (hI := CardLE.mk' hidx) (fun _ : ι => lam) (fun _ => hlk) (le_of_eq_of_le hsum hlk) x]
      exact cmul_congr hsum _ hlk x

/-- `add_α x` is closed under sums of size `< lam` for every `lam ≤ α⁺`, not just `lam ≤ α`:
at most `α` summands of `α · x` again add up to a summand of `α · x`, because `#ι · α = α`.

This is what makes `add_{ℵ₀} x` an `ℵ₁⁻`-monoid — the base of Corollary 4.7(2) — over a `κ`
that may be much larger than `ℵ₀`. -/
theorem addOfCard_isLSubset_succ {alpha lam : Cardinal.{u}} (halpha : ℵ₀ ≤ alpha)
    (hak : alpha ≤ κ) (hla : lam ≤ Order.succ alpha) (x : H) :
    IsLSubset lam (hla.trans (Order.succ_le_succ hak)) (addOfCard hak x) := by
  classical
  constructor
  · exact ⟨cmul (κ := κ) alpha hak x, zero_add _⟩
  · intro ι hι y hy
    choose z hz using hy
    have hια : #ι ≤ alpha := Order.lt_succ_iff.mp (lt_of_lt_of_le hι hla)
    have hidx : #ι ≤ κ := hια.trans hak
    rcases isEmpty_or_nonempty ι with hemp | hne
    · have := hemp
      refine ⟨cmul (κ := κ) alpha hak x, ?_⟩
      rw [show ∑[≤ κ] i, y i = 0 from LMonoid.lsumOf_isEmpty (h := cardLT_succ hidx) y,
        zero_add]
    · have hmk : #ι * alpha = alpha :=
        Cardinal.mul_eq_right halpha hια (Cardinal.mk_ne_zero_iff.mpr hne)
      have hsum : Cardinal.sum (fun _ : ι => alpha) = alpha :=
        (Cardinal.sum_const' ι alpha).trans hmk
      refine ⟨∑[≤ κ] i, z i, ?_⟩
      rw [← sumOf_add (h := CardLE.mk' hidx) y z, funext hz,
        ← cmul_sumOf_cardinal (hI := CardLE.mk' hidx) (fun _ : ι => alpha) (fun _ => hak) (le_of_eq_of_le hsum hak) x]
      exact cmul_congr hsum _ hak x

/-- `add_λ x` is divisor-closed. -/
theorem addOfCard_isSaturated {lam : Cardinal.{u}} (hlk : lam ≤ κ) (x : H) :
    ∀ a ∈ addOfCard hlk x, ∀ b c : H, a = b + c → b ∈ addOfCard hlk x := by
  rintro a ⟨z, hz⟩ b c rfl
  exact ⟨c + z, by rw [← add_assoc]; exact hz⟩

end KMonoid

/-- `add(x)` at `κ = ℵ₀`, the paper's `add(x)`.  Notation, not a definition: it expands to
`addOf x` with `κ := ℵ₀`, which is the only case §4 and §5 use. -/
scoped notation:max "add(" x ")" => KappaMonoid.KMonoid.addOf (κ := Cardinal.aleph0) x

end KappaMonoid
