/-
`add x` and `add_λ x`: the divisor-closed `λ⁻`-submonoid generated by the multiples of an
element.  Monoid theory — §4 uses it for `V(R) = add [R]`, §5 throughout.
-/
import KappaMonoid.Core

universe u v

open Cardinal Function Set

namespace KappaMonoid

/-! ## `add x` and `add_λ x`

For `x` in a `κ`-monoid, `add x` is the set of summands of multiples of `x` — the divisor-closed
submonoid generated by `x` — and `add_λ x` is the set of summands of `λ x`. -/

namespace KMonoid

variable {κ : Cardinal.{u}} {H : Type u} [KMonoid κ H]

/-- `add x`: the summands of the finite multiples of `x`. -/
def addOf (x : H) : Set H :=
  {y | ∃ (z : H) (n : ℕ), y + z = cmul (κ := κ) (n : Cardinal.{u})
    (le_trans (le_of_lt Cardinal.natCast_lt_aleph0) (aleph0_le (κ := κ) (H := H))) x}

/-- `add_λ x`: the summands of `λ x`, for an infinite `λ ≤ κ`. -/
def addOfCard {lam : Cardinal.{u}} (hlam : lam ≤ κ) (x : H) : Set H :=
  {y | ∃ z : H, y + z = cmul (κ := κ) lam hlam x}

/-- `add x` is a submonoid: it contains `0` and is closed under finite sums.  Stated as
`IsLSubset ℵ₀`, which is exactly closure under sums over index types of cardinality `< ℵ₀`, so
that the subtype picks up an `LMonoid ℵ₀` instance through `IsLSubset.lmonoid`. -/
theorem addOf_isLSubset (hκ : ℵ₀ ≤ κ) (x : H) : IsLSubset ℵ₀ hκ (addOf (κ := κ) x) := by
  classical
  constructor
  · -- `0 = 0 + 0` is a summand of `0 · x`
    refine ⟨0, 0, ?_⟩
    rw [add_zero]
    exact ((cmul_congr (Nat.cast_zero (R := Cardinal.{u})) _
      (zero_le (a := κ)) x).trans (cmul_zero_cardinal x)).symm
  · -- add the witnesses: `Σ y i + Σ z i = Σ (n i) · x = (Σ n i) · x`
    intro ι hι y hy
    choose z n hzn using hy
    have hidx : #ι ≤ κ := hι.le.trans hκ
    have hlt : Cardinal.sum (fun i => ((n i : ℕ) : Cardinal.{u})) < ℵ₀ :=
      Cardinal.sum_lt_of_isRegular Cardinal.isRegular_aleph0 hι fun _ => Cardinal.natCast_lt_aleph0
    obtain ⟨m, hm⟩ := Cardinal.lt_aleph0.mp hlt
    have hmκ : ((m : ℕ) : Cardinal.{u}) ≤ κ :=
      le_trans (le_of_lt Cardinal.natCast_lt_aleph0) hκ
    refine ⟨sumOf (κ := κ) hidx z, m, ?_⟩
    rw [← sumOf_add hidx y z, funext hzn,
      ← cmul_sumOf_cardinal hidx (fun i => ((n i : ℕ) : Cardinal.{u}))
        (fun _ => le_trans (le_of_lt Cardinal.natCast_lt_aleph0) hκ) (le_trans hlt.le hκ) x]
    exact cmul_congr hm _ hmκ x

/-- The `ℵ₀⁻`-monoid structure on `add x`, as an instance.

Section 5 states nearly everything over `add (x₁ + x₂)`, and without this instance every such
statement has to open with

    letI := IsLSubset.lmonoid Cardinal.isRegular_aleph0
      (KMonoid.addOf_isLSubset (κ := ℵ₀) le_rfl (x₁ + x₂))

repeated verbatim in the statement and again at the top of the proof.  Since `IsLSubset` is a
`Prop` (trap 13), any two such structures are *definitionally* equal, so making this an instance
changes nothing about the mathematics and lets instance search carry it instead. -/
noncomputable instance instLMonoidAddOf {H : Type u} [KMonoid (ℵ₀ : Cardinal.{u}) H] (x : H) :
    LMonoid ℵ₀ ↥(addOf (κ := (ℵ₀ : Cardinal.{u})) x) :=
  IsLSubset.lmonoid Cardinal.isRegular_aleph0 (addOf_isLSubset le_rfl x)


/-- `x ∈ add x`: take one copy of `x` and the summand `0`. -/
theorem self_mem_addOf (x : H) : x ∈ addOf (κ := κ) x :=
  ⟨0, 1, by rw [add_zero, cmul_natCast, one_nsmul]⟩

/-- `add x` is divisor-closed: a summand of an element of `add x` is again in `add x`. -/
theorem addOf_isSaturated (x : H) :
    ∀ a ∈ addOf (κ := κ) x, ∀ b c : H, a = b + c → b ∈ addOf (κ := κ) x := by
  rintro a ⟨z, n, hzn⟩ b c rfl
  exact ⟨c + z, n, by rw [← add_assoc]; exact hzn⟩

/-- `add_λ x` is a `λ⁻`-submonoid of `H`. -/
theorem addOfCard_isLSubset {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ κ) (x : H) :
    IsLSubset lam hlk (addOfCard hlk x) := by
  classical
  constructor
  · exact ⟨cmul (κ := κ) lam hlk x, zero_add _⟩
  · intro ι hι y hy
    choose z hz using hy
    have hidx : #ι ≤ κ := hι.le.trans hlk
    rcases isEmpty_or_nonempty ι with hemp | hne
    · -- an empty sum is `0`, which is a summand of `λ · x`
      haveI := hemp
      refine ⟨cmul (κ := κ) lam hlk x, ?_⟩
      rw [show sumOf (κ := κ) hidx y = 0 from LMonoid.lsumOf_isEmpty _ y, zero_add]
    · -- otherwise `#ι · λ = λ`, so the witnesses again add up to `λ · x`
      have hmk : #ι * lam = lam :=
        Cardinal.mul_eq_right hlam.aleph0_le hι.le (Cardinal.mk_ne_zero_iff.mpr hne)
      have hsum : Cardinal.sum (fun _ : ι => lam) = lam :=
        (Cardinal.sum_const' ι lam).trans hmk
      refine ⟨sumOf (κ := κ) hidx z, ?_⟩
      rw [← sumOf_add hidx y z, funext hz,
        ← cmul_sumOf_cardinal hidx (fun _ : ι => lam) (fun _ => hlk)
          (le_of_eq_of_le hsum hlk) x]
      exact cmul_congr hsum _ hlk x

end KMonoid

end KappaMonoid
