/-
Lemma 2.15 of

  Zahra Nazemian and Daniel Smertnig,
  *A monoid-theoretical approach to infinite direct-sum decompositions of modules*.

A cyclic `κ`-monoid generated by a faithful order-unit `u` splits as

  `C₀ ⊎ {α : ℵ₀ ≤ α ≤ κ}`,

where `C₀ = {n u : n ∈ ℕ₀}` is the cyclic submonoid of size-zero elements and the second part is
`{α u : α infinite}`, parametrised by the cardinal `α` itself.  Faithfulness is what makes the
parametrisation injective and keeps the two parts disjoint.
-/
import KappaMonoid.Core.OrderUnit

universe u v

open Cardinal

namespace KappaMonoid

namespace KMonoid

variable {κ : Cardinal.{u}} {H : Type v} [KMonoid κ H]

/-- A sum of copies of `z` indexed by `ι` is `#ι · z`. -/
theorem sumOf_const {ι : Type u} (hι : #ι ≤ κ) (z : H) :
    sumOf (κ := κ) hι (fun _ : ι => z) = cmul (κ := κ) (#ι) hι z := by
  obtain ⟨Ψ⟩ := Cardinal.eq.mp (mk_Idx (#ι))
  exact sumOf_equiv hι (le_of_eq_of_le (mk_Idx (#ι)) hι) Ψ (fun _ : ι => z)

/-! ## Every element of a cyclic `κ`-monoid is a multiple of the generator -/

/-- If `H` is generated by `u` as a `κ`-monoid, every element is `α u` for some `α ≤ κ`.

Paper proof: an element is a `κ`-sum of copies of `u` and of `0`; discarding the zeros leaves a
sum of `α` copies of `u`, where `α` is the size of the support. -/
theorem exists_cmul_of_kGenerates {u : H} (hgen : KGenerates κ ({u} : Set H)) (x : H) :
    ∃ (α : Cardinal.{u}) (hα : α ≤ κ), x = cmul (κ := κ) α hα u := by
  classical
  have hsub : ({u} : Set H) ⊆ ({0, u} : Set H) := fun _ hv => Set.mem_insert_of_mem _ hv
  have hgen' : KGenerates κ ({0, u} : Set H) :=
    Set.eq_univ_of_univ_subset (hgen ▸ kclosure_mono hsub)
  obtain ⟨y, hy, hxy⟩ :=
    (mem_kclosure_iff (Set.mem_insert _ _) x).mp (kGenerates_iff.mp hgen' x)
  -- on its support `y` takes the value `u`
  have hsupp : ∀ i : Function.support y, y (i : Idx κ) = u := by
    rintro ⟨i, hi⟩
    rcases hy i with h0 | hu
    · exact absurd h0 hi
    · exact hu
  have hmk : #(Function.support y) ≤ κ :=
    le_of_le_of_eq (Cardinal.mk_le_mk_of_subset (Set.subset_univ _))
      (by rw [Cardinal.mk_univ, mk_Idx])
  refine ⟨#(Function.support y), hmk, ?_⟩
  rw [hxy, ← sumOf_Idx y, sumOf_subtype_support (le_of_eq (mk_Idx κ)) y hmk,
    show (fun i : Function.support y => y (i : Idx κ)) = fun _ : Function.support y => u from
      funext hsupp,
    sumOf_const hmk u]

/-! ## Faithfulness pins down the infinite multiples -/

/-- For a faithful order-unit, distinct infinite cardinals give distinct multiples. -/
theorem cmul_injOn_of_faithful {u : H} (hu : IsFaithful (κ := κ) u) {α β : Cardinal.{u}}
    (hα0 : ℵ₀ ≤ α) (hβ0 : ℵ₀ ≤ β) (hα : α ≤ κ) (hβ : β ≤ κ)
    (h : cmul (κ := κ) α hα u = cmul (κ := κ) β hβ u) : α = β := by
  by_contra hne
  rcases lt_or_gt_of_ne hne with hlt | hlt
  · exact hu.2 α β hα hβ hlt hβ0 (AddLe.of_eq h.symm)
  · exact hu.2 β α hβ hα hlt hα0 (AddLe.of_eq h)

/-- `C₀`, the set of finite multiples of `u`. -/
def finitePart (u : H) : Set H := {x | ∃ n : ℕ, x = cmul (κ := κ) (n : Cardinal.{u}) (by
  exact le_trans (le_of_lt (Cardinal.natCast_lt_aleph0)) (aleph0_le (κ := κ) (H := H))) u}

/-- An infinite multiple of a faithful order-unit is not a finite multiple. -/
theorem cmul_notMem_finitePart {u : H} (hu : IsFaithful (κ := κ) u) {β : Cardinal.{u}}
    (hβ0 : ℵ₀ ≤ β) (hβ : β ≤ κ) : cmul (κ := κ) β hβ u ∉ finitePart (κ := κ) u := by
  rintro ⟨n, hn⟩
  have hnκ : (n : Cardinal.{u}) ≤ κ :=
    le_trans (le_of_lt Cardinal.natCast_lt_aleph0) (aleph0_le (κ := κ) (H := H))
  exact hu.2 (n : Cardinal.{u}) β hnκ hβ (lt_of_lt_of_le Cardinal.natCast_lt_aleph0 hβ0) hβ0
    (AddLe.of_eq hn)

/-! ## Lemma 2.15 -/

/-- **Lemma 2.15**: a cyclic `κ`-monoid generated by a faithful order-unit `u` is the disjoint
union of the finite multiples of `u` and the infinite multiples, the latter being parametrised
faithfully by the cardinals `ℵ₀ ≤ α ≤ κ`.

The three parts below are (i) that the parametrising map is surjective, (ii) that the two pieces
are disjoint, and (iii) that the infinite parameters are recovered from their multiples. -/
theorem lemma_2_15 {u : H} (hu : IsFaithful (κ := κ) u) (hgen : KGenerates κ ({u} : Set H)) :
    (∀ x : H, x ∈ finitePart (κ := κ) u ∨
        ∃ (α : Cardinal.{u}) (_hα0 : ℵ₀ ≤ α) (hα : α ≤ κ), x = cmul (κ := κ) α hα u) ∧
      (∀ (β : Cardinal.{u}) (_hβ0 : ℵ₀ ≤ β) (hβ : β ≤ κ),
        cmul (κ := κ) β hβ u ∉ finitePart (κ := κ) u) ∧
      (∀ (α β : Cardinal.{u}) (_hα0 : ℵ₀ ≤ α) (_hβ0 : ℵ₀ ≤ β) (hα : α ≤ κ) (hβ : β ≤ κ),
        cmul (κ := κ) α hα u = cmul (κ := κ) β hβ u → α = β) := by
  refine ⟨fun x => ?_, fun β hβ0 hβ => cmul_notMem_finitePart hu hβ0 hβ,
    fun α β hα0 hβ0 hα hβ h => cmul_injOn_of_faithful hu hα0 hβ0 hα hβ h⟩
  obtain ⟨α, hα, rfl⟩ := exists_cmul_of_kGenerates hgen x
  rcases lt_or_ge α ℵ₀ with hfin | hinf
  · obtain ⟨n, rfl⟩ := Cardinal.lt_aleph0.mp hfin
    exact Or.inl ⟨n, cmul_congr rfl hα _ u⟩
  · exact Or.inr ⟨α, hinf, hα, rfl⟩

/-- The packaged form of Lemma 2.15: `H ≃ C₀ ⊎ {α : ℵ₀ ≤ α ≤ κ}`. -/
noncomputable def equivFinitePartSumCard {u : H} (hu : IsFaithful (κ := κ) u)
    (hgen : KGenerates κ ({u} : Set H)) :
    ↥(finitePart (κ := κ) u) ⊕ {α : Cardinal.{u} // ℵ₀ ≤ α ∧ α ≤ κ} ≃ H := by
  refine Equiv.ofBijective
    (Sum.elim (fun p => (p : H)) fun a => cmul (κ := κ) (a : Cardinal.{u}) a.2.2 u) ⟨?_, ?_⟩
  · rintro (p | a) (q | b) h <;> simp only [Sum.elim_inl, Sum.elim_inr] at h
    · exact congrArg Sum.inl (Subtype.ext h)
    · exact absurd (by rw [← h]; exact p.2) (cmul_notMem_finitePart hu b.2.1 b.2.2)
    · exact absurd (by rw [h]; exact q.2) (cmul_notMem_finitePart hu a.2.1 a.2.2)
    · exact congrArg Sum.inr
        (Subtype.ext (cmul_injOn_of_faithful hu a.2.1 b.2.1 a.2.2 b.2.2 h))
  · intro x
    rcases (lemma_2_15 hu hgen).1 x with hfin | ⟨α, hα0, hα, rfl⟩
    · exact ⟨Sum.inl ⟨x, hfin⟩, rfl⟩
    · exact ⟨Sum.inr ⟨α, hα0, hα⟩, rfl⟩

/-- **Lemma 2.15**, the operation: *"with the obvious operation"*.

The bijection `equivFinitePartSumCard` carries the operation of `H` to the obvious one on
`C₀ ⊎ {α : ℵ₀ ≤ α ≤ κ}`: `C₀` is closed under `+`, an infinite multiple `α u` absorbs every
element of `C₀`, and two infinite multiples add to the multiple indexed by the larger cardinal.
These three clauses determine the operation on the disjoint union completely, so together with
the bijection they *are* the isomorphism the lemma asserts.

None of it needs faithfulness of `u`: the three identities are the cardinal arithmetic
`n + m`, `n + α = α` and `α + β = max α β` read through Lemma 2.7(2). -/
theorem lemma_2_15_add (u : H) :
    (∀ p ∈ finitePart (κ := κ) u, ∀ q ∈ finitePart (κ := κ) u,
        p + q ∈ finitePart (κ := κ) u) ∧
      (∀ p ∈ finitePart (κ := κ) u, ∀ (α : Cardinal.{u}) (_hα0 : ℵ₀ ≤ α) (hα : α ≤ κ),
        p + cmul (κ := κ) α hα u = cmul (κ := κ) α hα u) ∧
      (∀ (α β : Cardinal.{u}) (_hα0 : ℵ₀ ≤ α) (_hβ0 : ℵ₀ ≤ β) (hα : α ≤ κ) (hβ : β ≤ κ),
        cmul (κ := κ) α hα u + cmul (κ := κ) β hβ u
          = cmul (κ := κ) (max α β) (max_le hα hβ) u) := by
  have hnat : ∀ n : ℕ, ((n : ℕ) : Cardinal.{u}) ≤ κ := fun n =>
    le_trans (le_of_lt Cardinal.natCast_lt_aleph0) (aleph0_le (κ := κ) (H := H))
  refine ⟨?_, ?_, ?_⟩
  · rintro p ⟨n, rfl⟩ q ⟨m, rfl⟩
    have hsum : ((n : ℕ) : Cardinal.{u}) + ((m : ℕ) : Cardinal.{u}) = ((n + m : ℕ) : Cardinal.{u}) := by
      push_cast; ring
    have hle : ((n : ℕ) : Cardinal.{u}) + ((m : ℕ) : Cardinal.{u}) ≤ κ := hsum.trans_le (hnat (n + m))
    refine ⟨n + m, ?_⟩
    rw [← cmul_add (hnat n) (hnat m) hle u]
    exact cmul_congr hsum hle (hnat (n + m)) u
  · rintro p ⟨n, rfl⟩ α hα0 hα
    have hsum : ((n : ℕ) : Cardinal.{u}) + α = α := by
      rw [add_comm]
      exact Cardinal.add_eq_left hα0 (le_trans (le_of_lt Cardinal.natCast_lt_aleph0) hα0)
    have hle : ((n : ℕ) : Cardinal.{u}) + α ≤ κ := hsum.trans_le hα
    rw [← cmul_add (hnat n) hα hle u]
    exact cmul_congr hsum hle hα u
  · intro α β hα0 hβ0 hα hβ
    have hsum : α + β = max α β := Cardinal.add_eq_max hα0
    have hle : α + β ≤ κ := hsum.trans_le (max_le hα hβ)
    rw [← cmul_add hα hβ hle u]
    exact cmul_congr hsum hle (max_le hα hβ) u

end KMonoid

end KappaMonoid
