import Comparator.Bridge.Braiding

/-!
# Bridge, part 3: monoids of modules

A challenge realisation `P : H → ModuleCat R` of `V^κ(C)` is a library `ModuleClass` with
carrier `H` (`IsVMonoidOf.toClass`); a realisation of `V^κ(R)` is an isomorphism with the
library's `projClass` (`IsVProjOf.exists_iso`, `IsVProjOf.of_iso`).  With these, Theorem 4.3 and
Corollary 4.5 are read off the library.
-/

universe u t

open Cardinal Function Set DirectSum
open scoped KappaMonoid

namespace KappaChallenge

attribute [-instance] KMonoid.instAdd KMonoid.instSMul LMonoid.instAdd KMonoid.toZero LMonoid.toZero

variable {κ : Cardinal.{u}} {R : Type u} [Ring R]

/-! ## Rings -/

theorem isHereditary_iff : IsHereditary R ↔ _root_.IsHereditary R :=
  ⟨fun h => ⟨⟨h.1⟩, ⟨h.2⟩⟩, fun h => ⟨h.1.1, h.2.1⟩⟩

/-- A direct summand of a projective module is projective. -/
theorem projective_of_directSum {ι : Type u} (N : ι → ModuleCat.{u} R) {M : ModuleCat.{u} R}
    [Module.Projective R M] (e : M ≃ₗ[R] ⨁ i, N i) (i : ι) : Module.Projective R (N i) := by
  classical
  refine Module.Projective.of_split (e.symm.toLinearMap ∘ₗ DirectSum.lof R ι (fun i => N i) i)
    (DirectSum.component R ι (fun i => N i) i ∘ₗ e.toLinearMap) ?_
  ext x
  simp

theorem projectivesAreSumsOfFG_iff :
    ProjectivesAreSumsOfFG R ↔ KappaMonoid.EveryProjectiveIsSumOfFG R := by
  constructor
  · intro h P _ _ hP
    obtain ⟨ι, N, hfin, ⟨e⟩⟩ := h (ModuleCat.of R P) hP
    exact ⟨ι, fun i => N i, fun _ => inferInstance, fun _ => inferInstance,
      fun i => projective_of_directSum N (M := ModuleCat.of R P) e i, hfin, ⟨e⟩⟩
  · intro h M hM
    obtain ⟨ι, Q, _, _, -, hfin, ⟨e⟩⟩ := h M inferInstance inferInstance hM
    exact ⟨ι, fun i => ModuleCat.of R (Q i), hfin, ⟨e⟩⟩

/-! ## A realisation as a library module class -/

/-- The library's module class of a realisation `P` of `H`. -/
@[reducible] noncomputable def IsVMonoidOf.toClass {H : Type u} {C : KMonoid κ H}
    {P : H → ModuleCat.{u} R} (hP : @IsVMonoidOf κ R _ H C P) : KappaMonoid.ModuleClass R κ where
  aleph0_le := C.aleph0_le
  carrier := H
  rep h := P h
  addCommGroup _ := inferInstance
  module _ := inferInstance
  eq_of_iso e := hP.inj _ _ ⟨e⟩
  zero := 𝟎[C]
  subsingleton_rep_zero := hP.zero
  dsum := C.sum
  dsum_iso := hP.sum_iso

theorem IsVMonoidOf.compat {H : Type u} {C : KMonoid κ H} {P : H → ModuleCat.{u} R}
    (hP : @IsVMonoidOf κ R _ H C P) :
    KMonoid.Compat C (KappaMonoid.ModuleClass.instKMonoid hP.toClass) :=
  ⟨rfl, fun x => (hP.toClass.instKMonoid_ksum x).symm⟩

theorem isLambdaSmall_lib {lam : Cardinal.{u}} {M : ModuleCat.{u} R} (h : IsLambdaSmall R lam M) :
    KappaMonoid.IsLambdaSmall R lam M := by
  intro ι N _ _ f
  obtain ⟨s, hs, h0⟩ := h (fun i => ModuleCat.of R (N i)) f
  exact ⟨s, hs, fun m i hi => h0 m i hi⟩

/-- **Theorem 4.3**, in the challenge's terms. -/
theorem theorem_4_3_bridge {H : Type u} (C : KMonoid κ H) {ι : Type u} [LinearOrder ι]
    [WellFoundedLT ι] [NoMaxOrder ι] [SuccOrder ι] (hι : #ι = κ) (P : H → ModuleCat.{u} R)
    (hP : @IsVMonoidOf κ R _ H C P)
    (hsummand : ∀ h (N N' : Submodule R (P h)), IsCompl N N' → ∃ h', Nonempty (P h' ≃ₗ[R] N))
    {lam : Cardinal.{u}} (hlam : lam.IsRegular) (hlk : lam ≤ Order.succ κ) (X : Set H)
    (hsmall : ∀ h ∈ X, IsLambdaSmall R lam (P h)) (hX : @KMonoid.IsLSubmonoid κ H C lam X)
    (hXsummand : ∀ a b : H, a +[C] b ∈ X → a ∈ X) :
    (∀ x y : ι → H, (∀ i, x i ∈ X) → (∀ i, y i ∈ X) →
        @KMonoid.sumOf κ H C ι x = @KMonoid.sumOf κ H C ι y → IsBraided lam X x y) ∧
      (@KMonoid.Generates κ H C X → IsBraidedOver ι lam X) := by
  let M := hP.toClass
  let L : KappaMonoid.KMonoid κ H := KappaMonoid.ModuleClass.instKMonoid M
  have hc : KMonoid.Compat C L := hP.compat
  have : M.IsSummandClosed := ⟨fun a N K h => hsummand a N K h⟩
  have : Fact lam.IsRegular := ⟨hlam⟩
  let S : M.SmallSubclass lam hlk :=
    { carrier := X
      isLambdaSmall := fun a ha => isLambdaSmall_lib (hsmall a ha)
      isLSubset := (hc.isLSubmonoid hlk X).mp hX
      summand_mem := fun {a b} h => hXsummand a b (hc.add a b ▸ h) }
  have key : ∀ x y : ι → H, (∀ i, x i ∈ X) → (∀ i, y i ∈ X) →
      @KMonoid.sumOf κ H C ι x = @KMonoid.sumOf κ H C ι y → IsBraided lam X x y := by
    intro x y hx hy hxy
    let _ : KappaMonoid.LMonoid lam S := KappaMonoid.ModuleClass.SmallSubclass.instLMonoid S
    have hr : range (fun a : S => (a : H)) = X := Subtype.range_coe
    have := isBraided_of_lib_idx hc hlk hι (X := S) (f := fun a : S => (a : H))
      ⟨rfl, fun {ι} hι z => S.coe_lsumOf hι z⟩ (fun x y h => KappaMonoid.theorem_4_3_core S x y h)
      x y (fun i => hr ▸ hx i) (fun i => hr ▸ hy i) hxy
    rw [hr] at this
    exact this
  exact ⟨key, fun hgen => ⟨hX, hgen, key⟩⟩

/-! ## A realisation of `V^κ(R)` is an isomorphism with `projClass` -/

/-- A summand of `R^{(κ)}` is generated by at most `κ` elements. -/
theorem summand_gen (Q : KappaMonoid.Summand R κ) :
    ∃ s : Set Q.1, #s ≤ κ ∧ Submodule.span R s = ⊤ := by
  let π := Submodule.projectionOnto Q.1 (KappaMonoid.Summand.compl R κ Q)
    (KappaMonoid.Summand.isCompl R κ Q)
  refine ⟨range (π ∘ KappaMonoid.freeGen R κ),
    Cardinal.mk_range_le.trans (KappaMonoid.mk_Idx κ).le, ?_⟩
  rw [range_comp, ← Submodule.map_span, KappaMonoid.freeMod_span, Submodule.map_top,
    LinearMap.range_eq_top]
  intro y
  exact ⟨y, congrArg (fun f => f y) (Submodule.projectionOnto_comp_subtype _)⟩

theorem mem_projClass (q : (KappaMonoid.projClass R κ hκ).carrier) :
    Module.Projective R ((KappaMonoid.projClass R κ hκ).rep q) ∧
      ∃ s : Set ((KappaMonoid.projClass R κ hκ).rep q), #s ≤ κ ∧ Submodule.span R s = ⊤ :=
  ⟨KappaMonoid.summand_projective R κ q.out, summand_gen q.out⟩

theorem exists_projClass (hκ : ℵ₀ ≤ κ) (M : ModuleCat.{u} R) [Module.Projective R M]
    {s : Set M} (hs : #s ≤ κ) (hspan : Submodule.span R s = ⊤) :
    ∃ q : (KappaMonoid.projClass R κ hκ).carrier,
      Nonempty ((KappaMonoid.projClass R κ hκ).rep q ≃ₗ[R] M) := by
  obtain ⟨Q, ⟨f⟩⟩ := KappaMonoid.exists_summand_of_projective R κ M s hs hspan
  exact ⟨⟦Q⟧, ⟨(Quotient.mk_out (s := KappaMonoid.summandSetoid R κ) Q).some.trans f⟩⟩

/-- A realisation of `V^κ(R)` is isomorphic to the library's `projClass`. -/
theorem IsVProjOf.exists_iso {H : Type u} {C : KMonoid κ H} {P : H → ModuleCat.{u} R}
    (hP : @IsVProjOf κ R _ H C P) :
    ∃ e : H → (KappaMonoid.projClass R κ C.aleph0_le).carrier,
      (letI := C.toLib; KappaMonoid.KMonoid.IsKHom κ e) ∧ Bijective e ∧
      ∀ h, Nonempty ((KappaMonoid.projClass R κ C.aleph0_le).rep (e h) ≃ₗ[R] P h) := by
  classical
  set V := KappaMonoid.projClass R κ C.aleph0_le
  have hQ : ∀ h, ∃ q : V.carrier, Nonempty (V.rep q ≃ₗ[R] P h) := fun h => by
    have := hP.projective h
    obtain ⟨s, hs, hspan⟩ := hP.gen h
    exact exists_projClass C.aleph0_le (P h) hs hspan
  choose e hrep using hQ
  have hinj : Injective e := fun a b hab =>
    hP.inj a b ⟨(hrep a).some.symm.trans ((V.iso_of_eq hab).some.trans (hrep b).some)⟩
  have hsurj : Surjective e := fun q => by
    obtain ⟨hproj, s, hs, hspan⟩ := mem_projClass q
    obtain ⟨h, ⟨f⟩⟩ := hP.surj (ModuleCat.of R (V.rep q)) hproj ⟨s, hs, hspan⟩
    exact ⟨h, V.eq_of_iso ((hrep h).some.trans f.symm)⟩
  let := C.toLib
  refine ⟨e, ⟨?_, fun x => ?_⟩, ⟨hinj, hsurj⟩, hrep⟩
  · have := hP.zero
    have := V.subsingleton_rep_zero
    exact V.eq_of_iso ((hrep _).some.trans (LinearEquiv.ofSubsingleton _ _))
  · rw [← (KMonoid.compat_toLib C).sum, V.instKMonoid_ksum]
    exact V.eq_of_iso ((hrep _).some.trans ((hP.sum_iso x).some.trans
      ((DFinsupp.mapRange.linearEquiv fun i => (hrep (x i)).some.symm).trans
        (V.dsum_iso (e ∘ x)).some.symm)))

/-- An isomorphism with the library's `projClass` is a realisation of `V^κ(R)`. -/
theorem IsVProjOf.of_iso {H : Type u} (C : KMonoid κ H)
    (e : (KappaMonoid.projClass R κ C.aleph0_le).carrier → H)
    (he : letI := C.toLib; KappaMonoid.KMonoid.IsKHom κ e) (hb : Bijective e) :
    ∃ P : H → ModuleCat.{u} R, @IsVProjOf κ R _ H C P ∧
      ∀ q, Nonempty (P (e q) ≃ₗ[R] (KappaMonoid.projClass R κ C.aleph0_le).rep q) := by
  let := C.toLib
  let V := KappaMonoid.projClass R κ C.aleph0_le
  let g := (Equiv.ofBijective e hb).symm
  have hge : ∀ q, g (e q) = q := (Equiv.ofBijective e hb).symm_apply_apply
  have heg : ∀ h, e (g h) = h := (Equiv.ofBijective e hb).apply_symm_apply
  have hg : KappaMonoid.KMonoid.IsKHom κ g := he.inv hb heg
  refine ⟨fun h => ModuleCat.of R (V.rep (g h)),
    ⟨⟨?_, fun a b ⟨f⟩ => ?_, fun x => ?_⟩, fun h => (mem_projClass (g h)).1,
      fun h => (mem_projClass (g h)).2, fun M hM ⟨s, hs, hspan⟩ => ?_⟩,
    fun q => V.iso_of_eq (hge q)⟩
  · show Subsingleton (V.rep (g 0))
    rw [hg.1]
    exact V.subsingleton_rep_zero
  · rw [← heg a, ← heg b, V.eq_of_iso f]
  · show Nonempty (V.rep (g (C.sum x)) ≃ₗ[R] ⨁ i, V.rep (g (x i)))
    rw [(KMonoid.compat_toLib C).sum, hg.2, V.instKMonoid_ksum]
    exact V.dsum_iso _
  · obtain ⟨q, ⟨f⟩⟩ := exists_projClass C.aleph0_le M hs hspan
    exact ⟨e q, ⟨f.symm.trans (V.iso_of_eq (hge q)).some.symm⟩⟩

/-- `H ≅ V^κ(R)` is the library's `∃ e : V^κ(R) → H, IsKHom κ e ∧ Bijective e`. -/
theorem isoV_iff {H : Type u} (C : KMonoid κ H) :
    @IsoV κ R _ H C ↔ ∃ e : (KappaMonoid.projClass R κ C.aleph0_le).carrier → H,
      (letI := C.toLib; KappaMonoid.KMonoid.IsKHom κ e) ∧ Bijective e := by
  constructor
  · rintro ⟨P, hP⟩
    obtain ⟨e, he, hb, -⟩ := hP.exists_iso
    let := C.toLib
    let E := Equiv.ofBijective e hb
    exact ⟨E.symm, he.inv hb E.apply_symm_apply, E.symm.bijective⟩
  · rintro ⟨e, he, hb⟩
    obtain ⟨P, hP, -⟩ := IsVProjOf.of_iso C e he hb
    exact ⟨P, hP⟩

/-! ## Corollary 4.5 -/

/-- A library braiding of `V^κ(R)` over `V^{λ⁻}(R)` gives, through a realisation, the braiding
and the universal property of Corollary 4.5 in the challenge's terms. -/
theorem corollary_4_5_bridge {H : Type u} (C : KMonoid κ H) (ι : Type u) [LinearOrder ι]
    [WellFoundedLT ι] [NoMaxOrder ι] [SuccOrder ι] (hι : #ι = κ) {P : H → ModuleCat.{u} R}
    (hP : @IsVProjOf κ R _ H C P) {lam : Cardinal.{u}} (hlam : lam.IsRegular)
    (hlk : lam ≤ Order.succ κ)
    (hbr : letI := ((KappaMonoid.projClass R κ C.aleph0_le).lambdaGenPart_isLSubset lam hlam
        hlk).lmonoid hlam
      KappaMonoid.IsBraidedOver lam κ ((KappaMonoid.projClass R κ C.aleph0_le).lambdaGenPart lam)
        (KappaMonoid.projClass R κ C.aleph0_le).carrier hlk (fun a => (a : _))) :
    IsBraidedOver ι lam {h | ∃ s : Set (P h), #s < lam ∧ Submodule.span R s = ⊤} ∧
      @IsUniversalOver.{u, u, t} κ H C lam
        {h | ∃ s : Set (P h), #s < lam ∧ Submodule.span R s = ⊤} := by
  set V := KappaMonoid.projClass R κ C.aleph0_le
  set T : Set H := {h | ∃ s : Set (P h), #s < lam ∧ Submodule.span R s = ⊤}
  obtain ⟨e, he, hb, hrep⟩ := hP.exists_iso
  let := C.toLib
  have hc := KMonoid.compat_toLib C
  have hS := V.lambdaGenPart_isLSubset lam hlam hlk
  let g := (Equiv.ofBijective e hb).symm
  have heg : ∀ q, e (g q) = q := (Equiv.ofBijective e hb).apply_symm_apply
  have hge : ∀ h, g (e h) = h := (Equiv.ofBijective e hb).symm_apply_apply
  have hg : KappaMonoid.KMonoid.IsKHom κ g := he.inv hb heg
  have hT : T = e ⁻¹' V.lambdaGenPart lam := by
    ext h
    exact ⟨fun h' => KappaMonoid.IsLambdaGenerated.of_equiv h' (hrep h).some.symm,
      fun h' => KappaMonoid.IsLambdaGenerated.of_equiv h' (hrep h).some⟩
  have hTs : KappaMonoid.IsLSubset lam hlk T := by
    rw [hT]
    refine ⟨show e 0 ∈ _ by rw [he.1]; exact hS.zero_mem, fun {ι} hι x hx => ?_⟩
    have := KappaMonoid.CardLE.mk' (Order.le_of_lt_succ (hι.trans_le hlk))
    rw [Set.mem_preimage, he.map_sumOf]
    exact hS.sumOf_mem hι _ hx
  have hgen : KappaMonoid.KMonoid.KGenerates κ T := by
    refine (hc.generates T).mp fun h => ?_
    let := hS.lmonoid hlam
    obtain ⟨z, hz⟩ := hbr.generates (e h)
    refine ⟨fun i => g (z i), fun i => Or.inl ?_, ?_⟩
    · rw [hT, Set.mem_preimage, heg]; exact (z i).2
    · rw [hc.sum, ← hge h, hz]
      exact (hg.2 _).symm
  have hsat : ∀ a ∈ T, ∀ b c : H, a = b + c → b ∈ T := by
    intro a ha b c habc
    rw [hT] at ha ⊢
    exact V.lambdaGenPart_summand lam (e a) ha (e b) ⟨e c, by rw [habc, he.map_add]⟩
  have hbr' := KappaMonoid.IsBraidedOver.of_kIso_subset hlam hS hTs hbr he hb
    (fun a ha => by rw [hT] at ha; exact ha) hsat hgen
  let := hTs.lmonoid hlam
  have hr : range (fun a : T => (a : H)) = T := Subtype.range_coe
  constructor
  · have := isBraidedOver_of_lib hc hlk ι hι hbr'
    rw [hr] at this
    exact this
  · have := isUniversalOver_of_lib.{u, u, u, t} hc hlk (hbr'.isUniversalKExtension hlk)
    rw [hr] at this
    exact this

theorem finite_iff_gen (M : ModuleCat.{u} R) :
    Module.Finite R M ↔ ∃ s : Set M, #s < ℵ₀ ∧ Submodule.span R s = ⊤ := by
  rw [Module.finite_def, Submodule.fg_def]
  exact exists_congr fun s => and_congr_left fun _ => Cardinal.lt_aleph0_iff_set_finite.symm

end KappaChallenge
