#!/usr/bin/env python3
"""Generate `Comparator/Solution.lean`: the challenge's theorem statements, copied verbatim from
`Comparator/Challenge.lean`, each with its proof from `Comparator/Bridge/`.

The statements are copied, not retyped, so that they cannot drift from the challenge; the
comparator checks the rest.  `--check` fails if the file on disk is out of date (CI runs this).
"""
import re, sys, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "Comparator/Challenge.lean").read_text()
thms = {m.group(2): m.group(1) for m in
        re.finditer(r"((?:/--(?:(?!-/).)*?-/\n)?theorem (\S+) .*?:=\n)  sorry\n", src, re.S)}

PROOFS = {
"theorem_3_12": """\
  theorem_3_12_bridge.{u, v, t} hι hlk X _ hred""",
"theorem_4_3": """\
  theorem_4_3_bridge _ hι P hP hsummand hlam hlk X hsmall hX hXsummand""",
"corollary_4_5_one": """\
  corollary_4_5_bridge.{u, t} _ ι hι hP hlam hlk
    (KappaMonoid.corollary_4_5.{u, t} R κ _ lam hlam h₁ hlk).1""",
"corollary_4_5_two": """\
  by
  have hset : {h | ∃ s : Set (P h), #s ≤ ℵ₀ ∧ Submodule.span R s = ⊤} =
      {h | ∃ s : Set (P h), #s < ℵ₁ ∧ Submodule.span R s = ⊤} := by
    simp only [Cardinal.lt_aleph_one_iff]
  have hlk : (ℵ₁ : Cardinal.{u}) ≤ Order.succ κ :=
    Cardinal.aleph_one_le_iff.mpr (Order.lt_succ_iff.mpr (KMonoid.aleph0_le H))
  rw [hset]
  exact corollary_4_5_bridge.{u, t} _ ι hι hP Cardinal.isRegular_aleph_one hlk
    (KappaMonoid.corollary_4_5.{u, t} R κ _ ℵ₁ Cardinal.isRegular_aleph_one le_rfl hlk).1""",
"corollary_4_5_three": """\
  by
  have hset : {h | Module.Finite R (P h)} =
      {h | ∃ s : Set (P h), #s < ℵ₀ ∧ Submodule.span R s = ⊤} :=
    Set.ext fun h => finite_iff_gen (P h)
  rw [hset]
  exact corollary_4_5_bridge.{u, t} _ ι hι hP Cardinal.isRegular_aleph0 _
    (KappaMonoid.corollary_4_5_three.{u, t} R κ _ (projectivesAreSumsOfFG_iff.mp hfg)).1""",
"theorem_5_3": """\
  by
  let _ : KappaMonoid.KMonoid ℵ₀ H := KMonoid.toLib ‹_›
  have hg := (generates_iff _ _).mp hgen
  have hn := fun x => mt (generates_iff _ {x}).mpr (hnc x)
  have hre : ∀ {a b c d e : Prop}, ((a ∧ c) ∧ (b ∧ d) ∧ e) ↔ (a ∧ b ∧ c ∧ d ∧ e) :=
    ⟨fun ⟨⟨a, c⟩, ⟨b, d⟩, e⟩ => ⟨a, b, c, d, e⟩, fun ⟨a, b, c, d, e⟩ => ⟨⟨a, c⟩, ⟨b, d⟩, e⟩⟩
  rw [conditions53_iff, conditions53_iff, noMixedForms_iff, isRealizable_iff, hre]
  exact ⟨KappaMonoid.TwoGen.theorem_5_3_sumFG x₁ x₂ hg hn, fun k _ h =>
    (hereditary_iff _ k).mpr ((KappaMonoid.TwoGen.theorem_5_3 x₁ x₂ k hg hn).mpr h)⟩""",
}
assert set(PROOFS) == set(thms), (set(PROOFS) ^ set(thms))

def thm(name):
    return thms[name] + PROOFS[name] + "\n"

out = f"""\
-- Generated by `scripts/comparator_solution.py`: the theorems of `Comparator/Challenge.lean`,
-- verbatim, with their proofs.  Do not edit; edit the script.
import Comparator.Defs
import Comparator.Bridge.Main

/-!
# The main results of Nazemian–Smertnig: solution

The comparator's solution module.  The definitions are `Comparator/Defs.lean`, the challenge's own
definitions verbatim; the proofs are read off the library through `Comparator/Bridge/`.
-/

universe u v w t

open Cardinal Set Function DirectSum

namespace KappaChallenge

open KMonoid

variable {{κ : Cardinal.{{u}}}} {{H : Type v}} [KMonoid κ H]
variable {{ι : Type u}} [LinearOrder ι] [WellFoundedLT ι] [NoMaxOrder ι] [SuccOrder ι]

{thm("theorem_3_12")}
section Modules

variable (R : Type u) [Ring R]

{thm("theorem_4_3")}
{thm("corollary_4_5_one")}
{thm("corollary_4_5_two")}
{thm("corollary_4_5_three")}
end Modules

section TwoGen

variable {{H : Type u}} [KMonoid (ℵ₀ : Cardinal.{{u}}) H]

{thm("theorem_5_3")}
end TwoGen

end KappaChallenge
"""

dst = root / "Comparator/Solution.lean"
if "--check" in sys.argv:
    if not dst.exists() or dst.read_text() != out:
        sys.exit("Comparator/Solution.lean is out of date: run scripts/comparator_solution.py")
else:
    dst.write_text(out)
