#!/usr/bin/env python3
"""Generate `Comparator/Defs.lean` from `Comparator/Challenge.lean`.

The comparator checks that every declaration the challenge's theorems mention is identical in the
solution's environment, so the solution needs the challenge's definitions verbatim.  `Defs.lean`
is the challenge with its theorems (a docstring, `theorem`, and a `sorry` body) removed; the
solution imports it.  `--check` fails if the file on disk is out of date (CI runs this).
"""
import re, sys, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "Comparator/Challenge.lean").read_text()

# a theorem: optional docstring, `theorem ...`, ending in a line `  sorry`
pat = re.compile(r"(/--(?:(?!-/).)*?-/\n)?theorem .*?\n  sorry\n\n?", re.S)
body, n = pat.subn("", src)
assert n > 0 and "sorry" not in body, "unexpected challenge layout"
header = ("-- Generated by `scripts/comparator_defs.py` from `Comparator/Challenge.lean`: its\n"
          "-- definitions, without its theorems.  Do not edit.\n")
out = header + body

dst = root / "Comparator/Defs.lean"
if "--check" in sys.argv:
    if not dst.exists() or dst.read_text() != out:
        sys.exit("Comparator/Defs.lean is out of date: run scripts/comparator_defs.py")
else:
    dst.write_text(out)
