/-
Example 2.13 of

  Zahra Nazemian and Daniel Smertnig,
  *A monoid-theoretical approach to infinite direct-sum decompositions of modules*,

the two clauses not covered by `ProjOrderUnit.lean` (`[R]` is a faithful order-unit) and
`Projective.lean` (Kaplansky's theorem).

* **Progenerators.**  The class `[P]` of a progenerator `P` is a faithful order-unit of `V^κ(R)`
  (`isFaithful_of_isProgenerator`), and an order-unit of `V(R)` in the sense of commutative monoids
  (`exists_add_eq_nsmul_of_isProgenerator`).  The module theory reduces to `[P] ≼ m [R]` and
  `[R] ≼ n [P]`; the rest is `KMonoid.IsFaithful.of_le_nsmul`.
* **The size filtration.**  With respect to `u = [R]`, `H_α = V^α(R)` for every infinite `α ≤ κ`
  (`part_unitClass_eq_of_aleph0_le`) and `H_0 = V(R)` (`part_unitClass_zero`).  Here `V^α(R)` is the
  subclass `lambdaGenPart (α⁺)` of classes generated by at most `α` elements, and `V(R)` — the
  finitely generated ones — is `lambdaGenPart ℵ₀`.  The key is `le_cmul_unitClass_iff`:
  `[M] ≼ β [R]` exactly when `M` is generated by at most `β` elements.
-/
import KappaMonoid.Core.OrderUnitTransfer
import KappaMonoid.Modules.Corollary47

universe u

open Cardinal Function Set DirectSum

namespace KappaMonoid

namespace Projective

variable (R : Type u) [Ring R]

/-! ## Progenerators -/

/-- A **progenerator**: a finitely generated projective module `M` that is a generator.  Since
`R` is cyclic, `M` is a generator exactly when `R` is a homomorphic image of some finite power
`M^n`, which is the form recorded here; as `R` is projective such a surjection splits, so
equivalently `R` is a direct summand of `M^n`. -/
def IsProgenerator (M : Type u) [AddCommGroup M] [Module R M] : Prop :=
  Module.Projective R M ∧ Module.Finite R M ∧
    ∃ n : ℕ, ∃ f : (Fin n → M) →ₗ[R] R, Function.Surjective f

variable {R} in
/-- Being a progenerator is invariant under isomorphism. -/
theorem IsProgenerator.of_equiv {M N : Type u} [AddCommGroup M] [Module R M] [AddCommGroup N]
    [Module R N] (h : IsProgenerator R M) (e : M ≃ₗ[R] N) : IsProgenerator R N := by
  obtain ⟨hproj, hfin, n, f, hf⟩ := h
  refine ⟨Module.Projective.of_equiv' e, Module.Finite.equiv e, n,
    f.comp (LinearEquiv.piCongrRight fun _ : Fin n => e.symm).toLinearMap, ?_⟩
  exact hf.comp (LinearEquiv.piCongrRight fun _ : Fin n => e.symm).surjective

/-- `R` itself is a progenerator. -/
theorem isProgenerator_self : IsProgenerator R R :=
  ⟨inferInstance, inferInstance, 1, LinearMap.proj (R := R) (φ := fun _ : Fin 1 => R) 0,
    fun r => ⟨fun _ => r, rfl⟩⟩

variable (κ : Cardinal.{u}) (hκ : ℵ₀ ≤ κ)

/-! ## `[M] ≼ β [R]` means that `M` is generated by `β` elements -/

/-- **`x ≼ β [R]` exactly when the representative of `x` is generated by at most `β`
elements**, for any cardinal `β ≤ κ`, finite or infinite.

A summand of `R^{(β)}` is a quotient of it, hence generated by the images of the `β` standard
generators; conversely a projective module spanned by a family indexed by `s` is a summand of
`R^{(s)}`, and `#s ≤ β` gives `#s [R] ≼ β [R]`. -/
theorem le_cmul_unitClass_iff (k : Idx κ) (x : (projClass R κ hκ).carrier) {β : Cardinal.{u}}
    (hβ : β ≤ κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    x ≼ KMonoid.cmul (κ := κ) β hβ (unitClass R κ hκ k) ↔
      ∃ s : Set ((projClass R κ hκ).rep x), #s ≤ β ∧ Submodule.span R s = ⊤ := by
  let := (projClass R κ hκ).instKMonoid hκ
  constructor
  · rintro ⟨c, hc⟩
    -- `rep x × rep c ≅ R^{(β)}`, and the first projection is onto
    have e : ((projClass R κ hκ).rep x × (projClass R κ hκ).rep c) ≃ₗ[R] ⨁ _ : Idx β, R :=
      ((projClass R κ hκ).rep_add hκ x c).some.symm.trans
        (((projClass R κ hκ).iso_of_eq hc).some.trans (rep_cmul_unitClass R κ hκ hβ k).some)
    set π : (⨁ _ : Idx β, R) →ₗ[R] (projClass R κ hκ).rep x :=
      (LinearMap.fst R ((projClass R κ hκ).rep x) ((projClass R κ hκ).rep c)).comp
        (e.symm : (⨁ _ : Idx β, R) →ₗ[R] _) with hπdef
    have hsurj : Function.Surjective π := fun w => ⟨e ⟨w, 0⟩, by simp [hπdef]⟩
    refine ⟨π '' Set.range (freeGen R β),
      Cardinal.mk_image_le.trans (Cardinal.mk_range_le.trans (le_of_eq (mk_Idx β))), ?_⟩
    rw [← Submodule.map_span, freeMod_span R β, Submodule.map_top,
      LinearMap.range_eq_top.mpr hsurj]
  · rintro ⟨s, hs, hspan⟩
    obtain ⟨c, hc⟩ := exists_add_eq_cmul_unitClass_family R κ hκ k x (hs.trans hβ)
      (Subtype.val : s → (projClass R κ hκ).rep x) (by rw [Subtype.range_coe]; exact hspan)
    exact AddLe.trans ⟨c, hc⟩ (KMonoid.cmul_le_cmul (hs.trans hβ) hβ hs _)

/-- The finite form of `le_cmul_unitClass_iff`: `x ≼ n [R]` for some `n ∈ ℕ₀` exactly when the
representative of `x` is finitely generated. -/
theorem exists_le_nsmul_unitClass_iff (k : Idx κ) (x : (projClass R κ hκ).carrier) :
    letI := (projClass R κ hκ).instKMonoid hκ
    (∃ n : ℕ, x ≼ n • unitClass R κ hκ k) ↔ Module.Finite R ((projClass R κ hκ).rep x) := by
  let := (projClass R κ hκ).instKMonoid hκ
  have hnκ : ∀ n : ℕ, ((n : ℕ) : Cardinal.{u}) ≤ κ := fun n =>
    le_trans (le_of_lt Cardinal.natCast_lt_aleph0) hκ
  constructor
  · rintro ⟨n, hn⟩
    rw [← KMonoid.cmul_natCast (κ := κ) (unitClass R κ hκ k) n] at hn
    obtain ⟨s, hs, hspan⟩ := (le_cmul_unitClass_iff R κ hκ k x (hnκ n)).mp hn
    exact ⟨Submodule.fg_def.mpr ⟨s, Cardinal.lt_aleph0_iff_set_finite.mp
      (lt_of_le_of_lt hs Cardinal.natCast_lt_aleph0), hspan⟩⟩
  · intro hfin
    obtain ⟨t, ht⟩ := hfin.fg_top
    obtain ⟨n, hn⟩ := Cardinal.lt_aleph0.mp
      (Cardinal.lt_aleph0_iff_set_finite.mpr t.finite_toSet :
        #(↑t : Set ((projClass R κ hκ).rep x)) < ℵ₀)
    refine ⟨n, ?_⟩
    rw [← KMonoid.cmul_natCast (κ := κ) (unitClass R κ hκ k) n]
    exact (le_cmul_unitClass_iff R κ hκ k x (hnκ n)).mpr ⟨↑t, le_of_eq hn, ht⟩

/-! ## `[R] ≼ [M]` when `R` is an image of `M` -/

/-- If the representative of `a` maps onto `R`, then `[R] ≼ a`: the surjection splits, and its
kernel is the complement. -/
theorem unitClass_le_of_surjective (k : Idx κ) (a : (projClass R κ hκ).carrier)
    (f : (projClass R κ hκ).rep a →ₗ[R] R) (hf : Function.Surjective f) :
    letI := (projClass R κ hκ).instKMonoid hκ
    unitClass R κ hκ k ≼ a := by
  let := (projClass R κ hκ).instKMonoid hκ
  obtain ⟨σ, -, hσinj, hcompl⟩ := ForMathlib.exists_isCompl_range_of_surjective f hf
  obtain ⟨c, hc⟩ := (projClass R κ hκ).exists_class_of_summand a (LinearEquiv.refl R _)
    hcompl.symm
  exact ⟨c, (projClass R κ hκ).add_eq_of_relCompl hκ hcompl.disjoint
    (codisjoint_iff.mp hcompl.codisjoint)
    ⟨(rep_unitClass R κ hκ k).some.trans (LinearEquiv.ofInjective σ hσinj)⟩ hc
    ⟨Submodule.topEquiv.symm⟩⟩

/-- The representative of `n • a` is the `n`-th power of the representative of `a`. -/
theorem rep_nsmul (a : (projClass R κ hκ).carrier) (n : ℕ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    Nonempty ((projClass R κ hκ).rep (n • a) ≃ₗ[R] (Fin n → (projClass R κ hκ).rep a)) := by
  let := (projClass R κ hκ).instKMonoid hκ
  have hι : #(ULift.{u} (Fin n)) ≤ κ := (Cardinal.lt_aleph0_of_finite _).le.trans hκ
  have hcard : ((n : ℕ) : Cardinal.{u}) = #(ULift.{u} (Fin n)) := by
    rw [Cardinal.mk_fintype, Fintype.card_ulift, Fintype.card_fin]
  have heq : n • a = ∑[≤ κ] _ : ULift.{u} (Fin n), a := by
    rw [← KMonoid.cmul_natCast (κ := κ) a n, ← KMonoid.cmul_eq_sumOf hι a]
    exact KMonoid.cmul_congr hcard _ _ a
  exact ⟨((projClass R κ hκ).iso_of_eq heq).some.trans
    (((projClass R κ hκ).rep_sumOf hκ hι _).some.trans
      ((DirectSum.linearEquivFunOnFintype R (ULift.{u} (Fin n))
          (fun _ => (projClass R κ hκ).rep a)).trans
        (LinearEquiv.funCongrLeft R ((projClass R κ hκ).rep a) Equiv.ulift.symm)))⟩

/-! ## Example 2.13: the class of a progenerator is a faithful order-unit -/

/-- The class of a progenerator lies between finite multiples of `[R]` in both directions:
`[R] ≼ n [P]` because `R` is an image of `P^n`, and `[P] ≼ m [R]` because `P` is finitely
generated. -/
theorem le_nsmul_of_isProgenerator (k : Idx κ) (p : (projClass R κ hκ).carrier)
    (hp : IsProgenerator R ((projClass R κ hκ).rep p)) :
    letI := (projClass R κ hκ).instKMonoid hκ
    (∃ n : ℕ, unitClass R κ hκ k ≼ n • p) ∧ ∃ m : ℕ, p ≼ m • unitClass R κ hκ k := by
  let := (projClass R κ hκ).instKMonoid hκ
  obtain ⟨-, hfin, n, f, hf⟩ := hp
  refine ⟨⟨n, ?_⟩, (exists_le_nsmul_unitClass_iff R κ hκ k p).mpr hfin⟩
  obtain ⟨e⟩ := rep_nsmul R κ hκ p n
  exact unitClass_le_of_surjective R κ hκ k (n • p) (f.comp (e : _ →ₗ[R] _))
    (hf.comp e.surjective)

/-- **Example 2.13** (progenerators): if `R` is nonzero and the representative of `p` is a
progenerator, then `p` is a faithful order-unit of `V^κ(R)`.  In particular the order-unit `[R]`
is not unique.

Paper proof: stated without proof in the paper.  Since `P` is finitely generated, `P ⊕ Q ≅ R^m`
for some `Q`, and since `P` is a generator, `P^n ≅ R ⊕ Q'` for some `Q'`; thus `[P] ≼ m [R]` and
`[R] ≼ n [P]`, and `KMonoid.IsFaithful.of_le_nsmul` transfers faithfulness from `[R]`
(`isFaithful_unitClass`) to `[P]`. -/
theorem isFaithful_of_isProgenerator [Nontrivial R] (p : (projClass R κ hκ).carrier)
    (hp : IsProgenerator R ((projClass R κ hκ).rep p)) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KMonoid.IsFaithful (κ := κ) p := by
  let := (projClass R κ hκ).instKMonoid hκ
  obtain ⟨k⟩ := nonempty_Idx hκ
  obtain ⟨⟨n, hn⟩, ⟨m, hm⟩⟩ := le_nsmul_of_isProgenerator R κ hκ k p hp
  exact (isFaithful_unitClass R κ hκ k).of_le_nsmul hn hm

/-- **Example 2.13** (progenerators), for a module given up to isomorphism: every progenerator `P`
has a class `[P]` in `V^κ(R)`, it lies in `V(R)`, and for nonzero `R` it is a faithful order-unit
of `V^κ(R)`. -/
theorem exists_isFaithful_of_isProgenerator [Nontrivial R] (P : Type u) [AddCommGroup P]
    [Module R P] (hP : IsProgenerator R P) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ p : (projClass R κ hκ).carrier, p ∈ (projClass R κ hκ).lambdaGenPart ℵ₀ ∧
      Nonempty ((projClass R κ hκ).rep p ≃ₗ[R] P) ∧ KMonoid.IsFaithful (κ := κ) p := by
  let := (projClass R κ hκ).instKMonoid hκ
  obtain ⟨p, hpV, ⟨e⟩⟩ := exists_class_of_fg_projective R κ hκ P hP.1 hP.2.1
  exact ⟨p, hpV, ⟨e⟩, isFaithful_of_isProgenerator R κ hκ p (hP.of_equiv e.symm)⟩

/-! ## Example 2.13: the size filtration is `H_α = V^α(R)` -/

/-- **Example 2.13** (the filtration, infinite pieces): with respect to the order-unit `[R]`,
`H_α = V^α(R)` for every infinite cardinal `α ≤ κ`, where `V^α(R)` is the subclass of classes
generated by at most `α` elements, i.e. by fewer than `α⁺`.

Paper proof: stated without proof in the paper.  For infinite `α`, `x ∈ H_α` means `x ≼ α [R]`
(`KMonoid.mem_part_iff_of_aleph0_le`), which by `le_cmul_unitClass_iff` means that the
representative is generated by at most `α` elements. -/
theorem part_unitClass_eq_of_aleph0_le (k : Idx κ) {α : Cardinal.{u}} (hα0 : ℵ₀ ≤ α)
    (hα : α ≤ κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KMonoid.part (κ := κ) (unitClass R κ hκ k) α
      = (projClass R κ hκ).lambdaGenPart (Order.succ α) := by
  let := (projClass R κ hκ).instKMonoid hκ
  ext x
  rw [KMonoid.mem_part_iff_of_aleph0_le (isOrderUnit_unitClass R κ hκ k) hα0 hα,
    le_cmul_unitClass_iff R κ hκ k x hα]
  exact ⟨fun ⟨s, hs, hspan⟩ => ⟨s, Order.lt_succ_iff.mpr hs, hspan⟩,
    fun ⟨s, hs, hspan⟩ => ⟨s, Order.lt_succ_iff.mp hs, hspan⟩⟩

/-- **Example 2.13** (the filtration, finite pieces): with respect to the order-unit `[R]`,
`H_α = V(R)` — the classes of finitely generated projective modules — for every finite `α`.

Paper proof: stated without proof in the paper.  For finite `α`, `x ∈ H_α` means `x ≼ n [R]` for
some `n ∈ ℕ₀` (`KMonoid.mem_part_iff_of_lt_aleph0`), which by `exists_le_nsmul_unitClass_iff`
means that the representative is finitely generated. -/
theorem part_unitClass_eq_of_lt_aleph0 (k : Idx κ) {α : Cardinal.{u}} (hα : α < ℵ₀) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KMonoid.part (κ := κ) (unitClass R κ hκ k) α = (projClass R κ hκ).lambdaGenPart ℵ₀ := by
  let := (projClass R κ hκ).instKMonoid hκ
  ext x
  rw [KMonoid.mem_part_iff_of_lt_aleph0 (isOrderUnit_unitClass R κ hκ k) hα,
    exists_le_nsmul_unitClass_iff R κ hκ k x]
  exact ⟨isLambdaGenerated_aleph0_of_finite, IsLambdaGenerated.finite_aleph0⟩

/-- **Example 2.13**: `H_0 = V(R)` with respect to the order-unit `[R]`. -/
theorem part_unitClass_zero (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KMonoid.part (κ := κ) (unitClass R κ hκ k) 0 = (projClass R κ hκ).lambdaGenPart ℵ₀ :=
  part_unitClass_eq_of_lt_aleph0 R κ hκ k Cardinal.aleph0_pos

/-- **Example 2.13**: `H_{ℵ₀} = V^{ℵ₀}(R)` with respect to the order-unit `[R]` — the classes of
countably generated projective modules, i.e. those generated by fewer than `ℵ₁` elements. -/
theorem part_unitClass_aleph0 (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KMonoid.part (κ := κ) (unitClass R κ hκ k) ℵ₀ = (projClass R κ hκ).lambdaGenPart ℵ₁ := by
  rw [← Cardinal.succ_aleph0]
  exact part_unitClass_eq_of_aleph0_le R κ hκ k le_rfl hκ

/-! ## Example 2.13: progenerators in `V(R)` -/

/-- **§2.2, before Definition 2.12**: in `V(R)`, the class of every progenerator is an order-unit
in the sense of commutative monoids.  `V(R)` is the part `lambdaGenPart ℵ₀` of `V^κ(R)`: for every
`x` in it there are `n ∈ ℕ₀` and `c`, again in `V(R)`, with `x + c = n [P]`.

Paper proof: stated without proof in the paper.  `x ≼ m [R]` since `x` is finitely generated and
`[R] ≼ n [P]` since `P` is a generator, so `x ≼ (m n) [P]`; a complement `c` of `x` in `(m n) [P]`
is below `(m n n') [R]`, where `[P] ≼ n' [R]`, and so is again finitely generated. -/
theorem exists_add_eq_nsmul_of_isProgenerator (p : (projClass R κ hκ).carrier)
    (hp : IsProgenerator R ((projClass R κ hκ).rep p)) (x : (projClass R κ hκ).carrier)
    (hx : x ∈ (projClass R κ hκ).lambdaGenPart ℵ₀) :
    letI := (projClass R κ hκ).instKMonoid hκ
    ∃ (n : ℕ) (c : (projClass R κ hκ).carrier),
      c ∈ (projClass R κ hκ).lambdaGenPart ℵ₀ ∧ x + c = n • p := by
  let := (projClass R κ hκ).instKMonoid hκ
  obtain ⟨k⟩ := nonempty_Idx hκ
  have hu := isOrderUnit_unitClass R κ hκ k
  have hV : ∀ y, y ∈ (projClass R κ hκ).lambdaGenPart ℵ₀ ↔
      ∃ n : ℕ, y ≼ n • unitClass R κ hκ k := fun y => by
    rw [← part_unitClass_zero R κ hκ k]
    exact KMonoid.mem_part_iff_of_lt_aleph0 hu Cardinal.aleph0_pos
  obtain ⟨⟨n, hn⟩, ⟨m', hm'⟩⟩ := le_nsmul_of_isProgenerator R κ hκ k p hp
  obtain ⟨m, hm⟩ := (hV x).mp hx
  obtain ⟨c, hc⟩ := KMonoid.le_mul_nsmul_of_le_nsmul hm hn
  refine ⟨m * n, c, (hV c).mpr ⟨m * n * m', ?_⟩, hc⟩
  exact KMonoid.le_mul_nsmul_of_le_nsmul ⟨x, by rw [add_comm, hc]⟩ hm'

end Projective

end KappaMonoid
