/-
Example 2.13 of

  Zahra Nazemian and Daniel Smertnig,
  *A monoid-theoretical approach to infinite direct-sum decompositions of modules*.

In `V^κ(R)` the class of `R` is a faithful order-unit.  That it is an order-unit is immediate
from the construction of `V^κ(R)` as the direct summands of `R^{(κ)}`: a summand and its
complement add up to `κ·[R] = [R^{(κ)}]`.  Faithfulness is where the invariance of infinite rank
enters, as axiom `mk_le_of_span_eq_top`.

(The remaining clause of Example 2.13, that `V^κ(R)` is generated by `V^{ℵ₀}(R)`, is Kaplansky's
theorem and is already proved in `ModuleClass.lean` as `kGenerates_of_countablyGenerated`.)
-/
import KappaMonoid.Modules
import KappaMonoid.Core.OrderUnit
import KappaMonoid.ForMathlib.FreeRank

universe u

open Cardinal Function Set DirectSum

namespace KappaMonoid

namespace Projective

variable (R : Type u) [Ring R] (κ : Cardinal.{u})

/-! ## `R` as a direct summand of `R^{(κ)}` -/

/-- The copy of `R` inside `R^{(κ)}` given by the `k`-th coordinate, as a summand. -/
noncomputable def unitSummand (k : Idx κ) : Summand R κ :=
  ⟨dsPart R (fun _ : Idx κ => R) {k},
    ⟨dsPart R (fun _ : Idx κ => R) {k}ᶜ,
      ⟨dsPart_disjoint R _ disjoint_compl_right,
        codisjoint_iff.mpr (by
          rw [← dsPart_union, Set.union_compl_self, dsPart_univ])⟩⟩⟩

/-- The `k`-th coordinate copy of `R` really is `R`. -/
noncomputable def unitSummandIso (k : Idx κ) : ↥(unitSummand R κ k).1 ≃ₗ[R] R := by
  classical
  letI : Unique ↥({k} : Set (Idx κ)) := Set.uniqueSingleton k
  have e2 : (⨁ _ : ({k} : Set (Idx κ)), R) ≃ₗ[R] R :=
    directSumEquivOfSubsingleton R (fun _ : ({k} : Set (Idx κ)) => R)
      ⟨k, Set.mem_singleton k⟩ fun i hi => absurd (Subsingleton.elim i _) hi
  exact (dsPartIso R (fun _ : Idx κ => R) {k}).trans e2

/-- The whole of `R^{(κ)}`, as a summand. -/
noncomputable def topSummand : Summand R κ := ⟨⊤, ⟨⊥, isCompl_top_bot⟩⟩

/-! ## `[R]` and `κ·[R]` -/

variable (hκ : ℵ₀ ≤ κ)

/-- **The class of `R`** in `V^κ(R)`. -/
noncomputable def unitClass (k : Idx κ) : (projClass R κ hκ).carrier := ⟦unitSummand R κ k⟧

/-- The representative of `[R]` is `R`. -/
theorem rep_unitClass (k : Idx κ) :
    Nonempty ((projClass R κ hκ).rep (unitClass R κ hκ k) ≃ₗ[R] R) :=
  ⟨((Quotient.mk_out (s := summandSetoid R κ) (unitSummand R κ k)).some).trans
    (unitSummandIso R κ k)⟩

/-- `α` copies of `[R]` are represented by the free module on `Idx α`. -/
theorem rep_cmul_unitClass {α : Cardinal.{u}} (hα : α ≤ κ) (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    Nonempty ((projClass R κ hκ).rep
      (KMonoid.cmul (κ := κ) α hα (unitClass R κ hκ k)) ≃ₗ[R] ⨁ _ : Idx α, R) := by
  letI := (projClass R κ hκ).instKMonoid hκ
  obtain ⟨e⟩ := (projClass R κ hκ).rep_sumOf hκ (le_of_eq_of_le (mk_Idx α) hα)
    (fun _ : Idx α => unitClass R κ hκ k)
  exact ⟨e.trans (DirectSum.congrLinearEquiv fun _ => (rep_unitClass R κ hκ k).some)⟩

/-- `κ` copies of `[R]` are the whole of `R^{(κ)}`. -/
theorem rep_cmul_top_unitClass (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    Nonempty ((projClass R κ hκ).rep (KMonoid.cmul (κ := κ) κ le_rfl (unitClass R κ hκ k))
      ≃ₗ[R] ↥(⊤ : Submodule R (freeMod R κ))) := by
  letI := (projClass R κ hκ).instKMonoid hκ
  exact ⟨(rep_cmul_unitClass R κ hκ le_rfl k).some.trans Submodule.topEquiv.symm⟩

/-! ## Example 2.13: `[R]` is an order-unit -/

/-- **Example 2.13**, first half: `[R]` is an order-unit of `V^κ(R)`.

Every class is that of a summand `P` of `R^{(κ)}`; its chosen complement `Q` gives
`[P] + [Q] = [R^{(κ)}] = κ·[R]`. -/
theorem isOrderUnit_unitClass (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KMonoid.IsOrderUnit (κ := κ) (unitClass R κ hκ k) := by
  letI := (projClass R κ hκ).instKMonoid hκ
  intro x
  set P : Summand R κ := x.out with hPdef
  set Q : Submodule R (freeMod R κ) := Summand.compl R κ P with hQdef
  have hPQ : IsCompl P.1 Q := Summand.isCompl R κ P
  refine ⟨⟦(⟨Q, ⟨P.1, hPQ.symm⟩⟩ : Summand R κ)⟧, ?_⟩
  refine (projClass R κ hκ).add_eq_of_relCompl hκ hPQ.disjoint
    (codisjoint_iff.mp hPQ.codisjoint) ?_ ?_ (rep_cmul_top_unitClass R κ hκ k)
  · exact ⟨LinearEquiv.refl R _⟩
  · exact ⟨(Quotient.mk_out (s := summandSetoid R κ) (⟨Q, ⟨P.1, hPQ.symm⟩⟩ : Summand R κ)).some⟩

/-! ## Example 2.13: `[R]` is faithful

This is where the invariance of infinite rank is used.  If `β·[R] ≼ α·[R]` then `R^{(β)}` is a
direct summand of `R^{(α)}`, hence a quotient of it, hence generated by `α` many elements; for
infinite `β` the axiom `mk_le_of_span_eq_top` then forces `β ≤ α`. -/

/-- The standard basis of `R^{(ι)}`. -/
noncomputable def freeBasis (ι : Type u) : Module.Basis ι R (⨁ _ : ι, R) := by
  classical
  exact (Finsupp.basisSingleOne (R := R) (ι := ι)).map (finsuppLEquivDirectSum R R ι)

/-- A surjection onto `R^{(ι)}` from a module spanned by `S` exhibits `R^{(ι)}` as spanned by the
image of `S`; with `ι` infinite the axiom bounds `#ι` by `#S`. -/
theorem mk_le_of_surjective [Nontrivial R] {ι : Type u} [Infinite ι] {W : Type u} [AddCommGroup W]
    [Module R W] (f : W →ₗ[R] (⨁ _ : ι, R)) (hf : Function.Surjective f) {S : Set W}
    (hS : Submodule.span R S = ⊤) : #ι ≤ #S := by
  have himg : Submodule.span R (⇑f '' S) = ⊤ := by
    rw [Submodule.span_image, hS, Submodule.map_top, LinearMap.range_eq_top.mpr hf]
  exact le_trans (mk_le_of_span_eq_top (freeBasis R ι) himg) Cardinal.mk_image_le

/-- **Example 2.13**, second half: `[R]` is a *faithful* order-unit of `V^κ(R)`. -/
theorem isFaithful_unitClass [Nontrivial R] (k : Idx κ) :
    letI := (projClass R κ hκ).instKMonoid hκ
    KMonoid.IsFaithful (κ := κ) (unitClass R κ hκ k) := by
  letI := (projClass R κ hκ).instKMonoid hκ
  refine ⟨isOrderUnit_unitClass R κ hκ k, ?_⟩
  rintro α β hα hβ hαβ hβ0 ⟨c, hc⟩
  haveI : Infinite (Idx β) := infinite_Idx hβ0
  -- `R^{(β)} × rep c ≅ R^{(α)}`
  set B := KMonoid.cmul (κ := κ) β hβ (unitClass R κ hκ k) with hBdef
  have e1 : ((⨁ _ : Idx β, R) × (projClass R κ hκ).rep c)
      ≃ₗ[R] ((projClass R κ hκ).rep B × (projClass R κ hκ).rep c) :=
    LinearEquiv.prodCongr (rep_cmul_unitClass R κ hκ hβ k).some.symm (LinearEquiv.refl R _)
  have e2 : ((projClass R κ hκ).rep B × (projClass R κ hκ).rep c)
      ≃ₗ[R] (projClass R κ hκ).rep (B + c) :=
    ((projClass R κ hκ).rep_add hκ B c).some.symm
  have e3 : (projClass R κ hκ).rep (B + c)
      ≃ₗ[R] (projClass R κ hκ).rep (KMonoid.cmul (κ := κ) α hα (unitClass R κ hκ k)) :=
    ((projClass R κ hκ).iso_of_eq hc).some
  have e : ((⨁ _ : Idx β, R) × (projClass R κ hκ).rep c) ≃ₗ[R] (⨁ _ : Idx α, R) :=
    e1.trans (e2.trans (e3.trans (rep_cmul_unitClass R κ hκ hα k).some))
  -- `R^{(α)}` is spanned by `α` many elements, and they map onto `R^{(β)}`
  have hspan : Submodule.span R (Set.range (freeGen R α)) = ⊤ := freeMod_span R α
  have hsurj : Function.Surjective
      ((LinearMap.fst R (⨁ _ : Idx β, R) ((projClass R κ hκ).rep c)).comp
        (e.symm : (⨁ _ : Idx α, R) →ₗ[R] _)) := by
    intro w
    exact ⟨e ⟨w, 0⟩, by simp⟩
  have hmk := mk_le_of_surjective R _ hsurj hspan
  rw [mk_Idx] at hmk
  exact absurd (hmk.trans ((Cardinal.mk_range_le).trans (le_of_eq (mk_Idx α)))) (not_le_of_gt hαβ)

end Projective

end KappaMonoid
