/-
Proposition 2.16 of

  Zahra Nazemian and Daniel Smertnig,
  *A monoid-theoretical approach to infinite direct-sum decompositions of modules*:

every cyclic `κ`-monoid generated by a faithful order-unit is `V^κ(𝓕^κ)` for some ring.

The paper's argument: by Leavitt's theorem there is a ring `R` whose finitely generated free
modules realise the size-zero submonoid `C₀`; both `V^κ(𝓕^κ)` and `H` are cyclic `κ`-monoids
generated by faithful order-units with the same `C₀`, so Lemma 2.15 identifies them.

Here that comparison is made explicit by the map `a ↦ #(basis a) · u`.  It is well defined
exactly because the two relations agree: on infinite ranks both sides are injective (invariance
of infinite rank on one side, faithfulness on the other), and on finite ranks the ring is chosen
so that `R^k ≅ R^l` iff `k·u = l·u`.
-/
import KappaMonoid.Modules.Rings.FreeUnit
import KappaMonoid.Core.Cyclic
import KappaMonoid.ForMathlib.FreeRank
import KappaMonoid.ForMathlib.CyclicMonoid
import KappaMonoid.Modules.Rings.Leavitt

universe u

open Cardinal Function Set DirectSum

namespace KappaMonoid

open KMonoid

/-! ## Rings realising a prescribed relation on ranks -/

/-- A ring whose finitely generated free modules realise the relation `P`. -/
structure Realiser (P : ℕ → ℕ → Prop) where
  /-- The realising ring. -/
  R : Type u
  [ring : Ring R]
  [nontrivial : Nontrivial R]
  /-- `R^k ≅ R^l` exactly when `P k l`. -/
  iso_iff : ∀ k l : ℕ, Nonempty ((⨁ _ : Fin k, R) ≃ₗ[R] (⨁ _ : Fin l, R)) ↔ P k l

attribute [instance] Realiser.ring Realiser.nontrivial

/-- `ℚ` realises equality: a field has invariant basis number. -/
noncomputable def realiserEq : Realiser.{u} (· = ·) where
  R := ULift.{u} ℚ
  iso_iff k l := by
    constructor
    · rintro ⟨e⟩
      have e' : (Fin k → ULift.{u} ℚ) ≃ₗ[ULift.{u} ℚ] (Fin l → ULift.{u} ℚ) :=
        (DirectSum.linearEquivFunOnFintype (ULift.{u} ℚ) (Fin k) fun _ => ULift.{u} ℚ).symm.trans
          (e.trans (DirectSum.linearEquivFunOnFintype (ULift.{u} ℚ) (Fin l)
            fun _ => ULift.{u} ℚ))
      have := e'.finrank_eq
      rwa [Module.finrank_fin_fun, Module.finrank_fin_fun] at this
    · rintro rfl
      exact ⟨LinearEquiv.refl _ _⟩

/-- Leavitt's theorem, as a `Realiser` for `CyclicRel m n`.  `1 ≤ m` is necessary: `C_{0,n}` is a
group, and only the zero ring could realise it. -/
noncomputable def realiserCyclicRel (m n : ℕ) (hm : 1 ≤ m) (hn : 1 ≤ n) :
    Realiser.{u} (CyclicRel m n) where
  R := (leavittData m n hm hn).R
  iso_iff := (leavittData m n hm hn).iso_iff

/-! ## Comparing the two relations

Fix a `κ`-monoid `H` with a faithful order-unit `u`, and a ring `R` whose finitely generated free
modules match the finite multiples of `u`.  Then two free modules are isomorphic exactly when the
corresponding multiples of `u` agree: on infinite ranks because both sides are injective, and on
finite ranks by the choice of `R`. -/

section Compare

variable {κ : Cardinal.{u}} {R : Type u} [Ring R] [Nontrivial R] {H : Type u} [KMonoid κ H]
  {u : H}

open FreeMod

/-- A finite cardinal, as a natural number. -/
theorem exists_natCast_of_lt_aleph0 {c : Cardinal.{u}} (h : c < ℵ₀) : ∃ n : ℕ, c = n :=
  Cardinal.lt_aleph0.mp h

theorem natCast_le (hκ : ℵ₀ ≤ κ) (n : ℕ) : (n : Cardinal.{u}) ≤ κ :=
  le_trans (le_of_lt Cardinal.natCast_lt_aleph0) hκ

omit [Nontrivial R] in
/-- A free module on a finite set is `R^n`. -/
theorem ofSet_equiv_fin {s : Set (Idx κ)} {n : ℕ} (hs : #s = (n : Cardinal.{u})) :
    Nonempty (ofSet R κ s ≃ₗ[R] (⨁ _ : Fin n, R)) := by
  have h : #s = #(ULift.{u} (Fin n)) := by
    rw [hs, Cardinal.mk_uLift, Cardinal.mk_fin]
    simp
  exact ⟨DirectSum.lequivCongrLeft R ((Cardinal.eq.mp h).some.trans Equiv.ulift)⟩

/-- **The two relations agree.** -/
theorem mkC_eq_iff_cmul_eq (hκ : ℵ₀ ≤ κ) (hu : KMonoid.IsFaithful (κ := κ) u)
    (hmatch : ∀ k l : ℕ, Nonempty ((⨁ _ : Fin k, R) ≃ₗ[R] (⨁ _ : Fin l, R)) ↔ k • u = l • u)
    {s t : Set (Idx κ)} :
    mkC R κ hκ s = mkC R κ hκ t ↔
      KMonoid.cmul (κ := κ) (#s) (mk_le_kappa s) u
        = KMonoid.cmul (κ := κ) (#t) (mk_le_kappa t) u := by
  -- the finite case, stated once and used in both directions
  have hfin : ∀ (s t : Set (Idx κ)) (k l : ℕ), #s = (k : Cardinal.{u}) → #t = (l : Cardinal.{u}) →
      (mkC R κ hκ s = mkC R κ hκ t ↔
        KMonoid.cmul (κ := κ) (#s) (mk_le_kappa s) u
          = KMonoid.cmul (κ := κ) (#t) (mk_le_kappa t) u) := by
    intro s t k l hsk htl
    rw [KMonoid.cmul_congr hsk _ (natCast_le hκ k), KMonoid.cmul_congr htl _ (natCast_le hκ l),
      KMonoid.cmul_natCast u k, KMonoid.cmul_natCast u l, ← hmatch k l]
    constructor
    · intro h
      exact ⟨((ofSet_equiv_fin (R := R) hsk).some.symm.trans
        (mkC_eq_mkC_iff (R := R) hκ |>.mp h).some).trans (ofSet_equiv_fin (R := R) htl).some⟩
    · intro h
      exact (mkC_eq_mkC_iff (R := R) hκ).mpr
        ⟨((ofSet_equiv_fin (R := R) hsk).some.trans h.some).trans
          (ofSet_equiv_fin (R := R) htl).some.symm⟩
  rcases lt_or_ge (#s) ℵ₀ with hs | hs
  · obtain ⟨k, hk⟩ := exists_natCast_of_lt_aleph0 hs
    rcases lt_or_ge (#t) ℵ₀ with ht | ht
    · obtain ⟨l, hl⟩ := exists_natCast_of_lt_aleph0 ht
      exact hfin s t k l hk hl
    · -- a finite rank and an infinite rank match on neither side
      constructor
      · intro h
        exact absurd (le_of_le_of_eq ht (mk_eq_of_mkC_eq hκ ht h.symm)) (not_le_of_gt hs)
      · intro h
        exact absurd (AddLe.of_eq h.symm)
          (hu.2 (#s) (#t) (mk_le_kappa s) (mk_le_kappa t) (lt_of_lt_of_le hs ht) ht)
  · constructor
    · intro h
      exact KMonoid.cmul_congr (mk_eq_of_mkC_eq hκ hs h) _ _ u
    · intro h
      rcases lt_or_ge (#t) ℵ₀ with ht | ht
      · exact absurd (AddLe.of_eq h)
          (hu.2 (#t) (#s) (mk_le_kappa t) (mk_le_kappa s) (lt_of_lt_of_le ht hs) hs)
      · exact mkC_eq_mkC_of_mk_eq hκ
          (KMonoid.cmul_injOn_of_faithful hu hs ht (mk_le_kappa s) (mk_le_kappa t) h)

/-! ## The comparison map -/

open FreeMod in
/-- The comparison map `V^κ(𝓕^κ) → H`, sending a class to `#(basis a)` copies of `u`. -/
noncomputable def toH (hκ : ℵ₀ ≤ κ) (u : H) (a : (freeClass R κ hκ).carrier) : H :=
  KMonoid.cmul (κ := κ) (#(basis a)) (mk_le_kappa _) u

variable (hκ : ℵ₀ ≤ κ) (hu : KMonoid.IsFaithful (κ := κ) u)
  (hmatch : ∀ k l : ℕ, Nonempty ((⨁ _ : Fin k, R) ≃ₗ[R] (⨁ _ : Fin l, R)) ↔ k • u = l • u)

include hu hmatch in
theorem toH_mkC (s : Set (Idx κ)) :
    toH (R := R) hκ u (mkC R κ hκ s) = KMonoid.cmul (κ := κ) (#s) (mk_le_kappa s) u :=
  (mkC_eq_iff_cmul_eq hκ hu hmatch).mp (mkC_basis hκ _)

include hu hmatch in
/-- `toH` is injective: the two relations agree. -/
theorem toH_injective : Function.Injective (toH (R := R) hκ u) := by
  intro a b h
  rw [← mkC_basis hκ a, ← mkC_basis hκ b]
  exact (mkC_eq_iff_cmul_eq hκ hu hmatch).mpr h

include hu hmatch in
/-- `toH` is surjective when `H` is cyclic on `u`. -/
theorem toH_surjective (hgen : KGenerates κ ({u} : Set H)) :
    Function.Surjective (toH (R := R) hκ u) := by
  intro y
  obtain ⟨α, hα, hy⟩ := KMonoid.exists_cmul_of_kGenerates hgen y
  refine ⟨mkC R κ hκ (setOfCard hα), ?_⟩
  rw [toH_mkC hκ hu hmatch, hy]
  exact KMonoid.cmul_congr (mk_setOfCard hα) _ hα u

include hu hmatch in
/-- `toH` is a `κ`-homomorphism: the rank of a direct sum is the sum of the ranks, and
`Lemma 2.7(2)` turns that into a sum in `H`. -/
theorem isKHom_toH :
    letI := (freeClass R κ hκ).instKMonoid hκ
    IsKHom κ (toH (R := R) hκ u) := by
  let := (freeClass R κ hκ).instKMonoid hκ
  constructor
  · -- the zero class is the class of the empty generating set
    have h0 : ((freeClass R κ hκ).zero : (freeClass R κ hκ).carrier) = mkC R κ hκ ∅ := rfl
    have hz : ((0 : (freeClass R κ hκ).carrier)) = mkC R κ hκ ∅ := h0
    rw [hz, toH_mkC hκ hu hmatch]
    rw [KMonoid.cmul_congr (by simp : #(∅ : Set (Idx κ)) = 0) _ zero_le,
      KMonoid.cmul_zero_cardinal]
  · intro x
    -- `Σ x` is the class of the disjoint union of the chosen bases
    have hks : KMonoid.ksum (κ := κ) x = mkC R κ hκ (sumSet R κ hκ x) :=
      (freeClass R κ hκ).instKMonoid_ksum hκ x
    have hcard : #(sumSet R κ hκ x) = Cardinal.sum fun i => #(basis (x i)) :=
      (Cardinal.mk_range_eq _ (emb (mk_sigma_basis_le R κ hκ x)).injective).trans
        (Cardinal.mk_sigma _)
    have hsum : (Cardinal.sum fun i => #(basis (x i))) ≤ κ := hcard ▸ mk_le_kappa _
    rw [hks, toH_mkC hκ hu hmatch, KMonoid.cmul_congr hcard _ hsum,
      KMonoid.cmul_sumOf_cardinal (le_of_eq (mk_Idx κ)) _ (fun i => mk_le_kappa _) hsum u]
    rfl

/-! ## Proposition 2.16 -/

end Compare

/-- **Proposition 2.16**: a cyclic `κ`-monoid generated by a faithful order-unit is `V^κ(𝓕^κ)`
for some ring.

The ring comes from Leavitt's theorem applied to the presentation of the size-zero
submonoid supplied by the classification of cyclic monoids; when that submonoid is `ℕ₀` no axiom
is needed, since any ring with invariant basis number will do.

The classification is applied to `u` itself rather than to the submonoid it generates: it is a
statement about the kernel of `k ↦ k • u`, and needs no generation hypothesis. -/
theorem prop_2_16 {κ : Cardinal.{u}} (hκ : ℵ₀ ≤ κ) (H : Type u) [KMonoid κ H] (u : H)
    (hu : KMonoid.IsFaithful (κ := κ) u) (hgen : KGenerates κ ({u} : Set H)) :
    ∃ (P : ℕ → ℕ → Prop) (Rl : Realiser.{u} P)
      (φ : (FreeMod.freeClass Rl.R κ hκ).carrier → H),
      letI := (FreeMod.freeClass Rl.R κ hκ).instKMonoid hκ
      IsKHom κ φ ∧ Function.Bijective φ := by
  -- present the submonoid generated by `u`
  obtain hinj | ⟨m, n, hn, hrel⟩ := cyclicMonoidClassification u
  · -- `C₀ = ℕ₀`: any ring with invariant basis number realises it
    refine ⟨(· = ·), realiserEq, toH hκ u, ?_⟩
    have hmatch : ∀ k l : ℕ,
        Nonempty ((⨁ _ : Fin k, (realiserEq.{u}).R) ≃ₗ[realiserEq.{u}.R]
          (⨁ _ : Fin l, (realiserEq.{u}).R)) ↔ k • u = l • u := by
      intro k l
      rw [realiserEq.iso_iff k l]
      constructor
      · rintro rfl; rfl
      · intro h
        exact (hinj k l).mp h
    exact ⟨isKHom_toH hκ hu hmatch, toH_injective hκ hu hmatch,
      toH_surjective hκ hu hmatch hgen⟩
  · -- `C₀ = C_{m,n}`: Leavitt.  `m ≥ 1`, since `u` is faithful and `m = 0` would mean `n u = 0`
    have hm : 1 ≤ m := by
      by_contra hm0
      refine KMonoid.nsmul_ne_zero_of_faithful hu hn ?_
      have h := (hrel n 0).mpr (Or.inr ⟨by omega, by omega, ⟨1, by push_cast; omega⟩⟩)
      simpa using h
    refine ⟨CyclicRel m n, realiserCyclicRel m n hm hn, toH hκ u, ?_⟩
    have hmatch : ∀ k l : ℕ,
        Nonempty ((⨁ _ : Fin k, (realiserCyclicRel.{u} m n hm hn).R)
            ≃ₗ[(realiserCyclicRel.{u} m n hm hn).R]
              (⨁ _ : Fin l, (realiserCyclicRel.{u} m n hm hn).R))
          ↔ k • u = l • u := by
      intro k l
      rw [(realiserCyclicRel m n hm hn).iso_iff k l, ← hrel k l]
    exact ⟨isKHom_toH hκ hu hmatch, toH_injective hκ hu hmatch,
      toH_surjective hκ hu hmatch hgen⟩

end KappaMonoid
