/-
**A2** Leavitt's realisation of the cyclic monoids `C_{m,n}`, and **A4** the classification of
cyclic monoids.  Both are monoid-theoretic; neither mentions a module.
-/
import Mathlib

universe u

open Cardinal DirectSum

namespace KappaMonoid


/-! ## A2: Leavitt's realisation theorem -/

/-- The congruence `∼_{m,n}` on `ℕ₀` defining the cyclic monoid `C_{m,n}`: `k` and `l` are
identified iff they are equal, or both are at least `m` and differ by a multiple of `n`. -/
def CyclicRel (m n k l : ℕ) : Prop := k = l ∨ (m ≤ k ∧ m ≤ l ∧ (n : ℤ) ∣ (k : ℤ) - l)

/-- A ring realising the cyclic monoid `C_{m,n}` as its monoid of finitely generated free
modules: `R^k ≅ R^l` exactly when `k ∼_{m,n} l`. -/
structure LeavittData (m n : ℕ) where
  /-- The realising ring. -/
  R : Type u
  [ring : Ring R]
  [nontrivial : Nontrivial R]
  /-- Isomorphism of finitely generated free modules is exactly `∼_{m,n}`. -/
  iso_iff : ∀ k l : ℕ,
    Nonempty ((⨁ _ : Fin k, R) ≃ₗ[R] (⨁ _ : Fin l, R)) ↔ CyclicRel m n k l

attribute [instance] LeavittData.ring LeavittData.nontrivial

/-- **Assumed** (Leavitt, 1962).  Every cyclic monoid `C_{m,n}` with `n ≥ 1` is the monoid of
finitely generated free modules over some ring.

The remaining cyclic monoid, `ℕ₀` itself, needs no axiom: every ring with invariant basis
number realises it. -/
axiom leavittData (m n : ℕ) (_hn : 1 ≤ n) : LeavittData.{u} m n

/-- **Assumed**: the classification of cyclic monoids.  A monoid generated by a single element
`u` is either free on `u` — so `n ↦ n • u` is injective, and the monoid is `ℕ₀` — or else it is
`C_{m,n}` for some `m ≥ 0`, `n ≥ 1`, meaning that `k • u = l • u` holds exactly when
`k ∼_{m,n} l`.

Standard proof, not formalised here: if `n ↦ n • u` is not injective, take the least `m` with
`m • u = l • u` for some `l > m`, and the least such `l`; then `n = l - m` and the relation
generated by `m ∼ m + n` is all of the kernel.

Mathlib has no classification of cyclic monoids (`IsCyclic` is about groups). -/
axiom cyclicMonoidClassification {M : Type u} [AddCommMonoid M] (u : M)
    (_hgen : ∀ x : M, ∃ n : ℕ, x = n • u) :
    (∀ k l : ℕ, k • u = l • u ↔ k = l) ∨
      ∃ m n : ℕ, 1 ≤ n ∧ ∀ k l : ℕ, k • u = l • u ↔ CyclicRel m n k l

end KappaMonoid
