/-
**A1**: invariance of infinite rank, in the generation form Example 2.13 needs.
-/
import Mathlib

universe u

open Cardinal DirectSum

namespace KappaMonoid


/-! ## A1: invariance of infinite rank -/

/-- **Assumed** (invariance of infinite rank).  Over a nontrivial ring, a free module with an
infinite basis cannot be generated by fewer elements than its rank.

Standard proof, not formalised here: every element of a generating set `S` has finite support in
the basis, so `S` lies in the span of a subfamily of the basis of cardinality at most `#S ⊔ ℵ₀`;
a basis element outside that subfamily would then lie in the span of the others, contradicting
linear independence.  Hence the subfamily is everything.

The conclusion is `#ι ≤ #S` with no `⊔ ℵ₀`: when `S` is finite the hypothesis is itself
contradictory, so nothing false is asserted, and the sharp form is what lets the application in
Example 2.13 avoid a case split.

This *generation* form, rather than the two-bases form `mk_eq_mk_of_infinite` below, is what the
application needs: the complement appearing in Example 2.13 is merely projective, not free, so
there is no second basis to compare against. -/
axiom mk_le_of_span_eq_top {R : Type u} [Ring R] [Nontrivial R] {M : Type u} [AddCommGroup M]
    [Module R M] {ι : Type u} (_b : Module.Basis ι R M) [Infinite ι] {S : Set M}
    (_hS : Submodule.span R S = ⊤) : #ι ≤ #S

/-- Invariance of infinite rank in its familiar form: two bases of the same module, one of them
infinite, have the same cardinality.  Derived from `mk_le_of_span_eq_top`. -/
theorem mk_eq_mk_of_infinite {R : Type u} [Ring R] [Nontrivial R] {M : Type u} [AddCommGroup M]
    [Module R M] {ι ι' : Type u} (b : Module.Basis ι R M) (b' : Module.Basis ι' R M) [Infinite ι] :
    #ι = #ι' := by
  have h₁ : #ι ≤ #(Set.range (b' : ι' → M)) := mk_le_of_span_eq_top b b'.span_eq
  have h₁' : #ι ≤ #ι' := h₁.trans (Cardinal.mk_range_le)
  -- `ι'` is infinite too, so the argument may be repeated with the roles exchanged
  haveI : Infinite ι' :=
    Cardinal.infinite_iff.mpr ((Cardinal.infinite_iff.mp ‹Infinite ι›).trans h₁')
  have h₂ : #ι' ≤ #(Set.range (b : ι → M)) := mk_le_of_span_eq_top b' b.span_eq
  exact le_antisymm h₁' (h₂.trans Cardinal.mk_range_le)

end KappaMonoid
